TEMPLATE_NAME = 'adult vision disorders'
TEMPLATE = {
    'aliases': [
        'vision disorders',
        'vision loss',
        'adult-onset vision loss',
        'amd',
        'glaucoma',
        'retinal dystrophy'
    ],
    'mode': 'complex',
    'gene_set': [
        {
            'gene': 'ABCA1',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ABCA4',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ACAA2',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ADAM19',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'AFF1',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'APOE',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ARMS2',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': 'AMD8(复杂);ARMS2-HTRA1位点A69S OR~2.7',
            'key_domains': '功能未知;线粒体/Surfeit域',
            'clingen_validity': 'Limited',
        },
        {
            'gene': 'ATOH7',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'BMP3',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'C2',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'C3',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': 'AMD9(复杂);补体C3;R102G AMD风险变异',
            'key_domains': 'β链(1-645);α链(650-1641);C3a/C3b/C3d',
            'clingen_validity': 'Moderate',
        },
        {
            'gene': 'C5',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CAV1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CAV2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CCND1',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CD46',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CDKN2B-AS1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CETP',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CFB',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CFD',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CFH',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': 'AMD1(复杂);补体因子H;Y402H为最强AMD风险位点',
            'key_domains': 'CCP/Sushi域(20个);CCP7(Y402H位点);CCP19-20(C3b结合)',
            'clingen_validity': 'Strong',
        },
        {
            'gene': 'CFI',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': 'AMD13(复杂);补体因子I;C3b/C4b蛋白酶',
            'key_domains': 'FIMAC;SRCR;LDLR;SP蛋白酶;跨膜',
            'clingen_validity': 'Moderate',
        },
        {
            'gene': 'CHD9',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CHM',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CLUL1',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'COL8A1',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CYP1B1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': 'GLC3A(AR);细胞色素P450;小梁网发育;原发性先天青光眼',
            'key_domains': 'P450域;血红素结合;跨膜螺旋',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'CYP26A1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'EFEMP1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'EXOC3L2',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'EYS',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'FOXC1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'FOXO1',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'GAS7',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'GATA5',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'GGT7',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'HLA-DQB1',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'HLA-DRB1',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'HTRA1',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': 'AMD8/ARMS2位点;丝氨酸蛋白酶;抑制TGF-β/Bruch膜',
            'key_domains': 'IGFBP;Kazal;Trypsin蛋白酶;PDZ',
            'clingen_validity': 'Limited',
        },
        {
            'gene': 'LIPC',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'LIPG',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'LOXL1',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'LTBP2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ME3',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'MMP9',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'MOXD1',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'MYO1E',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'MYOC',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': 'GLC1A(常显);视神经保护;小梁网;青少年/成人POAG',
            'key_domains': 'Olfactomedin域;leucine拉链;coiled-coil',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'OCA2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'OPTN',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': 'GLC1E(常显);optineurin;NF-κB/TNF-α信号;正常眼压青光眼',
            'key_domains': 'UBAN域;锌指;coiled-coil;LIR基序',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'PDGFB',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'PILRA',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'PILRB',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'PITX2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'PLTP',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'PRPH2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'RAD51B',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'RDH5',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'RHO',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'RLBP1',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'RP1L1',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'RPGR',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SERPINA1',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SIX1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SIX6',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SLC16A7',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SMAD3',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TBK1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TEK',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TGFB1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'THBS1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TIMP3',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TMCO1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TMEM40',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TNFRSF10A',
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AMD/黄斑变性核心GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TRPM1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TRPM2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TYR',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'UBAP2',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'USH2A',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '遗传性视网膜变性/营养不良基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'VEGFA',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '新生血管AMD GWAS;VEGF-A;抗VEGF治疗靶点',
            'key_domains': 'PDGF/VEGF域;肝素结合;Cys-knot',
            'clingen_validity': 'Limited',
        },
        {
            'gene': 'WDR36',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': 'POAG/青光眼致病或强风险基因',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ZBTB38',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成人视力相关GWAS位点',
            'phenotype_assoc': '',
            'key_domains': '',
            'clingen_validity': '',
        },
    ],
    'known_pathogenic_variants': [
        {
            'rsid': 'rs2297669',
            'chrom': 'chr1',
            'pos': 94001069,
            'ref': 'G',
            'alt': 'A',
            'gene': 'ABCA4',
            'effect_allele': 'A',
            'other_allele': 'G',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.9,
            'confidence': 'high',
            'note': 'ABCA4 p.Gly1961Glu; Stargardt disease / cone-rod dystrophy / AMD-like retinopathy, autosomal recessive',
        },
        {
            'rsid': 'rs74315332',
            'chrom': 'chr1',
            'pos': 171636000,
            'ref': 'G',
            'alt': 'T',
            'gene': 'MYOC',
            'effect_allele': 'T',
            'other_allele': 'G',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.8,
            'confidence': 'high',
            'note': 'MYOC p.Gln368Ter; primary open-angle glaucoma, adult-onset / juvenile-onset',
        },
        {
            'rsid': 'rs111033566',
            'chrom': 'chr1',
            'pos': 215947066,
            'ref': 'C',
            'alt': 'T',
            'gene': 'USH2A',
            'effect_allele': 'T',
            'other_allele': 'C',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.9,
            'confidence': 'high',
            'note': 'USH2A p.Glu767SerfsTer21; Usher syndrome type 2A / retinitis pigmentosa 39, autosomal recessive',
        },
        {
            'rsid': 'rs753966040',
            'chrom': 'chr10',
            'pos': 13109191,
            'ref': 'A',
            'alt': 'AC',
            'gene': 'OPTN',
            'effect_allele': 'AC',
            'other_allele': 'A',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.85,
            'confidence': 'high',
            'note': 'OPTN 移码变异；常染色体显性原发性开角型青光眼 / ALS 12 型，杂合致病',
        },
        {
            'rsid': 'rs281865209',
            'chrom': 'chr11',
            'pos': 61951844,
            'ref': 'G',
            'alt': 'A',
            'gene': 'BEST1',
            'effect_allele': 'A',
            'other_allele': 'G',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.9,
            'confidence': 'high',
            'note': 'BEST1 p.Arg141His; 常染色体显性卵黄样黄斑营养不良，杂合导致成人起病视力下降',
        },
        {
            'rsid': 'rs2125193922',
            'chrom': 'chr1',
            'pos': 197268428,
            'ref': 'AT',
            'alt': 'A',
            'gene': 'CRB1',
            'effect_allele': 'A',
            'other_allele': 'AT',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.9,
            'confidence': 'high',
            'note': 'CRB1 移码变异；常染色体隐性 Leber 先天黑蒙 8 型 / 视网膜色素变性 12 型，纯合或复合杂合致病',
        },
        {
            'rsid': 'rs104893793',
            'chrom': 'chr3',
            'pos': 129531005,
            'ref': 'C',
            'alt': 'T',
            'gene': 'RHO',
            'effect_allele': 'T',
            'other_allele': 'C',
            'variant_class': 'known_pathogenic',
            'contribution_score': 1.0,
            'confidence': 'high',
            'note': 'RHO p.Pro23His; 常染色体显性视网膜色素变性 4 型，杂合致病，成人起病夜盲和周边视力丧失',
        },
        {
            'rsid': 'rs104893946',
            'chrom': 'chr6',
            'pos': 79916743,
            'ref': 'G',
            'alt': 'C',
            'gene': 'ELOVL4',
            'effect_allele': 'C',
            'other_allele': 'G',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.9,
            'confidence': 'high',
            'note': 'ELOVL4 p.Lys276Ter; 常染色体显性 Stargardt 病 3 型，杂合致病，成人黄斑变性样视力下降',
        },
        {
            'rsid': 'rs751768343',
            'chrom': 'chr2',
            'pos': 38070812,
            'ref': 'CTTGGGT',
            'alt': 'C',
            'gene': 'CYP1B1',
            'effect_allele': 'C',
            'other_allele': 'CTTGGGT',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.95,
            'confidence': 'high',
            'note': 'CYP1B1 移码变异；常染色体隐性原发性先天性青光眼 3A 型，纯合致病，杂合携带者风险不明确',
        },
        {
            'rsid': 'rs281865373',
            'chrom': 'chr6',
            'pos': 42704362,
            'ref': 'T',
            'alt': 'A',
            'gene': 'PRPH2',
            'effect_allele': 'A',
            'other_allele': 'T',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.85,
            'confidence': 'high',
            'note': 'PRPH2 错义变异；常染色体显性视网膜色素变性/黄斑营养不良，杂合致病，成人起病中心视力下降',
        },
        {
            'rsid': 'rs1800553',
            'chrom': 'chr1',
            'pos': 94008251,
            'ref': 'C',
            'alt': 'T',
            'gene': 'ABCA4',
            'effect_allele': 'T',
            'other_allele': 'C',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.8,
            'confidence': 'high',
            'note': 'ABCA4 p.Gly1961Glu; AR Stargardt disease, homozygous or compound het pathogenic',
        },
    ],
    'prs_variants_high': [
    ],
    'gwas_loci_genes': [
        'ABCA1',
        'ACAA2',
        'ADAM19',
        'AFF1',
        'APOE',
        'ARMS2',
        'C2',
        'C3',
        'C5',
        'CCND1',
        'CD46',
        'CETP',
        'CFB',
        'CFD',
        'CFH',
        'CFI',
        'CLUL1',
        'COL8A1',
        'EXOC3L2',
        'FOXO1',
        'GGT7',
        'HLA-DQB1',
        'HLA-DRB1',
        'HTRA1',
        'LIPC',
        'LIPG',
        'LOXL1',
        'MMP9',
        'MOXD1',
        'MYO1E',
        'PDGFB',
        'PILRA',
        'PILRB',
        'PLTP',
        'RAD51B',
        'RDH5',
        'RLBP1',
        'RP1L1',
        'SERPINA1',
        'SLC16A7',
        'TIMP3',
        'TMEM40',
        'TNFRSF10A',
        'UBAP2',
        'VEGFA',
        'ZBTB38'
    ],
    'gwas_lead_snps': [
        {
            'rsid': 'rs10033900',
            'chrom': 'chr4',
            'pos': 109737911,
            'gene': 'CFI',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.1398,
            'or_value': 1.15,
            'eaf_eur': 0.4809,
            'eaf_eas': 0.6172,
            'tier': 'gwas',
            'contribution_score': 0.168,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.15',
        },
        {
            'rsid': 'rs10781182',
            'chrom': 'chr9',
            'pos': 74002804,
            'gene': 'MIR6130',
            'effect_allele': 'T',
            'other_allele': 'G',
            'beta': 0.1044,
            'or_value': 1.11,
            'eaf_eur': 0.3027,
            'eaf_eas': 0.5466,
            'tier': 'gwas',
            'contribution_score': 0.125,
            'confidence': 'moderate',
            'note': 'MIR6130; EAS AF=0.55 vs EUR=0.30, significant divergence',
        },
        {
            'rsid': 'rs10922109',
            'chrom': 'chr1',
            'pos': 196735502,
            'gene': 'CFH',
            'effect_allele': 'C',
            'other_allele': 'A',
            'beta': 0.967,
            'or_value': 2.63,
            'eaf_eur': 0.5915,
            'eaf_eas': 0.5344,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=2.63',
        },
        {
            'rsid': 'rs11080055',
            'chrom': 'chr17',
            'pos': 28322698,
            'gene': 'TMEM97',
            'effect_allele': 'C',
            'other_allele': 'A',
            'beta': 0.0953,
            'or_value': 1.1,
            'eaf_eur': 0.52,
            'eaf_eas': 0.7356,
            'tier': 'gwas',
            'contribution_score': 0.114,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.1',
        },
        {
            'rsid': 'rs114092250',
            'chrom': 'chr5',
            'pos': 35494346,
            'gene': 'PRLR',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.3577,
            'or_value': 1.43,
            'eaf_eur': 0.9699,
            'eaf_eas': 0.9992,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=1.43',
        },
        {
            'rsid': 'rs1142',
            'chrom': 'chr7',
            'pos': 105115879,
            'gene': 'SRPK2',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.1044,
            'or_value': 1.11,
            'eaf_eur': 0.3051,
            'eaf_eas': 0.3366,
            'tier': 'gwas',
            'contribution_score': 0.125,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.11',
        },
        {
            'rsid': 'rs11884770',
            'chrom': 'chr2',
            'pos': 227222204,
            'gene': 'COL4A3',
            'effect_allele': 'C',
            'other_allele': 'T',
            'beta': 0.1044,
            'or_value': 1.11,
            'eaf_eur': 0.6384,
            'eaf_eas': 0.7888,
            'tier': 'gwas',
            'contribution_score': 0.125,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.11',
        },
        {
            'rsid': 'rs12019136',
            'chrom': 'chr19',
            'pos': 5835666,
            'gene': 'FUT6',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.3436,
            'or_value': 1.41,
            'eaf_eur': 0.96,
            'eaf_eas': 0.8737,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=1.41',
        },
        {
            'rsid': 'rs121913059',
            'chrom': 'chr1',
            'pos': 196747245,
            'gene': 'CFH',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 3.0096,
            'or_value': 20.28,
            'eaf_eur': 0.0004,
            'eaf_eas': None,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=20.28',
        },
        {
            'rsid': 'rs12357257',
            'chrom': 'chr10',
            'pos': 24710664,
            'gene': 'ARHGAP21',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.1044,
            'or_value': 1.11,
            'eaf_eur': 0.2235,
            'eaf_eas': 0.049,
            'tier': 'gwas',
            'contribution_score': 0.125,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.11',
        },
        {
            'rsid': 'rs13278062',
            'chrom': 'chr8',
            'pos': 23225458,
            'gene': 'TNFRSF10A',
            'effect_allele': 'T',
            'other_allele': 'G',
            'beta': 0.1044,
            'or_value': 1.11,
            'eaf_eur': 0.5118,
            'eaf_eas': 0.3009,
            'tier': 'gwas',
            'contribution_score': 0.125,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.11',
        },
        {
            'rsid': 'rs140647181',
            'chrom': 'chr3',
            'pos': 99461824,
            'gene': 'LOC105374007',
            'effect_allele': 'C',
            'other_allele': 'T',
            'beta': 0.4637,
            'or_value': 1.59,
            'eaf_eur': 0.0206,
            'eaf_eas': 0.0004,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=1.59',
        },
        {
            'rsid': 'rs141853578',
            'chrom': 'chr4',
            'pos': 109764664,
            'gene': 'CFI',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 1.292,
            'or_value': 3.64,
            'eaf_eur': 0.0008,
            'eaf_eas': None,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=3.64',
        },
        {
            'rsid': 'rs147859257',
            'chrom': 'chr19',
            'pos': 6718135,
            'gene': 'C3',
            'effect_allele': 'G',
            'other_allele': 'T',
            'beta': 1.0508,
            'or_value': 2.86,
            'eaf_eur': 0.0045,
            'eaf_eas': None,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=2.86',
        },
        {
            'rsid': 'rs148553336',
            'chrom': 'chr1',
            'pos': 196644043,
            'gene': 'CFH',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 1.2384,
            'or_value': 3.45,
            'eaf_eur': 0.9824,
            'eaf_eas': 1,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=3.45',
        },
        {
            'rsid': 'rs1626340',
            'chrom': 'chr9',
            'pos': 99161090,
            'gene': 'TGFBR1',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.131,
            'or_value': 1.14,
            'eaf_eur': 0.7858,
            'eaf_eas': 0.5319,
            'tier': 'gwas',
            'contribution_score': 0.157,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.14',
        },
        {
            'rsid': 'rs17231506',
            'chrom': 'chr16',
            'pos': 56960616,
            'gene': 'CETP',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.1484,
            'or_value': 1.16,
            'eaf_eur': 0.2759,
            'eaf_eas': 0.1665,
            'tier': 'gwas',
            'contribution_score': 0.178,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.16',
        },
        {
            'rsid': 'rs181705462',
            'chrom': 'chr6',
            'pos': 31979250,
            'gene': 'STK19',
            'effect_allele': 'T',
            'other_allele': 'G',
            'beta': 0.4383,
            'or_value': 1.55,
            'eaf_eur': 0.0084,
            'eaf_eas': 0.0021,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=1.55',
        },
        {
            'rsid': 'rs187328863',
            'chrom': 'chr1',
            'pos': 196411028,
            'gene': 'KCNT2',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.8198,
            'or_value': 2.27,
            'eaf_eur': 0.0253,
            'eaf_eas': None,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=2.27',
        },
        {
            'rsid': 'rs191281603',
            'chrom': 'chr1',
            'pos': 196989521,
            'gene': 'CFHR5',
            'effect_allele': 'G',
            'other_allele': 'C',
            'beta': 0.0677,
            'or_value': 1.07,
            'eaf_eur': 0.0015,
            'eaf_eas': None,
            'tier': 'gwas',
            'contribution_score': 0.081,
            'confidence': 'low',
            'note': 'PGS002269 OR=1.07',
        },
        {
            'rsid': 'rs201459901',
            'chrom': 'chr20',
            'pos': 58078669,
            'gene': 'C20orf85',
            'effect_allele': 'T',
            'other_allele': 'A',
            'beta': 0.2776,
            'or_value': 1.32,
            'eaf_eur': None,
            'eaf_eas': 0.00976,
            'tier': 'gwas',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=1.32',
        },
        {
            'rsid': 'rs2043085',
            'chrom': 'chr15',
            'pos': 58388755,
            'gene': 'LIPC',
            'effect_allele': 'T',
            'other_allele': 'A',
            'beta': 0.1398,
            'or_value': 1.15,
            'eaf_eur': 0.3767,
            'eaf_eas': 0.4892,
            'tier': 'gwas',
            'contribution_score': 0.168,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.15',
        },
        {
            'rsid': 'rs2070895',
            'chrom': 'chr15',
            'pos': 58431740,
            'gene': 'LIPC',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.1398,
            'or_value': 1.15,
            'eaf_eur': 0.7804,
            'eaf_eas': 0.5825,
            'tier': 'gwas',
            'contribution_score': 0.168,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.15',
        },
        {
            'rsid': 'rs2230199',
            'chrom': 'chr19',
            'pos': 6718376,
            'gene': 'C3',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.3577,
            'or_value': 1.43,
            'eaf_eur': 0.7918,
            'eaf_eas': 0.999,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'C3 R102G',
        },
        {
            'rsid': 'rs2740488',
            'chrom': 'chr9',
            'pos': 104899461,
            'gene': 'ABCA1',
            'effect_allele': 'A',
            'other_allele': 'C',
            'beta': 0.1044,
            'or_value': 1.11,
            'eaf_eur': 0.7376,
            'eaf_eas': 0.758,
            'tier': 'gwas',
            'contribution_score': 0.125,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.11',
        },
        {
            'rsid': 'rs2842339',
            'chrom': 'chr14',
            'pos': 68520282,
            'gene': 'RAD51B',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.131,
            'or_value': 1.14,
            'eaf_eur': 0.0933,
            'eaf_eas': 0.0104,
            'tier': 'gwas',
            'contribution_score': 0.157,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.14',
        },
        {
            'rsid': 'rs3138141',
            'chrom': 'chr12',
            'pos': 55721994,
            'gene': 'RDH5',
            'effect_allele': 'A',
            'other_allele': 'C',
            'beta': 0.1484,
            'or_value': 1.16,
            'eaf_eur': 0.2264,
            'eaf_eas': 0.1073,
            'tier': 'gwas',
            'contribution_score': 0.178,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.16',
        },
        {
            'rsid': 'rs35292876',
            'chrom': 'chr1',
            'pos': 196737512,
            'gene': 'CFH',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.8838,
            'or_value': 2.42,
            'eaf_eur': 0.0076,
            'eaf_eas': 0.0006,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=2.42',
        },
        {
            'rsid': 'rs3750846',
            'chrom': 'chr10',
            'pos': 122456049,
            'gene': 'ARMS2',
            'effect_allele': 'C',
            'other_allele': 'T',
            'beta': 1.0332,
            'or_value': 2.81,
            'eaf_eur': 0.2195,
            'eaf_eas': 0.4182,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'ARMS2 A69S tagging SNP (LD proxy for rs10490924)',
        },
        {
            'rsid': 'rs10490924',
            'chrom': 'chr10',
            'pos': 122454932,
            'gene': 'ARMS2',
            'effect_allele': 'T',
            'other_allele': 'G',
            'beta': 0.9933,
            'or_value': 2.7,
            'eaf_eur': 0.2,
            'eaf_eas': 0.4,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'ARMS2 c.205G>T (p.Ala69Ser), primary AMD causal variant at 10q26',
        },
        {
            'rsid': 'rs11200638',
            'chrom': 'chr10',
            'pos': 122462960,
            'gene': 'HTRA1',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.9163,
            'or_value': 2.5,
            'eaf_eur': 0.39,
            'eaf_eas': 0.42,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'HTRA1 c.-625G>A, promoter variant, AMD risk at 10q26',
        },
        {
            'rsid': 'rs429358',
            'chrom': 'chr19',
            'pos': 44908684,
            'gene': 'APOE',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.3577,
            'or_value': 1.43,
            'eaf_eur': 0.8621,
            'eaf_eas': 0.9023,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'APOE ε4/ε2, AMD risk/protective',
        },
        {
            'rsid': 'rs55975637',
            'chrom': 'chr3',
            'pos': 99701009,
            'gene': 'COL8A1',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.1398,
            'or_value': 1.15,
            'eaf_eur': 0.1231,
            'eaf_eas': 0.0371,
            'tier': 'gwas',
            'contribution_score': 0.168,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.15',
        },
        {
            'rsid': 'rs1061170',
            'chrom': 'chr1',
            'pos': 196659237,
            'gene': 'CFH',
            'effect_allele': 'C',
            'other_allele': 'T',
            'beta': 0.9163,
            'or_value': 2.5,
            'eaf_eur': 0.35,
            'eaf_eas': 0.065,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'CFH c.1204T>C (p.Tyr402His, Y402H), primary AMD risk variant in complement pathway',
        },
        {
            'rsid': 'rs570618',
            'chrom': 'chr1',
            'pos': 196687934,
            'gene': 'CFH',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.8671,
            'or_value': 2.38,
            'eaf_eur': 0.3809,
            'eaf_eas': 0.0515,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=2.38',
        },
        {
            'rsid': 'rs5754227',
            'chrom': 'chr22',
            'pos': 32709831,
            'gene': 'SYN3',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.2624,
            'or_value': 1.3,
            'eaf_eur': 0.8717,
            'eaf_eas': 0.3706,
            'tier': 'gwas',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=1.3',
        },
        {
            'rsid': 'rs5817082',
            'chrom': 'chr16',
            'pos': 56963438,
            'gene': 'CETP',
            'effect_allele': 'C',
            'other_allele': 'AA',
            'beta': 0.174,
            'or_value': 1.19,
            'eaf_eur': None,
            'eaf_eas': 0.101604,
            'tier': 'gwas',
            'contribution_score': 0.209,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.19',
        },
        {
            'rsid': 'rs61818925',
            'chrom': 'chr1',
            'pos': 196846320,
            'gene': '_CFH (CFHR3',
            'effect_allele': 'G',
            'other_allele': 'T',
            'beta': 0.5128,
            'or_value': 1.67,
            'eaf_eur': 0.6688,
            'eaf_eas': 0.4877,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=1.67',
        },
        {
            'rsid': 'rs61941274',
            'chrom': 'chr12',
            'pos': 111694806,
            'gene': 'ACAD10',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.4121,
            'or_value': 1.51,
            'eaf_eur': 0.0009,
            'eaf_eas': None,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=1.51',
        },
        {
            'rsid': 'rs61985136',
            'chrom': 'chr14',
            'pos': 68302482,
            'gene': 'RAD51B',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.1044,
            'or_value': 1.11,
            'eaf_eur': 0.5955,
            'eaf_eas': 0.4929,
            'tier': 'gwas',
            'contribution_score': 0.125,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.11',
        },
        {
            'rsid': 'rs62247658',
            'chrom': 'chr3',
            'pos': 64729479,
            'gene': 'ADAMTS9-AS2',
            'effect_allele': 'C',
            'other_allele': 'T',
            'beta': 0.131,
            'or_value': 1.14,
            'eaf_eur': 0.3739,
            'eaf_eas': 0.7622,
            'tier': 'gwas',
            'contribution_score': 0.157,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.14',
        },
        {
            'rsid': 'rs62358361',
            'chrom': 'chr5',
            'pos': 39327786,
            'gene': 'C9',
            'effect_allele': 'T',
            'other_allele': 'G',
            'beta': 0.5878,
            'or_value': 1.8,
            'eaf_eur': 0.0098,
            'eaf_eas': None,
            'tier': 'high_effect',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'PGS002269 OR=1.8',
        },
        {
            'rsid': 'rs6565597',
            'chrom': 'chr17',
            'pos': 81559795,
            'gene': 'NPLOC4',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.1222,
            'or_value': 1.13,
            'eaf_eur': 0.4211,
            'eaf_eas': 0.1968,
            'tier': 'gwas',
            'contribution_score': 0.147,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.13',
        },
        {
            'rsid': 'rs67538026',
            'chrom': 'chr19',
            'pos': 1031439,
            'gene': 'CNN2',
            'effect_allele': 'C',
            'other_allele': 'G',
            'beta': 0.1044,
            'or_value': 1.11,
            'eaf_eur': 0.5459,
            'eaf_eas': 0.4786,
            'tier': 'gwas',
            'contribution_score': 0.125,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.11',
        },
        {
            'rsid': 'rs72802342',
            'chrom': 'chr16',
            'pos': 75200974,
            'gene': 'CTRB2',
            'effect_allele': 'C',
            'other_allele': 'A',
            'beta': 0.239,
            'or_value': 1.27,
            'eaf_eur': 0.9101,
            'eaf_eas': 0.8799,
            'tier': 'gwas',
            'contribution_score': 0.287,
            'confidence': 'high',
            'note': 'PGS002269 OR=1.27',
        },
        {
            'rsid': 'rs73036519',
            'chrom': 'chr19',
            'pos': 45245104,
            'gene': 'EXOC3L2',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.0953,
            'or_value': 1.1,
            'eaf_eur': 0.6762,
            'eaf_eas': 0.9971,
            'tier': 'gwas',
            'contribution_score': 0.114,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.1',
        },
        {
            'rsid': 'rs7803454',
            'chrom': 'chr7',
            'pos': 100393925,
            'gene': 'PILRA',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.1222,
            'or_value': 1.13,
            'eaf_eur': 0.1939,
            'eaf_eas': 0.0337,
            'tier': 'gwas',
            'contribution_score': 0.147,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.13',
        },
        {
            'rsid': 'rs8135665',
            'chrom': 'chr22',
            'pos': 38080269,
            'gene': 'SLC16A8',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.131,
            'or_value': 1.14,
            'eaf_eur': 0.198,
            'eaf_eas': 0.1324,
            'tier': 'gwas',
            'contribution_score': 0.157,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.14',
        },
        {
            'rsid': 'rs943080',
            'chrom': 'chr6',
            'pos': 43858890,
            'gene': 'POLR1C',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.131,
            'or_value': 1.14,
            'eaf_eur': 0.5059,
            'eaf_eas': 0.7292,
            'tier': 'gwas',
            'contribution_score': 0.157,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.14',
        },
        {
            'rsid': 'rs9564692',
            'chrom': 'chr13',
            'pos': 31247103,
            'gene': 'B3GLCT',
            'effect_allele': 'C',
            'other_allele': 'A',
            'beta': 0.1133,
            'or_value': 1.12,
            'eaf_eur': 0.7092,
            'eaf_eas': 0.2759,
            'tier': 'gwas',
            'contribution_score': 0.136,
            'confidence': 'moderate',
            'note': 'PGS002269 OR=1.12',
        },
        {
            'rsid': 'rs2157719',
            'chrom': 'chr9',
            'pos': 22003367,
            'gene': 'CDKN2B-AS1',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.131,
            'or_value': 1.14,
            'eaf_eur': None,
            'eaf_eas': None,
            'tier': 'gwas',
            'contribution_score': 0.157,
            'confidence': 'moderate',
            'note': 'POAG GWAS locus CDKN2B-AS1',
        },
        {
            'rsid': 'rs7555523',
            'chrom': 'chr14',
            'pos': 60788658,
            'gene': 'SIX1',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.1222,
            'or_value': 1.13,
            'eaf_eur': None,
            'eaf_eas': None,
            'tier': 'gwas',
            'contribution_score': 0.147,
            'confidence': 'moderate',
            'note': 'SIX1/SIX6 optic nerve locus',
        },
        {
            'rsid': 'rs1900004',
            'chrom': 'chr9',
            'pos': 107560750,
            'gene': 'ABCA1',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.0953,
            'or_value': 1.1,
            'eaf_eur': None,
            'eaf_eas': None,
            'tier': 'gwas',
            'contribution_score': 0.114,
            'confidence': 'moderate',
            'note': 'ABCA1 POAG locus',
        },
        {
            'rsid': 'rs7081455',
            'chrom': 'chr1',
            'pos': 71500609,
            'gene': 'PLXDC2',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.1133,
            'or_value': 1.12,
            'eaf_eur': None,
            'eaf_eas': None,
            'tier': 'gwas',
            'contribution_score': 0.136,
            'confidence': 'moderate',
            'note': 'PLXDC2/TMCO1 POAG locus',
        },
        {
            'rsid': 'rs1052990',
            'chrom': 'chr7',
            'pos': 115993814,
            'gene': 'CAV1',
            'effect_allele': 'C',
            'other_allele': 'T',
            'beta': 0.1044,
            'or_value': 1.11,
            'eaf_eur': None,
            'eaf_eas': None,
            'tier': 'gwas',
            'contribution_score': 0.125,
            'confidence': 'moderate',
            'note': 'CAV1/CAV2 POAG locus',
        },
        {
            'rsid': 'rs11656696',
            'chrom': 'chr1',
            'pos': 171625297,
            'gene': 'GAS7',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.1044,
            'or_value': 1.11,
            'eaf_eur': None,
            'eaf_eas': None,
            'tier': 'gwas',
            'contribution_score': 0.125,
            'confidence': 'moderate',
            'note': 'GAS7 POAG locus',
        },
    ],
    'core_genes': [
        'ABCA4',
        'ATOH7',
        'BMP3',
        'CAV1',
        'CAV2',
        'CDKN2B-AS1',
        'CHD9',
        'CHM',
        'CYP1B1',
        'CYP26A1',
        'EFEMP1',
        'EYS',
        'FOXC1',
        'GAS7',
        'GATA5',
        'LTBP2',
        'ME3',
        'MYOC',
        'OCA2',
        'OPTN',
        'PITX2',
        'PRPH2',
        'RHO',
        'RPGR',
        'SIX1',
        'SIX6',
        'SMAD3',
        'TBK1',
        'TEK',
        'TGFB1',
        'THBS1',
        'TMCO1',
        'TRPM1',
        'TRPM2',
        'TYR',
        'USH2A',
        'WDR36'
    ],
    'key_regions': {
        'RHO': {
            'note': 'Rhodopsin; G-protein coupled receptor; AD RP4',
            'regions': [
                {'name': '7-TM', 'residues': '35-312', 'note': 'Seven-transmembrane GPCR fold (Class A)'},
                {'name': 'Retinal_binding', 'residues': '296-300', 'note': '11-cis-retinal binding pocket; Lys296 Schiff base'},
            ],
            'critical_residues': [
                {'residue': 'Pro23', 'note': 'P23H: most common AD RP mutation'},
                {'residue': 'Lys296', 'note': 'K296E/M: disrupts retinal binding; constitutive activation'},
            ],
        },
        'ABCA4': {
            'note': 'ABCA4; ATP-binding cassette transporter; AR Stargardt/CORD',
            'regions': [
                {'name': 'ECD1', 'residues': '44-645', 'note': 'Exocytoplasmic domain 1'},
                {'name': 'NBD1', 'residues': '1051-1360', 'note': 'Nucleotide-binding domain 1 (Walker A/B)'},
                {'name': 'NBD2', 'residues': '2141-2272', 'note': 'Nucleotide-binding domain 2'},
            ],
            'critical_residues': [
                {'residue': 'Gly1961', 'note': 'G1961E: common Stargardt variant in NBD2 Walker A'},
                {'residue': 'Gly863', 'note': 'G863A: common European Stargardt variant'},
            ],
        },
    },
    'regions': [
        {'chrom': 'chr1', 'start': 196600000, 'end': 197000000, 'gene': 'CFH/CFHR', 'type': 'gwas_locus', 'contribution_score': 0.6, 'note': '补体因子H/CFHR AMD最强风险区'},
        {'chrom': 'chr10', 'start': 122400000, 'end': 122500000, 'gene': 'ARMS2/HTRA1', 'type': 'gwas_locus', 'contribution_score': 0.55, 'note': 'ARMS2/HTRA1 AMD核心位点'},
        {'chrom': 'chr19', 'start': 6710000, 'end': 6730000, 'gene': 'C3', 'type': 'gwas_locus', 'contribution_score': 0.4, 'note': 'C3 AMD补体位点'},
        {'chrom': 'chr1', 'start': 171500000, 'end': 171700000, 'gene': 'GAS7/MYOC', 'type': 'gwas_locus', 'contribution_score': 0.3, 'note': 'POAG/MYOC青光眼风险区'},
        {'chrom': 'chr9', 'start': 21990000, 'end': 22020000, 'gene': 'CDKN2B-AS1', 'type': 'gwas_locus', 'contribution_score': 0.3, 'note': 'POAG CDKN2B-AS1位点'},
    ],
    'regulatory_regions': [
    ],
    'key_literature': [
        {'pmid': '27108990', 'title': 'A large genome-wide association study of age-related macular degeneration highlights contributions of rare and common variants.', 'genes': ['CFH', 'ARMS2', 'HTRA1', 'C3', 'C2', 'CFI', 'CETP', 'LIPC', 'TIMP3', 'SYN3', 'RAD51B'], 'note': 'Fritsche et al., Nat Genet 2016 (IAMDGC)', 'evidence_type': 'gwas'},
        {'pmid': '35012306', 'title': 'Age-Related Macular Degeneration Genomics: From SNPs to Function.', 'genes': ['CFH', 'ARMS2', 'HTRA1', 'APOE'], 'note': 'Hageman & Gehrs, Annu Rev Genomics Hum Genet 2022', 'evidence_type': 'review'},
        {'pmid': '30911158', 'title': 'Genome-wide association meta-analysis highlights light-induced signaling as a pathway for myopia.', 'genes': ['MYP1', 'MYP2', 'MYP3', 'PAX6', 'GJD2', 'PRSS56', 'BICC1', 'ATOH7', 'SIX6'], 'note': 'Tedja et al., Nat Genet 2019', 'evidence_type': 'gwas'},
        {'pmid': '32778723', 'title': 'Genome-wide meta-analysis identifies 127 open-angle glaucoma loci with consistent effect across ancestries.', 'genes': ['MYOC', 'OPTN', 'TBK1', 'CDKN2B-AS1', 'SIX1', 'SIX6', 'ABCA1', 'CAV1', 'CAV2', 'TMCO1', 'GAS7'], 'note': 'Gharahkhani et al., Nat Commun 2021', 'evidence_type': 'gwas'},
        {'pmid': '29643574', 'title': 'Rare variants in CFH, CFI and C3 are associated with progression to advanced AMD.', 'genes': ['CFH', 'CFI', 'C3'], 'note': 'Seddon et al., Nat Genet 2018', 'evidence_type': 'rare_variant_functional'},
    ],
}
