TEMPLATE_NAME = 'androgenetic alopecia'
TEMPLATE = {
    'aliases': [
        'androgenetic alopecia',
        'aga',
        'male pattern baldness',
        'female pattern hair loss',
        '雄激素性脱发',
        '男性型脱发',
        '脂溢性脱发',
        '脱发',
    ],
    'mode': 'complex',
    'gene_set': [
        {
            'gene': 'AR',
            'tier': 'strong_gwas',
            'contribution_score': 0.85,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.35,
            'evidence': 'gwas',
            'note': 'X 染色体雄激素受体，AGA 最强遗传位点；CAG 重复长度与男性 AGA 风险相关',
            'phenotype_assoc': '雄激素性脱发（AGA）最强遗传决定因素；AR 信号介导 DHT 诱导的毛囊微型化',
            'key_domains': 'NTD (1-558); DBD (559-624); HBD (665-919); CAG 重复 (exon1)',
            'clingen_validity': '',
        },
        {
            'gene': 'EDA2R',
            'tier': 'strong_gwas',
            'contribution_score': 0.80,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.30,
            'evidence': 'gwas',
            'note': 'X 染色体 AGA GWAS 最显著信号区（p<1e-30），与毛囊细胞凋亡和 NF-κB 通路相关',
            'phenotype_assoc': '雄激素性脱发；外胚层发育不良受体 A2，调控毛囊周期',
            'key_domains': 'TNFR 胞外域 (1-137); 跨膜域 (138-158); 死亡域 (200-268)',
            'clingen_validity': '',
        },
        {
            'gene': 'HDAC9',
            'tier': 'strong_gwas',
            'contribution_score': 0.45,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AGA 独立 GWAS 位点，参与 Wnt/β-catenin 信号调控毛囊周期',
            'phenotype_assoc': '雄激素性脱发；组蛋白去乙酰化酶 9，调控毛囊周期',
            'key_domains': 'HDAC 催化域 (669-1008); MEF2 结合域 (1-90)',
            'clingen_validity': '',
        },
        {
            'gene': 'SRD5A2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low',
            'penetrance_score': 0.15,
            'evidence': 'mixed',
            'note': 'II 型 5α-还原酶，将睾酮转化为 DHT；非那雄胺/度他雄胺靶点；V89L、A49T 为经典功能多态',
            'phenotype_assoc': '雄激素性脱发；5α-还原酶缺乏症（SRD5A2 缺乏）导致 DHT 生成减少，理论上降低 AGA 风险',
            'key_domains': 'FAD-binding Rossmann fold (aa12-157); 5α-还原酶催化域 (aa158-240)',
            'clingen_validity': 'Definitive (for 5-alpha-reductase 2 deficiency)',
        },
        {
            'gene': 'SRD5A1',
            'tier': 'gwas',
            'contribution_score': 0.30,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'I 型 5α-还原酶，皮肤/毛囊中表达；度他雄胺靶点',
            'phenotype_assoc': '雄激素性脱发；参与 DHT 合成，是药物靶点但 GWAS 关联弱于 SRD5A2',
            'key_domains': 'FAD-binding Rossmann fold; 5α-还原酶催化域',
            'clingen_validity': '',
        },
        {
            'gene': 'WNT10A',
            'tier': 'gwas',
            'contribution_score': 0.35,
            'penetrance': 'low',
            'penetrance_score': 0.08,
            'evidence': 'gwas',
            'note': 'Wnt 信号通路成员，调控毛囊发育和再生；与遗传性少毛症和 AGA 相关',
            'phenotype_assoc': '雄激素性脱发；毛囊发育和周期调控',
            'key_domains': 'Wnt 结构域 (aa1-417)',
            'clingen_validity': '',
        },
        {
            'gene': 'HSD3B1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '3β-羟基类固醇脱氢酶，雄激素合成通路',
            'phenotype_assoc': '雄激素性脱发；参与雄激素前体代谢',
            'key_domains': '3-beta-HSD 活性域 (aa1-373); 跨膜域',
            'clingen_validity': '',
        },
        {
            'gene': 'HSD3B2',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '肾上腺/性腺 3β-羟基类固醇脱氢酶，雄激素合成通路',
            'phenotype_assoc': '雄激素性脱发；参与雄激素生物合成',
            'key_domains': '3-beta-HSD 活性域 (aa1-373)',
            'clingen_validity': '',
        },
        {
            'gene': 'CYP17A1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '17α-羟化酶/17,20-裂解酶，雄激素合成关键酶',
            'phenotype_assoc': '雄激素性脱发；调控雄激素前体生成',
            'key_domains': 'CYP450 血红素结合域 (aa427-454); 跨膜域 (aa1-30)',
            'clingen_validity': '',
        },
        {
            'gene': 'FGF5',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成纤维细胞生长因子 5，抑制毛囊生长期（anagen）向延长期转换',
            'phenotype_assoc': '雄激素性脱发；毛囊周期调控',
            'key_domains': 'FGF 核心域 (aa32-150)',
            'clingen_validity': '',
        },
        {
            'gene': 'APCDD1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'Wnt 通路抑制因子，参与毛囊发育',
            'phenotype_assoc': '雄激素性脱发；Wnt/β-catenin 信号调控',
            'key_domains': 'Transmembrane domain (aa1-45); N-terminal secretory domain',
            'clingen_validity': '',
        },
        {
            'gene': 'TWIST1',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '毛囊间充质干细胞调控因子',
            'phenotype_assoc': '雄激素性脱发；毛囊发育调控',
            'key_domains': 'bHLH DNA-binding domain (aa109-160); WRPW motif',
            'clingen_validity': '',
        },
        {
            'gene': 'IL1A',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '促炎细胞因子，参与毛囊炎症微环境',
            'phenotype_assoc': '雄激素性脱发；炎症辅助通路',
            'key_domains': 'IL-1 前体蛋白 (aa1-271)',
            'clingen_validity': '',
        },
        {
            'gene': 'IL1B',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '促炎细胞因子，参与毛囊炎症微环境',
            'phenotype_assoc': '雄激素性脱发；炎症辅助通路',
            'key_domains': 'IL-1 前体蛋白 (aa1-269)',
            'clingen_validity': '',
        },
        {
            'gene': 'ESR1',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '雌激素受体 1，激素代谢调控；与女性型脱发和毛发周期相关',
            'phenotype_assoc': '雄激素性脱发；激素代谢与毛发生长调控',
            'key_domains': 'NTD (1-184); DBD (185-250); HBD (302-553); AF2 (591-595)',
            'clingen_validity': '',
        },
        {
            'gene': 'CYP19A1',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '芳香化酶，介导雄激素向雌激素转化，影响局部雄激素/雌激素平衡',
            'phenotype_assoc': '雄激素性脱发；激素代谢辅助通路',
            'key_domains': 'CYP450 血红素结合域 (aa438-466); 跨膜域 (aa1-47)',
            'clingen_validity': '',
        },
    ],
    'known_pathogenic_variants': [
        {
            'rsid': 'rs523349',
            'chrom': 'chr2',
            'pos': 31580636,
            'ref': 'G',
            'alt': 'A',
            'gene': 'SRD5A2',
            'effect_allele': 'A',
            'other_allele': 'G',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.4,
            'confidence': 'medium',
            'note': 'SRD5A2 p.Val89Leu (V89L); 影响酶活性与 DHT 生成；与 5α-还原酶缺乏症相关，在 AGA 中作为药物靶点功能变异',
        },
        {
            'rsid': 'rs9282858',
            'chrom': 'chr2',
            'pos': 31580756,
            'ref': 'C',
            'alt': 'T',
            'gene': 'SRD5A2',
            'effect_allele': 'T',
            'other_allele': 'C',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.35,
            'confidence': 'medium',
            'note': 'SRD5A2 p.Ala49Thr (A49T); 经典功能多态；与 5α-还原酶缺乏症相关',
        },
    ],
    'gwas_lead_snps': [
        {
            'rsid': 'rs6152',
            'chrom': 'chrX',
            'pos': 67545785,
            'gene': 'AR',
            'effect_allele': 'A',
            'other_allele': 'G',
            'or_value': 1.4,
            'beta': None,
            'eaf_eur': 0.18,
            'eaf_eas': 0.002,
            'tier': 'strong_gwas',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'AR StuI RFLP (E211E); A 等位基因与男性 AGA 风险降低相关；东亚人群 G 几乎固定',
        },
        {
            'rsid': 'rs1385699',
            'chrom': 'chrX',
            'pos': 66605144,
            'gene': 'EDA2R',
            'effect_allele': 'T',
            'other_allele': 'C',
            'or_value': 1.45,
            'beta': None,
            'eaf_eur': 0.67,
            'eaf_eas': 0.65,
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'confidence': 'high',
            'note': 'EDA2R 错义变异，AGA 最强 GWAS 信号区（p<1e-30）',
        },
        {
            'rsid': 'rs2497938',
            'chrom': 'chrX',
            'pos': 67343176,
            'gene': 'AR/EDA2R',
            'effect_allele': 'C',
            'other_allele': 'T',
            'or_value': 1.5,
            'beta': None,
            'eaf_eur': 0.33,
            'eaf_eas': 0.34,
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'confidence': 'high',
            'note': 'AR-EDA2R 基因间区域，AGA 全基因组显著位点',
        },
        {
            'rsid': 'rs1160312',
            'chrom': 'chr20',
            'pos': 22069865,
            'gene': 'HDAC9/20p11',
            'effect_allele': 'G',
            'other_allele': 'A',
            'or_value': 1.25,
            'beta': None,
            'eaf_eur': 0.40,
            'eaf_eas': 0.40,
            'tier': 'gwas',
            'contribution_score': 0.22,
            'confidence': 'medium',
            'note': '20p11/HDAC9 区域 AGA 关联位点',
        },
        {
            'rsid': 'rs13283456',
            'chrom': 'chr9',
            'pos': 128122474,
            'gene': 'HDAC9/unknown',
            'effect_allele': 'T',
            'other_allele': 'C',
            'or_value': 1.2,
            'beta': None,
            'eaf_eur': 0.07,
            'eaf_eas': 0.08,
            'tier': 'gwas',
            'contribution_score': 0.15,
            'confidence': 'low',
            'note': '报告列出的 AGA 候选位点（chr9），与 HDAC9 位置关系需进一步验证',
        },
        {
            'rsid': 'rs7349332',
            'chrom': 'chr2',
            'pos': 218891661,
            'gene': 'WNT10A',
            'effect_allele': 'T',
            'other_allele': 'C',
            'or_value': 1.2,
            'beta': None,
            'eaf_eur': 0.15,
            'eaf_eas': 0.15,
            'tier': 'gwas',
            'contribution_score': 0.18,
            'confidence': 'medium',
            'note': 'WNT10A 区域 AGA 关联位点，调控毛囊发育',
        },
        {
            'rsid': 'rs2180439',
            'chrom': 'chr20',
            'pos': 21872462,
            'gene': '20p11',
            'effect_allele': 'C',
            'other_allele': 'T',
            'or_value': 1.25,
            'beta': None,
            'eaf_eur': 0.46,
            'eaf_eas': 0.45,
            'tier': 'gwas',
            'contribution_score': 0.18,
            'confidence': 'medium',
            'note': '20p11 区域 AGA 关联位点（中国汉族人群验证）',
        },
    ],
    'prs_variants': [],
    'prs_variants_high': [],
    'regulatory_regions': [
        {'chrom': 'chrX', 'start': 66600000, 'end': 67350000, 'gene': 'AR/EDA2R', 'note': 'AGA 最强 GWAS 区域'},
        {'chrom': 'chr20', 'start': 21800000, 'end': 22200000, 'gene': '20p11', 'note': '独立 AGA 风险区'},
    ],
    'key_regions': {
        'AR': {
            'note': 'X 染色体雄激素受体，AGA 最强遗传决定因素',
            'regions': [
                {'name': 'N-terminal domain', 'residues': '1-558', 'note': '转录激活；含 CAG 重复多态'},
                {'name': 'DNA-binding domain', 'residues': '559-624', 'note': '结合雄激素应答元件'},
                {'name': 'Hinge/Ligand-binding domain', 'residues': '665-919', 'note': 'DHT/睾酮结合'},
            ],
            'critical_residues': [
                {'residue': 'Glu211', 'note': 'rs6152 同义位点，StuI RFLP 标记'},
            ],
        },
        'EDA2R': {
            'note': 'X 染色体 AGA 最强 GWAS 信号，调控毛囊细胞凋亡',
            'regions': [
                {'name': 'TNFR extracellular domain', 'residues': '1-137', 'note': '配体结合'},
                {'name': 'Death domain', 'residues': '200-268', 'note': '介导凋亡信号'},
            ],
            'critical_residues': [
                {'residue': 'rs1385699', 'note': 'AGA 最强关联位点所在区域'},
            ],
        },
        'SRD5A2': {
            'note': 'II 型 5α-还原酶，DHT 合成与非那雄胺靶点',
            'regions': [
                {'name': 'FAD-binding Rossmann fold', 'residues': '12-157', 'note': '辅酶结合'},
                {'name': '5α-reductase catalytic domain', 'residues': '158-240', 'note': '催化睾酮→DHT；非那雄胺结合区'},
            ],
            'critical_residues': [
                {'residue': 'Ala49', 'note': 'rs9282858 A49T 影响酶活性'},
                {'residue': 'Val89', 'note': 'rs523349 V89L 影响酶稳定性与活性'},
            ],
        },
    },
    'key_literature': [
        {
            'pmid': '31501595',
            'title': 'Genetic prediction of male pattern baldness.',
            'genes': ['AR', 'EDA2R', 'HDAC9', 'WNT10A'],
            'note': 'PLoS Genet 2019; 基于 UK Biobank 205,000 男性的 AGA GWAS 与多基因预测模型',
            'evidence_type': 'gwas',
        },
        {
            'pmid': '23776682',
            'title': 'Genetic Variants at 20p11 Confer Risk to Androgenetic Alopecia in the Chinese Han Population.',
            'genes': ['20p11'],
            'note': 'PLoS One 2013; 中国汉族人群验证 20p11 AGA 位点',
            'evidence_type': 'gwas',
        },
        {
            'pmid': '22032556',
            'title': 'Male-pattern baldness susceptibility locus at 20p11.',
            'genes': ['20p11', 'PAX1', 'FOXA2'],
            'note': 'Nat Genet 2011; 首次报道 20p11 AGA 易感位点，验证 AR/EDA2R 信号',
            'evidence_type': 'gwas',
        },
    ],
}
