"""Disease template: androgenetic alopecia (AGA).

Sources: Pirastu et al. 2017 Nat Commun (71 loci, 70k men);
         Hagenaars et al. 2017; PGS Catalog PGS002314/PGS003558.
"""

import math

TEMPLATE_NAME = 'androgenetic alopecia'
TEMPLATE = {
    'aliases': [
        'androgenetic alopecia',
        'aga',
        'male pattern baldness',
        'female pattern hair loss',
        '雄激素性脱发',
        '男性型脱发',
        '脂溢性脱发',
        '脱发',
    ],
    'mode': 'complex',
    'core_genes': [
        'AR', 'EDA2R', 'SRD5A2', 'SRD5A1', 'WNT10A', 'HDAC9', 'FGF5', 'TWIST1',
    ],
    'gwas_loci_genes': [
        'TWIST2', 'IRF4', 'SETBP1', 'RSPO2', 'MSI2', 'BCL2', 'DFFA',
        'RUNX2', 'RUNX3', 'PTHLH', 'PDGFA', 'AUTS2', 'EBF1', 'ALX4',
        'PAX1', 'PAX3', 'FAM9B', 'WNT3', 'LGR4', 'DKK2', 'SOX13',
        'APCDD1', 'CYP17A1', 'CYP19A1', 'ESR1', 'HSD3B1', 'HSD3B2',
        'IL1A', 'IL1B', 'ZNF462', 'COPB2', 'WARS2', 'PRKD1', 'IQGAP1',
    ],
    'gene_set': [
        {
            'gene': 'AR',
            'tier': 'strong_gwas',
            'contribution_score': 0.85,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.35,
            'evidence': 'gwas',
            'note': 'X 染色体雄激素受体，AGA 最强遗传位点；CAG 重复长度与男性 AGA 风险相关',
            'phenotype_assoc': '雄激素性脱发（AGA）最强遗传决定因素；AR 信号介导 DHT 诱导的毛囊微型化',
            'key_domains': 'NTD (1-558); DBD (559-624); HBD (665-919); CAG 重复 (exon1)',
            'clingen_validity': '',
        },
        {
            'gene': 'EDA2R',
            'tier': 'strong_gwas',
            'contribution_score': 0.80,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.30,
            'evidence': 'gwas',
            'note': 'X 染色体 AGA GWAS 最显著信号区（p<1e-30），与毛囊细胞凋亡和 NF-κB 通路相关',
            'phenotype_assoc': '雄激素性脱发；外胚层发育不良受体 A2，调控毛囊周期',
            'key_domains': 'TNFR 胞外域 (1-137); 跨膜域 (138-158); 死亡域 (200-268)',
            'clingen_validity': '',
        },
        {
            'gene': 'HDAC9',
            'tier': 'strong_gwas',
            'contribution_score': 0.45,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'AGA 独立 GWAS 位点，参与 Wnt/β-catenin 信号调控毛囊周期',
            'phenotype_assoc': '雄激素性脱发；组蛋白去乙酰化酶 9，调控毛囊周期',
            'key_domains': 'HDAC 催化域 (669-1008); MEF2 结合域 (1-90)',
            'clingen_validity': '',
        },
        {
            'gene': 'SRD5A2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'low',
            'penetrance_score': 0.15,
            'evidence': 'mixed',
            'note': 'II 型 5α-还原酶，将睾酮转化为 DHT；非那雄胺/度他雄胺靶点；V89L、A49T 为经典功能多态',
            'phenotype_assoc': '雄激素性脱发；5α-还原酶缺乏症（SRD5A2 缺乏）导致 DHT 生成减少，理论上降低 AGA 风险',
            'key_domains': 'FAD-binding Rossmann fold (aa12-157); 5α-还原酶催化域 (aa158-240)',
            'clingen_validity': 'Definitive (for 5-alpha-reductase 2 deficiency)',
        },
        {
            'gene': 'SRD5A1',
            'tier': 'gwas',
            'contribution_score': 0.30,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'I 型 5α-还原酶，皮肤/毛囊中表达；度他雄胺靶点',
            'phenotype_assoc': '雄激素性脱发；参与 DHT 合成，是药物靶点但 GWAS 关联弱于 SRD5A2',
            'key_domains': 'FAD-binding Rossmann fold; 5α-还原酶催化域',
            'clingen_validity': '',
        },
        {
            'gene': 'WNT10A',
            'tier': 'gwas',
            'contribution_score': 0.35,
            'penetrance': 'low',
            'penetrance_score': 0.08,
            'evidence': 'gwas',
            'note': 'Wnt 信号通路成员，调控毛囊发育和再生；与遗传性少毛症和 AGA 相关',
            'phenotype_assoc': '雄激素性脱发；毛囊发育和周期调控',
            'key_domains': 'Wnt 结构域 (aa1-417)',
            'clingen_validity': '',
        },
        {
            'gene': 'FGF5',
            'tier': 'gwas',
            'contribution_score': 0.30,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '成纤维细胞生长因子 5，抑制毛囊生长期（anagen）向延长期转换；Pirastu 2017 locus 27 (p=4.60E-25)',
            'phenotype_assoc': '雄激素性脱发；毛囊周期调控',
            'key_domains': 'FGF 核心域 (aa32-150)',
            'clingen_validity': '',
        },
        {
            'gene': 'TWIST1',
            'tier': 'gwas',
            'contribution_score': 0.35,
            'penetrance': 'low',
            'penetrance_score': 0.08,
            'evidence': 'gwas',
            'note': '毛囊间充质干细胞调控因子；Pirastu 2017 locus 38 (p=7.34E-63)',
            'phenotype_assoc': '雄激素性脱发；毛囊发育调控',
            'key_domains': 'bHLH DNA-binding domain (aa109-160); WRPW motif',
            'clingen_validity': '',
        },
        {
            'gene': 'TWIST2',
            'tier': 'gwas',
            'contribution_score': 0.30,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'bHLH 转录因子，毛囊发育调控；Pirastu 2017 locus 21 (p=1.43E-39)',
            'phenotype_assoc': '雄激素性脱发；Wnt 通路基因社区',
            'key_domains': 'bHLH DNA-binding domain; WRPW motif',
            'clingen_validity': '',
        },
        {
            'gene': 'IRF4',
            'tier': 'strong_gwas',
            'contribution_score': 0.40,
            'penetrance': 'low',
            'penetrance_score': 0.08,
            'evidence': 'gwas',
            'note': '干扰素调节因子 4；Pirastu 2017 locus 32 (p=2.35E-52)，凋亡通路基因社区',
            'phenotype_assoc': '雄激素性脱发；转录调控与凋亡通路',
            'key_domains': 'IRF tryptophan pentad repeat DNA-binding domain (aa1-119); IRF association domain (aa225-450)',
            'clingen_validity': '',
        },
        {
            'gene': 'BCL2',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '抗凋亡蛋白；Pirastu 2017 locus 64 (p=2.35E-08)，凋亡通路基因社区',
            'phenotype_assoc': '雄激素性脱发；毛囊细胞凋亡调控',
            'key_domains': 'BH1-BH4 domains; Bcl-2 homology region (aa10-205)',
            'clingen_validity': '',
        },
        {
            'gene': 'DFFA',
            'tier': 'gwas',
            'contribution_score': 0.35,
            'penetrance': 'low',
            'penetrance_score': 0.08,
            'evidence': 'gwas',
            'note': 'DNA 断裂因子 A；Pirastu 2017 locus 1 (p=6.04E-49)，凋亡通路基因社区',
            'phenotype_assoc': '雄激素性脱发；毛囊细胞凋亡',
            'key_domains': 'DFFA N-terminal domain (aa1-50); DFFA C-terminal domain (aa200-331)',
            'clingen_validity': '',
        },
        {
            'gene': 'SETBP1',
            'tier': 'gwas',
            'contribution_score': 0.30,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'SET 结合蛋白 1；Pirastu 2017 locus 63 (p=8.03E-25)',
            'phenotype_assoc': '雄激素性脱发；基因调控',
            'key_domains': 'SET-binding domain (aa548-824); AT-hook DNA-binding motif',
            'clingen_validity': '',
        },
        {
            'gene': 'RSPO2',
            'tier': 'gwas',
            'contribution_score': 0.30,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'R-spondin 2，Wnt 信号增强子；Pirastu 2017 locus 42 (p=2.13E-22)',
            'phenotype_assoc': '雄激素性脱发；Wnt 通路基因社区',
            'key_domains': 'Thrombospondin type-1 repeat (aa40-85); Furin-like cysteine-rich domain',
            'clingen_validity': '',
        },
        {
            'gene': 'MSI2',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'RNA 结合蛋白 Musashi 2；Pirastu 2017 locus 61 (p=8.95E-23)',
            'phenotype_assoc': '雄激素性脱发；转录后调控',
            'key_domains': 'RNA recognition motif 1 (aa20-100); RNA recognition motif 2 (aa110-190)',
            'clingen_validity': '',
        },
        {
            'gene': 'RUNX2',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'Runt 相关转录因子 2；Pirastu 2017 locus 34 (p=3.62E-08)，AR/TGFβ 通路',
            'phenotype_assoc': '雄激素性脱发；成骨分化与 TGFβ 信号',
            'key_domains': 'Runt homology domain (aa50-177); Proline-rich transactivation domain',
            'clingen_validity': '',
        },
        {
            'gene': 'RUNX3',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'Runt 相关转录因子 3；Pirastu 2017 locus 2 (p=1.28E-20)，AR/TGFβ 通路',
            'phenotype_assoc': '雄激素性脱发；TGFβ 信号通路',
            'key_domains': 'Runt homology domain (aa40-167); Proline-rich domain',
            'clingen_validity': '',
        },
        {
            'gene': 'PDGFA',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '血小板衍生生长因子 A；Pirastu 2017 locus 37 (p=6.00E-20)，AR/TGFβ 通路',
            'phenotype_assoc': '雄激素性脱发；生长因子信号',
            'key_domains': 'PDGF/VEGF domain (aa87-190); CUB domain (aa226-316)',
            'clingen_validity': '',
        },
        {
            'gene': 'PTHLH',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'PTHrP 甲状旁腺激素样激素；Pirastu 2017 locus 51 (p=3.43E-09)，AR/TGFβ 通路',
            'phenotype_assoc': '雄激素性脱发；毛发生长周期调控',
            'key_domains': 'PTH/PTHrP N-terminal domain (aa1-34)',
            'clingen_validity': '',
        },
        {
            'gene': 'EBF1',
            'tier': 'gwas',
            'contribution_score': 0.30,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '早期 B 细胞因子 1；Pirastu 2017 locus 31 (p=2.29E-44)',
            'phenotype_assoc': '雄激素性脱发；转录调控',
            'key_domains': 'Zinc-coordinating DBD (aa24-86); IPT domain (aa170-260)',
            'clingen_validity': '',
        },
        {
            'gene': 'AUTS2',
            'tier': 'gwas',
            'contribution_score': 0.30,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '自闭症易感性基因 2；Pirastu 2017 locus 40 (p=2.06E-41)',
            'phenotype_assoc': '雄激素性脱发；基因调控',
            'key_domains': 'AUTS2 domain (aa300-500); Coiled-coil domain',
            'clingen_validity': '',
        },
        {
            'gene': 'ALX4',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'Aristaless-like 同源框基因 4；Pirastu 2017 locus 49 (p=2.14E-19)',
            'phenotype_assoc': '雄激素性脱发；毛囊发育转录调控',
            'key_domains': 'Paired-type homeodomain (aa138-197); OAR domain (aa218-235)',
            'clingen_validity': '',
        },
        {
            'gene': 'PAX1',
            'tier': 'gwas',
            'contribution_score': 0.35,
            'penetrance': 'low',
            'penetrance_score': 0.08,
            'evidence': 'gwas',
            'note': '配对盒基因 1；Pirastu 2017 locus 65 (p=1.42E-105)，20p11 区域',
            'phenotype_assoc': '雄激素性脱发；20p11 区域最强 AGA 信号',
            'key_domains': 'Paired box domain (aa1-128)',
            'clingen_validity': '',
        },
        {
            'gene': 'PAX3',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '配对盒基因 3；Pirastu 2017 locus 20 (p=3.63E-10)，AR/TGFβ 通路',
            'phenotype_assoc': '雄激素性脱发；毛囊发育调控',
            'key_domains': 'Paired box domain (aa1-128); Homeodomain (aa219-278)',
            'clingen_validity': '',
        },
        {
            'gene': 'WNT3',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'Wnt 3 配体；Pirastu 2017 locus 60 (p=1.49E-26)，Wnt 通路基因社区',
            'phenotype_assoc': '雄激素性脱发；Wnt/β-catenin 信号',
            'key_domains': 'Wnt signaling domain (aa1-350)',
            'clingen_validity': '',
        },
        {
            'gene': 'DKK2',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'Dickkopf 2，Wnt 信号拮抗剂；Pirastu 2017 locus 29 (p=8.10E-11)，Wnt 通路',
            'phenotype_assoc': '雄激素性脱发；Wnt 信号负调控',
            'key_domains': 'Dickkopf domain (aa95-180)',
            'clingen_validity': '',
        },
        {
            'gene': 'LGR4',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '富含亮氨酸重复 GPCR 4；Pirastu 2017 locus 48 (p=8.99E-12)，Wnt 通路',
            'phenotype_assoc': '雄激素性脱发；Wnt 信号增强受体',
            'key_domains': 'Leucine-rich repeat (aa30-500); 7TM GPCR domain',
            'clingen_validity': '',
        },
        {
            'gene': 'SOX13',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'SRY-box 13 转录因子；Pirastu 2017 locus 9 (p=8.57E-15)，Wnt 通路',
            'phenotype_assoc': '雄激素性脱发；Wnt 转录调控',
            'key_domains': 'HMG-box DNA-binding domain (aa180-250)',
            'clingen_validity': '',
        },
        {
            'gene': 'HSD3B1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '3β-羟基类固醇脱氢酶，雄激素合成通路',
            'phenotype_assoc': '雄激素性脱发；参与雄激素前体代谢',
            'key_domains': '3-beta-HSD 活性域 (aa1-373); 跨膜域',
            'clingen_validity': '',
        },
        {
            'gene': 'HSD3B2',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '肾上腺/性腺 3β-羟基类固醇脱氢酶，雄激素合成通路',
            'phenotype_assoc': '雄激素性脱发；参与雄激素生物合成',
            'key_domains': '3-beta-HSD 活性域 (aa1-373)',
            'clingen_validity': '',
        },
        {
            'gene': 'CYP17A1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '17α-羟化酶/17,20-裂解酶，雄激素合成关键酶',
            'phenotype_assoc': '雄激素性脱发；调控雄激素前体生成',
            'key_domains': 'CYP450 血红素结合域 (aa427-454); 跨膜域 (aa1-30)',
            'clingen_validity': '',
        },
        {
            'gene': 'APCDD1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'Wnt 通路抑制因子，参与毛囊发育；Pirastu 2017 locus 62 (p=7.09E-10)',
            'phenotype_assoc': '雄激素性脱发；Wnt/β-catenin 信号调控',
            'key_domains': 'Transmembrane domain (aa1-45); N-terminal secretory domain',
            'clingen_validity': '',
        },
        {
            'gene': 'IL1A',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '促炎细胞因子，参与毛囊炎症微环境',
            'phenotype_assoc': '雄激素性脱发；炎症辅助通路',
            'key_domains': 'IL-1 前体蛋白 (aa1-271)',
            'clingen_validity': '',
        },
        {
            'gene': 'IL1B',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '促炎细胞因子，参与毛囊炎症微环境',
            'phenotype_assoc': '雄激素性脱发；炎症辅助通路',
            'key_domains': 'IL-1 前体蛋白 (aa1-269)',
            'clingen_validity': '',
        },
        {
            'gene': 'ESR1',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '雌激素受体 1，激素代谢调控；与女性型脱发和毛发周期相关',
            'phenotype_assoc': '雄激素性脱发；激素代谢与毛发生长调控',
            'key_domains': 'NTD (1-184); DBD (185-250); HBD (302-553); AF2 (591-595)',
            'clingen_validity': '',
        },
        {
            'gene': 'CYP19A1',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '芳香化酶，介导雄激素向雌激素转化，影响局部雄激素/雌激素平衡',
            'phenotype_assoc': '雄激素性脱发；激素代谢辅助通路',
            'key_domains': 'CYP450 血红素结合域 (aa438-466); 跨膜域 (aa1-47)',
            'clingen_validity': '',
        },
        {
            'gene': 'FAM9B',
            'tier': 'gwas',
            'contribution_score': 0.20,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': 'X 染色体睾丸相关基因；Pirastu 2017 locus 70 (p=4.07E-13)，与睾酮水平相关',
            'phenotype_assoc': '雄激素性脱发；X 染色体 AGA 关联位点',
            'key_domains': 'DUF2645 domain',
            'clingen_validity': '',
        },
    ],
    'known_pathogenic_variants': [
        {
            'rsid': 'rs523349',
            'chrom': 'chr2',
            'pos': 31580636,
            'ref': 'G',
            'alt': 'A',
            'gene': 'SRD5A2',
            'effect_allele': 'A',
            'other_allele': 'G',
            'or_value': 0.65,
            'beta': math.log(0.65),
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.4,
            'confidence': 'medium',
            'note': 'SRD5A2 p.Val89Leu (V89L); 影响酶活性与 DHT 生成；A 等位基因降低酶活性（保护性）；与 5α-还原酶缺乏症相关',
        },
        {
            'rsid': 'rs9282858',
            'chrom': 'chr2',
            'pos': 31580756,
            'ref': 'C',
            'alt': 'T',
            'gene': 'SRD5A2',
            'effect_allele': 'T',
            'other_allele': 'C',
            'or_value': 1.5,
            'beta': math.log(1.5),
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.35,
            'confidence': 'medium',
            'note': 'SRD5A2 p.Ala49Thr (A49T); 经典功能多态；T 等位基因增加酶活性；与 5α-还原酶缺乏症相关',
        },
    ],
    'gwas_lead_snps': [
        {
            'rsid': 'rs6152',
            'chrom': 'chrX',
            'pos': 67545785,
            'gene': 'AR',
            'effect_allele': 'A',
            'other_allele': 'G',
            'or_value': 1.4,
            'beta': round(math.log(1.4), 4),
            'eaf_eur': 0.18,
            'eaf_eas': 0.002,
            'tier': 'strong_gwas',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': 'AR StuI RFLP (E211E); A 等位基因与男性 AGA 风险降低相关；东亚人群 G 几乎固定',
        },
        {
            'rsid': 'rs1385699',
            'chrom': 'chrX',
            'pos': 66605144,
            'gene': 'EDA2R',
            'effect_allele': 'T',
            'other_allele': 'C',
            'or_value': 1.45,
            'beta': round(math.log(1.45), 4),
            'eaf_eur': 0.67,
            'eaf_eas': 0.65,
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'confidence': 'high',
            'note': 'EDA2R 错义变异，AGA 最强 GWAS 信号区（p<1e-30）',
        },
        {
            'rsid': 'rs2497938',
            'chrom': 'chrX',
            'pos': 67343176,
            'gene': 'AR/EDA2R',
            'effect_allele': 'C',
            'other_allele': 'T',
            'or_value': 1.5,
            'beta': round(math.log(1.5), 4),
            'eaf_eur': 0.33,
            'eaf_eas': 0.34,
            'tier': 'strong_gwas',
            'contribution_score': 0.35,
            'confidence': 'high',
            'note': 'AR-EDA2R 基因间区域，AGA 全基因组显著位点',
        },
        {
            'rsid': 'rs1160312',
            'chrom': 'chr20',
            'pos': 22069865,
            'gene': 'HDAC9',
            'effect_allele': 'G',
            'other_allele': 'A',
            'or_value': 1.25,
            'beta': round(math.log(1.25), 4),
            'eaf_eur': 0.40,
            'eaf_eas': 0.40,
            'tier': 'gwas',
            'contribution_score': 0.22,
            'confidence': 'medium',
            'note': '20p11/HDAC9 区域 AGA 关联位点',
        },
        {
            'rsid': 'rs13283456',
            'chrom': 'chr9',
            'pos': 128122474,
            'gene': 'ZNF462',
            'effect_allele': 'T',
            'other_allele': 'C',
            'or_value': 1.2,
            'beta': round(math.log(1.2), 4),
            'eaf_eur': 0.07,
            'eaf_eas': 0.08,
            'tier': 'gwas',
            'contribution_score': 0.15,
            'confidence': 'low',
            'note': 'chr9 AGA 关联位点（Pirastu 2017 locus 44），最近基因 ZNF462',
        },
        {
            'rsid': 'rs7349332',
            'chrom': 'chr2',
            'pos': 218891661,
            'gene': 'WNT10A',
            'effect_allele': 'T',
            'other_allele': 'C',
            'or_value': 1.2,
            'beta': round(math.log(1.2), 4),
            'eaf_eur': 0.15,
            'eaf_eas': 0.15,
            'tier': 'gwas',
            'contribution_score': 0.18,
            'confidence': 'medium',
            'note': 'WNT10A 区域 AGA 关联位点，调控毛囊发育',
        },
        {
            'rsid': 'rs2180439',
            'chrom': 'chr20',
            'pos': 21872462,
            'gene': 'PAX1',
            'effect_allele': 'C',
            'other_allele': 'T',
            'or_value': 1.25,
            'beta': round(math.log(1.25), 4),
            'eaf_eur': 0.46,
            'eaf_eas': 0.45,
            'tier': 'gwas',
            'contribution_score': 0.18,
            'confidence': 'medium',
            'note': '20p11/PAX1 区域 AGA 关联位点（中国汉族人群验证）；Pirastu 2017 locus 65 (p=1.42E-105)',
        },
        {
            'rsid': 'rs5934505',
            'chrom': 'chrX',
            'pos': 8945785,
            'gene': 'FAM9B',
            'effect_allele': 'C',
            'other_allele': 'T',
            'or_value': 1.2,
            'beta': round(math.log(1.2), 4),
            'eaf_eur': 0.27,
            'eaf_eas': 0.27,
            'tier': 'gwas',
            'contribution_score': 0.15,
            'confidence': 'medium',
            'note': 'FAM9B 区域；Pirastu 2017 locus 70 (p=4.07E-13)，与睾酮水平相关',
        },
        {
            'rsid': 'rs17265513',
            'chrom': 'chr20',
            'pos': 41203988,
            'gene': 'ZHX3',
            'effect_allele': 'C',
            'other_allele': 'T',
            'or_value': 1.15,
            'beta': round(math.log(1.15), 4),
            'eaf_eur': 0.14,
            'eaf_eas': 0.18,
            'tier': 'gwas',
            'contribution_score': 0.15,
            'confidence': 'medium',
            'note': 'ZHX3 错义变异；Pirastu 2017 locus 66 (p=4.04E-16)，论文唯一编码区 SNP',
        },
    ],
    'prs_variants': [
        {
            'rsid': 'rs1160312',
            'chrom': 'chr20',
            'pos': 22069865,
            'ref': 'A',
            'alt': 'G',
            'gene': 'HDAC9',
            'effect_allele': 'G',
            'other_allele': 'A',
            'or_value': 1.25,
            'beta': round(math.log(1.25), 4),
            'eaf_eur': 0.40,
            'eaf_eas': 0.40,
            'variant_class': 'prs',
            'contribution_score': 0.22,
            'confidence': 'medium',
            'note': '20p11/HDAC9 PRS 位点',
        },
        {
            'rsid': 'rs7349332',
            'chrom': 'chr2',
            'pos': 218891661,
            'ref': 'C',
            'alt': 'T',
            'gene': 'WNT10A',
            'effect_allele': 'T',
            'other_allele': 'C',
            'or_value': 1.2,
            'beta': round(math.log(1.2), 4),
            'eaf_eur': 0.15,
            'eaf_eas': 0.15,
            'variant_class': 'prs',
            'contribution_score': 0.18,
            'confidence': 'medium',
            'note': 'WNT10A PRS 位点',
        },
        {
            'rsid': 'rs13283456',
            'chrom': 'chr9',
            'pos': 128122474,
            'ref': 'C',
            'alt': 'T',
            'gene': 'ZNF462',
            'effect_allele': 'T',
            'other_allele': 'C',
            'or_value': 1.2,
            'beta': round(math.log(1.2), 4),
            'eaf_eur': 0.07,
            'eaf_eas': 0.08,
            'variant_class': 'prs',
            'contribution_score': 0.15,
            'confidence': 'low',
            'note': 'ZNF462 PRS 位点',
        },
    ],
    'prs_variants_high': [
        {
            'rsid': 'rs6152',
            'chrom': 'chrX',
            'pos': 67545785,
            'ref': 'G',
            'alt': 'A',
            'gene': 'AR',
            'effect_allele': 'A',
            'other_allele': 'G',
            'or_value': 1.4,
            'beta': round(math.log(1.4), 4),
            'eaf_eur': 0.18,
            'eaf_eas': 0.002,
            'tier': 'prs_high',
            'variant_class': 'prs_high',
            'contribution_score': 0.30,
            'confidence': 'high',
            'note': 'AR StuI RFLP; AGA 最强 X 染色体 PRS 位点',
        },
        {
            'rsid': 'rs1385699',
            'chrom': 'chrX',
            'pos': 66605144,
            'ref': 'C',
            'alt': 'T',
            'gene': 'EDA2R',
            'effect_allele': 'T',
            'other_allele': 'C',
            'or_value': 1.45,
            'beta': round(math.log(1.45), 4),
            'eaf_eur': 0.67,
            'eaf_eas': 0.65,
            'tier': 'prs_high',
            'variant_class': 'prs_high',
            'contribution_score': 0.35,
            'confidence': 'high',
            'note': 'EDA2R; AGA 最强 GWAS 信号（p<1e-30），核心 PRS 位点',
        },
        {
            'rsid': 'rs2180439',
            'chrom': 'chr20',
            'pos': 21872462,
            'ref': 'T',
            'alt': 'C',
            'gene': 'PAX1',
            'effect_allele': 'C',
            'other_allele': 'T',
            'or_value': 1.25,
            'beta': round(math.log(1.25), 4),
            'eaf_eur': 0.46,
            'eaf_eas': 0.45,
            'tier': 'prs_high',
            'variant_class': 'prs_high',
            'contribution_score': 0.25,
            'confidence': 'high',
            'note': '20p11/PAX1; 独立 AGA 风险区，中国汉族验证',
        },
        {
            'rsid': 'rs2497938',
            'chrom': 'chrX',
            'pos': 67343176,
            'ref': 'T',
            'alt': 'C',
            'gene': 'AR/EDA2R',
            'effect_allele': 'C',
            'other_allele': 'T',
            'or_value': 1.5,
            'beta': round(math.log(1.5), 4),
            'eaf_eur': 0.33,
            'eaf_eas': 0.34,
            'tier': 'prs_high',
            'variant_class': 'prs_high',
            'contribution_score': 0.28,
            'confidence': 'high',
            'note': 'AR-EDA2R 基因间区域；AGA 全基因组显著位点',
        },
    ],
    'regulatory_regions': [],
    'regions': [
        {'chrom': 'chrX', 'start': 66600000, 'end': 67900000, 'gene': 'AR/EDA2R', 'type': 'gwas_locus', 'contribution_score': 0.85, 'note': 'AGA 最强 GWAS 区域（Pirastu 2017 locus 71）'},
        {'chrom': 'chr20', 'start': 21600000, 'end': 22500000, 'gene': 'PAX1/HDAC9', 'type': 'gwas_locus', 'contribution_score': 0.50, 'note': '20p11 独立 AGA 风险区（Pirastu 2017 locus 65）'},
        {'chrom': 'chr2', 'start': 31400000, 'end': 33600000, 'gene': 'SRD5A2', 'type': 'gwas_locus', 'contribution_score': 0.55, 'note': 'SRD5A2 区域（Pirastu 2017 locus 12, p=1.90E-26）'},
        {'chrom': 'chr7', 'start': 18500000, 'end': 20000000, 'gene': 'TWIST1', 'type': 'gwas_locus', 'contribution_score': 0.35, 'note': 'TWIST1 区域（Pirastu 2017 locus 38, p=7.34E-63）'},
        {'chrom': 'chr1', 'start': 10400000, 'end': 11500000, 'gene': 'DFFA', 'type': 'gwas_locus', 'contribution_score': 0.35, 'note': 'DFFA 区域（Pirastu 2017 locus 1, p=6.04E-49）'},
        {'chrom': 'chr2', 'start': 239000000, 'end': 240000000, 'gene': 'TWIST2', 'type': 'gwas_locus', 'contribution_score': 0.30, 'note': 'TWIST2 区域（Pirastu 2017 locus 21, p=1.43E-39）'},
        {'chrom': 'chr4', 'start': 81000000, 'end': 81400000, 'gene': 'FGF5', 'type': 'gwas_locus', 'contribution_score': 0.30, 'note': 'FGF5 区域（Pirastu 2017 locus 27, p=4.60E-25）'},
        {'chrom': 'chr18', 'start': 42400000, 'end': 42900000, 'gene': 'SETBP1', 'type': 'gwas_locus', 'contribution_score': 0.30, 'note': 'SETBP1 区域（Pirastu 2017 locus 63, p=8.03E-25）'},
        {'chrom': 'chr6', 'start': 220000, 'end': 650000, 'gene': 'IRF4', 'type': 'gwas_locus', 'contribution_score': 0.40, 'note': 'IRF4 区域（Pirastu 2017 locus 32, p=2.35E-52）'},
        {'chrom': 'chr8', 'start': 108000000, 'end': 111000000, 'gene': 'RSPO2', 'type': 'gwas_locus', 'contribution_score': 0.30, 'note': 'RSPO2 区域（Pirastu 2017 locus 42, p=2.13E-22）'},
    ],
    'key_regions': {
        'AR': {
            'note': 'X 染色体雄激素受体，AGA 最强遗传决定因素',
            'regions': [
                {'name': 'N-terminal domain', 'residues': '1-558', 'note': '转录激活；含 CAG 重复多态'},
                {'name': 'DNA-binding domain', 'residues': '559-624', 'note': '结合雄激素应答元件'},
                {'name': 'Hinge/Ligand-binding domain', 'residues': '665-919', 'note': 'DHT/睾酮结合'},
            ],
            'critical_residues': [
                {'residue': 'Glu211', 'note': 'rs6152 同义位点，StuI RFLP 标记'},
            ],
        },
        'EDA2R': {
            'note': 'X 染色体 AGA 最强 GWAS 信号，调控毛囊细胞凋亡',
            'regions': [
                {'name': 'TNFR extracellular domain', 'residues': '1-137', 'note': '配体结合'},
                {'name': 'Death domain', 'residues': '200-268', 'note': '介导凋亡信号'},
            ],
            'critical_residues': [
                {'residue': 'rs1385699', 'note': 'AGA 最强关联位点所在区域'},
            ],
        },
        'SRD5A2': {
            'note': 'II 型 5α-还原酶，DHT 合成与非那雄胺靶点',
            'regions': [
                {'name': 'FAD-binding Rossmann fold', 'residues': '12-157', 'note': '辅酶结合'},
                {'name': '5alpha-reductase catalytic domain', 'residues': '158-240', 'note': '催化睾酮 to DHT；非那雄胺结合区'},
            ],
            'critical_residues': [
                {'residue': 'Ala49', 'note': 'rs9282858 A49T 影响酶活性'},
                {'residue': 'Val89', 'note': 'rs523349 V89L 影响酶稳定性与活性'},
            ],
        },
        'TWIST1': {
            'note': 'bHLH 转录因子，毛囊间充质干细胞调控',
            'regions': [
                {'name': 'bHLH DNA-binding domain', 'residues': '109-160', 'note': 'DNA 结合与二聚化'},
                {'name': 'WRPW motif', 'residues': '198-201', 'note': 'Groucho/TLE 共抑制子结合'},
            ],
            'critical_residues': [],
        },
        'FGF5': {
            'note': '成纤维细胞生长因子 5，毛囊周期调控',
            'regions': [
                {'name': 'FGF core domain', 'residues': '32-150', 'note': '受体结合与生物学活性'},
            ],
            'critical_residues': [],
        },
        'IRF4': {
            'note': '干扰素调节因子 4，凋亡通路',
            'regions': [
                {'name': 'IRF DNA-binding domain', 'residues': '1-119', 'note': 'DNA 结合（色氨酸五联重复）'},
                {'name': 'IRF association domain', 'residues': '225-450', 'note': '蛋白质相互作用'},
            ],
            'critical_residues': [],
        },
        'BCL2': {
            'note': '抗凋亡蛋白，凋亡通路',
            'regions': [
                {'name': 'BH4 domain', 'residues': '10-30', 'note': '抗凋亡功能必需'},
                {'name': 'BH3 domain', 'residues': '90-100', 'note': '促凋亡蛋白结合'},
                {'name': 'BH1-BH2 domain', 'residues': '130-205', 'note': '通道形成与促凋亡因子结合'},
            ],
            'critical_residues': [],
        },
        'WNT10A': {
            'note': 'Wnt 信号通路成员，毛囊发育',
            'regions': [
                {'name': 'Wnt signaling domain', 'residues': '1-417', 'note': 'Wnt 配体活性'},
            ],
            'critical_residues': [],
        },
    },
    'key_literature': [
        {
            'pmid': '29093463',
            'title': 'GWAS for male-pattern baldness identifies 71 susceptibility loci explaining 38% of the risk.',
            'genes': ['AR', 'EDA2R', 'HDAC9', 'WNT10A', 'TWIST1', 'IRF4', 'SETBP1', 'RSPO2', 'BCL2', 'DFFA'],
            'note': 'Nat Commun 2017; 70,000+ 男性 AGA GWAS，鉴定 71 个 loci（30 个新发现），解释 38% 遗传度；三条通路基因社区',
            'evidence_type': 'gwas',
        },
        {
            'pmid': '31501595',
            'title': 'Genetic prediction of male pattern baldness.',
            'genes': ['AR', 'EDA2R', 'HDAC9', 'WNT10A'],
            'note': 'PLoS Genet 2019; 基于 UK Biobank 205,000 男性的 AGA GWAS 与多基因预测模型',
            'evidence_type': 'gwas',
        },
        {
            'pmid': '28165477',
            'title': 'Genetic prediction of male pattern baldness from 52,000 UK Biobank participants.',
            'genes': ['AR', 'EDA2R', 'HDAC9'],
            'note': 'PLoS Genet 2017; UK Biobank AGA PRS 模型开发',
            'evidence_type': 'prs',
        },
        {
            'pmid': '23776682',
            'title': 'Genetic Variants at 20p11 Confer Risk to Androgenetic Alopecia in the Chinese Han Population.',
            'genes': ['PAX1', 'HDAC9'],
            'note': 'PLoS One 2013; 中国汉族人群验证 20p11 AGA 位点',
            'evidence_type': 'gwas',
        },
        {
            'pmid': '22032556',
            'title': 'Male-pattern baldness susceptibility locus at 20p11.',
            'genes': ['PAX1', 'FOXA2'],
            'note': 'Nat Genet 2011; 首次报道 20p11 AGA 易感位点，验证 AR/EDA2R 信号',
            'evidence_type': 'gwas',
        },
        {
            'pmid': '35241807',
            'title': 'PGS002314: Balding Type 1 polygenic score (Weissbrod et al. 2022).',
            'genes': [],
            'note': 'Nat Genet 2022; PGS Catalog 条目，1,109,311 个变异的全基因组 PRS',
            'evidence_type': 'prs',
        },
        {
            'pmid': '22693459',
            'title': 'Six novel susceptibility loci for early-onset androgenetic alopecia and their unexpected association with common diseases.',
            'genes': ['AR', 'EDA2R', 'HDAC9', 'WNT10A', 'RUNX3', 'TWIST1'],
            'note': 'PLoS Genet 2012; 12,806 人 meta-analysis，发现 6 个新 AGA loci；AGA 与帕金森病共享 17q21.31 风险',
            'evidence_type': 'gwas',
        },
    ],
}
