"""Disease template: breast cancer."""

TEMPLATE_NAME = 'breast_cancer'
TEMPLATE = {   'aliases': [   'breast cancer',
                   'breast carcinoma',
                   'hereditary breast cancer',
                   'familial breast cancer',
                   'hboc',
                   'hereditary breast and ovarian cancer',
                   'triple negative breast cancer',
                   'tnbc',
                   'er+ breast cancer'],
    'mode': 'complex',
    'gene_set': [   {   'gene': 'BRCA1',
                        'tier': 'mendelian_high',
                        'contribution_score': 1.0,
                        'penetrance': '>0.95',
                        'penetrance_score': 0.85,
                        'evidence': 'familial',
                        'note': '遗传性乳腺卵巢癌综合征(HBOC); 终身乳腺癌风险~55-72%; 三阴性乳腺癌倾向',
                        'phenotype_assoc': 'HBOC1(常显);乳腺癌(55-72%);卵巢癌(39-44%);三阴性倾向',
                        'key_domains': 'RING域(aa1-109);BRCT×2(aa1646-1863);DNA损伤应答',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'BRCA2',
                        'tier': 'mendelian_high',
                        'contribution_score': 1.0,
                        'penetrance': '>0.95',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': '遗传性乳腺卵巢癌综合征(HBOC); 终身乳腺癌风险~45-69%; 男性乳腺癌',
                        'phenotype_assoc': 'HBOC2(常显);乳腺癌(45-69%);卵巢癌(11-17%);男性乳腺癌;Fanconi贫血D1型(AR)',
                        'key_domains': 'BRC重复×8;DNA结合OB-fold;Tower域;PALB2结合',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'TP53',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.95,
                        'penetrance': 'high',
                        'penetrance_score': 0.85,
                        'evidence': 'familial',
                        'note': 'Li-Fraumeni综合征; 早发性乳腺癌(常<35岁); 多种原发肿瘤',
                        'phenotype_assoc': 'Li-Fraumeni(常显);早发乳腺癌;肉瘤;脑肿瘤;肾上腺皮质癌',
                        'key_domains': '反式激活域(aa1-42);DNA结合域(aa102-292);四聚化域(aa325-356)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'PTEN',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.9,
                        'penetrance': 'high',
                        'penetrance_score': 0.85,
                        'evidence': 'familial',
                        'note': 'Cowden综合征; 乳腺癌风险~25-50%; 甲状腺癌; 子宫内膜癌',
                        'phenotype_assoc': 'Cowden综合征(常显);乳腺癌(~25-50%);甲状腺癌;子宫内膜癌;巨头畸形',
                        'key_domains': '磷酸酶域(aa123-130);C2域(aa186-351);PDZ结合基序',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'STK11',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.9,
                        'penetrance': 'high',
                        'penetrance_score': 0.85,
                        'evidence': 'familial',
                        'note': 'Peutz-Jeghers综合征; 乳腺癌风险~32-54%; 胃肠道错构瘤息肉',
                        'phenotype_assoc': 'Peutz-Jeghers(常显);乳腺癌(32-54%);胃肠息肉;GI/胰腺/妇科癌症',
                        'key_domains': '激酶域(aa49-309);N端调节域;C端调节域',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'CDH1',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.9,
                        'penetrance': 'high',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': '遗传性弥漫性胃癌(HDGC); 小叶乳腺癌风险~39-52%',
                        'phenotype_assoc': 'HDGC(常显);小叶乳腺癌(39-52%);弥漫性胃癌',
                        'key_domains': '钙粘蛋白前体域;钙粘蛋白重复×5;跨膜域;β-catenin结合',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'PALB2',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.85,
                        'penetrance': 'high',
                        'penetrance_score': 0.7,
                        'evidence': 'familial',
                        'note': 'Fanconi贫血N型(AR); 杂合乳腺癌风险~33-58%',
                        'phenotype_assoc': 'Fanconi贫血N型(AR);乳腺癌(杂合~33-58%);BRCA2协同因子',
                        'key_domains': '卷曲螺旋域;WD40重复×7;BRCA1/BRCA2/RAD51结合',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'ATM',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.65,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.35,
                        'evidence': 'mixed',
                        'note': '共济失调毛细血管扩张症(AR); 杂合乳腺癌风险~2-3x',
                        'phenotype_assoc': 'AT(AR);杂合乳腺癌OR~2.4;DNA损伤应答激酶',
                        'key_domains': 'FAT域;PI3K/PI4K激酶域;FATC域',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'CHEK2',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.6,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'mixed',
                        'note': '细胞周期检查点激酶2; 1100delC等致病变异~2-3x乳腺癌风险',
                        'phenotype_assoc': '乳腺癌OR~2.5(1100delC);细胞周期G2/M检查点激酶',
                        'key_domains': 'SQ/TQ簇域;FHA域;激酶域',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'BARD1',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.55,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.25,
                        'evidence': 'mixed',
                        'note': 'BRCA1相关RING域蛋白1; BRCA1异源二聚体; 乳腺癌OR~2-3x',
                        'phenotype_assoc': '乳腺癌OR~2-3;BRCA1异源二聚体;DNA损伤修复',
                        'key_domains': 'RING域;ANK重复×3;BRCT×2',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'RAD51C',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.55,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.25,
                        'evidence': 'mixed',
                        'note': 'Fanconi贫血O型(AR); 杂合卵巢癌/乳腺癌风险',
                        'phenotype_assoc': 'Fanconi贫血O型(AR);卵巢癌风险;乳腺癌风险较低',
                        'key_domains': 'RAD51/REC-A样N端;ATP酶域;DNA结合',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'RAD51D',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.55,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.25,
                        'evidence': 'mixed',
                        'note': 'RAD51旁系同源蛋白D; 卵巢癌(OR~6x)及部分乳腺癌风险',
                        'phenotype_assoc': 'HR修复;卵巢癌OR~6;乳腺癌OR~2',
                        'key_domains': 'RAD51/REC-A样域;ATP结合',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'BRIP1',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.5,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.2,
                        'evidence': 'mixed',
                        'note': 'Fanconi贫血J型(AR); 杂合卵巢癌风险(OR~3-4x); 乳腺癌?',
                        'phenotype_assoc': 'Fanconi贫血J型(AR);卵巢癌OR~3.4;BRCA1结合解旋酶',
                        'key_domains': '解旋酶域;Fe-S簇;BRCA1结合C端',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'NBN',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.5,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.2,
                        'evidence': 'mixed',
                        'note': 'Nijmegen断裂综合征(AR); 杂合乳腺癌风险~2-3x',
                        'phenotype_assoc': 'NBS(AR);杂合乳腺癌OR~2.7;MRN复合体DNA修复',
                        'key_domains': 'FHA域;BRCT域;MRE11结合域;ATM结合',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'NF1',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.5,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'mixed',
                        'note': '神经纤维瘤病1型(AD); 50岁前乳腺癌风险~4x',
                        'phenotype_assoc': 'NF1(常显);乳腺癌<50yr OR~4;RAS负调控因子',
                        'key_domains': 'GAP相关域;Sec14-like域;PH-like域',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'RAD50',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.45,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.2,
                        'evidence': 'mixed',
                        'note': 'Nijmegen断裂样综合征; MRN复合体成员; 乳腺癌? 证据有限',
                        'phenotype_assoc': 'MRN复合体;NBS样(AR);乳腺癌关联证据有限',
                        'key_domains': 'ATP酶域;卷曲螺旋域;MRE11结合',
                        'clingen_validity': 'Limited'},
                    {   'gene': 'FGFR2',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.35,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '乳腺癌最强GWAS位点之一(内含子2变异); ER+乳腺癌',
                        'phenotype_assoc': 'FGFR2;乳腺癌GWAS最强;ER+乳腺癌;FGFR信号通路',
                        'key_domains': 'Ig-like C2型×3;蛋白激酶域',
                        'clingen_validity': ''},
                    {   'gene': 'ESR1',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.3,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '雌激素受体α; ER+乳腺癌核心GWAS位点; 内分泌治疗靶点',
                        'phenotype_assoc': 'ESR1/ERα;ER+乳腺癌;内分泌治疗靶点(tamoxifen/AI)',
                        'key_domains': 'AF-1;DNA结合锌指;配体结合域;AF-2',
                        'clingen_validity': ''},
                    {   'gene': 'TOX3',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.3,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'TNRC9/TOX3; 仅次于FGFR2的乳腺癌GWAS位点',
                        'phenotype_assoc': 'TOX3/TNRC9;乳腺癌GWAS(第二强);HMGB家族转录因子',
                        'key_domains': 'HMG-box域',
                        'clingen_validity': ''},
                    {   'gene': 'MAP3K1',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.28,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'MEKK1; JNK信号通路; 乳腺癌GWAS位点',
                        'phenotype_assoc': 'MAP3K1/MEKK1;乳腺癌GWAS;JNK/p38/MAPK信号级联',
                        'key_domains': 'RING锌指;激酶域;SWIM锌指',
                        'clingen_validity': ''},
                    {   'gene': 'CCND1',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'Cyclin D1; ER+乳腺癌GWAS; 细胞周期调控',
                        'phenotype_assoc': 'Cyclin D1;G1/S细胞周期;ER+乳腺癌GWAS',
                        'key_domains': 'Cyclin N;Cyclin C',
                        'clingen_validity': ''},
                    {   'gene': 'MYC',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '8q24乳腺癌GWAS位点; MYC原癌基因',
                        'phenotype_assoc': 'c-Myc;8q24乳腺癌GWAS;转录因子/细胞增殖',
                        'key_domains': 'bHLH;亮氨酸拉链(与MAX二聚化)',
                        'clingen_validity': ''},
                    {   'gene': 'ZNF365',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '乳腺癌GWAS位点(10q21)',
                        'phenotype_assoc': 'ZNF365;10q21乳腺癌GWAS;中心体/有丝分裂',
                        'key_domains': '锌指C2H2型',
                        'clingen_validity': ''},
                    {   'gene': 'LSP1',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '11p15.5乳腺癌GWAS位点; 白细胞特异性蛋白1',
                        'phenotype_assoc': 'LSP1;11p15乳腺癌GWAS;F-actin结合/免疫细胞迁移',
                        'key_domains': 'F-actin结合域;SH3-like',
                        'clingen_validity': ''},
                    {   'gene': 'RAD51B',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '14q24乳腺癌GWAS; RAD51旁系同源蛋白B; HR修复',
                        'phenotype_assoc': 'RAD51B/REC2;14q24乳腺癌GWAS;同源重组修复',
                        'key_domains': 'RAD51/REC-A样域;ATP结合',
                        'clingen_validity': ''},
                    {   'gene': 'CASP8',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '2q33乳腺癌GWAS; 凋亡起始caspase',
                        'phenotype_assoc': 'Caspase-8;2q33乳腺癌GWAS;外源凋亡起始蛋白酶',
                        'key_domains': 'DED×2;催化域',
                        'clingen_validity': ''},
                    {   'gene': 'TERT',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '5p15乳腺癌/多种癌症GWAS; 端粒酶催化亚基',
                        'phenotype_assoc': 'TERT;5p15乳腺癌GWAS;端粒酶催化亚基;多种癌症',
                        'key_domains': 'TERT/TERT_RBD/TERT_RNA;逆转录酶域',
                        'clingen_validity': ''},
                    {   'gene': 'ANKRD16',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '乳腺癌GWAS位点(10p13)',
                        'phenotype_assoc': 'ANKRD16;10p13乳腺癌GWAS;tRNA修饰/蛋白翻译',
                        'key_domains': 'ANK重复',
                        'clingen_validity': ''},
                    {   'gene': 'COX11',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '乳腺癌GWAS位点(17q22); 细胞色素c氧化酶组装因子',
                        'phenotype_assoc': 'COX11;17q22乳腺癌GWAS;线粒体呼吸链组装',
                        'key_domains': 'COX11/CtaG',
                        'clingen_validity': ''},
                    {   'gene': 'STXBP4',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '乳腺癌GWAS位点(17q22)',
                        'phenotype_assoc': 'STXBP4/Synip;17q22乳腺癌GWAS;GLUT4/SNARE调控',
                        'key_domains': 'WW域',
                        'clingen_validity': ''},
                    {   'gene': 'DMRT1',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '乳腺癌GWAS位点(9p24)',
                        'phenotype_assoc': 'DMRT1;9p24乳腺癌GWAS;性决定转录因子',
                        'key_domains': 'DM DNA结合域',
                        'clingen_validity': ''},
                    {   'gene': 'MIR2052HG',
                        'tier': 'gwas',
                        'contribution_score': 0.12,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '乳腺癌GWAS关联lncRNA(8q24)',
                        'phenotype_assoc': 'MIR2052HG;8q24乳腺癌lncRNA GWAS位点',
                        'key_domains': '',
                        'clingen_validity': ''}],
    'known_pathogenic_variants': [   {   'rsid': 'rs80357906',
                                         'chrom': 'chr17',
                                         'pos': 43092958,
                                         'ref': 'A',
                                         'alt': 'G',
                                         'gene': 'BRCA1',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 1.0,
                                         'confidence': 'high',
                                         'note': 'BRCA1 c.68_69delAG (185delAG) — Ashkenazi founder'},
                                     {   'rsid': 'rs80357304',
                                         'chrom': 'chr17',
                                         'pos': 43063359,
                                         'ref': 'T',
                                         'alt': 'G',
                                         'gene': 'BRCA1',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 1.0,
                                         'confidence': 'high',
                                         'note': 'BRCA1 c.5266dupC (5382insC) — Ashkenazi founder'},
                                     {   'rsid': 'rs80359550',
                                         'chrom': 'chr13',
                                         'pos': 32316524,
                                         'ref': 'T',
                                         'alt': 'C',
                                         'gene': 'BRCA2',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 1.0,
                                         'confidence': 'high',
                                         'note': 'BRCA2 c.5946delT (6174delT) — Ashkenazi founder'},
                                     {   'rsid': 'rs28934573',
                                         'chrom': 'chr17',
                                         'pos': 7674877,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'TP53',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 1.0,
                                         'confidence': 'high',
                                         'note': 'TP53 R248W — Li-Fraumeni hotspot'},
                                     {   'rsid': 'rs28934576',
                                         'chrom': 'chr17',
                                         'pos': 7675083,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'TP53',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 1.0,
                                         'confidence': 'high',
                                         'note': 'TP53 R273H — Li-Fraumeni hotspot'},
                                     {   'rsid': 'rs555607708',
                                         'chrom': 'chr22',
                                         'pos': 28695868,
                                         'ref': 'T',
                                         'alt': 'C',
                                         'gene': 'CHEK2',
                                         'effect_allele': 'C',
                                         'or_value': 2.5,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.8,
                                         'confidence': 'high',
                                         'note': 'CHEK2 1100delC — 欧洲人群乳腺癌OR~2.5'},
                                     {   'rsid': 'rs180177138',
                                         'chrom': 'chr16',
                                         'pos': 23646280,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'PALB2',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.9,
                                         'confidence': 'high',
                                         'note': 'PALB2 c.3113G>A (W1038X) — 芬兰founder'},
                                     {   'rsid': '3780928',
                                         'chrom': '10',
                                         'pos': 87863231,
                                         'ref': 'A',
                                         'alt': 'G',
                                         'gene': 'PTEN',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | PTEN hamartoma tumor syndrome'},
                                     {   'rsid': '3780927',
                                         'chrom': '10',
                                         'pos': 87863292,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'PTEN',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | PTEN hamartoma tumor syndrome'},
                                     {   'rsid': '576830',
                                         'chrom': '19',
                                         'pos': 1205798,
                                         'ref': 'GGCGTGTCGGGCGCGGAAGGGGGAGGCGGCCCGGGGCGCCCGCGAGTGAGGCGCGGGGCGGCGAAGGGAGCGCGGGTGGCGGCACTTGCTGCCGCGGCCTTGGATGGGCTGGGCCCCCCTCGCCGCTCCGCCTCCTCCACACGCGCGGCGGCCGCGGCGAGGGGGACGCGCCGCCCGGGGCCCGGCACCTTCGGGAACCCCCCGGCCCGGAGCCTGCGGCCTGCGCCGCCTCGGCCGCCGGGAGCCCCGTGGAGCCCCCGCCGCCGCGCCGCCCCGCGGACCGGACGCTGAGGGCACTCGGGGCGGGGCGCGCGCTCGGGCAGACGTTTGCGGGGAGGGGGGCGCCTGCCGGGCCCCGGCGACCACCTTGGGGGTCGCGGGCCGGCTCGGGGGGCGCCCAGTGCGGGCCCTCGCGGGCGCCGGGCAGCGACCAGCCCTGAGCGGAGCTGTTGGCCGCGGCGGGAGGCCTCCCGGACGCCCCCAGCCCCCCGAACGCTCGCCCGGGCCGGCGGGAGTCGGCGCCCCCCGGGAGGTCCGCTCGGTCGTCCGCGGCGGAGCGTTTGCTCCTGGGACAGGCGGTGGGACCGGGGCGTCGCCGGAGACGCCCCCAGCGAAGTTGGGCTCTCCAGGTGTGGGGGTCCCGGGGGGTAGCGACGTCGCGGACCCGGCCTGTGGGATGGGCGGCCCGGAGAAGACTGCGCTCGGCCGTGTTCATACTTGTCCGTGGGCCTGAGGTCCCCGGAGGATGACCTAGCACTGAAAAGCCCCGGCCGGCCTCCCCAGGGTCCCCGAGGACGAAGTTGACCCTGACCGGGCCGTCTCCCAGTTCTGAGGCCCGGGTCCCACTGGAACTCGCGTCTGAGCCGCCGTCCCGGACCCCCGGTGCCCGCCGGTCCGCAGACCCTGCACCGGGCTTGGACTCGCAGCCGGGACTGACGTGTAGAACAATCGTTTCTGTTGGAAGAAGGGTTTTTCCCTTCCTTTTGGGGTTTTTGTTGCCTTTTTTTTTTCTTTTTTCTTTGTAAAATTTTGGAGAAGGGAAGTCGGAACACAAGGAAGGACCGCTCACCCGCGGACTCAGGGCTGGCGGCGGGACTCCAGGACCCTGGGTCCAGCATGGAGGTGGTGGACCCGCAGCAGCTGGGCATGTTCACGGAGGGCGAGCTGATGTCGGTGGGTATGGACACGTTCATCCACCGCATCGACTCCACCGAGGTCATCTACCAGCCGCGCCGCAAGCGGGCCAAGCTCATCGGCAAGTACCTGATGGGGGACCTGCTGGGGGAAGGCTCTTACGGCAAGGTGAAGGAGGTGCTGGACTCGGAGACGCTGTGCAGGAGGGCCGTCAAGATCCTCAAGAAGAAGAAGTTGCGAAGGATCCCCAACGGGGAGGCCAACGTGAAGAA',
                                         'alt': 'G',
                                         'gene': 'STK11',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Peutz-Jeghers syndrome'},
                                     {   'rsid': '1050750',
                                         'chrom': '19',
                                         'pos': 1206911,
                                         'ref': 'AGCATGGAGGTGGTGGACCCGCAGCAGCTGGGCATGTTCACGGAGGGCGAGCTGATGTCGGTGGGTATGGACACGTTCATCCACCGCATCGACTCCACCGAGGTCATCTACCAGCCGCGCCGCAAGCGGGCCAAGCTCATCGGCAAGTACCTGATGGGGGACCTGCTGGGGGAAGGCTCTTACGGCAAGGTGAAGGAGGTGCTGGACTCGGAGACGCTGTGCAGGAGGGCCGTCAAGATCCTCAAGAAGAAGAAGTTGCGAAGGATCCCCAACGGGGAGGCCAACGTGAAGAAGTAAGTATGGCTTGCTGGGGTCGGGGCCGGGCCGGGCCAGTCACGGTGCTGATGGTTCTGTCTTCCTTCCTTCTCTCCTCCCTCCCTCCCTTACTTCCTCTTAACACCCTGAGCTGGACCCGTCTGGCGCCTGTGTCCTCCGTGCCAGGGAGAGCGTGGTTGGGGGCCTGCGTTACGGACTTTCACTCAGGCAAGGCCAGTTGTCGCAGCGGGGCGTGCGTTTGCATGGGCTCTTGGACTCCAGTTAAAATGCCCTGGTAGCGAAACCCTCCTGAGAAGGGAGCGGCCCCCAATCCCCTAAGACTAGCCCCTTGGCTCCCCCAGCTGTCCAAGGAGCAGAGGCGCCCAGTGGAATCAGCCTGTGTTTGTTTGGGCCCCGAGAGTTTGTGTGCGGCCGCCAACACGTTTTCTGCGCAGTGTGTGGCCGTTACCGGGGCCAGGCGAAATGTGATTTGTTTATCCTGTCAGAGGGGAACCCTGGGCTGCCAAAAATAACTGTTTGCACCGGCTTATCAGTCAGCAGGAGGGAAACGTAGCCTTTCCTCATTTGCCAGGGATGTGACGCTGGAAGCATCCCTGGCCCCCGGGGCTGGAAGCCCTGCCCGAGGGGGACTGTGCCTCCCTCCCGAATTGCATCCGGAAGACCTTACTTTTCCAACTGACTTCTTCAGGCACGGGGCTGCCGCTGGGCATCCCGGACGCCTCTGCATCTGTGCGCGGAGAAGCTCCTACCTAGGGCAGCACTGGCCGGCCTGAGCCTCTCCCAGCTGGTGGGGGTGGCCGGGGGTGTCCCTGCCTTATCGCAGCCAGACACGCTGCACCTGCCGCCGCCTGGCGGGCCCTGCCCAGGCCCTGCTCCTTTCCCAGCCTTCTTAACTTTCAAAACTTTGCCTCCTGTTTCCAAGAAAGGACCTTATCTGCTGGGCTAGGCCTCGAGGGACTGGCAAGGACACCCTGCGCAGGGCACCATGACCTTGGAAGGAGGTCCGGGGAGGGGCTGCTGCGGTGTCTGC',
                                         'alt': 'A',
                                         'gene': 'STK11',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Generalized juvenile polyposis/juvenile '
                                                 'polyposis coli'},
                                     {   'rsid': '532457',
                                         'chrom': '16',
                                         'pos': 68737416,
                                         'ref': 'A',
                                         'alt': 'G',
                                         'gene': 'CDH1',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.8,
                                         'confidence': 'high',
                                         'note': 'ClinVar: Pathogenic | Hereditary cancer-predisposing '
                                                 'syndrome|Hereditary diffuse gastric adenocarcinom'},
                                     {   'rsid': '2035285',
                                         'chrom': '16',
                                         'pos': 68737416,
                                         'ref': 'A',
                                         'alt': 'T',
                                         'gene': 'CDH1',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic/Likely_pathogenic | Hereditary '
                                                 'cancer-predisposing syndrome|Hereditary diffuse gastric '
                                                 'adenocarcinom'},
                                     {   'rsid': '3780824',
                                         'chrom': '11',
                                         'pos': 108223043,
                                         'ref': 'A',
                                         'alt': 'G',
                                         'gene': 'ATM',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | ATM-related cancer predisposition'},
                                     {   'rsid': '550420',
                                         'chrom': '11',
                                         'pos': 108223781,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'ATM',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Ataxia-telangiectasia '
                                                 'syndrome|ATM-related cancer predisposition'},
                                     {   'rsid': '1049655',
                                         'chrom': '2',
                                         'pos': 214728673,
                                         'ref': 'TATTCAGCTGTCAAGAGGAAGCAACTCAAAGGACATCACACAGTCTATAAACCAGCTCGAAGGAGCCTTCCAGACTTTGCCCTGCCGAACCCTCTCTGGGTGATAATTACACAAATCTTCATAGATGATATACTGTGTGCAGAAGCGCTGATCAGAATCGGGTCTCGCATGGTATGCGACTGTATTGATGGTCTGAGTCACGTCACTGTCTGGCTTGGGCTTTCTACTGAGGATCTGGCCCCCACCTGCAGTGACGAGCTTAATAAGGTTGTCCTTTGGATGGTGTTTGAAGGTTCCCCACAAATAGAAGTAGCATCCATCAAACAGCTTTGGCAACTGAAATAATGAGAAAACATTTGTTAAAGGCAGATCAAAATACTGTATTCAAAAACACTGTATATGAATGAGGAAAATAAAAATACAAGTTGAATATCCCTTACCTGAAACATTTGGAGGAGAAGCATTTCAGATTCATAAATTTTTTGGGTTTTGGAAAATTTGCATATACATGAGGTATCTTAAGGATGAGGCTCAAGCCTAAACACAAAATTCGTTTGTTTCTTGTACACCTTATGCACATAGCCTGAAGTAATTTTATACAATATCTTCAGTAATTTTGTGCATGAAACAAAATTTTGACTGTGTTCTGACCGTGACCTGTCACATGAGGTCAGGTGTGGAATTTTCCACTTGTGGCATCATGTCAAAGCTCAAAAAGTTTTGGATTTTGGAGCATTTTAGATGTTGGATTAGGAATGCTCCATCTGTAACAATTATGAGCAGCTAAGAAGCTACTTAATGAGGTGCTGGGACAAGTTATATTTCAAGCATACTAACTGGATCAAGAAAAATACTTAGGCAAATAGGGGCTTCCTATTTACAATTTTTTCCCTAAGATTCAGTCACCATCTCGGTTCCTTTTCACTCTTCTAAAATTTTAGATATGCTTGGTATAAAGAAAAAAACAAACTATTCATCAAACTTTTTTCATCAGGATGTTTATGCTTATTTGGTGGGACTTAAAGCCTCCACAACTCCTAGCTTATTTGAAATAGGCTTCAGAGACACCAGGCTAAACATTATTAAATTACAAGAGTAACATCTTTTCCGTGGACTTTTATCCAATTCTGCCCATCCACATTCAGGTCCTTACATATTACCAACCTAAGGTCTCCAGGGCAGCCACCATGGGGGTGTGCCCTCCAGGGTTCCAGAAATGTATTCACGGGGCACAAAAGATTTTTGTGCTGAGGCTAGGGATCCAATTAGCTATGAAACATACTTCCGTATGCTCGTTGGAAATAAAAAAAGTTTCATAATTCCCTTCTATGGAAATTTTCTTTGTGACTTCTAATATACTTATATAATATCAACAGGATAATGCGATATTATCCATTAAAGCTACAATATGTGGCCATAGAGACATATGGTAACTAAATCCAAGCAGCAGCTGTAAGTCTTCTTTCAAGCTACTTCCTGTATCTGAGATTTACCTCAGATTCTGAAAGGTTTATGGCAATGTTCAAGATGCCAAAAATCCATTAACAGTATGAAATTATTACCTTCTGGATTTTACTGCTCATCGTGATCATCTTTCAGAATCAAGTGCTTGAAATAAGCACAATTAAAATTTTAATCAGTCACCTGTAGCTGTTGAAAGGGCAGAAGTTCTTCCTGATGGTGATAATAATAGTATGTCATAATAAGAACAATGAAAGTTGTATTAAAAGAAAAATACCAGCTGTTCTCTGTTGAGCCTGCTTCTGCGTGGACCTTCAGGAATTTCATACTTTTCTTCCTGTTCACATACTTTTCTTCGTAGACATGCTTTTACCCCTGACAAAAACACAAGAATTAAAGCAAACTAAGTATCAAGTGAGCACTATATCTCTCTCATTAAAATCAAGCAATTTACCTAAGTGGTTTTTCTTCTTCATGGCAGTTTTTAAGTATTATTCTAAAATGCAAACAGAAATCTTACTTATGCCAAAACAAAATGTAATACAACTGGTTTTCCCATATAAAGAAAATATTTTAAAAAACTCTTTCTTTGGAGGATTAAGCCATAAGTTAGTACTGAACACTAACTGTAATTTTAATCTCCTTTCTGAAAAACCTAAGCCAGGATACTATTTCAAAGACAAAAATAAAAGTCTACATTTCCACTCATAGCAATTACCCAAAATTAAGGTGAATAAAAAGTCCATGACACAATAACCTAAACTGAGCACTTACCATCTATACTGCTCATTTTGACAGTTATATGTCTAATCGTCTGTTAAACTGTAAGTGATTTGACATGAAGGAATGTGCTTTAGTCTACAGCACCAAGCTCAGC',
                                         'alt': 'T',
                                         'gene': 'BARD1',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Malignant tumor of breast'},
                                     {   'rsid': '1789295',
                                         'chrom': '2',
                                         'pos': 214728707,
                                         'ref': 'ATC',
                                         'alt': 'GATGT',
                                         'gene': 'BARD1',
                                         'effect_allele': 'GATGT',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Hereditary cancer-predisposing '
                                                 'syndrome'},
                                     {   'rsid': '1098890',
                                         'chrom': '17',
                                         'pos': 58692629,
                                         'ref': 'GCAGGTGAGCCTGCGATGCGCGGGAAGA',
                                         'alt': 'G',
                                         'gene': 'RAD51C',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Breast-ovarian cancer, familial, '
                                                 'susceptibility to, 3'},
                                     {   'rsid': '2848340',
                                         'chrom': '17',
                                         'pos': 58692667,
                                         'ref': 'T',
                                         'alt': 'TGAAATGCAGCGGGGCCGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGCGGATCACGAGGTCAGGNNNNNNNNNNAAAAAAAAAAAAAAAAAAAA',
                                         'gene': 'RAD51C',
                                         'effect_allele': 'TGAAATGCAGCGGGGCCGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGCGGATCACGAGGTCAGGNNNNNNNNNNAAAAAAAAAAAAAAAAAAAA',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Fanconi anemia complementation group O'},
                                     {   'rsid': '986729',
                                         'chrom': '17',
                                         'pos': 35099487,
                                         'ref': 'AAAGATACTGAAGATTAATTTCTCCTGAGGTCTTCTGTGAAAGCAAGCGCTAGGATTCCCCCAGGCTTAGGCTTACCAACCCTGTCCTGAATCCAACACCCTGGTGCCAGTTTGCCACTCCTTCCCAATCCTCCATGATTCTATCCCTGTTGCATTCATCACCTCTAAATGTCATTACTTTCTGAGTGTAACTCGGACCCTCCTTTCCTGCAGCCAAGACATAACTGATTAATTACACAACAGGCTCTCTAACCAAGAAAGATGACCTTCCTTTAAAAGATGTGGCCAGTAACCAATCCTGATCATTTCTGTACTTTTCCTTTTATTTTCCATTCCCTGGTGTCTTCGTCCCCTCCCAGCCAGGGTCATGGCTCTCAGACGGATGGCCACAGTGCTGGTGAAAGACAGAGGGATTATTTCATACACTAGGGCACTAGCTGTGGTACAGCTGGCAGGAAGAGAGGTGTAATTATATTGCATCTTGGAGCCACCAGCAATGAATTTCTGCATAAAGGACTAGATTTGCCATGTATTATTTACGTCAGCATCAATTTTCCCAGCTGGCTCTATTTACTGTGCAAATTCTCCTCTGTCTGTTTATGGGCAAGGCCATGGTTCAGCACCTCTGGTTATGCTGTACTGTGGAGGGGCCCCACAGGGCACCATGCATATTAAATGAGTGGCTGGATTCACCAGGAGCAGGTCATACCCTCCCTTTCTGTTAAATTATATCCCTGGAACTGCAGCGAGCCCACACGTTCTCACCTAGTCATGGTGATGCAGGCAGGTCTGAAACCAAATCAGCAAGAGGAAAGGAGGAATAAACTGTTCTTTGGGCCTCACTGGGGGAAACTGAAAAACAGCCTTCTAAGGGGAAATCAGGTGGCTCTAGGGCTCGGGGAATTGCCTTTTTATATTTTTAAGAGCAAAACAGAGATGAAGAAGAGTATTTCATTTATAAGCTTATTTCCACCCAGTAACTCAGAGACAGAGCTAAGGAAGAGTGGGCCCCCATCTAACAAATGGAAAGGCAGAGACAAAAGAAAAAAAAGGCAGCAGCAGCAAAGGCAAGTTAGAGGCTTTCCCGGCTTGGCCACTGCGCTAGGAGGGAGCACAGGACACAATGGTGATGCACAGGATTATCCATCCAGTCGCCAGCATGCCTCATCAGAGATGCTCCCAGCCAGGGTGAACTTGGTTTCCACCAGAAACATACACGTTAGAAATAAGGGAAGGAAACGTGGCACCAGTATGAATTTCTGGGTCCTCGCAATGCAGCATCCTCTTTCGCCTGTGGTTTATATGCTTACAGAGAGTGAGGCCAAGGAACCCAAGATGTCTCTTCTGGCCAGCCTGAGAACGTCTGTAGTCACCAGTGCCAGGTGGCAGTAAACAGCAGGCGTTACTGGGAAGAAAAGTTGGGAGGGGTCCCCAATGCTTCCCTGTTTCCCAAACAACAGCACAGGTCATGTCTGATCACCCTGTAATGTGGCACTCTGCTCTGAGGTCCCCCAGGTCCCAATGTCTACCATCTCCTGGAAACCTGTTGGCTGGAAGAAGAAGTAAGGAGTCAGTGGAGTTAAGCAACCCAAGTGGGTAGCTTCTTTAGTTGCAAGGTTTCAGCCTCTAAAGAGTTCTTCTCGAAGACATCTGTGGGTATGGAAACCACCCTCCAGGGCCCAAGATTACTGGCATCTTCCTGGGGCTGGCTCACCTGTCGGGAAGATTTGGCCAGACACGCCATGCGCCGGCCGCCTGATGCTCCTGCTCCCTCGATGGTGTCCAGGAGAATCCGAGTGCTGGGCACAAAGCTCCAGGAGCGTCCGAGGGCAGGTTTGAGCCTCCCGCTGTCCCTGTCTCGAGTTATGTGGTTGGTCACCTGCAGCAGAAACAGACTTACAGATCCATAATGCTAGTATAGAGGACATCGATTACTACCGCTTCATTTTACGGAGAGGAAAACAGAGGCCTAGCACAGAGAAATAACTTCCCCAAGGTTACAAAACCTAATGGCAGGTCTGGAACTAGAACCTGGGCCTCCTGACTTGTGCCCCGCTCTTTCCACTAAATCTCGATGCCTCAGGTTTGACCCGAACCAGAAGGCGATGGGGCACATGTCACCATGCTTTCCAGGCTGGTCTCAAACTCTTGAGCTCATGCAGTCCGCCAGCCTCAGCCTCCCAAAGTGCTGGGATTACAAGTGTGGGCCACCACGCCCAGACACTCAGCCTTTAAAAGGAAGGAAAGTCTGACACATGCTACAAGGTGGATGAACCTTCTGGACATTATGCTAAGTGAAATACTCCAGTCACAAAAAGTAAATACCATATGATTCCATGTATATGAGGTTCCTAGAGTAGTCAAAAAGCATAGATACAGAAAGTAGAATGGTGGTTGTCAGGGGCTGGGGAAGGGGAAAATGAGTTATTTTTAATGGGTACAGAGTTTCAGTTTTACAAGGTGAAGAGTTATAGAGATGGATGGTGGTGATGGTTGTACAGCGTTATGAATGTATTTAACACCACCGAACTGTATACCTTAAAGTGGTTAAGATAGTAAATTTTATGTTACATGTATTTTACCACAATAAAAGAAACTGGAAAAAATATATAGCTGCTAAAAATTACATTTCTAAAAAATCTATTTTAAAACATAGGAAATGGACTCAGATGGTATTTTTTATGTTGTTGTTTTGGTTTGTTTGTTTTTGAGATGAGGTTTTGCTCTGTTGCCCAGGCTGGAGTGCAGTGGCATGATCACAGCTCACTGCAGCCTCGATCTCCCAGGCTCAAGCAATTCTCCTGCCACCAAGGCCACCTAGTTTTTGTATTTTTTGTAGAGGTGGGGTTTTGCCATGTTGCCCAGGCTAGTCTCGAACTCCTGGGCTCAAGTGATCCACCAGCCTTGGCTTCTCAAAGTGCTGGGATTACACGCATAAACCAGCGCACCTGGCCTATTTTTTTTTATTTTTTCATGAGGTTAGTTTAGTTAGAAAGCTGGTTAAGTGTGGGCTCACACCTGTAATACCAACACTTTGGGAGGCTGAGGCGGGTGGATTGCTTGAGCCTGGAAGGTCGAGCTGCAGTGAGCTGTGATTGTGCCCCTGCACTCCAGCCTGGGAAACAGAGCGAAACCCTATCTCAAAAGAAAAAAAAAAGAAAGAAAGAAAGTTGGCTAAAAGTATAAGTAAATATGCAGAAAAAGTATTGTATGGAGATATGTAAAAATATTAATATGGTTTCTGTGGATGTGGAGATTGATGACAAATTTGAATCATATTTATTTTCTATCCTTTCTATGAGAAGCATGCAGACTTTAAAAAAACTACCTCATAAGCAGAAAAAGTTACTTCAATAGCAAAAAGAT',
                                         'alt': 'A',
                                         'gene': 'RAD51D',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Malignant tumor of breast'},
                                     {   'rsid': '1516502',
                                         'chrom': '17',
                                         'pos': 35100447,
                                         'ref': 'AGCTTATTTCCACCCAGTAACTCAGAGACAGAGCTAAGGAAGAGTGGGCCCCCATCTAACAAATGGAAAGGCAGAGACAAAAGAAAAAAAAGGCAGCAGCAGCAAAGGCAAGTTAGAGGCTTTCCCGGCTTGGCCACTGCGCTAGGAGGGAGCACAGGACACAATGGTGATGCACAGGATTATCCATCCAGTCGCCAGCATGCCTCATCAGAGATGCTCCCAGCCAGGGTGAACTTGGTTTCCACCAGAAACATACACGTTAGAAATAAGGGAAGGAAACGTGGCACCAGTATGAATTTCTGGGTCCTCGCAATGCAGCATCCTCTTTCGCCTGTGGTTTATATGCTTACAGAGAGTGAGGCCAAGGAACCCAAGATGTCTCTTCTGGCCAGCCTGAGAACGTCTGTAGTCACCAGTGCCAGGTGGCAGTAAACAGCAGGCGTTACTGGGAAGAAAAGTTGGGAGGGGTCCCCAATGCTTCCCTGTTTCCCAAACAACAGCACAGGTCATGTCTGATCACCCTGTAATGTGGCACTCTGCTCTGAGGTCCCCCAGGTCCCAATGTCTACCATCTCCTGGAAACCTGTTGGCTGGAAGAAGAAGTAAGGAGTCAGTGGAGTTAAGCAACCCAAGTGGGTAGCTTCTTTAGTTGCAAGGTTTCAGCCTCTAAAGAGTTCTTCTCGAAGACATCTGTGGGTATGGAAACCACCCTCCAGGGCCCAAGATTACTGGCATCTTCCTGGGGCTGGCTCACCTGTCGGG',
                                         'alt': 'A',
                                         'gene': 'RAD51D',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Breast-ovarian cancer, familial, '
                                                 'susceptibility to, 4'},
                                     {   'rsid': '1801596',
                                         'chrom': '17',
                                         'pos': 61683453,
                                         'ref': 'A',
                                         'alt': 'AT',
                                         'gene': 'BRIP1',
                                         'effect_allele': 'AT',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Gastric cancer'},
                                     {   'rsid': '1713220',
                                         'chrom': '17',
                                         'pos': 61683518,
                                         'ref': 'T',
                                         'alt': 'TA',
                                         'gene': 'BRIP1',
                                         'effect_allele': 'TA',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Ovarian cancer'},
                                     {   'rsid': '554991',
                                         'chrom': '8',
                                         'pos': 89935609,
                                         'ref': 'G',
                                         'alt': 'C',
                                         'gene': 'NBN',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Microcephaly, normal intelligence and '
                                                 'immunodeficiency'},
                                     {   'rsid': '1801525',
                                         'chrom': '8',
                                         'pos': 89935613,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'NBN',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Gastric cancer'},
                                     {   'rsid': '3780883',
                                         'chrom': '17',
                                         'pos': 31095037,
                                         'ref': 'A',
                                         'alt': 'C',
                                         'gene': 'NF1',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Neurofibromatosis, type 1'},
                                     {   'rsid': '1404731',
                                         'chrom': '17',
                                         'pos': 31095037,
                                         'ref': 'A',
                                         'alt': 'G',
                                         'gene': 'NF1',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Neurofibromatosis, type 1'},
                                     {   'rsid': '229813',
                                         'chrom': '5',
                                         'pos': 132557325,
                                         'ref': 'A',
                                         'alt': 'G',
                                         'gene': 'RAD50',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Hereditary cancer-predisposing '
                                                 'syndrome'},
                                     {   'rsid': '128024',
                                         'chrom': '5',
                                         'pos': 132557327,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'RAD50',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic/Likely_pathogenic | Hereditary '
                                                 'cancer-predisposing syndrome|not provided|Nijmegen breakage '
                                                 'syndrome-'}],
    'gwas_lead_snps': [   {   'rsid': 'rs2981579',
                              'chrom': 'chr10',
                              'pos': 121558475,
                              'beta': 0.25,
                              'or_value': 1.28,
                              'eaf_eur': 0.4,
                              'eaf_eas': 0.45,
                              'gene': 'FGFR2',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.3,
                              'confidence': 'high',
                              'note': 'FGFR2 intron 2 — BCAC GWAS lead SNP'},
                          {   'rsid': 'rs3803662',
                              'chrom': 'chr16',
                              'pos': 52372689,
                              'beta': 0.2,
                              'or_value': 1.22,
                              'eaf_eur': 0.25,
                              'eaf_eas': 0.45,
                              'gene': 'TOX3',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.25,
                              'confidence': 'high',
                              'note': 'TOX3/TNRC9 — BCAC GWAS'},
                          {   'rsid': 'rs889312',
                              'chrom': 'chr5',
                              'pos': 56071811,
                              'beta': 0.15,
                              'or_value': 1.16,
                              'eaf_eur': 0.28,
                              'eaf_eas': 0.25,
                              'gene': 'MAP3K1',
                              'effect_allele': 'C',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.2,
                              'confidence': 'high',
                              'note': 'MAP3K1 — BCAC GWAS'},
                          {   'rsid': 'rs554219',
                              'chrom': 'chr11',
                              'pos': 69595540,
                              'beta': 0.18,
                              'or_value': 1.19,
                              'eaf_eur': 0.55,
                              'eaf_eas': 0.6,
                              'gene': 'CCND1',
                              'effect_allele': 'G',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.18,
                              'confidence': 'high',
                              'note': 'CCND1 — BCAC GWAS'},
                          {   'rsid': 'rs3817198',
                              'chrom': 'chr11',
                              'pos': 1906639,
                              'beta': 0.12,
                              'or_value': 1.13,
                              'eaf_eur': 0.3,
                              'eaf_eas': 0.1,
                              'gene': 'LSP1',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': 'LSP1 — BCAC GWAS'},
                          {   'rsid': 'rs999737',
                              'chrom': 'chr14',
                              'pos': 68206635,
                              'beta': 0.12,
                              'or_value': 1.12,
                              'eaf_eur': 0.22,
                              'eaf_eas': 0.2,
                              'gene': 'RAD51B',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': 'RAD51B — BCAC GWAS'},
                          {   'rsid': 'rs10941679',
                              'chrom': 'chr5',
                              'pos': 44714974,
                              'beta': 0.15,
                              'or_value': 1.16,
                              'eaf_eur': 0.25,
                              'eaf_eas': 0.3,
                              'gene': 'FGF10',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'moderate',
                              'note': 'FGF10/MRPS30 — BCAC GWAS'},
                          {   'rsid': 'rs13387042',
                              'chrom': 'chr2',
                              'pos': 216109926,
                              'beta': 0.18,
                              'or_value': 1.2,
                              'eaf_eur': 0.49,
                              'eaf_eas': 0.85,
                              'gene': 'TNP1',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.18,
                              'confidence': 'high',
                              'note': '2q35 — BCAC GWAS (long-range ESR1 regulation)'},
                          {   'rsid': 'rs10069690',
                              'chrom': 'chr5',
                              'pos': 1279722,
                              'beta': 0.15,
                              'or_value': 1.16,
                              'eaf_eur': 0.25,
                              'eaf_eas': 0.2,
                              'gene': 'TERT',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': 'TERT — BCAC GWAS'},
                          {   'rsid': 'rs1045485',
                              'chrom': 'chr2',
                              'pos': 201288432,
                              'beta': 0.08,
                              'or_value': 1.08,
                              'eaf_eur': 0.88,
                              'eaf_eas': 0.95,
                              'gene': 'CASP8',
                              'effect_allele': 'C',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.12,
                              'confidence': 'high',
                              'note': 'CASP8 — BCAC GWAS'},
                          {   'rsid': 'rs62355902',
                              'chrom': 'chr5',
                              'pos': 5830916,
                              'beta': None,
                              'or_value': 1.1,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'ZSWIM5',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'BCAC GWAS (Michailidou 2017)'},
                          {   'rsid': 'rs9790517',
                              'chrom': 'chr5',
                              'pos': 88202625,
                              'beta': None,
                              'or_value': 1.08,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'TCERG1',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BCAC GWAS (Michailidou 2017)'},
                          {   'rsid': 'rs132390',
                              'chrom': 'chr1',
                              'pos': 121024011,
                              'beta': None,
                              'or_value': 1.08,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'EMBP1',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BCAC GWAS (Michailidou 2017)'},
                          {   'rsid': 'rs12422552',
                              'chrom': 'chr12',
                              'pos': 14349336,
                              'beta': None,
                              'or_value': 1.05,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'ERP27',
                              'effect_allele': 'G',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BCAC GWAS (Michailidou 2017)'},
                          {   'rsid': 'rs4973768',
                              'chrom': 'chr3',
                              'pos': 27387118,
                              'beta': None,
                              'or_value': 1.11,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'SLC4A7',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'BCAC GWAS (Ahmed 2009/Michailidou 2017)'},
                          {   'rsid': 'rs6504950',
                              'chrom': 'chr17',
                              'pos': 55080413,
                              'beta': None,
                              'or_value': 1.05,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'STXBP4',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BCAC GWAS (Michailidou 2017)'},
                          {   'rsid': 'rs1432679',
                              'chrom': 'chr8',
                              'pos': 29513801,
                              'beta': None,
                              'or_value': 1.07,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'EBF1',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BCAC GWAS (Michailidou 2017)'},
                          {   'rsid': 'rs11780156',
                              'chrom': 'chr8',
                              'pos': 128352613,
                              'beta': None,
                              'or_value': 1.07,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'MYC',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': '8q24 BCAC GWAS (Michailidou 2017)'},
                          {   'rsid': 'rs7904519',
                              'chrom': 'chr10',
                              'pos': 113116916,
                              'beta': None,
                              'or_value': 1.06,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'TCF7L2',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BCAC GWAS (Michailidou 2017)'},
                          {   'rsid': 'rs17356907',
                              'chrom': 'chr12',
                              'pos': 95600391,
                              'beta': None,
                              'or_value': 1.1,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'NTN4',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'BCAC GWAS (Michailidou 2017)'}],
    'regions': [   {   'chrom': 'chr17',
                       'start': 43030295,
                       'end': 43125483,
                       'gene': 'BRCA1',
                       'rtype': 'coding',
                       'source': 'clinvar_pathogenic',
                       'note': 'BRCA1基因区域 — ClinVar致病突变密集'},
                   {   'chrom': 'chr13',
                       'start': 32315086,
                       'end': 32400268,
                       'gene': 'BRCA2',
                       'rtype': 'coding',
                       'source': 'clinvar_pathogenic',
                       'note': 'BRCA2基因区域'},
                   {   'chrom': 'chr16',
                       'pos': 23636141,
                       'start': 23636141,
                       'end': 23652184,
                       'gene': 'PALB2',
                       'rtype': 'coding',
                       'source': 'clinical',
                       'note': 'PALB2基因区域'},
                   {   'chrom': 'chr10',
                       'start': 121478332,
                       'end': 121598575,
                       'gene': 'FGFR2',
                       'rtype': 'regulatory',
                       'source': 'gwas',
                       'note': 'FGFR2内含子2乳腺癌GWAS增强子区域'}],
    'regulatory_regions': [],
    'prs_variants_high': [],
    'prs_variants': [],
    'key_literature': [   {   'pmid': '28530676',
                              'title': 'Association analysis identifies 65 new breast cancer risk loci',
                              'note': 'Michailidou et al. 2017 Nature; BCAC GWAS ~118K cases'},
                          {   'pmid': '29059683',
                              'title': 'Genome-wide association study identifies 32 novel breast cancer susceptibility '
                                       'loci',
                              'note': 'Zhang et al. 2020 Nat Genet; 亚洲人群乳腺癌GWAS'},
                          {   'pmid': '23535729',
                              'title': 'Large-scale genotyping identifies 41 new loci associated with breast cancer '
                                       'risk',
                              'note': 'Michailidou et al. 2013 Nat Genet'}],
    'key_regions': {
        'BRCA1': {
            'note': 'RING域(aa1-109);BRCT×2(aa1646-1863);DNA损伤应答',
            'regions': [(1, 109), (1646, 1863)],
        },
        'PTEN': {
            'note': '磷酸酶域(aa123-130);C2域(aa186-351);PDZ结合基序',
            'regions': [(123, 130), (186, 351)],
        },
        'STK11': {
            'note': '激酶域(aa49-309);N端调节域;C端调节域',
            'regions': [(49, 309)],
        },
        'TP53': {
            'note': '反式激活域(aa1-42);DNA结合域(aa102-292);四聚化域(aa325-356)',
            'regions': [(1, 42), (102, 292), (325, 356)],
        },
    },
}
