"""Circadian glucose regulation disease template.

Source: Sinnott-Armstrong et al. 2026 (Nature Communications) "Genetic variants affect diurnal
        glucose levels throughout the day" (DOI: 10.1038/s41467-026-72432-6).
        Built from Supplementary Data 1: 68 independent glucose-associated loci across
        random, 2h post-prandial, and fasting glucose traits.

Notes:
- This template captures the *time-of-day* genetic component of glucose homeostasis.
- It is separate from the T2D template to avoid double-counting T2D risk scores.
- Top two loci (MTNR1B, CRY2) are placed in prs_variants_high; remaining loci are in
  gwas_lead_snps with low contribution scores to limit systematic score inflation.
"""

TEMPLATE_NAME = "circadian glucose regulation"

TEMPLATE = {   'aliases': ['circadian glucose regulation', '血糖昼夜节律', 'diurnal glucose', 'glucose rhythm', '血糖节律'],
    'gene_set': [   {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'ABO',
                        'key_domains': '',
                        'note': 'ABO血型;与代谢性状多效关联',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'ADCY5',
                        'key_domains': '',
                        'note': '腺苷酸环化酶5;cAMP信号/胰岛素分泌;出生体重多效性',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'ARAP1',
                        'key_domains': '',
                        'note': 'ArfGAP with RhoGAP domain;胰岛胰岛素分泌',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'BTBD7P2',
                        'key_domains': '',
                        'note': 'BTB domain containing 7 pseudogene 2;假基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'C5orf67',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'CAST',
                        'key_domains': '',
                        'note': 'Calpastatin;肌肉/代谢',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'CCND2',
                        'key_domains': '',
                        'note': 'Cyclin D2;beta细胞增殖/周期',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'CDC123',
                        'key_domains': '',
                        'note': '细胞分裂周期蛋白123;胰岛beta细胞',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'CDKAL1',
                        'key_domains': '',
                        'note': 'tRNA修饰酶;胰岛胰岛素分泌',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'CDKN2B',
                        'key_domains': '',
                        'note': '细胞周期抑制因子p15;T2D GWAS位点',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'CDKN2B-AS1',
                        'key_domains': '',
                        'note': 'CDKN2B antisense RNA 1;ANRIL;血管/代谢多效性',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'COBLL1',
                        'key_domains': '',
                        'note': 'Cordon-bleu WH2 repeat protein-like 1;脂肪/代谢',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'CRY2',
                        'key_domains': '',
                        'note': '隐花色素2;核心昼夜节律基因;rs12419690;夜间/空腹血糖调控',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'DGKB',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'ENSG00000250838',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'ENSG00000259362',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'ENSG00000294041',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'ENSG00000297540',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'ENSG00000298263',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'ENSG00000308044',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'ENSG00000309265',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'FAM234A',
                        'key_domains': '',
                        'note': 'Family with sequence similarity 234 member A;功能待明确',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'FBRSL1',
                        'key_domains': '',
                        'note': 'Fibrosin-like 1;染色质/转录调控',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'FOXN3',
                        'key_domains': '',
                        'note': 'Forkhead box N3;转录调控',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'FTO',
                        'key_domains': '',
                        'note': '肥胖/T2D GWAS;能量稳态',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'GCK',
                        'key_domains': '',
                        'note': '葡萄糖激酶;MODY2/血糖稳态',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'GCKR',
                        'key_domains': '',
                        'note': '葡萄糖激酶调节蛋白;肝脏葡萄糖感应',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'GIN1',
                        'key_domains': '',
                        'note': 'Gyroscope induced 1;细胞骨架/代谢',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'GLIS3',
                        'key_domains': '',
                        'note': '转录因子;胰岛beta细胞发育/功能',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'GPSM1',
                        'key_domains': '',
                        'note': 'G-protein signaling modulator 1;胰岛信号',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'HBP1',
                        'key_domains': '',
                        'note': 'HMG-box transcription factor;代谢调控',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'HERC1',
                        'key_domains': '',
                        'note': 'E3泛素连接酶;信号转导',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'HLA-DQA1',
                        'key_domains': '',
                        'note': 'MHC II类;自身免疫/糖尿病风险',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'HLA-DQB1',
                        'key_domains': '',
                        'note': 'MHC II类;自身免疫/糖尿病风险',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'HNF1B',
                        'key_domains': '',
                        'note': '转录因子;MODY4/肾脏囊肿糖尿病',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'IGF2BP2',
                        'key_domains': '',
                        'note': 'RNA结合蛋白;胰岛素信号',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'JAZF1',
                        'key_domains': '',
                        'note': '转录抑制因子;胰岛素信号',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'KCNQ1',
                        'key_domains': '',
                        'note': 'Kv7.1钾通道;胰岛+心肌;东亚T2D GWAS强信号',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'KCNQ1-AS1',
                        'key_domains': '',
                        'note': 'KCNQ1 antisense RNA 1;非编码调控',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'LINC01080',
                        'key_domains': '',
                        'note': 'Long intergenic non-protein coding RNA 1080;非编码调控',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'MADD',
                        'key_domains': '',
                        'note': 'MAP激酶激活死亡域蛋白;胰岛beta细胞功能',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'MAU2',
                        'key_domains': '',
                        'note': 'Cohesin loading complex;染色质/代谢',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'MTNR1B',
                        'key_domains': '',
                        'note': '褪黑素受体1B;rs10830963;胰岛分泌节律;空腹/夜间血糖核心位点',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'NCR3LG1',
                        'key_domains': '',
                        'note': 'NCR3 ligand 1;免疫调节',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'NOSTRIN',
                        'key_domains': '',
                        'note': 'Nitric oxide synthase traffic inducer;血管/代谢',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'PPP1R3B-DT',
                        'key_domains': '',
                        'note': 'PPP1R3B divergent transcript;非编码调控',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'PROX1',
                        'key_domains': '',
                        'note': '转录因子;肝脏代谢/空腹血糖',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'RFX6',
                        'key_domains': '',
                        'note': 'Regulatory factor X6;胰腺发育/beta细胞功能',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'RGS17',
                        'key_domains': '',
                        'note': 'Regulator of G-protein signaling;神经/代谢',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'RMST',
                        'key_domains': '',
                        'note': 'Rhabdomyosarcoma 2 associated transcript;lncRNA',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'RN7SKP15',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'RN7SL836P',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'RSPO3',
                        'key_domains': '',
                        'note': 'R-spondin 3;Wnt信号/代谢',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'SLC12A8',
                        'key_domains': '',
                        'note': 'Solute carrier family 12 member 8;离子转运',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'SLC30A8',
                        'key_domains': '',
                        'note': 'ZnT8锌转运蛋白;胰岛素分泌颗粒',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'SPC25',
                        'key_domains': '',
                        'note': 'kinetochore蛋白;细胞周期',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'TAOK1',
                        'key_domains': '',
                        'note': 'TAO kinase 1;应激/代谢信号',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'TCF7L2',
                        'key_domains': '',
                        'note': 'T2D最强GWAS位点;Wnt信号;本研究中2h血糖显著关联',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'TENT5C',
                        'key_domains': '',
                        'note': 'Terminal nucleotidyltransferase;RNA代谢',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'THADA',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'TP53INP1',
                        'key_domains': '',
                        'note': 'p53 inducible nuclear protein;应激/凋亡',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'TSHZ2',
                        'key_domains': '',
                        'note': 'Teashirt zinc finger homeobox 2;发育/代谢',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'},
                    {   'contribution_score': 0.3,
                        'evidence': 'gwas',
                        'gene': 'YKT6',
                        'key_domains': '',
                        'note': 'SNARE蛋白;分泌/代谢',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'Y_RNA',
                        'key_domains': '',
                        'note': '血糖节律GWAS位点关联基因',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.25,
                        'evidence': 'gwas',
                        'gene': 'ZBED3-AS1',
                        'key_domains': '',
                        'note': 'ZBED3 antisense RNA 1;非编码调控',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'strong_gwas'},
                    {   'contribution_score': 0.18,
                        'evidence': 'gwas',
                        'gene': 'ZMIZ1',
                        'key_domains': '',
                        'note': '锌指蛋白;免疫/代谢',
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'phenotype_assoc': 'diurnal glucose regulation / T2D risk factor',
                        'tier': 'gwas'}],
    'gwas_lead_snps': [   {   'beta': 0.0206,
                              'chrom': 'chr1',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.1029,
                              'eaf_eur': 0.3102,
                              'effect_allele': 'A',
                              'gene': 'TENT5C',
                              'note': 'TENT5C; random glucose; p=1.56e-12; beta=0.0206',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 117626841,
                              'rsid': 'rs2282456',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0256,
                              'chrom': 'chr1',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.3978,
                              'eaf_eur': 0.5436,
                              'effect_allele': 'C',
                              'gene': 'PROX1',
                              'note': 'PROX1; random glucose; p=4.96e-21; beta=0.0256',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 213985913,
                              'rsid': 'rs340874',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0297,
                              'chrom': 'chr10',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.5318,
                              'eaf_eur': 0.2012,
                              'effect_allele': 'T',
                              'gene': 'CDC123',
                              'note': 'CDC123; random glucose; p=4.02e-19; beta=0.0297',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 12265895,
                              'rsid': 'rs11257655',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0166,
                              'chrom': 'chr10',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.3165,
                              'eaf_eur': 0.0003,
                              'effect_allele': 'C',
                              'gene': 'ZMIZ1',
                              'note': 'ZMIZ1; random glucose; p=3.99e-08; beta=0.0166',
                              'or_value': None,
                              'other_allele': 'A',
                              'pos': 79197634,
                              'rsid': 'rs34942927',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0217,
                              'chrom': 'chr10',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.8636,
                              'eaf_eur': 0.4317,
                              'effect_allele': 'G',
                              'gene': 'Y_RNA',
                              'note': 'Y_RNA; random glucose; p=1.51e-15; beta=-0.0217',
                              'or_value': None,
                              'other_allele': 'A',
                              'pos': 92706682,
                              'rsid': 'rs12219514',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.019,
                              'chrom': 'chr10',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.901,
                              'eaf_eur': 0.7874,
                              'effect_allele': 'T',
                              'gene': 'BTBD7P2',
                              'note': 'BTBD7P2; fasting glucose; p=2.96e-19; beta=0.0190',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 111287020,
                              'rsid': 'rs36106955',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.057,
                              'chrom': 'chr10',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0,
                              'eaf_eur': 0.0188,
                              'effect_allele': 'T',
                              'gene': 'TCF7L2',
                              'note': 'TCF7L2; random glucose; p=1.17e-08; beta=-0.0570',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 112977874,
                              'rsid': 'rs144155527',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.066,
                              'chrom': 'chr10',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.0261,
                              'eaf_eur': 0.2938,
                              'effect_allele': 'C',
                              'gene': 'TCF7L2',
                              'note': 'TCF7L2; random glucose; p=2.93e-109; beta=0.0660',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 112994312,
                              'rsid': 'rs34872471',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0158,
                              'chrom': 'chr11',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.9802,
                              'eaf_eur': 0.3799,
                              'effect_allele': 'T',
                              'gene': 'KCNQ1',
                              'note': 'KCNQ1; random glucose; p=1.29e-08; beta=0.0158',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 2671019,
                              'rsid': 'rs231360',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0198,
                              'chrom': 'chr11',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.6504,
                              'eaf_eur': 0.6172,
                              'effect_allele': 'A',
                              'gene': 'NCR3LG1',
                              'note': 'NCR3LG1; random glucose; p=1.04e-12; beta=-0.0198',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 17362995,
                              'rsid': 'rs12146652',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0219,
                              'chrom': 'chr11',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.0012,
                              'eaf_eur': 0.2634,
                              'effect_allele': 'C',
                              'gene': 'MADD',
                              'note': 'MADD; fasting glucose; p=1.09e-29; beta=-0.0219',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 47272248,
                              'rsid': 'rs10501320',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0231,
                              'chrom': 'chr11',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.9282,
                              'eaf_eur': 0.8443,
                              'effect_allele': 'A',
                              'gene': 'ARAP1',
                              'note': 'ARAP1; fasting glucose; p=3.50e-25; beta=0.0231',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 72749353,
                              'rsid': 'rs77464186',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.1116,
                              'chrom': 'chr12',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.971,
                              'eaf_eur': 0.0222,
                              'effect_allele': 'G',
                              'gene': 'CCND2',
                              'note': 'CCND2; random glucose; p=1.68e-26; beta=-0.1116',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 4275678,
                              'rsid': 'rs76895963',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0249,
                              'chrom': 'chr12',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.3413,
                              'eaf_eur': 0.2074,
                              'effect_allele': 'G',
                              'gene': 'RN7SKP15',
                              'note': 'RN7SKP15; random glucose; p=1.34e-13; beta=-0.0249',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 27804600,
                              'rsid': 'rs7133214',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0267,
                              'chrom': 'chr12',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.0008,
                              'eaf_eur': 0.1103,
                              'effect_allele': 'C',
                              'gene': 'RMST',
                              'note': 'RMST; random glucose; p=1.33e-09; beta=-0.0267',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 97475128,
                              'rsid': 'rs17331697',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0158,
                              'chrom': 'chr12',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.1128,
                              'eaf_eur': 0.3164,
                              'effect_allele': 'C',
                              'gene': 'FBRSL1',
                              'note': 'FBRSL1; random glucose; p=3.82e-08; beta=0.0158',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 132536375,
                              'rsid': 'rs11146919',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0265,
                              'chrom': 'chr13',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.1941,
                              'eaf_eur': 0.1676,
                              'effect_allele': 'G',
                              'gene': 'ENSG00000308044',
                              'note': 'ENSG00000308044; random glucose; p=2.39e-13; beta=0.0265',
                              'or_value': None,
                              'other_allele': 'A',
                              'pos': 32986355,
                              'rsid': 'rs11839569',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0207,
                              'chrom': 'chr13',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.2684,
                              'eaf_eur': 0.2852,
                              'effect_allele': 'G',
                              'gene': 'LINC01080',
                              'note': 'LINC01080; random glucose; p=3.92e-12; beta=-0.0207',
                              'or_value': None,
                              'other_allele': 'A',
                              'pos': 80133294,
                              'rsid': 'rs1215468',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0202,
                              'chrom': 'chr14',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.1459,
                              'eaf_eur': 0.6332,
                              'effect_allele': 'C',
                              'gene': 'FOXN3',
                              'note': 'FOXN3; random glucose; p=6.08e-13; beta=-0.0202',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 89582590,
                              'rsid': 'rs11626777',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0172,
                              'chrom': 'chr15',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.0668,
                              'eaf_eur': 0.313,
                              'effect_allele': 'A',
                              'gene': 'HERC1',
                              'note': 'HERC1; random glucose; p=4.64e-09; beta=-0.0172',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 63746141,
                              'rsid': 'rs67507374',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.021,
                              'chrom': 'chr15',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.3547,
                              'eaf_eur': 0.7134,
                              'effect_allele': 'A',
                              'gene': 'ENSG00000259362',
                              'note': 'ENSG00000259362; random glucose; p=2.60e-12; beta=0.0210',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 77540420,
                              'rsid': 'rs7177055',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0283,
                              'chrom': 'chr16',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.3195,
                              'eaf_eur': 0.156,
                              'effect_allele': 'T',
                              'gene': 'FAM234A',
                              'note': 'FAM234A; random glucose; p=4.15e-14; beta=-0.0283',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 259721,
                              'rsid': 'rs56337617',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0226,
                              'chrom': 'chr16',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.1964,
                              'eaf_eur': 0.4364,
                              'effect_allele': 'T',
                              'gene': 'FTO',
                              'note': 'FTO; random glucose; p=1.34e-16; beta=0.0226',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 53765367,
                              'rsid': 'rs57292959',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.02,
                              'chrom': 'chr17',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.6517,
                              'eaf_eur': 0.2012,
                              'effect_allele': 'T',
                              'gene': 'TAOK1',
                              'note': 'TAOK1; random glucose; p=4.02e-09; beta=-0.0200',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 29494037,
                              'rsid': 'rs9906711',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0181,
                              'chrom': 'chr17',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.0319,
                              'eaf_eur': 0.3284,
                              'effect_allele': 'A',
                              'gene': 'ENSG00000250838',
                              'note': 'ENSG00000250838; random glucose; p=4.06e-10; beta=-0.0181',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 48982960,
                              'rsid': 'rs35895680',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0283,
                              'chrom': 'chr19',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.1643,
                              'eaf_eur': 0.0849,
                              'effect_allele': 'T',
                              'gene': 'MAU2',
                              'note': 'MAU2; random glucose; p=3.82e-09; beta=0.0283',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 19346108,
                              'rsid': 'rs58489806',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0165,
                              'chrom': 'chr19',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.3481,
                              'eaf_eur': 0.4216,
                              'effect_allele': 'A',
                              'gene': 'RN7SL836P',
                              'note': 'RN7SL836P; random glucose; p=2.83e-09; beta=-0.0165',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 45654658,
                              'rsid': 'rs7507912',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.028,
                              'chrom': 'chr2',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.4925,
                              'eaf_eur': 0.4014,
                              'effect_allele': 'T',
                              'gene': 'GCKR',
                              'note': 'GCKR; fasting glucose; p=1.53e-59; beta=-0.0280',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 27519736,
                              'rsid': 'rs780093',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0386,
                              'chrom': 'chr2',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.0013,
                              'eaf_eur': 0.0973,
                              'effect_allele': 'A',
                              'gene': 'THADA',
                              'note': 'THADA; random glucose; p=1.90e-17; beta=-0.0386',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 43242476,
                              'rsid': 'rs80323638',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0226,
                              'chrom': 'chr2',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.0892,
                              'eaf_eur': 0.4092,
                              'effect_allele': 'T',
                              'gene': 'COBLL1',
                              'note': 'COBLL1; random glucose; p=2.32e-16; beta=-0.0226',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 164651879,
                              'rsid': 'rs10184004',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0207,
                              'chrom': 'chr2',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.8711,
                              'eaf_eur': 0.6921,
                              'effect_allele': 'C',
                              'gene': 'NOSTRIN',
                              'note': 'NOSTRIN; random glucose; p=2.45e-12; beta=-0.0207',
                              'or_value': None,
                              'other_allele': 'A',
                              'pos': 168828762,
                              'rsid': 'rs830021',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0161,
                              'chrom': 'chr2',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.9274,
                              'eaf_eur': 0.6392,
                              'effect_allele': 'G',
                              'gene': 'ENSG00000297540',
                              'note': 'ENSG00000297540; random glucose; p=1.10e-08; beta=0.0161',
                              'or_value': None,
                              'other_allele': 'A',
                              'pos': 226230042,
                              'rsid': 'rs2203452',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0177,
                              'chrom': 'chr20',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.4407,
                              'eaf_eur': 0.5672,
                              'effect_allele': 'T',
                              'gene': 'TSHZ2',
                              'note': 'TSHZ2; random glucose; p=1.22e-10; beta=-0.0177',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 53011095,
                              'rsid': 'rs2255805',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0281,
                              'chrom': 'chr3',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.9973,
                              'eaf_eur': 0.7753,
                              'effect_allele': 'A',
                              'gene': 'ADCY5',
                              'note': 'ADCY5; fasting glucose; p=1.63e-43; beta=0.0281',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 123346931,
                              'rsid': 'rs11708067',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0148,
                              'chrom': 'chr3',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.3691,
                              'eaf_eur': 0.5322,
                              'effect_allele': 'C',
                              'gene': 'SLC12A8',
                              'note': 'SLC12A8; random glucose; p=4.53e-08; beta=0.0148',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 125200933,
                              'rsid': 'rs4679370',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0211,
                              'chrom': 'chr3',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.2525,
                              'eaf_eur': 0.3187,
                              'effect_allele': 'A',
                              'gene': 'IGF2BP2',
                              'note': 'IGF2BP2; random glucose; p=3.71e-13; beta=0.0211',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 185801319,
                              'rsid': 'rs71320321',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0187,
                              'chrom': 'chr3',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.9951,
                              'eaf_eur': 0.6138,
                              'effect_allele': 'C',
                              'gene': 'ENSG00000298263',
                              'note': 'ENSG00000298263; random glucose; p=1.72e-11; beta=0.0187',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 188023111,
                              'rsid': 'rs4686471',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0126,
                              'chrom': 'chr5',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.4986,
                              'eaf_eur': 0.7427,
                              'effect_allele': 'T',
                              'gene': 'C5orf67',
                              'note': 'C5orf67; fasting glucose; p=2.08e-09; beta=0.0126',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 56511543,
                              'rsid': 'rs464605',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0196,
                              'chrom': 'chr5',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.9486,
                              'eaf_eur': 0.697,
                              'effect_allele': 'A',
                              'gene': 'ZBED3-AS1',
                              'note': 'ZBED3-AS1; random glucose; p=1.27e-11; beta=-0.0196',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 77131486,
                              'rsid': 'rs6878122',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0247,
                              'chrom': 'chr5',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.683,
                              'eaf_eur': 0.7132,
                              'effect_allele': 'T',
                              'gene': 'CAST',
                              'note': 'CAST; fasting glucose; p=1.91e-34; beta=0.0247',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 96360881,
                              'rsid': 'rs1820176',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0384,
                              'chrom': 'chr5',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0,
                              'eaf_eur': 0.0496,
                              'effect_allele': 'T',
                              'gene': 'GIN1',
                              'note': 'GIN1; random glucose; p=7.79e-10; beta=0.0384',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 103087264,
                              'rsid': 'rs115505614',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0324,
                              'chrom': 'chr6',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.3775,
                              'eaf_eur': 0.271,
                              'effect_allele': 'A',
                              'gene': 'CDKAL1',
                              'note': 'CDKAL1; random glucose; p=4.33e-26; beta=0.0324',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 20686342,
                              'rsid': 'rs7766070',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0251,
                              'chrom': 'chr6',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0,
                              'eaf_eur': 0,
                              'effect_allele': 'A',
                              'gene': 'HLA-DQA1',
                              'note': 'HLA-DQA1; random glucose; p=5.15e-15; beta=0.0251',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 32648735,
                              'rsid': 'rs553276313',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0313,
                              'chrom': 'chr6',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0,
                              'eaf_eur': 0.0004,
                              'effect_allele': 'T',
                              'gene': 'HLA-DQA1',
                              'note': 'HLA-DQA1; random glucose; p=1.13e-19; beta=0.0313',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 32650413,
                              'rsid': 'rs185774696',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0207,
                              'chrom': 'chr6',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.8002,
                              'eaf_eur': 0.6929,
                              'effect_allele': 'C',
                              'gene': 'ENSG00000294041',
                              'note': 'ENSG00000294041; random glucose; p=1.64e-12; beta=-0.0207',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 43837071,
                              'rsid': 'rs2396083',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0216,
                              'chrom': 'chr6',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.6012,
                              'eaf_eur': 0.8069,
                              'effect_allele': 'A',
                              'gene': 'RFX6',
                              'note': 'RFX6; random glucose; p=1.27e-09; beta=0.0216',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 116947315,
                              'rsid': 'rs5024233',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0222,
                              'chrom': 'chr6',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.0398,
                              'eaf_eur': 0.2314,
                              'effect_allele': 'T',
                              'gene': 'RSPO3',
                              'note': 'RSPO3; random glucose; p=3.29e-12; beta=-0.0222',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 127107087,
                              'rsid': 'rs35323862',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0168,
                              'chrom': 'chr6',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.8502,
                              'eaf_eur': 0.4212,
                              'effect_allele': 'C',
                              'gene': 'RGS17',
                              'note': 'RGS17; random glucose; p=1.26e-09; beta=0.0168',
                              'or_value': None,
                              'other_allele': 'A',
                              'pos': 153109733,
                              'rsid': 'rs63739861',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.028,
                              'chrom': 'chr7',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.4408,
                              'eaf_eur': 0.1746,
                              'effect_allele': 'T',
                              'gene': 'DGKB',
                              'note': 'DGKB; fasting glucose; p=4.17e-36; beta=0.0280',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 14858657,
                              'rsid': 'rs17168486',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0247,
                              'chrom': 'chr7',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.5256,
                              'eaf_eur': 0.4864,
                              'effect_allele': 'A',
                              'gene': 'ENSG00000309265',
                              'note': 'ENSG00000309265; fasting glucose; p=1.74e-46; beta=-0.0247',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 15020785,
                              'rsid': 'rs7786873',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.02,
                              'chrom': 'chr7',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.2253,
                              'eaf_eur': 0.4981,
                              'effect_allele': 'G',
                              'gene': 'JAZF1',
                              'note': 'JAZF1; random glucose; p=1.38e-13; beta=-0.0200',
                              'or_value': None,
                              'other_allele': 'A',
                              'pos': 28156603,
                              'rsid': 'rs849134',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0293,
                              'chrom': 'chr7',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.7078,
                              'eaf_eur': 0.7874,
                              'effect_allele': 'A',
                              'gene': 'GCK',
                              'note': 'GCK; fasting glucose; p=6.03e-29; beta=-0.0293',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 44146356,
                              'rsid': 'rs76323047',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0612,
                              'chrom': 'chr7',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.8125,
                              'eaf_eur': 0.828,
                              'effect_allele': 'A',
                              'gene': 'YKT6',
                              'note': 'YKT6; fasting glucose; p=2.20e-164; beta=-0.0612',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 44200725,
                              'rsid': 'rs1985469',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0099,
                              'chrom': 'chr8',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.2767,
                              'eaf_eur': 0.4972,
                              'effect_allele': 'T',
                              'gene': 'TP53INP1',
                              'note': 'TP53INP1; fasting glucose; p=5.61e-09; beta=0.0099',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 94948283,
                              'rsid': 'rs896854',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0284,
                              'chrom': 'chr8',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.4557,
                              'eaf_eur': 0.3048,
                              'effect_allele': 'A',
                              'gene': 'SLC30A8',
                              'note': 'SLC30A8; fasting glucose; p=1.15e-56; beta=-0.0284',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 117172786,
                              'rsid': 'rs3802177',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0198,
                              'chrom': 'chr9',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.6215,
                              'eaf_eur': 0.6386,
                              'effect_allele': 'A',
                              'gene': 'GLIS3',
                              'note': 'GLIS3; fasting glucose; p=9.85e-31; beta=-0.0198',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 4291928,
                              'rsid': 'rs10974438',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0175,
                              'chrom': 'chr9',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.5149,
                              'eaf_eur': 0.3802,
                              'effect_allele': 'T',
                              'gene': 'CDKN2B',
                              'note': 'CDKN2B; random glucose; p=3.93e-10; beta=0.0175',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 22003224,
                              'rsid': 'rs3217992',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0223,
                              'chrom': 'chr9',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.4132,
                              'eaf_eur': 0.1707,
                              'effect_allele': 'A',
                              'gene': 'CDKN2B-AS1',
                              'note': 'CDKN2B-AS1; fasting glucose; p=7.94e-25; beta=-0.0223',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 22134069,
                              'rsid': 'rs10811660',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0206,
                              'chrom': 'chr9',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.107,
                              'eaf_eur': 0.045,
                              'effect_allele': 'C',
                              'gene': 'GPSM1',
                              'note': 'GPSM1; random glucose; p=6.08e-14; beta=0.0206',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 136352330,
                              'rsid': 'rs28413886',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0164,
                              'chrom': 'chrHG2030_PATCH',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.2049,
                              'eaf_eur': 0.1955,
                              'effect_allele': 'T',
                              'gene': 'ABO',
                              'note': 'ABO; fasting glucose; p=5.43e-16; beta=0.0164',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 92550,
                              'rsid': 'rs2519093',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0149,
                              'chrom': 'chrHG2266_PATCH',
                              'confidence': 'moderate',
                              'contribution_score': 0.18,
                              'eaf_eas': 0.594,
                              'eaf_eur': 0.5256,
                              'effect_allele': 'C',
                              'gene': 'HBP1',
                              'note': 'HBP1; random glucose; p=3.64e-08; beta=-0.0149',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 22798,
                              'rsid': 'rs6971864',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0282,
                              'chrom': 'chrHG76_PATCH',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.0123,
                              'eaf_eur': 0.0873,
                              'effect_allele': 'A',
                              'gene': 'PPP1R3B-DT',
                              'note': 'PPP1R3B-DT; fasting glucose; p=3.57e-23; beta=0.0282',
                              'or_value': None,
                              'other_allele': 'G',
                              'pos': 4025671,
                              'rsid': 'rs9987289',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0249,
                              'chrom': 'chrHSCHR11_1_CTG7',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.3352,
                              'eaf_eur': 0.4154,
                              'effect_allele': 'C',
                              'gene': 'KCNQ1-AS1',
                              'note': 'KCNQ1-AS1; random glucose; p=7.90e-20; beta=0.0249',
                              'or_value': None,
                              'other_allele': 'A',
                              'pos': 68142,
                              'rsid': 'rs2237895',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': -0.0185,
                              'chrom': 'chrHSCHR17_7_CTG4',
                              'confidence': 'high',
                              'contribution_score': 0.22,
                              'eaf_eas': 0.744,
                              'eaf_eur': 0.6074,
                              'effect_allele': 'G',
                              'gene': 'HNF1B',
                              'note': 'HNF1B; random glucose; p=2.95e-11; beta=-0.0185',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 1982937,
                              'rsid': 'rs11658063',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0877,
                              'chrom': 'chrHSCHR2_1_CTG7_2',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.9662,
                              'eaf_eur': 0.7051,
                              'effect_allele': 'C',
                              'gene': 'SPC25',
                              'note': 'SPC25; random glucose; p=3.48e-194; beta=0.0877',
                              'or_value': None,
                              'other_allele': 'T',
                              'pos': 93265,
                              'rsid': 'rs560887',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'},
                          {   'beta': 0.0382,
                              'chrom': 'chrHSCHR6_MHC_SSTO_CTG1',
                              'confidence': 'high',
                              'contribution_score': 0.28,
                              'eaf_eas': 0.3602,
                              'eaf_eur': 0.2719,
                              'effect_allele': 'A',
                              'gene': 'HLA-DQB1',
                              'note': 'HLA-DQB1; random glucose; p=1.90e-38; beta=0.0382',
                              'or_value': None,
                              'other_allele': 'C',
                              'pos': 4055718,
                              'rsid': 'rs9273363',
                              'tier': 'gwas',
                              'variant_class': 'gwas_lead'}],
    'key_literature': [   {   'evidence_type': 'gwas',
                              'genes': ['MTNR1B', 'CRY2'],
                              'note': 'Sinnott-Armstrong et al., Nature Communications 2026; 420k UKB + replication; '
                                      'diurnal glucose GWAS (preprint PMID 39091879)',
                              'pmid': '39091879',
                              'title': 'Genetic variants affect diurnal glucose levels throughout the day'},
                          {   'evidence_type': 'review',
                              'genes': ['CRY2', 'MTNR1B', 'CLOCK', 'PER3'],
                              'note': '2025 systematic review; CRY2 associated with higher FBG and IGT risk',
                              'pmid': '40850217',
                              'title': 'The association between clock gene polymorphisms and type 2 diabetes: a '
                                       'systematic review and meta-analysis'},
                          {   'evidence_type': 'gwas',
                              'genes': ['CRY1', 'CRY2', 'MTNR1B'],
                              'note': 'Renström et al., Diabetologia 2015; season-dependent effects on fasting/2h '
                                      'glucose',
                              'pmid': '25707907',
                              'title': 'Season-dependent associations of circadian rhythm-regulating loci (CRY1, CRY2 '
                                       'and MTNR1B) and glucose homeostasis'}],
    'key_regions': {   'CRY2': {   'critical_residues': [],
                                   'note': 'Cryptochrome circadian regulator; photolyase-like domain; PER/CRY complex',
                                   'regions': [   {   'name': 'Photolyase-like domain',
                                                      'note': 'core circadian clock component',
                                                      'residues': 'aa 1-500'}]},
                       'MTNR1B': {   'critical_residues': [],
                                     'note': 'G-protein coupled melatonin receptor; 7-TM domain; beta-cell insulin '
                                             'secretion rhythm',
                                     'regions': [   {   'name': '7-TM GPCR domain',
                                                        'note': 'ligand binding and signal transduction',
                                                        'residues': 'aa 1-350'}]}},
    'known_pathogenic_variants': [],
    'mode': 'complex',
    'prs_variants': [],
    'prs_variants_high': [   {   'beta': -0.03,
                                 'chrom': 'chr11',
                                 'confidence': 'high',
                                 'contribution_score': 0.28,
                                 'eaf_eas': 0.2682,
                                 'eaf_eur': 0.5607,
                                 'effect_allele': 'A',
                                 'gene': 'CRY2',
                                 'note': 'CRY2; T2D multi-ancestry beta=-0.030; diurnal glucose core locus',
                                 'or_value': None,
                                 'other_allele': 'G',
                                 'pos': 45837033,
                                 'rsid': 'rs12419690',
                                 'tier': 'strong_gwas',
                                 'variant_class': 'prs_high'},
                             {   'beta': -0.0772,
                                 'chrom': 'chr11',
                                 'confidence': 'high',
                                 'contribution_score': 0.28,
                                 'eaf_eas': 0.5666,
                                 'eaf_eur': 0.7207,
                                 'effect_allele': 'C',
                                 'gene': 'MTNR1B',
                                 'note': 'MTNR1B; core diurnal glucose/T2D locus; rs10830963',
                                 'or_value': None,
                                 'other_allele': 'G',
                                 'pos': 92975544,
                                 'rsid': 'rs10830963',
                                 'tier': 'strong_gwas',
                                 'variant_class': 'prs_high'}],
    'regulatory_regions': []}
