"""Disease template: colorectal cancer."""

TEMPLATE_NAME = 'colorectal_cancer'
TEMPLATE = {   'aliases': [   'colorectal cancer',
                   'colon cancer',
                   'rectal cancer',
                   'crc',
                   'hereditary colorectal cancer',
                   'lynch syndrome',
                   'familial adenomatous polyposis',
                   'fap',
                   'hnpcc',
                   'map',
                   'mutyh-associated polyposis'],
    'mode': 'complex',
    'gene_set': [   {   'gene': 'APC',
                        'tier': 'mendelian_high',
                        'contribution_score': 1.0,
                        'penetrance': '>0.95',
                        'penetrance_score': 0.95,
                        'evidence': 'familial',
                        'note': '家族性腺瘤性息肉病(FAP); 未治疗终身CRC风险~100%',
                        'phenotype_assoc': 'FAP(常显);终身CRC~100%;数千腺瘤;Gardner/Turcot变异型',
                        'key_domains': '寡聚化域;犰狳重复×7;15aa重复×3;20aa重复×7;SAMP重复;EB1/HDL结合',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'MLH1',
                        'tier': 'mendelian_high',
                        'contribution_score': 1.0,
                        'penetrance': 'high',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': 'Lynch综合征(MMR); 终身CRC风险~40-80%; 子宫内膜癌风险高',
                        'phenotype_assoc': 'Lynch综合征(常显);CRC(40-80%);子宫内膜癌(25-60%);MSI-H',
                        'key_domains': 'ATP酶域;MutL C端二聚化域;PMS2/MLH3结合',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'MSH2',
                        'tier': 'mendelian_high',
                        'contribution_score': 1.0,
                        'penetrance': 'high',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': 'Lynch综合征(MMR); 终身CRC风险~40-80%; 泌尿系癌风险高',
                        'phenotype_assoc': 'Lynch(常显);CRC(40-80%);泌尿系/皮脂腺肿瘤(Muir-Torre)',
                        'key_domains': 'MutS域I-V;DNA错配识别;ATP酶;MSH6/MSH3异源二聚体',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'MSH6',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.95,
                        'penetrance': 'high',
                        'penetrance_score': 0.7,
                        'evidence': 'familial',
                        'note': 'Lynch综合征; 终身CRC风险~20-40%(晚发); 子宫内膜癌为主',
                        'phenotype_assoc': 'Lynch(常显);CRC(晚发~20-40%);子宫内膜癌(高);不完全外显',
                        'key_domains': 'MutS域;PWWP域;MSH2异源二聚体',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'PMS2',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.9,
                        'penetrance': 'high',
                        'penetrance_score': 0.6,
                        'evidence': 'familial',
                        'note': 'Lynch综合征; 终身CRC风险~15-25%(较低); 外显率低于MLH1/MSH2',
                        'phenotype_assoc': 'Lynch(常显);CRC(较低~15-25%);不完全外显',
                        'key_domains': 'ATP酶域;MutL C端域;MLH1异源二聚体',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'MUTYH',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.85,
                        'penetrance': 'high',
                        'penetrance_score': 0.7,
                        'evidence': 'familial',
                        'note': 'MUTYH相关息肉病(MAP)(AR); 双等位变异CRC风险~80%',
                        'phenotype_assoc': 'MAP(常隐);双等位CRC~80%;10-100+腺瘤;碱基切除修复',
                        'key_domains': 'HhH-GPD域;Fe-S簇;8-oxoG识别',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'STK11',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.75,
                        'penetrance': 'high',
                        'penetrance_score': 0.7,
                        'evidence': 'familial',
                        'note': 'Peutz-Jeghers综合征; 终身CRC风险~39%',
                        'phenotype_assoc': 'Peutz-Jeghers(常显);CRC~39%;错构瘤息肉;色素斑',
                        'key_domains': '激酶域(aa49-309)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'SMAD4',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.75,
                        'penetrance': 'high',
                        'penetrance_score': 0.7,
                        'evidence': 'familial',
                        'note': '幼年性息肉病综合征(JPS); CRC终身风险~40-50%',
                        'phenotype_assoc': 'JPS(常显);CRC~40-50%;幼年性错构瘤息肉;TGF-β信号',
                        'key_domains': 'MH1域;MH2域(SMAD结合)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'BMPR1A',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.75,
                        'penetrance': 'high',
                        'penetrance_score': 0.7,
                        'evidence': 'familial',
                        'note': '幼年性息肉病综合征(JPS); BMP/TGF-β受体',
                        'phenotype_assoc': 'JPS(常显);BMP/TGF-β1型受体;错构瘤息肉',
                        'key_domains': '活化素受体域;GS域;蛋白激酶域',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'POLE',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.65,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.4,
                        'evidence': 'mixed',
                        'note': '聚合酶校对相关息肉病(PPAP); 杂合POLE致病变异→超突变CRC',
                        'phenotype_assoc': 'PPAP(常显);超突变CRC;DNA聚合酶epsilon校对缺陷',
                        'key_domains': '核酸外切酶校对域;聚合酶域;Zf-C4pol',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'POLD1',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.6,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.35,
                        'evidence': 'mixed',
                        'note': '聚合酶校对相关息肉病; DNA聚合酶delta校对亚基',
                        'phenotype_assoc': 'PPAP(常显);DNA聚合酶δ校对缺陷;CRC+子宫内膜癌',
                        'key_domains': '核酸外切酶校对域;聚合酶域',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'CHEK2',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.5,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.2,
                        'evidence': 'mixed',
                        'note': 'CRC风险~2x; 1100delC等致病变异; 可能与Lynch修饰',
                        'phenotype_assoc': 'CRC OR~2;细胞周期检查点;1100delC',
                        'key_domains': 'SQ/TQ簇域;FHA域;激酶域',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'PTEN',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.55,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.25,
                        'evidence': 'mixed',
                        'note': 'Cowden综合征; CRC风险~9-16%; 错构瘤息肉',
                        'phenotype_assoc': 'Cowden(常显);CRC~9-16%;错构瘤息肉;PI3K/AKT通路',
                        'key_domains': '磷酸酶域;C2域;PDZ结合',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'GREM1',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.55,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'mixed',
                        'note': '遗传性混合性息肉病(HMPS); 上游重复→GREM1过表达→混合息肉',
                        'phenotype_assoc': 'HMPS(常显);BMP拮抗剂;混合息肉(增生/腺瘤/幼年)',
                        'key_domains': 'DAN域',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'AXIN2',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.5,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.25,
                        'evidence': 'mixed',
                        'note': '少牙-结直肠癌综合征; Wnt/β-catenin通路支架蛋白',
                        'phenotype_assoc': 'ODCRCS(常显);少牙/缺牙;CRC;Wnt调控',
                        'key_domains': 'RGS域;β-catenin结合;DIX域',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'NTHL1',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.5,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'mixed',
                        'note': 'NTHL1相关息肉病(AR); 双等位变异→腺瘤性息肉+CRC',
                        'phenotype_assoc': 'NAP(常隐);碱基切除修复;多发性腺瘤;CRC',
                        'key_domains': 'HhH-GPD域;Fe-S簇;DNA糖基化酶',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'MSH3',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.45,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.25,
                        'evidence': 'mixed',
                        'note': 'MSH3相关息肉病(AR); 双等位变异→腺瘤性息肉+CRC',
                        'phenotype_assoc': 'MAP2(常隐);MMR;腺瘤性息肉;CRC',
                        'key_domains': 'MutS域;MSH2异源二聚体',
                        'clingen_validity': 'Limited'},
                    {   'gene': 'RNF43',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.45,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.25,
                        'evidence': 'mixed',
                        'note': '锯齿状息肉病综合征(SPS); Wnt受体Frizzled泛素化E3连接酶',
                        'phenotype_assoc': 'SPS;Wnt受体降解E3连接酶;锯齿状息肉',
                        'key_domains': 'RING锌指;蛋白酶相关域',
                        'clingen_validity': 'Limited'},
                    {   'gene': 'TCF7L2',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.28,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS最强位点之一(10q25); Wnt通路转录因子; 也与T2D关联',
                        'phenotype_assoc': 'TCF7L2/TCF4;10q25 CRC GWAS;Wnt/β-catenin效应子;T2D',
                        'key_domains': 'β-catenin结合域;HMG-box;CTNNB1结合',
                        'clingen_validity': ''},
                    {   'gene': 'SMAD7',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS强位点(18q21); TGF-β/BMP通路抑制性SMAD',
                        'phenotype_assoc': 'SMAD7;18q21 CRC GWAS;TGF-β通路抑制性SMAD',
                        'key_domains': 'MH1域;MH2域(SMAD结合)',
                        'clingen_validity': ''},
                    {   'gene': 'GREM1',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS 15q13位点; BMP拮抗剂',
                        'phenotype_assoc': 'GREM1;15q13 CRC GWAS;BMP通路拮抗剂',
                        'key_domains': 'DAN域',
                        'clingen_validity': ''},
                    {   'gene': 'BMP4',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS 14q22位点; BMP信号通路配体',
                        'phenotype_assoc': 'BMP4;14q22 CRC GWAS;TGF-β超家族;发育/肿瘤',
                        'key_domains': 'TGF-β前体域;TGF-β结构域',
                        'clingen_validity': ''},
                    {   'gene': 'CDKN2A',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '9p21 CRC GWAS/CDKN2A位点; p16/p14ARF抑癌基因',
                        'phenotype_assoc': 'p16/p14ARF;9p21;细胞周期/CDKN2A;CRC GWAS',
                        'key_domains': 'ANK重复×4(p16)',
                        'clingen_validity': ''},
                    {   'gene': 'MYC',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '8q24 CRC GWAS核心位点; MYC原癌基因',
                        'phenotype_assoc': 'c-Myc;8q24 CRC GWAS;多癌种风险位点',
                        'key_domains': 'bHLH;亮氨酸拉链',
                        'clingen_validity': ''},
                    {   'gene': 'CCND2',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS 12p13位点; Cyclin D2',
                        'phenotype_assoc': 'Cyclin D2;12p13 CRC GWAS;G1/S转换;细胞周期',
                        'key_domains': 'Cyclin N;Cyclin C',
                        'clingen_validity': ''},
                    {   'gene': 'EIF3H',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS 8q23位点; 翻译起始因子3亚基H',
                        'phenotype_assoc': 'EIF3H;8q23 CRC GWAS;翻译起始因子;细胞增殖',
                        'key_domains': 'MPN域',
                        'clingen_validity': ''},
                    {   'gene': 'TERT',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '5p15 CRC/多癌种GWAS; 端粒酶催化亚基',
                        'phenotype_assoc': 'TERT;5p15 CRC GWAS;端粒酶;多癌种风险',
                        'key_domains': 'TERT_RBD/TERT_RNA;逆转录酶域',
                        'clingen_validity': ''},
                    {   'gene': 'FADS1',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS 11q12位点; 脂肪酸去饱和酶',
                        'phenotype_assoc': 'FADS1;11q12 CRC GWAS;PUFA代谢;炎症调控',
                        'key_domains': '脂肪酸去饱和酶域;细胞色素b5-like',
                        'clingen_validity': ''},
                    {   'gene': 'LAMC1',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS 1q25位点; 层粘连蛋白γ1',
                        'phenotype_assoc': 'LAMC1;1q25 CRC GWAS;细胞外基质/基底膜组成',
                        'key_domains': '层粘连蛋白N端;EGF-like;层粘连蛋白卷曲螺旋',
                        'clingen_validity': ''},
                    {   'gene': 'CDH1',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS 16q22位点; E-cadherin',
                        'phenotype_assoc': 'E-cadherin;16q22 CRC GWAS;上皮粘附;Wnt/EMT',
                        'key_domains': '钙粘蛋白重复×5;跨膜域;β-catenin结合',
                        'clingen_validity': ''},
                    {   'gene': 'ZNF90',
                        'tier': 'gwas',
                        'contribution_score': 0.12,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS 19p13位点',
                        'phenotype_assoc': 'ZNF90;19p13 CRC GWAS;锌指转录因子',
                        'key_domains': 'C2H2锌指;KRAB域',
                        'clingen_validity': ''},
                    {   'gene': 'RHPN2',
                        'tier': 'gwas',
                        'contribution_score': 0.12,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS 19q13位点; Rhophilin-2',
                        'phenotype_assoc': 'RHPN2;19q13 CRC GWAS;Rho GTPase效应蛋白',
                        'key_domains': 'HR1域;PDZ域',
                        'clingen_validity': ''},
                    {   'gene': 'NOC2L',
                        'tier': 'gwas',
                        'contribution_score': 0.12,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CRC GWAS 1p36位点; 核仁复合体蛋白',
                        'phenotype_assoc': 'NOC2L/NIR;1p36 CRC GWAS;p53/TP53调控;核仁',
                        'key_domains': 'Nucleolar complex protein 2;Armadillo-type fold',
                        'clingen_validity': ''}],
    'known_pathogenic_variants': [   {   'rsid': 'rs137854568',
                                         'chrom': 'chr5',
                                         'pos': 112174760,
                                         'ref': 'G',
                                         'alt': 'T',
                                         'gene': 'APC',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 1.0,
                                         'confidence': 'high',
                                         'note': 'APC c.3920T>A (I1307K) — Ashkenazi CRC风险~2x'},
                                     {   'rsid': 'rs63751445',
                                         'chrom': 'chr3',
                                         'pos': 37035078,
                                         'ref': 'A',
                                         'alt': 'G',
                                         'gene': 'MLH1',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 1.0,
                                         'confidence': 'high',
                                         'note': 'MLH1 c.676C>T (R226X) — Lynch founder (中国)'},
                                     {   'rsid': 'rs63751657',
                                         'chrom': 'chr2',
                                         'pos': 47416267,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'MSH2',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 1.0,
                                         'confidence': 'high',
                                         'note': 'MSH2 c.942+3A>T — Lynch剪接变异'},
                                     {   'rsid': 'rs36053993',
                                         'chrom': 'chr1',
                                         'pos': 45319775,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'MUTYH',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.8,
                                         'confidence': 'high',
                                         'note': 'MUTYH Y179C (c.536A>G) — 欧洲人群中常见MAP致病变异'},
                                     {   'rsid': 'rs34612342',
                                         'chrom': 'chr1',
                                         'pos': 45328038,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'MUTYH',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.8,
                                         'confidence': 'high',
                                         'note': 'MUTYH G396D (c.1187G>A) — 欧洲人群中常见MAP致病变异'},
                                     {   'rsid': 'rs483352909',
                                         'chrom': 'chr12',
                                         'pos': 132673438,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'POLE',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.8,
                                         'confidence': 'high',
                                         'note': 'POLE P286R — 核酸外切酶热点; 超突变CRC'},
                                     {   'rsid': 'rs121909109',
                                         'chrom': 'chr19',
                                         'pos': 50401021,
                                         'ref': 'T',
                                         'alt': 'C',
                                         'gene': 'POLD1',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'high',
                                         'note': 'POLD1 S478N — 校对域热点; PPAP'},
                                     {   'rsid': '1765255',
                                         'chrom': '2',
                                         'pos': 47783103,
                                         'ref': 'C',
                                         'alt': 'CCACTGGGGCCCGGGTTCCTCCGGCGGAGCGCGCCTCCCCCCAGATTTCCCGCCAGCAGGAGCCGCGCGGTAGATGCGGTGCTTTTAGGAGCTCCGTCCGACAGAACGGTTGGGCCTTGCCGGCTGTCGGTATGTCGCGACAGAGCACCCTGTACAGCTTCTTCCCCAAGTCTCCGGCGCTGAGTGATGCCAACAAGGCCTCGGCCAGGGCCTCACGCGAAGGCGGCCGTGCCGCCGCTGCCCCCGGGGCCTCTCCTTCCCCAGGCGGGGATGCGGCCTGGAGCGAGGCTGGGCCTGGGCCCAGGCCCTTGGCGCGCTCCGCGT',
                                         'gene': 'MSH6',
                                         'effect_allele': 'CCACTGGGGCCCGGGTTCCTCCGGCGGAGCGCGCCTCCCCCCAGATTTCCCGCCAGCAGGAGCCGCGCGGTAGATGCGGTGCTTTTAGGAGCTCCGTCCGACAGAACGGTTGGGCCTTGCCGGCTGTCGGTATGTCGCGACAGAGCACCCTGTACAGCTTCTTCCCCAAGTCTCCGGCGCTGAGTGATGCCAACAAGGCCTCGGCCAGGGCCTCACGCGAAGGCGGCCGTGCCGCCGCTGCCCCCGGGGCCTCTCCTTCCCCAGGCGGGGATGCGGCCTGGAGCGAGGCTGGGCCTGGGCCCAGGCCCTTGGCGCGCTCCGCGT',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Hereditary cancer-predisposing '
                                                 'syndrome'},
                                     {   'rsid': '1736919',
                                         'chrom': '2',
                                         'pos': 47783229,
                                         'ref': 'TCGGTATGTCGCGACAGAGCACCCTGTACAGCTTCTTCCCCAAGTCTC',
                                         'alt': 'T',
                                         'gene': 'MSH6',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Hereditary cancer-predisposing syndrome'},
                                     {   'rsid': '2682828',
                                         'chrom': '7',
                                         'pos': 5973305,
                                         'ref': 'GGTTCATTTTAAAACAAAAAAGGTTAGTGAAGACTCTGTCTTTCAAAACATAAAAATCTGCGATAAAACCAATTATTCCATACAGTGACTACGGTCAGTTCTGAGAAATGACACCCAGGTTGGCGATGTGTCTCATGGTTGGCCTTCCATGGGGACAGTTCCAGGGGTGGTCCATCTCCCCCATGTGGGTGATCAGTTTCTTCATCTCGCTTGTGTTAAGAGCAGTCCCAATCATCACCTGAGTGTGAGACACAATGGTTCAACGTTTTAGTAGTTTTTTGACGTCAGAATGGCAGCTCTTCAGAAGCATTCTTCTCTAAAATAAGGCTGGACAAGATTACAGCTCAAAAACTACCTTCCCTGAAAAACCTTCCCCCAGAGAAGCCTAGGTTCTAGATCTCAGCCCTCCACCCTTCTGTGAAATCAGGCTCCTTGTGGCTCCTTCAAGGTGGCACCGCCTCCACTCCAGACGCCGACCACACCTGTCTCAGCAGCCACCCTGCCCTCTCACCCTGGCAGGTGCAGCAGCCTCCCAGCAGGCCTCCCTGCCCCACTGCGACCCCTCCGAGCCGCTCTCCACTCAGCAGCCAGTGATTACTTTTAAAGGGCTGTCAGGTTATTCATTCCACTTCACAGCTCTCCCCCTCACCTGAATAAAAGCCCCCGTCTGTCCCCTGACTTGGCCCTCGCTGGGCTGTGCCTGCACCCCCACCTCCAAGCACGAATGCCTCCCTTCCTCACCCCAGCTGCACTGCTACTCCCTTCCTCTTGCACAGGCCCATCACGCAAACACCTGCCTTGGGACTGTGGCACTCCCGGGACCCTCTCCCCCAATGGGTGCAGGCGTCACTCCCCCTCTGTCGAGCTCCGACCTGCTGCCCATAGCACTCCAGCCCTGGCCCTGCTGCCTCCCTGCCATGGGTCCTCTGACAGGAAGGAGAGGACACAAGCCTGAAGCCCAATGTCACCTTCTTTCTTCCTGCAGCACCCTGAGGGCTCGCCATGTGCCAAGCACAGTCAGAAGGCTGGGGTGACAGCAGGTTGGAGAAGGACAGACAATCAACAAGTCAACAGAGAACCAAGACAGGTGGCACCAGGCGAGGCGGCCTGCTCAGGTGTGGGGATGGGGTGAAGGGTGACGGTGGCAAACCCAGGTAGAGAGGAGAGTAGGGAGAAAGGGTGTAAGGCAGGGAGGAGACTGAGGCGAGCGTGGAACTGGAAGGCAGCTACATGGCTGGAAGCTACATGGTGGGGAGATGGGGCTGGAAGGGTGGGCAGGGCTCAAAGCAGGAGCCTCCTGGGCAGGCAGTGACAACACCGGAGATGGACGGGTAGGCCAGGGCGAGAGGGAAGGAGCAGCCTGTGGTTCCCCGGGCCACTGAGTCACACTAAACTCAGGACATCAAAACTGCCCGGCTATGAGCTCAGCTCCACGCTCTCACTCACAGACTCCAAGACTGGAAGATCCATATTATGTCTTTTATTTTGGTGAGGTCAGGGGTGGTGGAGAGACTCTGTCTCCCAGGCTGGAATGCAATGGTGCGATCTCAGCTCACTGCAACTCCGCCTCCCAGATTCAAGCAATTCTCCCGCTTCAGCCTCCCGAGTAGCTGGGATTACAGGCGCCCACCACCATGCCCAGCTAATTTTCGTACTTTTAGTAGGGATGGGGTTTCACCATGTTGGCCAAGCTGGTCTCAAATTCCTGACCTCAGGTGATCAACCCACCTCCGCCTTCCAAAGTGCTGGGATTACAGGTGTGAGCCACCACGCCCAGCCCCTATTAGGTCTTTATCCAAGAAACACTGTGGCTAGAAGTCAGACTCTGGGCCCTCTTCTAATTAAACTCTGCCCTTGAGTCATTTCATCTAATCTCATGGCTGTAAATTACACCTGAAGCTCACACAGCAGGCTCCATCCCACCCACTCCCCACGTGGCCCCCAGCTGCTGCTCTCCTCAGCGGCCGCAGCCACCGCACCCCTTCCAGTCTGTTCTCTCTCCAGCAGCTGCAATCACGGGACTCCTTCCCGTCTGTTCTCTCCAGTGGCTCGTGCCACACACAGCACAGACCCCCAGGGTCTAGGTATGACCGGCAACACTCTACGTGGCTGTCCTCTGGACGCCGCTCTGCTCACTCCCTTCCCCTCTCCAGGGACACAATCAGCCTCTGGCTTCAGTCTTGCTACTTCCTTCGCTTGGAAAGTTCTTACCCAAGAGGGCTCCATTCTACCTTTTTTTTTTTTTTTTTTGAGACAAGGTCTTACTCTGTCACCCAGGCTGGAGTGCAGTTGCGTGATGTTGGCTCATTGTAACCTCGACCTCCCTGGCTCAAGTGATCCTCCCACCTCAGCCTCCTGAGTAGCTGTGACTACAGGCACATGCCACCACACCTGGCTAATCTTTTAATTTTTTGTACACATGGGGTCTGCCTGTGTTGCCCAGGCTGGTCTCTTAACTCCTGGCCTCAAGCAATCCTCCTGCCTTGGCCTCCCAAAATGCTGGGATTACACGTGTGAGCCACCATGCCTGGCTTCCATCCCACCTTTTAGATGGCAGCTGAGATGCCACCTGCCCAGATGCCATTCCCTGACCACCATCTCACCTGGTCACCATGTTTTTCTCTTGTCATTTCCTGCCCCAAAACGCTGTTTTAGGCCAGGTGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGACCAAGGCGGGCAGATCATGAGGTCAGGAGATCAACACCAGCCTGACCAACATGGTGAAACCCCATCTCTATTAAAAATATAAAAATTAGCCAGGTGTGGTGGGTGCCTGTAGTCCCAGCTACTTGGGAGGCTGAGGCAGGAGAATCGCTTGAACCTGGGAGGCGGAGGTTGCAGTGAGCTGAGATCACATCACTGCACTCCAGCCTAGTAACAGAGCGAGACTCCGTCTCAAAAACAGACAAAGAAAAATGCTGTTTGAATCTCTTGACTGTGCTTACTGGCATCTAATGCGTGTCATTTATTTGTGGTGATGCCTATTTCTCCCCACTGTCTGCTCCACAGGGGCAGGGGCTGCAGCCGCCTTGTTACCTCTGTGTCCCGAGCACCTGGAGCAGGGCGGGCCCCACATCAGGGGCTCAAGGAGCACCTGCTGAATAAATAAAGGAATGGCGTCCTGGCCCTTCCCAGTGGCCAGCTGATACACAGTCACTTTTCTTGGACATCAGGCTAATCCCCACTGCAGGCAGAACCACTGCTGCCACCTTCCCACACCAACCGAAGCAGCGGCAGTGACGCCACGTGCAATGACAACCACGGCACCCCGTGAAGCACCTGCTGCCTCGATGACTCTGCAGAATCGTGTCCAATGTCGCCGAGTCCTGGCAGCAGCAAATCTTTATCTCCCAATGTTGTTATGACCCATAAGGTCCATAGACGAACAAGGTACCTCAAACGCTAACTGCGTTGGAGTCAACCAAAGCTCGGAGATAGAATACTGGCCGGGCCAGGCACAGTGGCTCATGCCTGTAATTCCAGCACTTTGGGAGGCTGAGACAAGGGGCAAAAGGAGACCATGTTTCTACAAAAAATTTAAAAATTAGCTGGGCATGGTGGTGCATGCCTGTGGTCACAACTACTTGGGAGACAGAGAGAGGAGGATCGCTTCAGCCTGGTACGTCAAGGCTGCAGTGAGCTGTGATTGTGCCACTGCACTCCAGCCTGGGGGACAGAGGGAGAATCTGTCTAAAAAAAAAAAAAAGAAGAATTCTGGGTTTTTTTTGTTTTTTTGAGACGGAGTCTCGCTCTGTCGCCCAGGTTGGAGTGCAGTGGTATGAACTTGGCTCACTGCAAGTTCCGCCTTCTGGGTTCACGCCATTCTCCTGCCTCAGCCTCCCGAGTAGCTGGGACTATAGGCGCCCGACACCACGCCCGGCTAATTTTTTTGTATTTTTAGTAGAGACGGGCTTTCACCATGTTAGCCAGGATGGTCTCGATCTCCTGAACTCGTGATCCGCCCGCCTCAGCTTCCCAAAGTGCTGGGATTAGAGGCTTGAGCCACCATGCCCGGCCAAGAATACTGCTTAACAGAGGTAACAAAAGAGCAATAATTATGAGTTCAAGGTCACAGAGAACGCAGACGACACAGATGCTCAGCTACGACGCTGCACGTAGCTCTCTGTGTAAAATGACCCCTGGCAATCACAAAGGCGTTTACAACCTTGACCAAATCAGGAGCTGGGCTGAGACCTTCCTCGACTGCAAGCTTGAGCAGCTGAGCTGACAGCCAGGCTTTCTTTACTTACCGACTTCCGGCAGGCTCTGGAGGCAAACATCTGCTTGACTCGGGAAGGCCGGCACATGACCCCAGGGCTGTCGCTCAGCATGAAGATCAGTTCATCGACGTCCTGGGGTCCGAAGGTCCAGTTTTTACTAGTTGGCAAGGAAATCAGTTTAGCCCTTTCAGTGACTGGAGCTAAAAGAATACAATTTTGAGAAAAATCCATGACTTGACAAACACGTTTCACTTGAAAGCTACTTAGGATGAACATCTGAGGCCGGGCGTGGTGGCTCACGCCTGTAATCCCTGCACTTTGGGAGGCTGAGGCCAGCGGATCATGAGGTCAGGAGATACAGACCATCCTGGCTAACATGGTGAAACCCCGTCTCTACTAAAAAATAGAAAAAATTAGCTGGGTGTGGTGGCAGGCACCTGTAGTCCCAGCTACTCGGGAGGCTGAGGCAGGAGAATGGTGTGAACCTGGGAGGCGGAGCTTGCAGTGAGCCGAGATCGGCACCACTGCGCTCCAGCCTGGGCGACAGAGCAAGACTCCATCTCAGAAAAAAAAAAAGTGAACACCTGAAAGAGAGGAAACTCACAAAATGCTTTTTGGAGGAACTTTTTAATCTTTTATAAAATTAAAAAAAACTGGTCTATATGACCTGAAAGATTATTCCCAGCTCTAAAAAGACAAGAATCTATAGTTCTGATTTTTTTTTTTTTTTGAGACAGAGTTTCACTCTTGTTGCCCAGGCTGGAGTGCAGTGACGTGATCTCGGCTCACTGCAACCTCCACCTCCCGGGTTCAAGCGATTCTCCCACCTCAGCCTCCTGAGTAGCTGGGATTACAGGCACCCGCCACCACGCCCGGCTACTTTTTGTATTTTCAGTAGAGATGGGGTTTCACCATGTTAGCCAGGCTGGTCTCAAACTCCTGACCTCAGGCGATCTGCCCGCCTTGGCCTCCCAGAGTGCTGGGATTACAGACGTGAGCCACCACACCCAGCCGCTATAGTTCTAATTAATAACTTACCATTTTCATCGATAACAAAATCAAAGCCATTCTTTCTAAATATTTCCAGATTTTCTATCAGAACAGCTTCATTAACAGCAGTTAAGTTGAGAGTCTGAGGTCTGAAAAACACAAAAATGATTCAAACCATATCCTGAAGTCAAACATTTAGCTTTACAGCAGAAATGAAATGAAAACAACAATACTGTATTTTGAATTCATGTCAAAATAACAACACAAATAACAACACTACTCAGCTAAGTGTCACAAAACTTCCTGAGAAGTTCCTTTTAATTTTCTCTTTCTTAAAGTTCTTTTTAGAAGTTAAAGTAGCTACAGGCCAGGTGCGGTGGCTCACGCCTGTAATCTCAGCACTTTAGGAGCCCGAGGCAGGCAGATCTCTTGAGGCCAGGAGTTTGAGACCGGCCTGGTCAACACAGCGAAACACTCTCTCTACTAAAAATATAAAAATTAGGCCAGGCATGGTGGCGCACGCCTGTAGTCCCAGCTACTTGGGAGGCTTAGGCATGAGATTCGTTTGAACCCAGGAGGGAGGCAGAGGTTGTAGTGAGAGCCAAGATCACGCCACTGTACTCCAGCCTGGGCGACACAACAAGACTCTGTCTCAAAAAAAAAAAAAAAAAAAAAACACCCATAAAAACAAAAATTAGCTGGAAGTGGTGGCTCATGCCTGTAATCCCAGCTACTCGGGAGGCTGAGGCACTAGAATTGCTTGAACCCAGGAGGTGGAGGTTGCAGTGAGCCAAGATCACACCACTGCACTCCAGCCTGGGCAACAGGGCAAGACTCTGTCTCAAAAAAAAAAAAAAAGTTCAAGTAGCTACAAAAGTAGTTTGCTTTTTCCTCAGCCTGCCACGCCAATGACTCCCACTTTTTCTGAATCCTTTCCTTAAGGATAACAGTATCACAAAAATGCTATTTTTCCTCCTTCTAATACAGAATTTGAAACACTGGGTTAGGTCATTGCCAGCATTTGTAAACAGAATGAACAGACAGCTTTTATTTTGCTATCCTGTTCCTTCCTCTGCCTGTATTATATCTCCATCCCTCTCTCCTCCTGGATTTACTGTTTGTTTTTTTTTAACCTTTCGTTATTTTTTTCAAAGATAGAGACAGGGTCTCACTATGTTGCCCAGGCTGCTCTCAAACTCCTGGGCTCAAGCGATCCTTCCACTTCAGCCTCCCAAAGTGCTGGGATTACGAGTGTGAGCCACTGCATCTGGTCCTGAGTGCTGGATAAGACAAACACTGCTCAAGGCAGGAGACAGCTGGTGAGCAAACACAGGCTTGGTCCTGGAGCCAACAGATTACCGGGGAAGAAAGACGTTGAGCAAATACTCAGGCAAGTCGATTATGATGAGAAACGACAGGAAGGTCAGGAAGAAAAAGCAGCCAGTGTCATAGAGAGACTTCACCCTGGGGTCAGGAAGTGACCTTTGAGCTGAGTCCGGGGATAAGAGAGTTAATCAGGTAACGGGGGAGAAGTGGGTGCAGGGTGCAGGACAAGTATTCTAGACAGGGACAACAATCTGTGCCAAGCCCCAGGATGGACCGCTGATGTTTGCAGAGCCACACATAAAGATATCCTTCATTCTGCTTAGTGGCCACATAGGGATTCATCAGGCCTGCCAAGGGAAAAAGAAAGACAGCCAGAGAGGCTTGAGTACAGGGAACAAGGGGAAGACGAACGGGAAAAGCTACAGAGGTCAACAGGGCCACCCTACACAGGGGCTGGCAGGGCAGGGTGGAACTGGGTCTTTATCCTTTAATCTTGAAGTGTGGTCCATCTGGGACCCTAAGTGGTCTGTGATTACCTGGGCCAACTTGAAATGTCACAGATGAGAGGTTATCTTTGCCGAATGGCTAAAAAATACAAGACCTCAGCCGGGCATGGTGGCTCACACCTGTAATCCCAGCACTTTGGGAGGCTGAGGTTGGTGGATCACCTGAGGTCAGGAGTTCAAGACCAGCCTGACAAACATGGCAAAACTCCCTATCTATTAAAAATCCAAAAATTAGCCAGGTGTGGTGGCGGGTGCCTGTAATCCCAGCTACTCGGGAGGCTGAGGCAGGAGAATCACTTGAACCCGAGAGGCAGAGGTTGCAGTAAGCCGAGATCACATCACTGCACTCCAGTATGGGCGAAAGAGTGAAACTCTGTCTCAAAAACACAAAAACAAAAAACCTCTATTAAGAGGAACAGGGAAGGGATATAAAGTAGCTTACTAAATGTCTATTATTACCATTGCCTCCTACTGAGAATAAAAACAATTCACGCATTCCACAGGAGAGTACTCAGCAAACTACACAGGAGAGTACTCAGCAAACTACACAGGAGAGTACTCAGTAAACTACACAGGAGAGTACTCAGCAAACTACACAGGTTCAGTGGTACATTTCTCCATGTGGGATCTACTTGTTGGGATCTGAGTTTACTTCACTACGTGGTTTAATTTCCCACACGAAAATCCATGACCTCTTCTTCTAACTTTGCTGAAGACAAGACTTTGGTTTTACATGATACTATCACACCTGACCTTTGTGAAGTAGTCAGGGTAAAACATTCCAGTTTGGCCGAGGAGAGAGAAATACCAAATTCTGCAGTGACTATCTTAAAATAATTTTTAAATTTTATTTTATTTTATTTATTAATTTATTTGTGAGACAGAGTCTCACTGTCTCACTCTGTCACCCAGGCTGGAGAGCTGTGCAGTGGCACGATCATGGCAGCCTCAATCTCCTGGGCTCAAACGATCCTCCCACCTCAGCCTCCCGAATAGCTGGGACCACAGGCACACACCATCAAGTCTGACTAATTTTTTACATTTGTTGTAGAGACAAGGTTTCACCATGATGCCCAGGCTGGTCTCAAACTCCTAAGCTCGAGGGATCTGCCTGCCTCAGCCTCCCAAAGCTCTGGGATTACAGGCGTGTGCCCCTGCATCCAACCTGCAGTGACTATCTGACTTCTGATTACTCTACTGTCAATCAACACTGGCGCACAGGCTGTCTGTCTTTCTGAACACACACATTCCATACACTATGCATACTAATACTCCATACTATCAATTGCCCTCATCAGAAGGATCTTCTGGC',
                                         'alt': 'G',
                                         'gene': 'PMS2',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | not provided'},
                                     {   'rsid': '1049466',
                                         'chrom': '7',
                                         'pos': 5973395,
                                         'ref': 'ACGGTCAGTTCTGAGAAATGACACCCAGGTTGGCGATGTGTCTCATGGTTGGCCTTCCATGGGGACAGTTCCAGGGGTGGTCCATCTCCCCCATGTGGGTGATCAGTTTCTTCATCTCGCTTGTGTTAAGAGCAGTCCCAATCATCACCTGAGTGTGAGACACAATGGTTCAACGTTTTAGTAGTTTTTTGACGTCAGAATGGCAGCTCTTCAGAAGCATTCTTCTCTAAAATAAGGCTGGACAAGATTACAGCTCAAAAACTACCTTCCCTGAAAAACCTTCCCCCAGAGAAGCCTAGGTTCTAGATCTCAGCCCTC',
                                         'alt': 'A',
                                         'gene': 'PMS2',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Endometrial carcinoma'},
                                     {   'rsid': '576830',
                                         'chrom': '19',
                                         'pos': 1205798,
                                         'ref': 'GGCGTGTCGGGCGCGGAAGGGGGAGGCGGCCCGGGGCGCCCGCGAGTGAGGCGCGGGGCGGCGAAGGGAGCGCGGGTGGCGGCACTTGCTGCCGCGGCCTTGGATGGGCTGGGCCCCCCTCGCCGCTCCGCCTCCTCCACACGCGCGGCGGCCGCGGCGAGGGGGACGCGCCGCCCGGGGCCCGGCACCTTCGGGAACCCCCCGGCCCGGAGCCTGCGGCCTGCGCCGCCTCGGCCGCCGGGAGCCCCGTGGAGCCCCCGCCGCCGCGCCGCCCCGCGGACCGGACGCTGAGGGCACTCGGGGCGGGGCGCGCGCTCGGGCAGACGTTTGCGGGGAGGGGGGCGCCTGCCGGGCCCCGGCGACCACCTTGGGGGTCGCGGGCCGGCTCGGGGGGCGCCCAGTGCGGGCCCTCGCGGGCGCCGGGCAGCGACCAGCCCTGAGCGGAGCTGTTGGCCGCGGCGGGAGGCCTCCCGGACGCCCCCAGCCCCCCGAACGCTCGCCCGGGCCGGCGGGAGTCGGCGCCCCCCGGGAGGTCCGCTCGGTCGTCCGCGGCGGAGCGTTTGCTCCTGGGACAGGCGGTGGGACCGGGGCGTCGCCGGAGACGCCCCCAGCGAAGTTGGGCTCTCCAGGTGTGGGGGTCCCGGGGGGTAGCGACGTCGCGGACCCGGCCTGTGGGATGGGCGGCCCGGAGAAGACTGCGCTCGGCCGTGTTCATACTTGTCCGTGGGCCTGAGGTCCCCGGAGGATGACCTAGCACTGAAAAGCCCCGGCCGGCCTCCCCAGGGTCCCCGAGGACGAAGTTGACCCTGACCGGGCCGTCTCCCAGTTCTGAGGCCCGGGTCCCACTGGAACTCGCGTCTGAGCCGCCGTCCCGGACCCCCGGTGCCCGCCGGTCCGCAGACCCTGCACCGGGCTTGGACTCGCAGCCGGGACTGACGTGTAGAACAATCGTTTCTGTTGGAAGAAGGGTTTTTCCCTTCCTTTTGGGGTTTTTGTTGCCTTTTTTTTTTCTTTTTTCTTTGTAAAATTTTGGAGAAGGGAAGTCGGAACACAAGGAAGGACCGCTCACCCGCGGACTCAGGGCTGGCGGCGGGACTCCAGGACCCTGGGTCCAGCATGGAGGTGGTGGACCCGCAGCAGCTGGGCATGTTCACGGAGGGCGAGCTGATGTCGGTGGGTATGGACACGTTCATCCACCGCATCGACTCCACCGAGGTCATCTACCAGCCGCGCCGCAAGCGGGCCAAGCTCATCGGCAAGTACCTGATGGGGGACCTGCTGGGGGAAGGCTCTTACGGCAAGGTGAAGGAGGTGCTGGACTCGGAGACGCTGTGCAGGAGGGCCGTCAAGATCCTCAAGAAGAAGAAGTTGCGAAGGATCCCCAACGGGGAGGCCAACGTGAAGAA',
                                         'alt': 'G',
                                         'gene': 'STK11',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Peutz-Jeghers syndrome'},
                                     {   'rsid': '1050750',
                                         'chrom': '19',
                                         'pos': 1206911,
                                         'ref': 'AGCATGGAGGTGGTGGACCCGCAGCAGCTGGGCATGTTCACGGAGGGCGAGCTGATGTCGGTGGGTATGGACACGTTCATCCACCGCATCGACTCCACCGAGGTCATCTACCAGCCGCGCCGCAAGCGGGCCAAGCTCATCGGCAAGTACCTGATGGGGGACCTGCTGGGGGAAGGCTCTTACGGCAAGGTGAAGGAGGTGCTGGACTCGGAGACGCTGTGCAGGAGGGCCGTCAAGATCCTCAAGAAGAAGAAGTTGCGAAGGATCCCCAACGGGGAGGCCAACGTGAAGAAGTAAGTATGGCTTGCTGGGGTCGGGGCCGGGCCGGGCCAGTCACGGTGCTGATGGTTCTGTCTTCCTTCCTTCTCTCCTCCCTCCCTCCCTTACTTCCTCTTAACACCCTGAGCTGGACCCGTCTGGCGCCTGTGTCCTCCGTGCCAGGGAGAGCGTGGTTGGGGGCCTGCGTTACGGACTTTCACTCAGGCAAGGCCAGTTGTCGCAGCGGGGCGTGCGTTTGCATGGGCTCTTGGACTCCAGTTAAAATGCCCTGGTAGCGAAACCCTCCTGAGAAGGGAGCGGCCCCCAATCCCCTAAGACTAGCCCCTTGGCTCCCCCAGCTGTCCAAGGAGCAGAGGCGCCCAGTGGAATCAGCCTGTGTTTGTTTGGGCCCCGAGAGTTTGTGTGCGGCCGCCAACACGTTTTCTGCGCAGTGTGTGGCCGTTACCGGGGCCAGGCGAAATGTGATTTGTTTATCCTGTCAGAGGGGAACCCTGGGCTGCCAAAAATAACTGTTTGCACCGGCTTATCAGTCAGCAGGAGGGAAACGTAGCCTTTCCTCATTTGCCAGGGATGTGACGCTGGAAGCATCCCTGGCCCCCGGGGCTGGAAGCCCTGCCCGAGGGGGACTGTGCCTCCCTCCCGAATTGCATCCGGAAGACCTTACTTTTCCAACTGACTTCTTCAGGCACGGGGCTGCCGCTGGGCATCCCGGACGCCTCTGCATCTGTGCGCGGAGAAGCTCCTACCTAGGGCAGCACTGGCCGGCCTGAGCCTCTCCCAGCTGGTGGGGGTGGCCGGGGGTGTCCCTGCCTTATCGCAGCCAGACACGCTGCACCTGCCGCCGCCTGGCGGGCCCTGCCCAGGCCCTGCTCCTTTCCCAGCCTTCTTAACTTTCAAAACTTTGCCTCCTGTTTCCAAGAAAGGACCTTATCTGCTGGGCTAGGCCTCGAGGGACTGGCAAGGACACCCTGCGCAGGGCACCATGACCTTGGAAGGAGGTCCGGGGAGGGGCTGCTGCGGTGTCTGC',
                                         'alt': 'A',
                                         'gene': 'STK11',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Generalized juvenile polyposis/juvenile '
                                                 'polyposis coli'},
                                     {   'rsid': '1351575',
                                         'chrom': '18',
                                         'pos': 51047067,
                                         'ref': 'GA',
                                         'alt': 'G',
                                         'gene': 'SMAD4',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Juvenile polyposis syndrome'},
                                     {   'rsid': '2572319',
                                         'chrom': '18',
                                         'pos': 51047095,
                                         'ref': 'CTG',
                                         'alt': 'C',
                                         'gene': 'SMAD4',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Myhre syndrome'},
                                     {   'rsid': '571700',
                                         'chrom': '10',
                                         'pos': 86756637,
                                         'ref': 'CGGCGGCCGCTGCAGAGATTGGAATCCGCCTGCCGGGCTTGGCGAAGGAGAAGGGAGGAGGCAGGAGCGAGGAGGGAGGAGGGCCAAGGGCGGGCAGGAAGGCTTAGGCTCGGCGCGTCCGTCCGCGCGCGGCGAAGATCGCACGGCCCGATCGAGGGGCGACCGGGTCGGGGCCGCTGCACGCCAAGGGCGAAGGCCGATTCGGGCCCCACTTCGCCCCGGCGGCTCGCCGCGCCCACCCGCTCCGCGCCGAGGGCTGGAGGATGCGTTCCCTGGGGTCCG',
                                         'alt': 'C',
                                         'gene': 'BMPR1A',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Generalized juvenile polyposis/juvenile '
                                                 'polyposis coli'},
                                     {   'rsid': '3647840',
                                         'chrom': '10',
                                         'pos': 86875913,
                                         'ref': 'C',
                                         'alt': 'CGATCTTTTACAAGAAAATCTCACTGAATGATAGTCATTTAAATTGGTGAAGTAGCAAGACCAATTATTAAAGGTGACAGTACACAGGAAACATTACAATTGAACAATGACTCAGCTATACATTTACATCA',
                                         'gene': 'BMPR1A',
                                         'effect_allele': 'CGATCTTTTACAAGAAAATCTCACTGAATGATAGTCATTTAAATTGGTGAAGTAGCAAGACCAATTATTAAAGGTGACAGTACACAGGAAACATTACAATTGAACAATGACTCAGCTATACATTTACATCA',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Juvenile polyposis syndrome'},
                                     {   'rsid': '2583652',
                                         'chrom': '22',
                                         'pos': 28687947,
                                         'ref': 'CGGCTTCCCCTTCACGGGGCCGCTTTCGACTAGTAGAAGGCTGAAAATAAAGGAAAATGGAGAAATGTTCAAAAGAAAATCACT',
                                         'alt': 'C',
                                         'gene': 'CHEK2',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Familial cancer of breast'},
                                     {   'rsid': '230579',
                                         'chrom': '22',
                                         'pos': 28687970,
                                         'ref': 'T',
                                         'alt': 'TG',
                                         'gene': 'CHEK2',
                                         'effect_allele': 'TG',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Hereditary cancer-predisposing '
                                                 'syndrome|Familial cancer of breast'},
                                     {   'rsid': '3780928',
                                         'chrom': '10',
                                         'pos': 87863231,
                                         'ref': 'A',
                                         'alt': 'G',
                                         'gene': 'PTEN',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | PTEN hamartoma tumor syndrome'},
                                     {   'rsid': '3780927',
                                         'chrom': '10',
                                         'pos': 87863292,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'PTEN',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | PTEN hamartoma tumor syndrome'},
                                     {   'rsid': '3660739',
                                         'chrom': '17',
                                         'pos': 65533984,
                                         'ref': 'CG',
                                         'alt': 'C',
                                         'gene': 'AXIN2',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Oligodontia-cancer predisposition syndrome'},
                                     {   'rsid': '849114',
                                         'chrom': '17',
                                         'pos': 65533986,
                                         'ref': 'G',
                                         'alt': 'C',
                                         'gene': 'AXIN2',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Oligodontia-cancer predisposition syndrome'},
                                     {   'rsid': '1765701',
                                         'chrom': '16',
                                         'pos': 2039956,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'NTHL1',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Hereditary cancer-predisposing '
                                                 'syndrome|not provided'},
                                     {   'rsid': '620182',
                                         'chrom': '16',
                                         'pos': 2040004,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'NTHL1',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic/Likely_pathogenic | NTHL1-related disorder|not '
                                                 'provided|Familial adenomatous polyposis 3|Hereditary '},
                                     {   'rsid': '940655',
                                         'chrom': '5',
                                         'pos': 80654739,
                                         'ref': 'GA',
                                         'alt': 'G',
                                         'gene': 'MSH3',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic/Likely_pathogenic | Familial adenomatous '
                                                 'polyposis 4|Endometrial carcinoma|Hereditary cancer-predisp'},
                                     {   'rsid': '2676774',
                                         'chrom': '5',
                                         'pos': 80654741,
                                         'ref': 'AG',
                                         'alt': 'A',
                                         'gene': 'MSH3',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Endometrial carcinoma'},
                                     {   'rsid': '1801831',
                                         'chrom': '17',
                                         'pos': 58357467,
                                         'ref': 'C',
                                         'alt': 'A',
                                         'gene': 'RNF43',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Sessile serrated polyposis cancer '
                                                 'syndrome'},
                                     {   'rsid': '4812959',
                                         'chrom': '17',
                                         'pos': 58357467,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'RNF43',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Sessile serrated polyposis cancer '
                                                 'syndrome'}],
    'gwas_lead_snps': [   {   'rsid': 'rs6983267',
                              'chrom': 'chr8',
                              'pos': 127401060,
                              'beta': 0.18,
                              'or_value': 1.2,
                              'eaf_eur': 0.5,
                              'eaf_eas': 0.4,
                              'gene': 'MYC',
                              'effect_allele': 'G',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.25,
                              'confidence': 'high',
                              'note': '8q24 — 最强CRC GWAS位点; MYC增强子'},
                          {   'rsid': 'rs4939827',
                              'chrom': 'chr18',
                              'pos': 48959519,
                              'beta': 0.15,
                              'or_value': 1.16,
                              'eaf_eur': 0.52,
                              'eaf_eas': 0.3,
                              'gene': 'SMAD7',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.22,
                              'confidence': 'high',
                              'note': 'SMAD7 — CRC GWAS'},
                          {   'rsid': 'rs4779584',
                              'chrom': 'chr15',
                              'pos': 32716452,
                              'beta': 0.15,
                              'or_value': 1.16,
                              'eaf_eur': 0.19,
                              'eaf_eas': 0.3,
                              'gene': 'SCG5',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.18,
                              'confidence': 'high',
                              'note': '15q13 (GREM1/SCG5) — CRC GWAS'},
                          {   'rsid': 'rs10795668',
                              'chrom': 'chr10',
                              'pos': 8684102,
                              'beta': 0.12,
                              'or_value': 1.12,
                              'eaf_eur': 0.3,
                              'eaf_eas': 0.35,
                              'gene': 'LINC01475',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': '10p14 — CRC GWAS'},
                          {   'rsid': 'rs16892766',
                              'chrom': 'chr8',
                              'pos': 128637580,
                              'beta': 0.2,
                              'or_value': 1.22,
                              'eaf_eur': 0.08,
                              'eaf_eas': 0.05,
                              'gene': 'EIF3H',
                              'effect_allele': 'C',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.2,
                              'confidence': 'high',
                              'note': 'EIF3H — CRC GWAS (低频率大效应)'},
                          {   'rsid': 'rs4444235',
                              'chrom': 'chr14',
                              'pos': 53963376,
                              'beta': 0.1,
                              'or_value': 1.1,
                              'eaf_eur': 0.55,
                              'eaf_eas': 0.4,
                              'gene': 'BMP4',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': 'BMP4 — CRC GWAS'},
                          {   'rsid': 'rs9929218',
                              'chrom': 'chr16',
                              'pos': 68785694,
                              'beta': 0.1,
                              'or_value': 1.1,
                              'eaf_eur': 0.72,
                              'eaf_eas': 0.85,
                              'gene': 'CDH1',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': 'CDH1 — CRC GWAS'},
                          {   'rsid': 'rs174537',
                              'chrom': 'chr11',
                              'pos': 61782597,
                              'beta': 0.1,
                              'or_value': 1.1,
                              'eaf_eur': 0.35,
                              'eaf_eas': 0.55,
                              'gene': 'FADS1',
                              'effect_allele': 'T',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.12,
                              'confidence': 'high',
                              'note': 'FADS1/2 — CRC GWAS'},
                          {   'rsid': 'rs10936599',
                              'chrom': 'chr3',
                              'pos': 169796749,
                              'beta': 0.1,
                              'or_value': 1.1,
                              'eaf_eur': 0.22,
                              'eaf_eas': 0.35,
                              'gene': 'TERC',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.12,
                              'confidence': 'moderate',
                              'note': 'TERC — CRC GWAS (端粒酶RNA组分)'},
                          {   'rsid': 'rs3087967',
                              'chrom': 'chr1',
                              'pos': 216198303,
                              'beta': None,
                              'or_value': 1.09,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'USP21',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'CRC GWAS (Huyghe 2019)'},
                          {   'rsid': 'rs11603367',
                              'chrom': 'chr11',
                              'pos': 74506099,
                              'beta': None,
                              'or_value': 1.07,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'SPCS2',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'CRC GWAS (Huyghe 2019)'},
                          {   'rsid': 'rs17816465',
                              'chrom': 'chr3',
                              'pos': 40945031,
                              'beta': None,
                              'or_value': 1.08,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'CTNNB1',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'CRC GWAS (Huyghe 2019)'},
                          {   'rsid': 'rs12688682',
                              'chrom': 'chr3',
                              'pos': 170810922,
                              'beta': None,
                              'or_value': 1.06,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'TNIK',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'CRC GWAS (Schumacher 2015)'},
                          {   'rsid': 'rs6066825',
                              'chrom': 'chr20',
                              'pos': 6373868,
                              'beta': None,
                              'or_value': 1.07,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'BMP2',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'CRC GWAS (Huyghe 2019)'},
                          {   'rsid': 'rs2735940',
                              'chrom': 'chr5',
                              'pos': 1286546,
                              'beta': None,
                              'or_value': 1.1,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'TERT',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'CRC GWAS (Huyghe 2019)'},
                          {   'rsid': 'rs12635938',
                              'chrom': 'chr3',
                              'pos': 71245149,
                              'beta': None,
                              'or_value': 1.06,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'FOXP1',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'CRC GWAS (Huyghe 2019)'},
                          {   'rsid': 'rs1552896',
                              'chrom': 'chr19',
                              'pos': 38671185,
                              'beta': None,
                              'or_value': 1.08,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'SIK3',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'CRC GWAS (Huyghe 2019)'},
                          {   'rsid': 'rs11255894',
                              'chrom': 'chr10',
                              'pos': 114774303,
                              'beta': None,
                              'or_value': 1.1,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'TCF7L2',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'CRC GWAS (Huyghe 2019)'},
                          {   'rsid': 'rs11623717',
                              'chrom': 'chr14',
                              'pos': 59290960,
                              'beta': None,
                              'or_value': 1.07,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'RTN1',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'CRC GWAS (Huyghe 2019)'}],
    'regions': [   {   'chrom': 'chr5',
                       'start': 112073277,
                       'end': 112181936,
                       'gene': 'APC',
                       'rtype': 'coding',
                       'source': 'clinical',
                       'note': 'APC基因区域 — FAP核心基因'},
                   {   'chrom': 'chr3',
                       'start': 37009970,
                       'end': 37059890,
                       'gene': 'MLH1',
                       'rtype': 'coding',
                       'source': 'clinical',
                       'note': 'MLH1基因区域 — Lynch综合征'},
                   {   'chrom': 'chr2',
                       'start': 47403322,
                       'end': 47483305,
                       'gene': 'MSH2',
                       'rtype': 'coding',
                       'source': 'clinical',
                       'note': 'MSH2基因区域 — Lynch综合征'},
                   {   'chrom': 'chr2',
                       'start': 47791948,
                       'end': 47870416,
                       'gene': 'MSH6',
                       'rtype': 'coding',
                       'source': 'clinical',
                       'note': 'MSH6基因区域 — Lynch综合征'},
                   {   'chrom': 'chr7',
                       'start': 5990159,
                       'end': 6031009,
                       'gene': 'PMS2',
                       'rtype': 'coding',
                       'source': 'clinical',
                       'note': 'PMS2基因区域 — Lynch综合征'}],
    'regulatory_regions': [],
    'prs_variants_high': [],
    'prs_variants': [],
    'key_literature': [   {   'pmid': '30510241',
                              'title': 'Discovery of common and rare genetic risk variants for colorectal cancer',
                              'note': 'Huyghe et al. 2019 Nat Genet; CRC GWAS ~125K cases; 40 new loci'},
                          {   'pmid': '26151821',
                              'title': 'Genome-wide association study of colorectal cancer identifies six new '
                                       'susceptibility loci',
                              'note': 'Schumacher et al. 2015 Nat Commun; CRC GWAS meta-analysis'},
                          {   'pmid': '18372905',
                              'title': 'Meta-analysis of genome-wide association data identifies four new '
                                       'susceptibility loci for colorectal cancer',
                              'note': 'Houlston et al. 2008 Nat Genet; 初始CRC GWAS meta'}]}
