"""Disease template: familial hypercholesterolemia / dyslipidemia."""

TEMPLATE_NAME = 'familial hypercholesterolemia'
TEMPLATE = {   'aliases': [   'familial hypercholesterolemia',
                   'fh',
                   'hypercholesterolemia',
                   'dyslipidemia',
                   'hyperlipidemia',
                   'high cholesterol',
                   'high ldl',
                   'high ldl cholesterol',
                   'low hdl',
                   'high triglycerides',
                   'hypertriglyceridemia',
                   'mixed hyperlipidemia',
                   'lipid disorder',
                   'combined hyperlipidemia'],
    'mode': 'complex',
    'gene_set': [   {   'gene': 'LDLR',
                        'tier': 'mendelian_high',
                        'contribution_score': 1.0,
                        'penetrance': '>0.95',
                        'penetrance_score': 0.95,
                        'evidence': 'familial',
                        'note': '家族性高胆固醇血症1型(FH1,AD); LDL受体缺陷→LDL-C清除障碍; 杂合~1/250; 纯合罕见; 未治疗LDL-C>190mg/dL→早发CAD',
                        'phenotype_assoc': 'FH1(常显);杂合LDL-C>190;纯合>500;早发CAD/MI;黄色瘤;角膜弓',
                        'key_domains': '配体结合域(aa1-322);EGF前体同源域(aa323-698);O-糖基化茎域;跨膜域;NPxY内吞信号',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'APOB',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.95,
                        'penetrance': 'high',
                        'penetrance_score': 0.9,
                        'evidence': 'familial',
                        'note': 'FH2(AD); APOB配体结合域缺陷→LDL颗粒不能有效结合LDLR→LDL-C升高; 家族性配体缺陷型apoB-100(FDB)',
                        'phenotype_assoc': 'FH2/FDB(常显);LDLR结合域(Arg3500Gln)突变;LDL-C升高;apoB-100配体缺陷',
                        'key_domains': 'βα1域(LDLR结合aa3359-3369);βα2域;C端脂蛋白锚定;N端脂质转移',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'PCSK9',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.95,
                        'penetrance': 'high',
                        'penetrance_score': 0.85,
                        'evidence': 'familial',
                        'note': 'FH3(AD功能增强); PCSK9降解LDLR→LDL-C升高; LOF变异保护性(低LDL-C); PCSK9抑制剂(evolocumab/alirocumab)靶点',
                        'phenotype_assoc': 'FH3(常显);功能增强→LDLR降解;PCSK9i靶点;LOF→低LDL保护CAD',
                        'key_domains': '前体域(aa31-152,自催化切割);催化域(aa153-452);C端域(aa453-692)含M2M3重复',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'LDLRAP1',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.85,
                        'penetrance': 'high',
                        'penetrance_score': 0.85,
                        'evidence': 'familial',
                        'note': '常染色体隐性高胆固醇血症(ARH); LDLRAP1/ARH介导LDLR内吞; 纯合致病变异→严重FH表型',
                        'phenotype_assoc': 'ARH(常隐);LDLR内吞适配蛋白;纯合→重度高胆固醇(~FH纯合);NPxY信号通路',
                        'key_domains': 'PTB域(磷酸化酪氨酸结合);AP-2/Clathrin结合基序',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'ABCG5',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.7,
                        'penetrance': 'high',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': '植物固醇血症/谷固醇血症(AR); ABCG5/G8异源二聚体→植物固醇肠道外排; 纯合→固醇蓄积+高胆固醇+黄色瘤+早发CAD',
                        'phenotype_assoc': '谷固醇血症(常隐);ABCG5/G8固醇转运体;植物固醇蓄积;高胆固醇;黄色瘤',
                        'key_domains': 'NBD(核苷酸结合域);TMD×6(ABC转运体跨膜域)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'ABCG8',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.7,
                        'penetrance': 'high',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': '植物固醇血症(AR); 与ABCG5形成固醇转运异源二聚体; 编码固醇外排泵; 纯合→谷固醇血症',
                        'phenotype_assoc': '谷固醇血症(常隐);ABCG5/G8异源二聚体;植物固醇外排泵',
                        'key_domains': 'NBD;TMD×6(ABC转运体)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'ANGPTL3',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.65,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'mixed',
                        'note': '血管生成素样蛋白3; LOF→复合低脂血症(FHBL2,AR); LPL/EL抑制剂; evinacumab(ANGPTL3抗体)靶点; 杂合LOF保护CAD',
                        'phenotype_assoc': 'FHBL2(AR复合低脂);LPL/EL抑制剂;evinacumab靶点;LOF→低TG/LDL/HDL',
                        'key_domains': '卷曲螺旋域;纤维蛋白原C端域',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'APOE',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.6,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'mixed',
                        'note': '家族性异常β脂蛋白血症(III型高脂蛋白血症,AR/AD); APOE E2/E2基因型+二次打击→残粒脂蛋白蓄积; E4→LDL-C升高',
                        'phenotype_assoc': 'III型异常β脂蛋白血症;E2/E2→残粒清除障碍(需二次打击);E4→高LDL/AD风险',
                        'key_domains': 'LDL受体结合域(aa136-150);脂质结合域(aa244-272);N端4-螺旋束',
                        'clingen_validity': 'Definitive (risk factor)'},
                    {   'gene': 'LIPA',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.65,
                        'penetrance': 'high',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': '溶酶体酸性脂肪酶; Wolman病(AR重度婴儿型)/CESD(AR轻症); LAL缺陷→胆固醇酯/TG在溶酶体积聚→肝脾肿大+高脂血症',
                        'phenotype_assoc': 'Wolman病/CESD(常隐);溶酶体胆固醇酯/TG积聚;肝脾肿大;LAL缺乏',
                        'key_domains': 'α/β水解酶折叠;催化三联体Ser/His/Asp',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'CELSR2',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.3,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'SORT1/CELSR2/PSRC1 1p13 LDL-C GWAS最强位点; SORT1调控肝脏VLDL分泌; 非编码变异→肝脏SORT1表达改变',
                        'phenotype_assoc': '1p13 LDL-C GWAS最强;SORT1/sortilin;肝脏VLDL分泌调控',
                        'key_domains': 'EGF-like×8;层粘连蛋白G-like;GPS域(GPCR蛋白水解位点)',
                        'clingen_validity': ''},
                    {   'gene': 'HMGCR',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.3,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'HMG-CoA还原酶; 胆固醇合成限速酶; statin药物靶点; LDL-C GWAS; HMGCR变异影响statin疗效',
                        'phenotype_assoc': 'HMGCR;LDL-C GWAS;胆固醇合成限速酶;statin靶点;他汀疗效PGx',
                        'key_domains': 'N端8-TM固醇感应域;连接域;催化域(NADPH结合+底物结合)',
                        'clingen_validity': ''},
                    {   'gene': 'NPC1L1',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.28,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'Niemann-Pick C1-like 1; 肠道胆固醇吸收转运体; ezetimibe靶点; LDL-C GWAS; LOF→低LDL-C保护CAD',
                        'phenotype_assoc': 'NPC1L1;LDL-C GWAS;肠道胆固醇吸收;ezetimibe靶点;LOF保护性',
                        'key_domains': 'SSD(固醇感应域);NPC1_N端域;13-TM',
                        'clingen_validity': ''},
                    {   'gene': 'PCSK9',
                        'tier': 'gwas',
                        'contribution_score': 0.28,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'LDL-C GWAS; 常见LOF变异(如R46L)降低LDL-C~15%; 功能增强变异升高LDL-C(FH3)',
                        'phenotype_assoc': 'PCSK9;LDL-C GWAS;LOF→低LDL保护;GOF→FH3;PCSK9i靶点',
                        'key_domains': '前体域;催化域;C端域(M2M3)',
                        'clingen_validity': ''},
                    {   'gene': 'LDLR',
                        'tier': 'gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'LDL-C GWAS; 常见非致病变异轻微影响LDL-C水平',
                        'phenotype_assoc': 'LDLR;LDL-C GWAS;FH基因常见变异→轻微LDL-C变化',
                        'key_domains': '配体结合域;EGF前体;NPxY',
                        'clingen_validity': ''},
                    {   'gene': 'APOB',
                        'tier': 'gwas',
                        'contribution_score': 0.22,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'LDL-C GWAS; apoB-100是LDL颗粒主要结构蛋白(每LDL含1分子apoB); 常见变异调控LDL-C; 非-LDLR结合域变异',
                        'phenotype_assoc': 'APOB;LDL-C GWAS;apoB-100;LDL颗粒核心蛋白;非FDB致病变异',
                        'key_domains': 'βα1域(LDLR结合);C端脂质锚定',
                        'clingen_validity': ''},
                    {   'gene': 'CETP',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.28,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '胆固醇酯转移蛋白; HDL-C GWAS最强位点; CETP介导CE-TG异源交换; CETP抑制剂(anacetrapib/evacetrapib)靶点',
                        'phenotype_assoc': 'CETP;HDL-C GWAS最强;CE-TG交换;CETP抑制剂靶点;东亚常见LOF→极高HDL',
                        'key_domains': 'LTP/BPI/CETP家族域;脂质结合口袋',
                        'clingen_validity': ''},
                    {   'gene': 'LIPC',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '肝脂肪酶; HDL-C GWAS; 水解HDL-TG和磷脂→HDL重塑; LIPC变异影响HDL-C和HDL大小',
                        'phenotype_assoc': 'HL/LIPC;HDL-C GWAS;HDL重塑/代谢;肝脂肪酶缺乏(AR)→高HDL-TG',
                        'key_domains': '脂肪酶催化域(GxSxG);Lid域;PLAT/LH2域',
                        'clingen_validity': ''},
                    {   'gene': 'LIPG',
                        'tier': 'gwas',
                        'contribution_score': 0.22,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '内皮脂肪酶; HDL-C GWAS; 水解HDL磷脂→HDL分解代谢; LOF变异→HDL-C升高',
                        'phenotype_assoc': 'EL/LIPG;HDL-C GWAS;内皮脂肪酶;HDL磷脂水解;LOF→高HDL',
                        'key_domains': '脂肪酶催化域;Lid域',
                        'clingen_validity': ''},
                    {   'gene': 'LCAT',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '卵磷脂-胆固醇酰基转移酶; HDL-C GWAS; HDL成熟关键酶; 家族性LCAT缺乏(AR)→极低HDL/角膜混浊',
                        'phenotype_assoc': 'LCAT;HDL-C GWAS;HDL成熟;胆固醇酯化;LCAT缺乏(AR)→鱼眼病/低HDL',
                        'key_domains': 'α/β水解酶折叠;催化三联体;盖子域',
                        'clingen_validity': ''},
                    {   'gene': 'SCARB1',
                        'tier': 'gwas',
                        'contribution_score': 0.22,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'SR-BI; HDL-C GWAS; HDL胆固醇选择性摄取受体(肝脏); LOF→HDL-C升高但CAD风险增加(HDL功能受损)',
                        'phenotype_assoc': 'SR-BI/SCARB1;HDL-C GWAS;肝脏HDL胆固醇摄取;LOF→高HDL但CAD↑',
                        'key_domains': 'CD36家族域;2-TM;N/C端胞质尾',
                        'clingen_validity': ''},
                    {   'gene': 'LPL',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.3,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '脂蛋白脂肪酶; TG GWAS最强; 水解CM/VLDL中的TG→FFA; 家族性LPL缺乏(AR)→严重高TG/胰腺炎',
                        'phenotype_assoc': 'LPL;TG GWAS最强;CM/VLDL-TG水解;LPL缺乏(AR)→严重高TG;胰腺炎',
                        'key_domains': '脂肪酶催化域(GxSxG);Lid域;ApoC2结合域;肝素结合域;PLAT/LH2域',
                        'clingen_validity': ''},
                    {   'gene': 'APOA5',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.28,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'apoA-V; TG GWAS; LPL激活因子; 稳定LPL-底物相互作用; 东亚常见LOF→严重高TG',
                        'phenotype_assoc': 'APOA5;TG GWAS第二强;LPL激活因子;东亚LOF→严重高TG;胰腺炎风险',
                        'key_domains': '脂蛋白N端域;脂蛋白C端域',
                        'clingen_validity': ''},
                    {   'gene': 'APOC3',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.28,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'apoC-III; TG GWAS; LPL抑制剂; 抑制肝脏残粒摄取; LOF变异→低TG保护CAD; volanesorsen(APOC3 ASO)靶点',
                        'phenotype_assoc': 'APOC3;TG GWAS;LPL/LPLR抑制;LOF→低TG保护;ASO靶点',
                        'key_domains': '脂蛋白N端域;apoC-III脂质结合域',
                        'clingen_validity': ''},
                    {   'gene': 'ANGPTL4',
                        'tier': 'gwas',
                        'contribution_score': 0.22,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'ANGPTL4; TG GWAS; LPL抑制剂(进食→失活,禁食→激活); E40K LOF→低TG保护CAD',
                        'phenotype_assoc': 'ANGPTL4;TG GWAS;LPL抑制剂;E40K LOF→低TG;禁食/进食调控',
                        'key_domains': '卷曲螺旋域;纤维蛋白原C端域',
                        'clingen_validity': ''},
                    {   'gene': 'TRIB1',
                        'tier': 'gwas',
                        'contribution_score': 0.22,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'Tribbles假激酶1; TG/LDL/HDL GWAS; 肝脏脂质代谢调控; 调控C/EBPα→脂质合成基因',
                        'phenotype_assoc': 'TRIB1;TG GWAS;肝脏脂质代谢;假激酶;脂质合成调控',
                        'key_domains': '假激酶域;Tribbles域',
                        'clingen_validity': ''},
                    {   'gene': 'MLXIPL',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'ChREBP/MONDOB; TG GWAS; 碳水化合物应答转录因子; 肝脏脂肪生成(de novo lipogenesis)主调控因子',
                        'phenotype_assoc': 'ChREBP/MLXIPL;TG GWAS;葡萄糖应答→肝脏DNL↑;脂肪酸合成酶转录',
                        'key_domains': 'bHLH(与MLX二聚化);亮氨酸拉链;葡萄糖感应模块',
                        'clingen_validity': ''},
                    {   'gene': 'FADS1',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '脂肪酸去饱和酶1; TG/LDL GWAS; PUFA合成; FADS1/FADS2基因簇',
                        'phenotype_assoc': 'FADS1;TG/LDL GWAS;PUFA合成;Δ5-去饱和酶;炎症脂质介质',
                        'key_domains': '脂肪酸去饱和酶域;细胞色素b5-like血红素/类固醇结合域',
                        'clingen_validity': ''},
                    {   'gene': 'GCKR',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '葡萄糖激酶调节蛋白; TG GWAS; 肝脏葡萄糖代谢→脂质代谢耦合; P446L常见变异→TG升高/血糖降低',
                        'phenotype_assoc': 'GCKR;TG GWAS;葡萄糖代谢;P446L→TG↑血糖↓;F1P变构效应',
                        'key_domains': 'SIS域(糖异构酶结合);GCK结合域',
                        'clingen_validity': ''},
                    {   'gene': 'APOE',
                        'tier': 'gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'Total-C/LDL-C GWAS; E2/E3/E4单倍型决定人群脂质水平差异; E4→TC/LDL-C升高; E2→TC/LDL-C降低',
                        'phenotype_assoc': 'APOE;TC/LDL-C GWAS;E2/E3/E4→脂质水平分层;残粒脂蛋白代谢',
                        'key_domains': 'LDL受体结合域(aa136-150);脂质结合域(244-272)',
                        'clingen_validity': ''},
                    {   'gene': 'ABCG8',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'TC/LDL-C GWAS; 固醇转运体; 常见D19H变异→降低LDL-C; 肠道胆固醇吸收调控',
                        'phenotype_assoc': 'ABCG8;TC/LDL-C GWAS;D19H→低LDL保护;固醇外排泵;肠道胆固醇吸收',
                        'key_domains': 'NBD;TMD×6(ABC转运体)',
                        'clingen_validity': ''},
                    {   'gene': 'LPA',
                        'tier': 'gwas',
                        'contribution_score': 0.22,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'Lp(a); TC/LDL-C GWAS; 脂蛋白(a)水平主要由LPA基因KIV-2重复数决定(70-90%遗传度); Lp(a)→ASCVD独立风险因子',
                        'phenotype_assoc': 'LPA;Lp(a)水平;KIV-2重复数→剂量效应;ASCVD独立风险;PCSK9i可降Lp(a)~25%',
                        'key_domains': 'Kringle-IV×2-40+(KIV-2重复);Kringle-V;蛋白酶域(无活性)',
                        'clingen_validity': ''},
                    {   'gene': 'PCSK9',
                        'tier': 'gwas',
                        'contribution_score': 0.22,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'TC/LDL-C GWAS; 肝脏分泌的LDLR降解蛋白酶; 循环PCSK9水平受遗传调控',
                        'phenotype_assoc': 'PCSK9;TC GWAS;LDLR降解调控;scPCSK9水平遗传性;PCSK9i靶点',
                        'key_domains': '前体域;催化域;C端域',
                        'clingen_validity': ''}],
    'known_pathogenic_variants': [   {   'rsid': 'rs121908024',
                                         'chrom': 'chr19',
                                         'pos': 11113446,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'LDLR',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 1.0,
                                         'confidence': 'high',
                                         'note': 'LDLR c.682G>A (E228K) — LDLR配体结合域5; 欧洲常见FH致病变异'},
                                     {   'rsid': 'rs28942084',
                                         'chrom': 'chr19',
                                         'pos': 11113666,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'LDLR',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 1.0,
                                         'confidence': 'high',
                                         'note': 'LDLR c.2054C>T (P685L) — EGF前体域; 纯合FH; 全球常见'},
                                     {   'rsid': 'rs5742904',
                                         'chrom': 'chr2',
                                         'pos': 21038739,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'APOB',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.95,
                                         'confidence': 'high',
                                         'note': 'APOB Arg3527Gln (R3500Q;传统命名Arg3500Gln) — FDB/FH2; '
                                                 '欧洲频率~1/500-1/1000; LDLR结合缺陷'},
                                     {   'rsid': 'rs28942112',
                                         'chrom': 'chr1',
                                         'pos': 55051255,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'PCSK9',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.9,
                                         'confidence': 'high',
                                         'note': 'PCSK9 Asp374Tyr (D374Y) — 功能增强; LDLR降解效率增加最大; 极重度FH表型(纯合样)'},
                                     {   'rsid': 'rs11591147',
                                         'chrom': 'chr1',
                                         'pos': 55051770,
                                         'ref': 'G',
                                         'alt': 'T',
                                         'gene': 'PCSK9',
                                         'effect_allele': 'T',
                                         'or_value': 0.7,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.8,
                                         'confidence': 'high',
                                         'note': 'PCSK9 Arg46Leu (R46L) — LOF保护性变异; LDL-C降低~15%; CAD风险降低~47%; '
                                                 '欧洲频率~2-3%; 亚洲罕见'},
                                     {   'rsid': 'rs429358',
                                         'chrom': 'chr19',
                                         'pos': 44908684,
                                         'ref': 'T',
                                         'alt': 'C',
                                         'gene': 'APOE',
                                         'effect_allele': 'C',
                                         'or_value': 1.2,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'high',
                                         'note': 'APOE ε4-defining (Cys112Arg); ε4/ε4→LDL-C最高; ε4→残粒清除减慢; 心血管+AD风险增加'},
                                     {   'rsid': 'rs7412',
                                         'chrom': 'chr19',
                                         'pos': 44908822,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'APOE',
                                         'effect_allele': 'T',
                                         'or_value': 0.8,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.6,
                                         'confidence': 'high',
                                         'note': 'APOE ε2-defining (Arg158Cys); ε2/ε2→III型异常β脂蛋白血症风险; '
                                                 'ε2→LDL-C降低(~10%)'},
                                     {   'rsid': 'rs121908035',
                                         'chrom': 'chr1',
                                         'pos': 25881874,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'LDLRAP1',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.85,
                                         'confidence': 'high',
                                         'note': 'LDLRAP1 c.432insA — ARH 已知founder变异; 纯合→重度高胆固醇血症'},
                                     {   'rsid': 'rs118204057',
                                         'chrom': 'chr8',
                                         'pos': 19934981,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'LPL',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.8,
                                         'confidence': 'high',
                                         'note': 'LPL Gly188Glu (G188E) — 催化域; 家族性LPL缺乏热门致病变异; 东亚较多见'},
                                     {   'rsid': 'rs72651067',
                                         'chrom': 'chr1',
                                         'pos': 62643139,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'ANGPTL3',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.75,
                                         'confidence': 'high',
                                         'note': 'ANGPTL3 c.335-1G>A — 剪接位点LOF; 复合低脂血症(FHBL2); 杂合→TG/LDL-C降低'},
                                     {   'rsid': '212767',
                                         'chrom': '2',
                                         'pos': 43809711,
                                         'ref': 'G',
                                         'alt': 'T',
                                         'gene': 'ABCG5',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Asphyxiating thoracic dystrophy 1|Short-rib '
                                                 'thoracic dysplasia 15 with polydacty'},
                                     {   'rsid': '3629470',
                                         'chrom': '2',
                                         'pos': 43809719,
                                         'ref': 'C',
                                         'alt': 'A',
                                         'gene': 'ABCG5',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Short-rib thoracic dysplasia 15 with '
                                                 'polydactyly'},
                                     {   'rsid': '2989355',
                                         'chrom': '2',
                                         'pos': 43839105,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'ABCG8',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | not provided'},
                                     {   'rsid': '499853',
                                         'chrom': '2',
                                         'pos': 43839113,
                                         'ref': 'CTCGGTGAGTGAGCAATGGGAAGTCGGCCCAGGCCTGGTGGGCGGGTAGGAGAAA',
                                         'alt': 'C',
                                         'gene': 'ABCG8',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | not provided'},
                                     {   'rsid': '1323236',
                                         'chrom': '10',
                                         'pos': 89214843,
                                         'ref': 'CATTAG',
                                         'alt': 'C',
                                         'gene': 'LIPA',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic/Likely_pathogenic | Wolman disease|Lysosomal '
                                                 'acid lipase deficiency|not provided'},
                                     {   'rsid': '695034',
                                         'chrom': '10',
                                         'pos': 89214865,
                                         'ref': 'T',
                                         'alt': 'C',
                                         'gene': 'LIPA',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Lysosomal acid lipase deficiency'}],
    'gwas_lead_snps': [   {   'rsid': 'rs646776',
                              'chrom': 'chr1',
                              'pos': 109275908,
                              'beta': None,
                              'or_value': None,
                              'eaf_eur': 0.22,
                              'eaf_eas': 0.08,
                              'gene': 'CELSR2',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.3,
                              'confidence': 'high',
                              'note': 'SORT1/CELSR2(1p13) — LDL-C GWAS最强信号; SORT1肝脏表达调控'},
                          {   'rsid': 'rs12916',
                              'chrom': 'chr5',
                              'pos': 75358525,
                              'beta': None,
                              'or_value': None,
                              'eaf_eur': 0.6,
                              'eaf_eas': 0.7,
                              'gene': 'HMGCR',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.28,
                              'confidence': 'high',
                              'note': 'HMGCR — LDL-C GWAS; statin靶点; 内含子调控变异'},
                          {   'rsid': 'rs2072183',
                              'chrom': 'chr7',
                              'pos': 44609470,
                              'beta': None,
                              'or_value': None,
                              'eaf_eur': 0.28,
                              'eaf_eas': 0.35,
                              'gene': 'NPC1L1',
                              'effect_allele': 'G',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.25,
                              'confidence': 'high',
                              'note': 'NPC1L1 — LDL-C GWAS; ezetimibe靶点'},
                          {   'rsid': 'rs3764261',
                              'chrom': 'chr16',
                              'pos': 56979839,
                              'beta': None,
                              'or_value': None,
                              'eaf_eur': 0.32,
                              'eaf_eas': 0.15,
                              'gene': 'CETP',
                              'effect_allele': 'A',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.3,
                              'confidence': 'high',
                              'note': 'CETP — HDL-C GWAS最强; 东亚常见D442G LOF→极高HDL'},
                          {   'rsid': 'rs1800588',
                              'chrom': 'chr15',
                              'pos': 58431347,
                              'beta': None,
                              'or_value': None,
                              'eaf_eur': 0.22,
                              'eaf_eas': 0.45,
                              'gene': 'LIPC',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.25,
                              'confidence': 'high',
                              'note': 'LIPC — HDL-C GWAS; 肝脂肪酶启动子-514C>T; 东亚高频率'},
                          {   'rsid': 'rs12678919',
                              'chrom': 'chr8',
                              'pos': 19965269,
                              'beta': None,
                              'or_value': None,
                              'eaf_eur': 0.12,
                              'eaf_eas': 0.1,
                              'gene': 'LPL',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.3,
                              'confidence': 'high',
                              'note': 'LPL — TG GWAS最强; 内含子; 东亚/欧洲不同LD结构'},
                          {   'rsid': 'rs964184',
                              'chrom': 'chr11',
                              'pos': 116778201,
                              'beta': None,
                              'or_value': None,
                              'eaf_eur': 0.13,
                              'eaf_eas': 0.25,
                              'gene': 'APOA5',
                              'effect_allele': 'G',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.28,
                              'confidence': 'high',
                              'note': 'APOA5/A4/C3/A1基因簇 — TG GWAS; 东亚频率较高; 与胰腺炎/高TG关联'},
                          {   'rsid': 'rs2954029',
                              'chrom': 'chr8',
                              'pos': 125478839,
                              'beta': None,
                              'or_value': None,
                              'eaf_eur': 0.45,
                              'eaf_eas': 0.3,
                              'gene': 'TRIB1',
                              'effect_allele': 'A',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.22,
                              'confidence': 'high',
                              'note': 'TRIB1 — TG/TC GWAS; 肝脏脂质代谢'},
                          {   'rsid': 'rs429358',
                              'chrom': 'chr19',
                              'pos': 44908684,
                              'beta': None,
                              'or_value': 1.2,
                              'eaf_eur': 0.15,
                              'eaf_eas': 0.1,
                              'gene': 'APOE',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.28,
                              'confidence': 'high',
                              'note': 'APOE ε4(rs429358)+ε2(rs7412) — TC/LDL-C GWAS; 单倍型决定脂质水平; APOE ε4为风险型'}],
    'regions': [   {   'chrom': 'chr19',
                       'start': 11089042,
                       'end': 11137787,
                       'gene': 'LDLR',
                       'rtype': 'coding',
                       'source': 'clinical',
                       'note': 'LDLR基因区域 — FH1核心基因; 2000+已知FH致病变异'},
                   {   'chrom': 'chr2',
                       'start': 21028559,
                       'end': 21063574,
                       'gene': 'APOB',
                       'rtype': 'coding',
                       'source': 'clinical',
                       'note': 'APOB基因区域 — FH2; LDLR配体结合域(外显子26)'},
                   {   'chrom': 'chr1',
                       'start': 55039439,
                       'end': 55064853,
                       'gene': 'PCSK9',
                       'rtype': 'coding',
                       'source': 'clinical',
                       'note': 'PCSK9基因区域 — FH3; GOF→LDLR降解'}],
    'regulatory_regions': [],
    'prs_variants_high': [],
    'prs_variants': [],
    'key_literature': [   {   'pmid': '24097068',
                              'title': 'Discovery and refinement of loci associated with lipid levels',
                              'note': 'GLGC (Willer et al. 2013 Nat Genet); 188K样本; 157 lipid loci; 62 new'},
                          {   'pmid': '29083408',
                              'title': 'A comprehensive 1000 Genomes–based genome-wide association meta-analysis of '
                                       'coronary artery disease',
                              'note': 'CARDIoGRAMplusC4D (Nikpay et al. 2015 Nat Genet); CAD GWAS 185K'},
                          {   'pmid': '20686565',
                              'title': 'Biological, clinical and population relevance of 95 loci for blood lipids',
                              'note': 'GLGC (Teslovich et al. 2010 Nature); 100K样本; 95 lipid loci'},
                          {   'pmid': '32203549',
                              'title': 'The polygenic and monogenic basis of blood lipids and coronary artery disease',
                              'note': 'GLGC + UK Biobank (Klarin et al. 2018); lipid GWAS ~300K'}],
    'key_regions': {
        'APOB': {
            'note': 'βα1域(LDLR结合aa3359-3369);βα2域;C端脂蛋白锚定;N端脂质转移',
            'regions': [(3359, 3369)],
        },
        'APOE': {
            'note': 'LDL受体结合域(aa136-150);脂质结合域(244-272)',
            'regions': [(136, 150)],
        },
        'LDLR': {
            'note': '配体结合域(aa1-322);EGF前体同源域(aa323-698);O-糖基化茎域;跨膜域;NPxY内吞信号',
            'regions': [(1, 322), (323, 698)],
        },
        'PCSK9': {
            'note': '前体域(aa31-152,自催化切割);催化域(aa153-452);C端域(aa453-692)含M2M3重复',
            'regions': [(31, 152), (153, 452), (453, 692)],
        },
    },
}
