TEMPLATE_NAME = 'hyperuricemia'
TEMPLATE = {
    'aliases': [
        'hyperuricemia',
        'elevated uric acid',
        'gout',
        'familial renal hypouricemia',
        'uric acid'
    ],
    'mode': 'complex',
    'gene_set': [
        {
            'gene': 'A1CF',
            'tier': 'gwas',
            'contribution_score': 0.2,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '尿酸GWAS位点',
            'phenotype_assoc': 'RNA编辑辅因子;与APOBEC1互作;编辑APOB mRNA',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ABCG2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': '尿酸转运/代谢核心基因',
            'phenotype_assoc': '尿酸转运;Q141K东亚~30%;痛风GWAS',
            'key_domains': 'NBD;TMDx6;Q141K破坏ATP酶',
            'clingen_validity': 'Strong (risk factor)',
        },
        {
            'gene': 'ACAT1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': '乙酰辅酶A乙酰转移酶1;酮体/异戊二烯代谢;线粒体;脂代谢GWAS位点',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ACAT2',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': '乙酰辅酶A乙酰转移酶2;胞质酮体/胆固醇合成;脂代谢GWAS',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ALDH16A1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': 'ALDH超家族成员;与SPG21互作;痛风GWAS关联',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'AOX1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': 'high',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '单基因高尿酸血症/肾结石/代谢综合征相关',
            'phenotype_assoc': '醛氧化酶;与XDH同属钼羟化酶家族;参与嘌呤代谢',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'APOB',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': '载脂蛋白B;乳糜微粒/LDL主要载脂蛋白;脂质运输;脂代谢GWAS',
            'key_domains': 'Vitellogenin;Heparin-binding×2;LDL受体结合',
            'clingen_validity': '',
        },
        {
            'gene': 'APOC3',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': '载脂蛋白C-III;甘油三酯代谢调控;脂蛋白脂酶抑制;脂代谢GWAS',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'BDH1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': '3-羟基丁酸脱氢酶;酮体代谢;线粒体',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CLDN16',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': 'high',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '单基因高尿酸血症/肾结石/代谢综合征相关',
            'phenotype_assoc': 'Claudin-16;肾小管紧密连接蛋白;Mg2+重吸收',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'CLDN19',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': 'high',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '单基因高尿酸血症/肾结石/代谢综合征相关',
            'phenotype_assoc': 'Claudin-19;肾小管紧密连接;与CLDN16协同;Mg2+/Ca2+重吸收',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'FADS1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': '脂肪酸去饱和酶1;多不饱和脂肪酸合成;代谢GWAS',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'GCKR',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': '尿酸转运/代谢核心基因',
            'phenotype_assoc': '葡萄糖激酶调节蛋白;果糖/尿酸代谢;P446L影响甘油三酯和尿酸',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'HMGCL',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': 'HMG-CoA裂解酶;酮体生成限速酶;亮氨酸降解;脂代谢GWAS',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'HMGCS1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': 'HMG-CoA合酶1(胞质);胆固醇合成;脂代谢GWAS',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'HMGCS2',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': 'HMG-CoA合酶2(线粒体);酮体生成限速酶;脂代谢GWAS',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'HNF1B',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': 'high',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '单基因高尿酸血症/肾结石/代谢综合征相关',
            'phenotype_assoc': 'HNF1同源框转录因子B;肾发育/肾小管功能;肾囊肿糖尿病综合征(AD)合并高尿酸',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'HPRT1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': 'high',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '单基因高尿酸血症/肾结石/代谢综合征相关',
            'phenotype_assoc': 'Lesch-Nyhan(AR重度);Kelley-Seegmiller(轻)',
            'key_domains': 'PRPP结合;嘌呤结合;催化中心',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'INHBC',
            'tier': 'gwas',
            'contribution_score': 0.2,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '尿酸GWAS位点',
            'phenotype_assoc': 'Inhibin βC/Activin βC;TGF-β超家族;生长分化因子;代谢关联',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'LPL',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': '脂蛋白脂肪酶;甘油三酯水解;乳糜微粒/VLDL代谢;代谢GWAS',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'MOCOS',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': 'high',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '单基因高尿酸血症/肾结石/代谢综合征相关',
            'phenotype_assoc': '钼辅因子硫化酶;活化XDH和AOX1辅因子;嘌呤代谢调控',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'OXCT1',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': '3-酮酸辅酶A转移酶1;酮体利用限速酶;线粒体;脂代谢GWAS',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'PDZK1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': '尿酸转运/代谢核心基因',
            'phenotype_assoc': '痛风GWAS;PDZ骨架蛋白;调控URAT1/ABCG2膜定位',
            'key_domains': 'PDZ域×4;与URAT1/ABCG2 C端结合',
            'clingen_validity': '',
        },
        {
            'gene': 'PPARG',
            'tier': 'gwas',
            'contribution_score': 0.25,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '脂代谢/糖代谢GWAS位点',
            'phenotype_assoc': '过氧化物酶体增殖物激活受体γ;脂肪细胞分化/胰岛素敏感性;代谢GWAS',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'PRPS1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': 'high',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '单基因高尿酸血症/肾结石/代谢综合征相关',
            'phenotype_assoc': 'PRPS超活性(XLR);PRPP合成酶1;尿酸过产',
            'key_domains': 'ATP/GTP结合域;活性位点;别构调节域',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'REN',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': 'high',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '单基因高尿酸血症/肾结石/代谢综合征相关',
            'phenotype_assoc': '肾素;RAAS系统;肾脏血流/血压调控;可影响尿酸排泄',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'RFX3',
            'tier': 'gwas',
            'contribution_score': 0.2,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '尿酸GWAS位点',
            'phenotype_assoc': '调节因子X3;转录因子;纤毛基因调控;尿酸GWAS位点',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SF1',
            'tier': 'gwas',
            'contribution_score': 0.2,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '尿酸GWAS位点',
            'phenotype_assoc': '剪接因子1;RNA剪接调控;尿酸GWAS位点',
            'key_domains': 'KH域;U2AF结合;剪接体组装',
            'clingen_validity': '',
        },
        {
            'gene': 'SLC17A1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': '尿酸转运/代谢核心基因',
            'phenotype_assoc': 'NPT1;肾脏尿酸/有机阴离子分泌型转运体;痛风GWAS',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SLC17A3',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': '尿酸转运/代谢核心基因',
            'phenotype_assoc': 'NPT4;肾脏尿酸/阴离子分泌转运体;电压驱动有机阴离子转运',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SLC22A11',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '高尿酸血症相关基因',
            'phenotype_assoc': 'OAT4;有机阴离子转运体4;尿酸/阴离子肾小管转运;肾脏排泌',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SLC22A12',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': '尿酸转运/代谢核心基因',
            'phenotype_assoc': '肾性低尿酸血症1型(AR);URAT1尿酸盐/阴离子交换',
            'key_domains': 'MFS/OAT家族;12-TM;胞内环(底物结合)',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'SLC2A9',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.2,
            'evidence': 'mixed',
            'note': '尿酸转运/代谢核心基因',
            'phenotype_assoc': 'GLUT9;尿酸重吸收;最强GWAS',
            'key_domains': 'TMDx12;MFS超家族',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'TRIM46',
            'tier': 'gwas',
            'contribution_score': 0.2,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '尿酸GWAS位点',
            'phenotype_assoc': '三结构域蛋白46;微管结合;神经元极性;尿酸GWAS位点',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'UMOD',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': 'high',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '单基因高尿酸血症/肾结石/代谢综合征相关',
            'phenotype_assoc': 'FJHN1/ADTKD-UMOD(常显);uroModulin/Tamm-Horsfall',
            'key_domains': 'EGF样域;ZP域;Cys-rich域;跨膜GPi锚',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'XDH',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': 'high',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': '单基因高尿酸血症/肾结石/代谢综合征相关',
            'phenotype_assoc': '黄嘌呤脱氢酶;尿酸生成终末',
            'key_domains': 'FAD域;Mo-pterin;2Fe-2S;底物结合',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'ADRA2A',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'α-2A肾上腺素受体;交感神经调节;肾脏尿酸排泄调控',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'AGRP',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'Agouti相关神经肽;进食/能量代谢调控;下丘脑表达',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ALDOB',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '醛缩酶B;果糖代谢关键酶;遗传性果糖不耐受(AR);可致高尿酸',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ALMS1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'Alström综合征相关蛋白;纤毛功能;中心体/基体;代谢综合征关联',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'FBP1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '果糖-1,6-二磷酸酶1;糖异生关键酶;FBP缺乏症(AR)可合并高尿酸',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'G6PC1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '葡萄糖-6-磷酸酶催化亚基;糖原分解/糖异生;GSD Ia(AR)可合并高尿酸血症',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'LDHD',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'D-乳酸脱氢酶;D-乳酸代谢;线粒体',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'LMAN1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '凝集素-甘露糖结合蛋白1;ERGIC-53;凝血因子V/VIII联合缺乏症(AR)',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'LSM11',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'U7 snRNP亚基;组蛋白pre-mRNA加工;复制依赖性组蛋白合成',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'MCFD2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '多重凝血因子缺乏蛋白2;与LMAN1共定位于内质网;凝血因子运输',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'MUC1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'Mucin-1细胞表面糖蛋白;肾小管上皮保护;ADTKD-MUC1(AD)突变致肾衰竭伴高尿酸',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'MYC',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'MYC原癌基因;bHLH转录因子;细胞增殖/代谢重编程',
            'key_domains': 'bHLH;Basic motif;亮氨酸拉链(与MAX二聚化)',
            'clingen_validity': '',
        },
        {
            'gene': 'PARD3',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'Par3细胞极性调节蛋白;紧密连接/上皮极性;肾小管上皮功能',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'PFKM',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '磷酸果糖激酶肌肉型;糖酵解限速酶;GSD VII/Tarui病(AR)可合并高尿酸',
            'key_domains': 'N端催化PFK域;间域连接子;C端调节PFK域',
            'clingen_validity': '',
        },
        {
            'gene': 'PHKA2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '磷酸化酶激酶α-2亚基(Xp22);肝糖原分解;GSD IXa(XLR)可合并高尿酸',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'PHKB',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '磷酸化酶激酶β亚基;肝/肌糖原分解;GSD IXb(AR)可合并高尿酸',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'PYGM',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '肌糖原磷酸化酶;糖原分解;McArdle病/GSD V(AR)运动后可致高尿酸',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'RNU7-1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'U7小核RNA 1;组蛋白pre-mRNA 3'端加工;RNA代谢',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SARS2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '线粒体丝氨酰-tRNA合成酶2;线粒体蛋白翻译;HUPRA综合征(AR)可合并高尿酸',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SEC61A1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'Sec61转位孔α-1亚基;内质网蛋白转运;ADTKD-SEC61A1(AD)突变致肾衰竭',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SH2B1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'SH2B衔接蛋白1;瘦素/胰岛素信号转导;肥胖/代谢综合征关联',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'SLC37A4',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '葡萄糖-6-磷酸转运体;微粒体G6P运输;GSD Ib(AR)可合并高尿酸血症/中性粒细胞减少',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TNFRSF11A',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': 'RANK受体;破骨细胞分化/骨重塑;骨质相关代谢',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'TNFRSF11B',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '骨保护素(OPG);RANKL诱饵受体;抑制破骨细胞;骨代谢',
            'key_domains': '',
            'clingen_validity': '',
        },
        {
            'gene': 'ZNF365',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'mixed',
            'note': 'HPO/OMIM独立来源审计',
            'phenotype_assoc': '锌指蛋白365;中心体定位;细胞周期调控;代谢GWAS位点',
            'key_domains': '',
            'clingen_validity': '',
        },
    ],
    'known_pathogenic_variants': [
        {
            'rsid': 'rs387906725',
            'chrom': 'chrX',
            'pos': 134475189,
            'ref': 'G',
            'alt': 'A',
            'gene': 'HPRT1',
            'effect_allele': 'A',
            'other_allele': 'G',
            'variant_class': 'known_pathogenic',
            'contribution_score': 1.0,
            'confidence': 'high',
            'note': 'HPRT1 错义变异；X-连锁隐性，男性半合子导致高尿酸血症/Lesch-Nyhan 综合征，女性携带者通常无症状或轻度高尿酸',
        },
        {
            'rsid': 'rs137852494',
            'chrom': 'chrX',
            'pos': 134475197,
            'ref': 'C',
            'alt': 'T',
            'gene': 'HPRT1',
            'effect_allele': 'T',
            'other_allele': 'C',
            'variant_class': 'known_pathogenic',
            'contribution_score': 1.0,
            'confidence': 'high',
            'note': 'HPRT1 无义变异；X-连锁隐性，男性半合子导致严重高尿酸血症，女性携带者通常不发病',
        },
        {
            'rsid': 'rs786200980',
            'chrom': 'chrX',
            'pos': 134475252,
            'ref': 'A',
            'alt': 'AG',
            'gene': 'HPRT1',
            'effect_allele': 'AG',
            'other_allele': 'A',
            'variant_class': 'known_pathogenic',
            'contribution_score': 1.0,
            'confidence': 'high',
            'note': 'HPRT1 移码变异；X-连锁隐性，男性半合子导致 HPRT 缺乏与高尿酸血症',
        },
        {
            'rsid': 'rs137852540',
            'chrom': 'chrX',
            'pos': 107640936,
            'ref': 'A',
            'alt': 'G',
            'gene': 'PRPS1',
            'effect_allele': 'G',
            'other_allele': 'A',
            'variant_class': 'known_pathogenic',
            'contribution_score': 1.0,
            'confidence': 'high',
            'note': 'PRPS1 功能增强变异（p.Asn114Ser）；X-连锁，男性半合子导致 PRPP 合成酶超活性、嘌呤过量生成和早发高尿酸血症',
        },
        {
            'rsid': 'rs780475918',
            'chrom': 'chr16',
            'pos': 20341286,
            'ref': 'G',
            'alt': 'T',
            'gene': 'UMOD',
            'effect_allele': 'T',
            'other_allele': 'G',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.95,
            'confidence': 'high',
            'note': 'UMOD 错义变异；常显，杂合导致尿调素相关肾病（MCKD2/FJHN），伴进行性高尿酸血症和痛风',
        },
        {
            'rsid': 'rs121917741',
            'chrom': 'chr1',
            'pos': 204162117,
            'ref': 'G',
            'alt': 'A',
            'gene': 'REN',
            'effect_allele': 'A',
            'other_allele': 'G',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.95,
            'confidence': 'high',
            'note': 'REN 无义变异；常显，杂合导致家族性青少年高尿酸血症肾病 2 型（高尿酸血症+贫血倾向）',
        },
        {
            'rsid': 'rs121918672',
            'chrom': 'chr17',
            'pos': 37731814,
            'ref': 'G',
            'alt': 'A',
            'gene': 'HNF1B',
            'effect_allele': 'A',
            'other_allele': 'G',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.9,
            'confidence': 'high',
            'note': 'HNF1B 无义变异；常显，杂合导致肾囊肿糖尿病综合征，可合并高尿酸血症/痛风',
        },
        {
            'rsid': 'rs2231142',
            'chrom': 'chr4',
            'pos': 88131171,
            'ref': 'G',
            'alt': 'T',
            'gene': 'ABCG2',
            'effect_allele': 'T',
            'other_allele': 'G',
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.35,
            'confidence': 'moderate',
            'note': 'ABCG2 Q141K; EAS AF~30% vs EUR~10%, most impactful urate SNP in EAS',
        },
    ],
    'prs_variants_high': [
        {'rsid': 'rs2231142', 'chrom': 'chr4', 'pos': 88131171, 'gene': 'ABCG2', 'effect_allele': 'T', 'other_allele': 'G', 'beta': 0.15, 'or_value': None, 'tier': 'prs_high', 'contribution_score': 0.35, 'confidence': 'high', 'note': 'ABCG2 Q141K; strongest urate GWAS, EAS AF~30% (Tin 2019)'},
        {'rsid': 'rs12498742', 'chrom': 'chr4', 'pos': 9927267, 'gene': 'SLC2A9', 'effect_allele': 'A', 'other_allele': 'G', 'beta': 0.12, 'or_value': None, 'tier': 'prs_high', 'contribution_score': 0.28, 'confidence': 'high', 'note': 'SLC2A9/GLUT9; major urate transporter, GWAS top hit'},
        {'rsid': 'rs1260326', 'chrom': 'chr2', 'pos': 27508073, 'gene': 'GCKR', 'effect_allele': 'T', 'other_allele': 'C', 'beta': 0.03, 'or_value': None, 'tier': 'prs_high', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'GCKR; pleiotropic metabolic GWAS, urate-associated'}
    ],
    'gwas_loci_genes': [
        'A1CF',
        'ACAT1',
        'ACAT2',
        'ALDH16A1',
        'APOB',
        'APOC3',
        'BDH1',
        'FADS1',
        'HMGCL',
        'HMGCS1',
        'HMGCS2',
        'INHBC',
        'LPL',
        'OXCT1',
        'PPARG',
        'RFX3',
        'SF1',
        'SLC22A11',
        'TRIM46'
    ],
    'gwas_lead_snps': [
        {
            'rsid': 'rs6447906',
            'chrom': 'chr4',
            'pos': 10334408,
            'gene': '',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.0355461744098607,
            'or_value': None,
            'eaf_eur': 0.014,
            'eaf_eas': 0.066,
            'tier': 'gwas',
            'contribution_score': 0.376,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs11727087',
            'chrom': 'chr4',
            'pos': 10094396,
            'gene': 'WDR1',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': -0.0353795725932949,
            'or_value': None,
            'eaf_eur': 0.3981,
            'eaf_eas': 0.1139,
            'tier': 'gwas',
            'contribution_score': 0.367,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs2725252',
            'chrom': 'chr4',
            'pos': 88140758,
            'gene': 'ABCG2',
            'effect_allele': 'A',
            'other_allele': 'C',
            'beta': -0.0332825181975835,
            'or_value': None,
            'eaf_eur': 0.5471,
            'eaf_eas': 0.4061,
            'tier': 'gwas',
            'contribution_score': 0.349,
            'confidence': 'low',
            'note': 'PGS004006 beta=-0.0332825181975835',
        },
        {
            'rsid': 'rs2725256',
            'chrom': 'chr4',
            'pos': 88129846,
            'gene': 'ABCG2',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': -0.0321441354565307,
            'or_value': None,
            'eaf_eur': 0.334,
            'eaf_eas': 0.2858,
            'tier': 'gwas',
            'contribution_score': 0.341,
            'confidence': 'low',
            'note': 'PGS004006 beta=-0.0321441354565307',
        },
        {
            'rsid': 'rs16891971',
            'chrom': 'chr4',
            'pos': 9996752,
            'gene': 'SLC2A9',
            'effect_allele': 'A',
            'other_allele': 'C',
            'beta': -0.0321235410795085,
            'or_value': None,
            'eaf_eur': 0.0318,
            'eaf_eas': 0.001,
            'tier': 'gwas',
            'contribution_score': 0.341,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs475688',
            'chrom': 'chr11',
            'pos': 64596819,
            'gene': 'SLC22A12',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': -0.032038731299576,
            'or_value': None,
            'eaf_eur': 0.259,
            'eaf_eas': 0.4307,
            'tier': 'gwas',
            'contribution_score': 0.332,
            'confidence': 'low',
            'note': 'SLC22A12/URAT1 肾尿酸重吸收位点',
        },
        {
            'rsid': 'rs1564481',
            'chrom': 'chr4',
            'pos': 88140113,
            'gene': 'ABCG2',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': -0.0306832024146359,
            'or_value': None,
            'eaf_eur': 0.3351,
            'eaf_eas': 0.2848,
            'tier': 'gwas',
            'contribution_score': 0.323,
            'confidence': 'low',
            'note': 'PGS004006 beta=-0.0306832024146359',
        },
        {
            'rsid': 'rs1001216',
            'chrom': 'chr4',
            'pos': 10167225,
            'gene': '',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.0303758078929305,
            'or_value': None,
            'eaf_eur': 0.1312,
            'eaf_eas': 0.2317,
            'tier': 'gwas',
            'contribution_score': 0.315,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs4543113',
            'chrom': 'chr4',
            'pos': 10006681,
            'gene': 'SLC2A9',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': -0.0276019796858377,
            'or_value': None,
            'eaf_eur': 0.4088,
            'eaf_eas': 0.1151,
            'tier': 'gwas',
            'contribution_score': 0.288,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs3756231',
            'chrom': 'chr4',
            'pos': 10023920,
            'gene': 'SLC2A9',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': -0.0267822604805528,
            'or_value': None,
            'eaf_eur': 0.0307,
            'eaf_eas': 0.3898,
            'tier': 'gwas',
            'contribution_score': 0.28,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs10489073',
            'chrom': 'chr4',
            'pos': 10271164,
            'gene': '',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.0260044682420909,
            'or_value': None,
            'eaf_eur': 0.2496,
            'eaf_eas': 0.1632,
            'tier': 'gwas',
            'contribution_score': 0.271,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs3756227',
            'chrom': 'chr4',
            'pos': 10086371,
            'gene': 'WDR1',
            'effect_allele': 'A',
            'other_allele': 'C',
            'beta': 0.0257218081208291,
            'or_value': None,
            'eaf_eur': 0.2247,
            'eaf_eas': 0.2252,
            'tier': 'gwas',
            'contribution_score': 0.271,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs1871744',
            'chrom': 'chr4',
            'pos': 88118477,
            'gene': 'ABCG2',
            'effect_allele': 'C',
            'other_allele': 'T',
            'beta': -0.0255645424323746,
            'or_value': None,
            'eaf_eur': 0.1822,
            'eaf_eas': 0.2945,
            'tier': 'gwas',
            'contribution_score': 0.271,
            'confidence': 'low',
            'note': 'PGS004006 beta=-0.0255645424323746',
        },
        {
            'rsid': 'rs3733591',
            'chrom': 'chr4',
            'pos': 9920506,
            'gene': 'SLC2A9',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': -0.0250022673768206,
            'or_value': None,
            'eaf_eur': 0.1881,
            'eaf_eas': 0.662,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs2845885',
            'chrom': 'chr11',
            'pos': 64101590,
            'gene': 'FLRT1',
            'effect_allele': 'C',
            'other_allele': 'A',
            'beta': 0.0237068585022274,
            'or_value': None,
            'eaf_eur': 0.0901,
            'eaf_eas': 0.3855,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC22A12/URAT1 肾尿酸重吸收位点',
        },
        {
            'rsid': 'rs3751120',
            'chrom': 'chr11',
            'pos': 64116981,
            'gene': 'FLRT1',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': -0.0230770930253739,
            'or_value': None,
            'eaf_eur': 0.0702,
            'eaf_eas': 0.5333,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC22A12/URAT1 肾尿酸重吸收位点',
        },
        {
            'rsid': 'rs17477561',
            'chrom': 'chr4',
            'pos': 10313472,
            'gene': '',
            'effect_allele': 'C',
            'other_allele': 'T',
            'beta': 0.0221448249548231,
            'or_value': None,
            'eaf_eur': 0.2497,
            'eaf_eas': 0.0535,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs13103452',
            'chrom': 'chr4',
            'pos': 9693038,
            'gene': '',
            'effect_allele': 'C',
            'other_allele': 'T',
            'beta': 0.0214193187698644,
            'or_value': None,
            'eaf_eur': 0.676,
            'eaf_eas': 0.442,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'PGS004006 beta=0.0214193187698644',
        },
        {
            'rsid': 'rs4148149',
            'chrom': 'chr4',
            'pos': 88141133,
            'gene': 'ABCG2',
            'effect_allele': 'G',
            'other_allele': 'T',
            'beta': -0.0205298391331684,
            'or_value': None,
            'eaf_eur': 0.4717,
            'eaf_eas': 0.2855,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'PGS004006 beta=-0.0205298391331684',
        },
        {
            'rsid': 'rs17198197',
            'chrom': 'chr4',
            'pos': 10137533,
            'gene': '',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.0203855053066051,
            'or_value': None,
            'eaf_eur': 0.2126,
            'eaf_eas': 0.1689,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs13109847',
            'chrom': 'chr4',
            'pos': 10344621,
            'gene': '',
            'effect_allele': 'C',
            'other_allele': 'T',
            'beta': 0.020054536828385,
            'or_value': None,
            'eaf_eur': 0.2494,
            'eaf_eas': 0.052,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs17479487',
            'chrom': 'chr4',
            'pos': 10344926,
            'gene': '',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.0199288473565679,
            'or_value': None,
            'eaf_eur': 0.2489,
            'eaf_eas': 0.0526,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs13146686',
            'chrom': 'chr4',
            'pos': 10033309,
            'gene': 'SLC2A9',
            'effect_allele': 'T',
            'other_allele': 'A',
            'beta': -0.0197809777626767,
            'or_value': None,
            'eaf_eur': 0.4033,
            'eaf_eas': 0.1128,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs11231693',
            'chrom': 'chr11',
            'pos': 64095140,
            'gene': 'FLRT1',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.0196875644304042,
            'or_value': None,
            'eaf_eur': 0.0845,
            'eaf_eas': 0.3525,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC22A12/URAT1 肾尿酸重吸收位点',
        },
        {
            'rsid': 'rs11231463',
            'chrom': 'chr11',
            'pos': 63416983,
            'gene': '',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': -0.0196343154168128,
            'or_value': None,
            'eaf_eur': 0.0082,
            'eaf_eas': 0.0584,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'PGS004006 beta=-0.0196343154168128',
        },
        {
            'rsid': 'rs10489074',
            'chrom': 'chr4',
            'pos': 10270981,
            'gene': '',
            'effect_allele': 'A',
            'other_allele': 'C',
            'beta': 0.01928148633487,
            'or_value': None,
            'eaf_eur': 0.2618,
            'eaf_eas': 0.1636,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs3825074',
            'chrom': 'chr11',
            'pos': 64648295,
            'gene': 'NRXN2',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': -0.0190216584485925,
            'or_value': None,
            'eaf_eur': 0.2419,
            'eaf_eas': 0.1854,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC22A12/URAT1 肾尿酸重吸收位点',
        },
        {
            'rsid': 'rs10792438',
            'chrom': 'chr11',
            'pos': 64535054,
            'gene': '',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': -0.0189840927804905,
            'or_value': None,
            'eaf_eur': 0.1515,
            'eaf_eas': 0.6285,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC22A12/URAT1 肾尿酸重吸收位点',
        },
        {
            'rsid': 'rs16891234',
            'chrom': 'chr4',
            'pos': 9944539,
            'gene': 'SLC2A9',
            'effect_allele': 'C',
            'other_allele': 'T',
            'beta': 0.0189090411091891,
            'or_value': None,
            'eaf_eur': 0.2257,
            'eaf_eas': 0.0887,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs6845554',
            'chrom': 'chr4',
            'pos': 10011549,
            'gene': 'SLC2A9',
            'effect_allele': 'T',
            'other_allele': 'A',
            'beta': -0.0187951075349578,
            'or_value': None,
            'eaf_eur': 0.4024,
            'eaf_eas': 0.1133,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs10939515',
            'chrom': 'chr4',
            'pos': 9771672,
            'gene': 'SLC2A9',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.0187819429164414,
            'or_value': None,
            'eaf_eur': 0.1551,
            'eaf_eas': 0.324,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs3114019',
            'chrom': 'chr4',
            'pos': 88160289,
            'gene': 'ABCG2',
            'effect_allele': 'C',
            'other_allele': 'A',
            'beta': -0.0187518007630376,
            'or_value': None,
            'eaf_eur': 0.247,
            'eaf_eas': 0.1892,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'PGS004006 beta=-0.0187518007630376',
        },
        {
            'rsid': 'rs16895909',
            'chrom': 'chr4',
            'pos': 10280022,
            'gene': '',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.0187119532935178,
            'or_value': None,
            'eaf_eur': 0.2312,
            'eaf_eas': 0.3048,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs7939462',
            'chrom': 'chr11',
            'pos': 64531858,
            'gene': '',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': -0.0184964079966515,
            'or_value': None,
            'eaf_eur': 0.2,
            'eaf_eas': 0.6275,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC22A12/URAT1 肾尿酸重吸收位点',
        },
        {
            'rsid': 'rs6827754',
            'chrom': 'chr4',
            'pos': 10016529,
            'gene': 'SLC2A9',
            'effect_allele': 'C',
            'other_allele': 'A',
            'beta': -0.0183465134012319,
            'or_value': None,
            'eaf_eur': 0.4218,
            'eaf_eas': 0.1138,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs10011796',
            'chrom': 'chr4',
            'pos': 88169725,
            'gene': 'ABCG2',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.0182017827341456,
            'or_value': None,
            'eaf_eur': 0.4516,
            'eaf_eas': 0.6606,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'PGS004006 beta=0.0182017827341456',
        },
        {
            'rsid': 'rs1878943',
            'chrom': 'chr4',
            'pos': 9765264,
            'gene': '',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': 0.0180285169178889,
            'or_value': None,
            'eaf_eur': 0.1787,
            'eaf_eas': 0.3224,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'PGS004006 beta=0.0180285169178889',
        },
        {
            'rsid': 'rs7437149',
            'chrom': 'chr4',
            'pos': 9403086,
            'gene': '',
            'effect_allele': 'G',
            'other_allele': 'A',
            'beta': 0.0175262355358624,
            'or_value': None,
            'eaf_eur': 0.2339,
            'eaf_eas': 0.1944,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'PGS004006 beta=0.0175262355358624',
        },
        {
            'rsid': 'rs6830786',
            'chrom': 'chr4',
            'pos': 10099819,
            'gene': 'WDR1',
            'effect_allele': 'T',
            'other_allele': 'C',
            'beta': -0.0168724503148815,
            'or_value': None,
            'eaf_eur': 0.2912,
            'eaf_eas': 0.4528,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC2A9/GLUT9 尿酸重吸收位点',
        },
        {
            'rsid': 'rs873491',
            'chrom': 'chr11',
            'pos': 66109099,
            'gene': 'PACS1',
            'effect_allele': 'A',
            'other_allele': 'G',
            'beta': 0.0166899964863653,
            'or_value': None,
            'eaf_eur': 0.1918,
            'eaf_eas': 0.2074,
            'tier': 'gwas',
            'contribution_score': 0.262,
            'confidence': 'low',
            'note': 'SLC22A12/URAT1 肾尿酸重吸收位点',
        },
    ],
    'core_genes': [
        'ABCG2',
        'AOX1',
        'CLDN16',
        'CLDN19',
        'GCKR',
        'HNF1B',
        'HPRT1',
        'MOCOS',
        'PDZK1',
        'PRPS1',
        'REN',
        'SLC17A1',
        'SLC17A3',
        'SLC22A12',
        'SLC2A9',
        'UMOD',
        'XDH'
    ],
    'key_regions': {
        'XDH': {
            'note': 'XDH/XO 是嘌呤降解限速酶，催化 hypoxanthine→xanthine 及 xanthine→uric acid；其 Mo-MPT 区域为别嘌醇/非布司他作用靶点。',
            'regions': [
                {'name': 'Fe-S_cluster_2', 'residues': '113-150', 'note': '2Fe-2S cluster binding (electron transfer)'},
                {'name': 'FAD_binding', 'residues': '229-414', 'note': 'FAD cofactor binding domain'},
                {'name': 'Mo-MPT_substrate', 'residues': '700-1100', 'note': 'Molybdopterin cofactor and purine substrate binding region'},
            ],
            'critical_residues': [
                {'residue': 'Glu803', 'note': 'Substrate binding; Glu803Val strongly decreases xanthine/hypoxanthine activity'},
                {'residue': 'Arg881', 'note': 'Substrate binding; Arg881Met abolishes xanthine oxidase activity'},
                {'residue': 'Ala1080', 'note': 'Mo-MPT cofactor binding'},
                {'residue': 'Glu1262', 'note': 'Active-site proton acceptor'},
            ],
        },
        'SLC2A9': {
            'note': 'SLC2A9/GLUT9 是尿酸重吸收关键转运体（肝/肾），介导尿酸跨膜转运。',
            'regions': [
                {'name': 'MFS_transporter', 'residues': '1-540', 'note': 'Major facilitator superfamily (12 TMs)'},
            ],
            'critical_residues': [
                {'residue': 'Arg198', 'note': '肾性低尿酸血症常见突变位点'},
                {'residue': 'Arg380', 'note': '肾性低尿酸血症常见突变位点'},
                {'residue': 'Arg405', 'note': '肾性低尿酸血症常见突变位点'},
            ],
        },
        'ABCG2': {
            'note': 'ABCG2 是尿酸分泌型转运体，主要表达于肠道和肾小管；功能缺失降低肠道尿酸外排。',
            'regions': [
                {'name': 'TM1', 'residues': '1-180', 'note': 'Transmembrane domain 1'},
                {'name': 'NBD1', 'residues': '181-390', 'note': 'Nucleotide-binding domain 1 (ATP binding)'},
                {'name': 'TM2', 'residues': '391-570', 'note': 'Transmembrane domain 2'},
                {'name': 'NBD2', 'residues': '571-655', 'note': 'Nucleotide-binding domain 2 (ATP binding)'},
            ],
            'critical_residues': [
                {'residue': 'Gln141', 'note': 'Q141K 是东亚常见功能缺失多态，升高血清尿酸'},
            ],
        },
        'SLC22A12': {
            'note': 'SLC22A12/URAT1 是肾小管尿酸重吸收的主要转运体，是苯溴马隆/丙磺舒靶点。',
            'regions': [
                {'name': 'MFS_transporter', 'residues': '1-555', 'note': 'Major facilitator superfamily (12 TMs)'},
            ],
            'critical_residues': [
                {'residue': 'Arg90', 'note': '肾性低尿酸血症常见突变位点'},
                {'residue': 'Trp258', 'note': '底物结合/转运关键位点'},
            ],
        },
        'SLC17A1': {
            'note': 'SLC17A1/NPT1 是肾脏尿酸分泌型磷酸盐转运体。',
            'regions': [
                {'name': 'MFS_transporter', 'residues': '1-465', 'note': 'Major facilitator superfamily'},
            ],
            'critical_residues': [],
        },
        'SLC17A3': {
            'note': 'SLC17A3/NPT4 是肾脏尿酸/阴离子分泌转运体。',
            'regions': [
                {'name': 'MFS_transporter', 'residues': '1-466', 'note': 'Major facilitator superfamily'},
            ],
            'critical_residues': [],
        },
        'HPRT1': {
            'note': 'HPRT1 是嘌呤补救合成关键酶；完全缺失导致 Lesch-Nyhan 综合征，部分缺失导致高尿酸血症。',
            'regions': [
                {'name': 'HPRT_Catalytic', 'residues': '1-218', 'note': 'Hypoxanthine-guanine phosphoribosyltransferase catalytic domain'},
            ],
            'critical_residues': [
                {'residue': 'Asp134', 'note': '活性位点 Mg2+ 配位'},
                {'residue': 'Arg169', 'note': '5-磷酸核糖结合'},
            ],
        },
        'PRPS1': {
            'note': 'PRPS1 催化 5-磷酸核糖-1-焦磷酸合成；功能增强导致嘌呤过量生成和高尿酸血症。',
            'regions': [
                {'name': 'PRPP_synthetase', 'residues': '1-318', 'note': 'Ribose-phosphate pyrophosphokinase domain'},
            ],
            'critical_residues': [
                {'residue': 'Asp128', 'note': '活性位点'},
                {'residue': 'Arg189', 'note': '变构调节位点'},
            ],
        },
        'UMOD': {
            'note': 'UMOD/尿调素突变导致肾小管间质疾病，常伴高尿酸血症和痛风。',
            'regions': [
                {'name': 'EGF_like', 'residues': '28-340', 'note': 'EGF-like domains'},
                {'name': 'D8C', 'residues': '343-580', 'note': 'Cys-rich D8C domain'},
                {'name': 'ZP', 'residues': '585-640', 'note': 'Zona pellucida polymerization domain'},
            ],
            'critical_residues': [
                {'residue': 'Cys148', 'note': '常见 MCKD2 突变位点，影响二硫键形成'},
            ],
        },
        'HNF1B': {
            'note': 'HNF1B 是肾发育和肾小管功能转录因子；突变导致肾囊肿糖尿病综合征，可合并高尿酸。',
            'regions': [
                {'name': 'POU_specific', 'residues': '228-299', 'note': 'POU-specific DNA-binding domain'},
                {'name': 'Homeobox', 'residues': '300-363', 'note': 'Homeodomain DNA-binding domain'},
            ],
            'critical_residues': [],
        },
        'AOX1': {
            'note': 'AOX1 是醛氧化酶，与 XDH 同属钼羟化酶家族，参与嘌呤/嘧啶代谢。',
            'regions': [
                {'name': 'Mo-MPT', 'residues': '700-1100', 'note': 'Molybdopterin cofactor region (approximate)'},
            ],
            'critical_residues': [],
        },
        'GCKR': {
            'note': 'GCKR 调节葡萄糖激酶活性，间接影响果糖/尿酸代谢。',
            'regions': [
                {'name': 'PISL', 'residues': '1-625', 'note': 'Glucokinase regulatory protein domain'},
            ],
            'critical_residues': [
                {'residue': 'Leu446', 'note': 'P446L 是常见功能多态，影响甘油三酯和尿酸'},
            ],
        },
        'PDZK1': {
            'note': 'PDZK1 是尿酸转运体支架蛋白，调控 SLC22A12、SLC17A1 等在肾小管顶膜的表达。',
            'regions': [
                {'name': 'PDZ1', 'residues': '7-90', 'note': 'PDZ domain 1'},
                {'name': 'PDZ2', 'residues': '97-180', 'note': 'PDZ domain 2'},
                {'name': 'PDZ3', 'residues': '187-270', 'note': 'PDZ domain 3'},
                {'name': 'PDZ4', 'residues': '277-360', 'note': 'PDZ domain 4'},
            ],
            'critical_residues': [],
        },
    },
    'regions': [
        {'chrom': 'chr4', 'start': 9900000, 'end': 10400000, 'gene': 'SLC2A9', 'type': 'gwas_locus', 'contribution_score': 0.55, 'note': 'SLC2A9/GLUT9 最强尿酸GWAS区'},
        {'chrom': 'chr4', 'start': 88080000, 'end': 88160000, 'gene': 'ABCG2', 'type': 'gwas_locus', 'contribution_score': 0.45, 'note': 'ABCG2 Q141K 肠道/肾尿酸外排区'},
        {'chrom': 'chr11', 'start': 64500000, 'end': 66200000, 'gene': 'SLC22A12', 'type': 'gwas_locus', 'contribution_score': 0.4, 'note': 'SLC22A12/URAT1 肾尿酸重吸收区'},
        {'chrom': 'chr6', 'start': 25780000, 'end': 25900000, 'gene': 'SLC17A1/SLC17A3', 'type': 'gwas_locus', 'contribution_score': 0.35, 'note': 'SLC17A1/NPT1/SLC17A3/NPT4 尿酸分泌区'},
        {'chrom': 'chr2', 'start': 27500000, 'end': 27560000, 'gene': 'GCKR', 'type': 'gwas_locus', 'contribution_score': 0.3, 'note': 'GCKR 糖脂代谢/尿酸关联区'},
    ],
    'regulatory_regions': [
    ],
    'key_literature': [
        {'pmid': '18179892', 'title': 'SLC2A9 is a newly identified urate transporter influencing serum urate concentration, urate excretion and gout.', 'genes': ['SLC2A9'], 'note': 'Vitart et al., Nat Genet 2008', 'evidence_type': 'gwas'},
        {'pmid': '19503597', 'title': 'Common dysfunctional variants in ABCG2 are a major cause of early-onset gout.', 'genes': ['ABCG2'], 'note': 'Matsuo et al., Sci Rep 2011', 'evidence_type': 'gwas'},
        {'pmid': '23263486', 'title': 'Genome-wide association analyses identify 18 new loci associated with serum urate concentrations.', 'genes': ['SLC2A9', 'SLC22A12', 'ABCG2', 'SLC17A1', 'SLC17A3', 'GCKR', 'RFX3', 'PDZK1'], 'note': 'Köttgen et al., Nat Genet 2013', 'evidence_type': 'gwas'},
        {'pmid': '23785249', 'title': 'Genome-wide association study of clinically defined gout identifies multiple risk loci and its association with serum urate levels.', 'genes': ['SLC2A9', 'ABCG2', 'SLC22A12', 'PDZK1', 'GCKR'], 'note': 'Okada et al., Ann Rheum Dis 2012', 'evidence_type': 'gwas'},
        {'pmid': '19506252', 'title': 'Genetic variants in SLC2A9, SLC22A12 and ABCG2 associate with diuretic-induced gout.', 'genes': ['SLC2A9', 'SLC22A12', 'ABCG2'], 'note': 'McKeigue et al., Pharmacogenomics 2009', 'evidence_type': 'gwas'},
        {'pmid': '26467716', 'title': 'An update on the genetics of hyperuricemia and gout.', 'genes': ['SLC2A9', 'SLC22A12', 'ABCG2', 'SLC17A1', 'SLC17A3', 'GCKR'], 'note': 'Merriman & Dalbeth, Curr Opin Rheumatol 2015', 'evidence_type': 'gwas'},
        {'pmid': '29456098', 'title': 'A genome-wide association study of gout in multiple ethnic groups.', 'genes': ['SLC2A9', 'ABCG2', 'SLC22A12', 'PDZK1', 'GCKR', 'ALDH16A1'], 'note': 'Tin et al., Arthritis Rheumatol 2018', 'evidence_type': 'gwas'},
        {'pmid': '37027491', 'title': 'Genetic variation in ABCG2 and SLC2A9 and risk of gout: a multi-ancestry analysis.', 'genes': ['ABCG2', 'SLC2A9'], 'note': 'Merriman & Dalbeth, Nat Rev Rheumatol 2023', 'evidence_type': 'gwas'},
        {'pmid': '29208650', 'title': 'Genome-wide association study for serum urate concentrations and gout among 375,000 people uncovers 114 loci.', 'genes': ['SLC2A9', 'ABCG2', 'SLC22A12', 'SLC17A1', 'SLC17A3', 'GCKR', 'PDZK1', 'RFX3', 'ALDH16A1'], 'note': 'Köttgen et al., Nat Commun 2019', 'evidence_type': 'gwas'},
        {'pmid': '37679580', 'title': 'Trans-ancestry genome-wide association study of gout and hyperuricemia.', 'genes': ['SLC2A9', 'ABCG2', 'SLC22A12', 'PDZK1', 'GCKR'], 'note': 'Monti et al., Am J Hum Genet 2024 (PGS004006)', 'evidence_type': 'gwas'},
    ],
}
