"""Disease template: ibd."""

TEMPLATE_NAME = 'ibd'
TEMPLATE = {   'aliases': [   'inflammatory bowel disease',
                   'ibd',
                   "crohn's disease",
                   'crohn disease',
                   'cd',
                   'ulcerative colitis',
                   'uc',
                   'very early onset ibd',
                   'veo-ibd',
                   'crohn',
                   'colitis'],
    'mode': 'complex',
    'gene_set': [   {   'gene': 'NOD2',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.85,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'mixed',
                        'note': 'Crohn病最强遗传风险基因; NOD2/CARD15; '
                                '3个主要致病变异(Arg702Trp/Gly908Arg/Leu1007fs)增加CD风险~2-4x(杂合)~17-40x(纯合/复合杂合)',
                        'phenotype_assoc': 'Crohn病(OR杂合~2-4x,纯合~17-40x);Blau综合征(AD);NOD2信号通路;肠道菌群感知',
                        'key_domains': 'CARD×2;NACHT核苷酸结合域;LRR×10(胞壁酰二肽识别)',
                        'clingen_validity': 'Definitive (risk factor)'},
                    {   'gene': 'IL10RA',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.8,
                        'penetrance': 'high',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': '极早发IBD(VEO-IBD)(AR); IL-10受体α链缺陷→严重婴儿期结肠炎',
                        'phenotype_assoc': 'VEO-IBD(AR);婴儿期重度结肠炎;IL-10信号通路缺陷;HSCT治疗',
                        'key_domains': '纤连蛋白III型域×2;细胞因子受体同源域',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'IL10RB',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.8,
                        'penetrance': 'high',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': '极早发IBD(VEO-IBD)(AR); IL-10受体β链; 婴儿期发病',
                        'phenotype_assoc': 'VEO-IBD(AR);IL-10Rβ缺陷;婴儿期结肠炎+毛囊炎',
                        'key_domains': '纤连蛋白III型域×2;细胞因子受体同源域',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'IL10',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.8,
                        'penetrance': 'high',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': '极早发IBD(VEO-IBD)(AR); IL-10配体缺陷→早发重度结肠炎',
                        'phenotype_assoc': 'VEO-IBD(AR);IL-10缺陷;早发肠炎;HSCT治疗',
                        'key_domains': 'IL-10/19/20/22/24/26家族;4-α-螺旋束细胞因子',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'XIAP',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.75,
                        'penetrance': 'high',
                        'penetrance_score': 0.7,
                        'evidence': 'familial',
                        'note': 'X连锁淋巴增殖综合征2型(XLP2); 部分患者表现为VEO-IBD; NOD2信号必需',
                        'phenotype_assoc': 'XLP2(X连锁);VEO-IBD表型(~17%);HLH;NOD2通路RIPK2泛素化',
                        'key_domains': 'BIR×3;UBA域;RING锌指',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'ATG16L1',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.5,
                        'penetrance': 'low',
                        'penetrance_score': 0.1,
                        'evidence': 'mixed',
                        'note': '自噬相关基因16L1; T300A变异(rs2241880)增加CD风险~1.3x; Paneth细胞功能缺陷',
                        'phenotype_assoc': 'ATG16L1;CD GWAS/候选基因;自噬通路;Paneth细胞颗粒分泌',
                        'key_domains': 'ATG16 N端;卷曲螺旋域;WD40重复×7',
                        'clingen_validity': 'Moderate (risk factor)'},
                    {   'gene': 'IRGM',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.45,
                        'penetrance': 'low',
                        'penetrance_score': 0.1,
                        'evidence': 'mixed',
                        'note': '免疫相关GTP酶M; CD风险位点; 自噬/细菌清除; 上游缺失(rs13361189)调控表达',
                        'phenotype_assoc': 'IRGM;CD GWAS;自噬/胞内菌清除;IRGM-CD风险单倍型',
                        'key_domains': 'GTP酶域;p47 GTP酶家族',
                        'clingen_validity': 'Limited (risk factor)'},
                    {   'gene': 'IL23R',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.35,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'IBD最强GWAS位点之一; R381Q保护性变异(OR~0.3); IL-23/Th17通路核心; CD+UC',
                        'phenotype_assoc': 'IL-23受体;CD/UC GWAS最强;R381Q保护(OR~0.3);Th17通路;ustekinumab靶点',
                        'key_domains': '纤连蛋白III型域;细胞因子受体同源域;IL-23R特有N端',
                        'clingen_validity': ''},
                    {   'gene': 'IL12B',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'IL-12/IL-23共同亚基p40; CD/UC GWAS; ustekinumab治疗靶点',
                        'phenotype_assoc': 'IL-12p40/IL-23p40;CD/UC GWAS;ustekinumab靶点;Th1/Th17分化',
                        'key_domains': 'IL-12p40;纤连蛋白III型域;免疫球蛋白C2型',
                        'clingen_validity': ''},
                    {   'gene': 'JAK2',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'JAK-STAT信号通路; CD/UC GWAS; tofacitinib/upadacitinib靶点',
                        'phenotype_assoc': 'JAK2;CD/UC GWAS;JAK-STAT通路;JAK抑制剂靶点(tofacitinib)',
                        'key_domains': 'FERM域;SH2-like;假激酶域(JH2);蛋白激酶域(JH1)',
                        'clingen_validity': ''},
                    {   'gene': 'STAT3',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'STAT3; CD GWAS; IL-6/IL-23下游; Th17分化必需',
                        'phenotype_assoc': 'STAT3;CD GWAS;Th17/Treg平衡;高IgE综合征(AD)',
                        'key_domains': 'STAT N端;卷曲螺旋域;DNA结合域;SH2域;反式激活域',
                        'clingen_validity': ''},
                    {   'gene': 'TNFSF15',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.28,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'TL1A; CD GWAS强位点; TNF超家族; 肠道炎症/纤维化',
                        'phenotype_assoc': 'TL1A/TNFSF15;CD GWAS;TNF超家族;肠道纤维化;DR3配体',
                        'key_domains': 'TNF同源域',
                        'clingen_validity': ''},
                    {   'gene': 'CARD9',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CD/UC GWAS; CARD9-CBM复合体; 真菌识别/NF-κB激活; 与AS共有',
                        'phenotype_assoc': 'CARD9;CD/UC GWAS;真菌免疫;CBM信号体;NF-κB',
                        'key_domains': 'CARD域;卷曲螺旋域',
                        'clingen_validity': ''},
                    {   'gene': 'NKX2-3',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CD/UC GWAS; 同源盒转录因子; 淋巴组织发育/脾脏',
                        'phenotype_assoc': 'NKX2-3;CD/UC GWAS;NK2家族转录因子;淋巴器官发育',
                        'key_domains': '同源盒域',
                        'clingen_validity': ''},
                    {   'gene': 'PTGER4',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CD GWAS; PGE2受体EP4; 肠上皮屏障/免疫调节',
                        'phenotype_assoc': 'EP4/PGE2受体;CD GWAS;肠上皮屏障;PGE2信号',
                        'key_domains': 'GPCR视紫红质样7-TM',
                        'clingen_validity': ''},
                    {   'gene': 'MST1',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CD/UC GWAS; 巨噬细胞刺激蛋白(MSP); RON受体配体; 肠上皮修复',
                        'phenotype_assoc': 'MSP/MST1;CD/UC GWAS;RON受体配体;肠上皮修复/再生',
                        'key_domains': 'PAN/APPLE域;Kringle域×4;丝氨酸蛋白酶催化域',
                        'clingen_validity': ''},
                    {   'gene': 'CCR6',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CD GWAS; CCL20受体; Th17细胞肠道迁移; 上皮CCL20表达',
                        'phenotype_assoc': 'CCR6;CD GWAS;Th17肠道迁移;CCL20受体;GALT',
                        'key_domains': 'GPCR视紫红质样7-TM',
                        'clingen_validity': ''},
                    {   'gene': 'REL',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'UC GWAS; c-Rel/NF-κB亚基; 调节性T细胞; 与RA共有位点',
                        'phenotype_assoc': 'c-Rel;UC GWAS;NF-κB家族;Treg功能;B细胞活化',
                        'key_domains': 'Rel同源域(RHD);反式激活域',
                        'clingen_validity': ''},
                    {   'gene': 'HNF4A',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'UC GWAS强位点; 肝细胞核因子4α; 肠上皮紧密连接/屏障; MODY1',
                        'phenotype_assoc': 'HNF4α;UC GWAS(Top);肠上皮屏障;紧密连接调控;MODY1(AD)',
                        'key_domains': 'AF-1域;DNA结合锌指;配体结合域;AF-2',
                        'clingen_validity': ''},
                    {   'gene': 'ECM1',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'UC GWAS; 细胞外基质蛋白1; 肠上皮基底膜/屏障',
                        'phenotype_assoc': 'ECM1;UC GWAS;细胞外基质;Th2免疫;类脂蛋白沉积症(AR)',
                        'key_domains': 'EGF-like;CCP(SUSHI)重复',
                        'clingen_validity': ''},
                    {   'gene': 'IL2RA',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'UC GWAS; IL-2受体α链(CD25); Treg表面标记; 多自身免疫病共有',
                        'phenotype_assoc': 'CD25;UC GWAS;Treg功能;sIL-2Rα;多自身免疫病位点',
                        'key_domains': 'SUSHI域×2(CCP);细胞因子受体同源域',
                        'clingen_validity': ''},
                    {   'gene': 'SLC22A5',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CD GWAS(5q31 IBD5风险单倍型); OCTN2肉碱转运体; 肠上皮代谢',
                        'phenotype_assoc': 'OCTN2;IBD5风险单倍型(CD);肉碱转运;肠上皮屏障',
                        'key_domains': 'MFS转运体;TMD×12',
                        'clingen_validity': ''},
                    {   'gene': 'FUT2',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CD GWAS; α1,2-岩藻糖基转移酶; 分泌型状态(H抗原); 肠道菌群组成',
                        'phenotype_assoc': 'FUT2/Secretor;CD GWAS;肠道菌群组成;H抗原合成;非分泌型保护CD',
                        'key_domains': '糖基转移酶GT-B超家族',
                        'clingen_validity': ''},
                    {   'gene': 'TYK2',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CD/UC GWAS; JAK家族非受体酪氨酸激酶; IL-12/IL-23/IFN信号; deucravacitinib靶点',
                        'phenotype_assoc': 'TYK2;CD/UC GWAS;JAK-STAT通路;deucravacitinib靶点',
                        'key_domains': 'FERM域;SH2-like;假激酶域(JH2);蛋白激酶域(JH1)',
                        'clingen_validity': ''},
                    {   'gene': 'SMAD3',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CD GWAS; TGF-β通路R-SMAD; 肠道免疫/纤维化; Loeys-Dietz 3型(AD)',
                        'phenotype_assoc': 'SMAD3;CD GWAS;TGF-β通路;肠纤维化;LDS3(AD)',
                        'key_domains': 'MH1域;MH2域(SMAD结合)',
                        'clingen_validity': ''},
                    {   'gene': 'ZNF365',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CD GWAS(10q21); 锌指蛋白365; 上皮间质转化/细胞极性',
                        'phenotype_assoc': 'ZNF365;CD GWAS;中心体/有丝分裂;细胞极性',
                        'key_domains': '锌指C2H2型',
                        'clingen_validity': ''},
                    {   'gene': 'LAMB1',
                        'tier': 'gwas',
                        'contribution_score': 0.12,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'UC GWAS; 层粘连蛋白β1; 肠上皮基底膜组成',
                        'phenotype_assoc': 'LAMB1;UC GWAS;层粘连蛋白;基底膜;肠上皮完整性',
                        'key_domains': '层粘连蛋白N端;EGF-like×13;层粘连蛋白卷曲螺旋',
                        'clingen_validity': ''},
                    {   'gene': 'GNA12',
                        'tier': 'gwas',
                        'contribution_score': 0.12,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'UC GWAS; Gα12; 肠上皮紧密连接调控; RhoA信号',
                        'phenotype_assoc': 'Gα12;UC GWAS;RhoA/紧密连接;肠上皮屏障调控',
                        'key_domains': 'G蛋白α亚基;GTP酶域',
                        'clingen_validity': ''},
                    {   'gene': 'CREM',
                        'tier': 'gwas',
                        'contribution_score': 0.12,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'CD/UC GWAS; cAMP应答元件调节因子; T细胞分化; IL-2/IL-17转录调控',
                        'phenotype_assoc': 'CREM/ICER;CD/UC GWAS;cAMP应答;T细胞效应功能;IL-2/IL-17调控',
                        'key_domains': 'bZIP域(碱性亮氨酸拉链);激酶诱导域(KID)',
                        'clingen_validity': ''}],
    'known_pathogenic_variants': [   {   'rsid': 'rs2066844',
                                         'chrom': 'chr16',
                                         'pos': 50745436,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'NOD2',
                                         'effect_allele': 'T',
                                         'or_value': 3.0,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.85,
                                         'confidence': 'high',
                                         'note': 'NOD2 Arg702Trp (SNP8) — CD OR~3(杂合); 欧洲人群频率~5-10%'},
                                     {   'rsid': 'rs2066845',
                                         'chrom': 'chr16',
                                         'pos': 50742358,
                                         'ref': 'G',
                                         'alt': 'C',
                                         'gene': 'NOD2',
                                         'effect_allele': 'C',
                                         'or_value': 3.0,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.85,
                                         'confidence': 'high',
                                         'note': 'NOD2 Gly908Arg (SNP12) — CD OR~3(杂合)'},
                                     {   'rsid': 'rs2066847',
                                         'chrom': 'chr16',
                                         'pos': 50742602,
                                         'ref': '-',
                                         'alt': 'C',
                                         'gene': 'NOD2',
                                         'effect_allele': 'C',
                                         'or_value': 4.0,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.9,
                                         'confidence': 'high',
                                         'note': 'NOD2 Leu1007fs (SNP13/3020insC) — CD OR~4(杂合)~17-40(纯合); '
                                                 '最强的CD常见致病变异'},
                                     {   'rsid': 'rs11209026',
                                         'chrom': 'chr1',
                                         'pos': 67258828,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'IL23R',
                                         'effect_allele': 'A',
                                         'or_value': 0.3,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.35,
                                         'confidence': 'high',
                                         'note': 'IL23R R381Q — 强保护性变异(OR~0.3); 欧洲频率~7%; 亚洲罕见'},
                                     {   'rsid': 'rs2241880',
                                         'chrom': 'chr2',
                                         'pos': 233275150,
                                         'ref': 'T',
                                         'alt': 'C',
                                         'gene': 'ATG16L1',
                                         'effect_allele': 'C',
                                         'or_value': 1.32,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.4,
                                         'confidence': 'high',
                                         'note': 'ATG16L1 T300A — CD OR~1.3; 自噬缺陷; 欧洲频率~50%'},
                                     {   'rsid': 'rs13361189',
                                         'chrom': 'chr5',
                                         'pos': 150796064,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'IRGM',
                                         'effect_allele': 'T',
                                         'or_value': 1.38,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.35,
                                         'confidence': 'high',
                                         'note': 'IRGM上游缺失-调控变异 — CD OR~1.4; 自噬缺陷'},
                                     {   'rsid': '1047917',
                                         'chrom': '11',
                                         'pos': 117986314,
                                         'ref': 'TCGGGGGCGGGGCGTCTGTAGGCCTCGCCCCGCTGACGTCAGCCCTGCGGGGCGCTGGCGGAGCGGGCGGCGGAGCTGTCAGTCCCAGCCCAAGGGTAGCTGGAGGCGCGCAGGCCGGCTCCGCTCCGGCCCCGGACGATGCGGCGCGCCCAGGATGCTGCCGTGCCTCGTAGTGCTGCTGGCGGCGCTCCTCAGCCTCCGTCTTGGCTCAGACGCTCATGGTAAGGCTCCGGGACGCGGCCCTTCCCTGCCCTGCCCTCTCCGCGCCCGCTCCATTAAAGTTCTCCATCCAGTGGAGAGCCCTGGCTGGCTGGCCCTCTGGCAGAGCGGTGCC',
                                         'alt': 'T',
                                         'gene': 'IL10RA',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Inflammatory bowel disease 28'},
                                     {   'rsid': '1048075',
                                         'chrom': '11',
                                         'pos': 117986465,
                                         'ref': 'AGGATGCTGCCGTGCCTCGTAGTGCTGCTGGCGGCGCTCCTCAGCCTCCGTCTTGGCTCAGACGCTCAT',
                                         'alt': 'A',
                                         'gene': 'IL10RA',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Inflammatory bowel disease 28'},
                                     {   'rsid': '2664350',
                                         'chrom': '21',
                                         'pos': 33266484,
                                         'ref': 'AGCTGGCTGGGTGGCTGCCT',
                                         'alt': 'A',
                                         'gene': 'IL10RB',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Inflammatory bowel disease 25'},
                                     {   'rsid': '1066682',
                                         'chrom': '21',
                                         'pos': 33266516,
                                         'ref': 'T',
                                         'alt': 'G',
                                         'gene': 'IL10RB',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Inflammatory bowel disease 25'},
                                     {   'rsid': '1710531',
                                         'chrom': '1',
                                         'pos': 206773552,
                                         'ref': 'T',
                                         'alt': 'C',
                                         'gene': 'IL10',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Leprosy, susceptibility to, 1|Hepatitis C '
                                                 'virus, susceptibility to'},
                                     {   'rsid': '16874',
                                         'chrom': '1',
                                         'pos': 206775286,
                                         'ref': 'T',
                                         'alt': 'C',
                                         'gene': 'IL10',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Rheumatoid arthritis, progression of'},
                                     {   'rsid': '4820174',
                                         'chrom': 'X',
                                         'pos': 123853390,
                                         'ref': 'TAAAAATACAAAAAATTAGCCAGCGTCATGGTGTGTGCCTGTAATCTCAGCTACTCAGGAGGCTGAGGCAGGAGACTCGCTTAAACCCAGGAGGCAGAGGTTGCAGAGAGCTGAGATCATGCCACTGCACTCCAGCCTGTGCAACAGAACAAGACTCTGTCTCAAAAAAAAAAAAAAGAAGAACACTTAGAGGGTTACTGAGAAGATTAAAGAGATAAAGCGAGATAAAGCTTGCGAAGCACTTAAGACATGGCCTGACATATGGCAAACATTCAGTAAATGCTAACCACTATTACTTATATTTAGAAGAATGTAAATAACTATTATTATTACTATTATTTTTTGAGATGGAGTCTTGCACTGTTGCCCAGGCTGGAGTGCAGTGGTGCGATCTCAGCTCACTGCAAGCTCCGCCTCCGGGGTTCTTGCCATTCTCCTGCCTCAGCCTCCCGAGTAGCTGGGACTACAGGTGCCCGCCACCACGCCCGGCTAATTTTTTGTATTTTTAGTACAGACAGGGTTTCACCGTGTTAGCCAGGATGGTCTTGATCTCCTGACCTTGTGATCCGCCTGCCTTGGCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACTGCACCCGGCTATTATTATTTATACTCCCTTACATACATTCAGGTCTTTGGCATCACAGTCTTCCTTTCTAAACACAAATCTTACCACCATCCTGGATGATGATCTCTCCAACATGCCAGCCTCTCTCTTGGACCTCAACTCCAGCAGCTTTCACCTCCTCCCTACTCAAGATACACCATGACGACACTCTGACCTTGACATTGTTGTTGGATTGTTGGATTTTTGCACAATAATAGACTGGGTATAACAATAGGATTAGATTAGTGTATATTAATAGAAAGCTCAGGTGCAATTTTCCATTAGTTTGAGATGAGAGTGTAATCTTCTGTTCTTGCCACAAACAAGCAAGAAGTCTTTTCTGTATGACTGGGTCCCAGGAAGATAAAAGCAGAGAAAGGAAAGGAGGTGCTGGCTAGAGATGCTAGCTTTGCCAGCACAAGCTAAGGGCAGGCATCTTTATGACTACTCAAAGAGAGGAAATTACAGTTGCAGTCTTTCTGGCAGCAAAGAGGGAATGAGAGGTTAGTGACCAAGATACTGGATCATGAATCAGGAGACTGAGGGGCGGATGCTGCCAACAGATGCTATTTGACATGAATGCTCATCACAAAGGCTGTTTGGTTATTGGTGAGTCAAGAGTAATCCTCTGCAAGTCTGCACCGCTTTCTCCCAGAAGAAGTTTCTTTTTTATTGTTGTTGTTTCCCTACTCATAGAAGAAGTTTCATGAAGCTGATAGCTCCGAGAACAAGGCCTGAAAGTCGGGGCTCACCCGCCCCCACCCCCCACCCCGCTTCACTCAAAGCTCTTGCTTTTTTTTTTTTTTTTTGAGACGGAGTCTCGCTCTGTCGCCCAGGCTGGAGTGCAGTGGCGCTGCAAGCTCCGCCTCCCGGGTTCACGCCATTCTCCTGCCTCAGCCTCCCGAGTAGCTGGGACTACAGGCGCCCGCCACCATGCCCGGCTAATTTTTTGTATTTTTAATAGAGACGGGGTTTCACTGTGTTAGCCAGGATGGTCTCGATCTCCTGACCTCGTGATCCGCCCGCCTCGGCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACTGCGCCCGGCCTTTTTTTTTTTTTTTTTTTTGAGACAGAGTTTCTCTCTTGTTGCCCAGGCTGGAGTGCAATGGCGCGATCTTGGCTCGCTGCAACCTCTGCCTCCCTGGTTCAAGTGATTCTCCTGCCTCAGCTTCTCGAGTAGCTGGCGCCCGCCACCAAGCCCAGCTAATTTTTTGTATTTTTAGTAGAGACGGGGTTTCACTATGTTGCCCAAGCTGGCTTCGAACTCCTGACCTCAGGCAATCCGCCTGCCTTGGCCTCCCACAGTGCTGTGATTACAGGCGTGAGCCACTGTGCCCGGCCTATAACTGCATTTTGGAAAAGAGTTCTAGTGCTAAATCTTTGCCGTTCCCCTCAGCGGATAACTACATATTTTACGTTCCACAGTATCCAGCTGCCACTGAGGTGTGGTGGCCATCCTCAAAATTCCCTTCTACTTATCCACATCTTGTGTCCTTTAGTCTCTGAGGATGTGTCCTCTTTTTCTGTTCAAGGATAATGCCTCTATTCATGCTTGATCCGATCTCTTTCTCCTTTCCTCTGAGTCTTTATGCCATCAATTTTCCTTTCTTCTGTTAGGTTGAACCATATTAAATTGCTGTTTGCATCATTTGGCAATGGTGGAACATTGGCAACTTCATGCGGTTCAAGTTAATATATCTTCATTCTTTTCCTCTCTAAATGTTCCTTCTCCTCAACCAAAACCAATTACAATAAAATATCCTTGTATAGGTAAGAGTAAGCTCTCTATATATTGTGTTTTGAATTTTACACTTACATATGTCCCTGCATATAAAACCTAAACACCGTATCTCAGGTATACTGGCCTTTGCTGTTCATATCTCCCAGTTGACAATTCACCCAATAAGTATTTACTGAGGATCTGGCATGTTCATGAAACACTTATTCACTCACCCAACAAATATCTTCTGAGCACATACACTGTGTCAGATACTGTTCTAAGCACTCGAACGATATCAGTGAACAAAACAAGGATCCTTGTGCTCTTAGAGCTTATATTCTAGCAGGAGTGGAAAGGAGACAATGTACAGTAAAGAAACATAATAATTAAAAGTACCATATAGTATGTTAGAAAGTGACAGATGCCGGGCACGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCAGGCGGATCACCTAAGGTCGGGAGTTTGAGACCAGCCTGACCAACATGGAGAAACCCTGTCTCTACTAAAAATACAAAATTAGCTGGGCGTGGTGGTGCATGCCTGTAATCCCAGCTACTCGGGAGGCTGAGTAGGAGAATCGCTTGAACCTGGTAGGTGGAGGTTGCAGTGAGCCAACATCGTGCCATTAGCACTCCAGCCTGGGCAACGAGAGCGAAACTCTGTCTCAAAAAAAAAAAGAAAAAGAAAAAAGAAAGTGACAGATGCCATGGAAAAAGCAGAAAGTTGAGCAGAGGAAGGGAGATTGGGAGTGCTGGGAGGAGGAACTGTAATTTTAAATATTGTGGTCACTGTAGGCCTTTTGGAGAAGGTAACAATTAAGCAAAGACTTGAAGGAGGAGAAGGATATGCTATCTGGGGAAAGTGTTCCGGGCAGAGTAAACAGCAAGTACACAGACCCTGAGTCAGGAAAGCTAAAGAAAGAAGGAGGAGAATAGTAGGAAATGAAGACACAAAAGTAAGAGTTTAGGGTCTTTGTATTAGGTATCTACTGCTGTGTAACAAATTGCCCTAAAATTTGGCTATTGACAATAATACACAGGAATTCAAGAGTCCTTTGGCTTGGGGGTTCTGGCTCTGGGTCCCAAGAGGCTACAGTTTCTGAAGGCTGTGCCTGAAGATTCTTCTTCCAAGGCGGCTCACTCACATGGTTGGCAAATTGGTGCTGGTTGTTGATGGGGGAGGAAGAGATGAGGAGAGGGGAAGGGCTTTGTTTCTATTTGTGTGGGTCTCTCCACCTGCTGTTTTTAAAAAAAAGCCTAGTGAAGTAAAGCAGTGAGAGTAGAGAAGGAAGAAAGAAATCTGTAACTAGCTGTGATCAATTGGTTGTAAACACCACTTCACTCAGACCAGCCTCCACATGCTGTTTGAGTATCTTCATGACATGACAGCTGGCTTCCCCTACAGCAACCAATCCAAAAACGGAGCAAGGCAGATACCACAATGCCTTTTATGACCTAGTCTTGTAAGTCACACGCTATCATTTCTACCATATACTACTGATGACACAGTCAGCCCTGGTTCATTATAGAAGAGAACTACCCCAGGGTGTAAATAGCAAGAGGTGAAGACCATTGGTGGTCATCTTGGTGGCTATGATAGCCTTGGTAGGTCATTATAAATCTGTGGTTTTTACTTTGAGGGAAATGGGAAGCCAATTAAGGGATCTGAGCAGTGAAATGACAATGATCTCACATGTTTCATGAGGACAACTCTTGCCACTGTGTGAATTGACTGGAGAAGAGCAAGGATGTAAGCGGGAGACCAGTGAGAAGGCTATTACAGTCCAAGAGAGATGCACTAGGGTCATAATGGTGGAGTCGAGAATTGGTGATATTCTGGATTCATTTTGAAGACAGAGATGACAAGATTTGCTGATGGATTGGATGTGGGATATAAGAGAAAGGAATTAAAGATGACTTCTAAGGGTTTTGGAGGAATAGGAATTACAAAAATGAGTTCCACATAGATCTTGCCATAAATGAGCTTACAACATAGGAGAGACAAGGTGTGTACGCAAGTGCCATATATACTACATGGCAGAAAGCACTATGCTCCATAATACAGTGCCAAGTACAATAAAAAAGTTCTGGAGATGGTTGCACAACAATGTGAATGTACTTATTGCCACTGAAAAATGGTTAAAATGGTAAATTTTTATTTATTTACTTATTTTTATTTATTTTTAATTTATAAATTTTAATTTATAAATTTTATTTATTTATTTATTTATTTTTATTTTTATTTTTTTGAGACGGAGTCTCGCTGTGTCACCCAGGCTGCAGTGCAGTGGCAGGATCTCGGTTCACTGCAAGTTCTGCCTCCCAGGTTCACGCCATTCTCCTGCCTCAGGCTCCCGAGTAGCTGGGACTACAGGTGCCTGCCACCACGCCCGGCTAATTTTTTGTATTTTTAGTAGAGACTGGGGTTTCACCGTGTTAGCCAGGATGGTCTCGATCTCCTGACCTCGTGATCCGCCCGCCTCAGCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACGGCGCCCGGCCTATTTATTTTTATTTACTTATTTATTTTGAGACGGAGTCTCGCTCTGTCACCCAGGGTGGAGTGCAGTGGTGCGATCTCGGCTTACTGCAGCCTCCAACTCCCGGGTTCCAGAGATTCTCCAGCCTCAGCCTACCAAGTAGCTGGGATTACAGGCACTCACCACCACACTCGGCTAATTTTTGTATTTTTAGTAGAGACGGGTTTTCACCATGTTGGCCAGGCTGGTCTCGAACTACTGACTTCTGGTGATCCACCCGCCTCGGCCTCCCAAAGTGTTAGGATTACAGGCGTGAGCCACCATGCCCAGCCAAAACAGTAAATTTTATGTTATGTACATTTTACCACAAGAAAACAACGGTGCTTAAAAAAAGCAAAAACAAATATTAGAGAAGTGCCACTAGAGTTCAGAGCATGGAGAGATGAACTTCAGCTAAGAAAATCAGAGAAGGCTTTGTGTACGGGCAGTCTTTTTTTTTTTTTTTTTTTTGAGACGGAGTCTCGCTGCCTTCCACGGGCAGTCTTTTCACATAGGCAGAGGGAGTAGTTTGAACAAATTAGCGGAAGGCAGGAAAACTGAGGATAGGCGGGGCACAAGGAGTAGTTCTGATTTGTTAGAAGATAGGGTAGGGCACCCAAGGGGAGAATAAACATGCAACTACGAGTTTTAAGAAAATTCTTTCCTCTCCTCCCTCCAAGTTCCCTTGTTGTGAAGGGAGGATCATATCTTGTATCACTTGATTTCATTTGAAATGAAATATTCAGAATCCATCATCTCACCACATTACCCTGTAAGATCCCATTTTCCTGAAACAAAAATTCCTATGTTGATCTGACAATCCTACAACGCATTTGAAATAAATCCAGGGTATGACCAGCATTTTATGTACACAGACTTCCTTTGTTTCCGGTCCATCTGCTTTCTTTTTCCTCTATTAATTTTCCCTTCACCTCCCAATCTTAACCCCCGCCATTCCCCCAGGGTCTCCCTTTCTTGTCATCCCTTTCATCCTTCCCTTCTTGGAAACAGATCCGATTCTAACCTCAGTTACCTTATTAGCCGCGTGATACTGGGATAGTTATCCCCTGTGGGCCTCAGTTTCCTTTGTAAAATGGGCTTATTAAACCCCCAAAGACAGTGCTTATCTTACAGGGTTGTCAACATTACAACAAAGAACACGTTATATGCCTAACACAGTACCTGATCTATAGTAAGAACTCAACATTTTCGCCCCTTCTCCTCCTCTTTTCTGTCCTTGTGCCTTTCTTCCACTATTCCTCAACCCCAGGGCCCAACAGGTAAAAACCGTGGGAAAAACCATCCTTAAGGCTGAAAGAAGAAACACTGGAGCTGGGGGCGGAGACTACGAGGTGCTCACTGCGCATGTGCGCGCGCTAGGTCAGCTTCTCGGTTCCAGCCGGGCGGGGGGGTCGGGTGGGGGTGGGGGTAGGGGTTGCAAGGGCCTCATTTTTTCTTACTGCCCCCATCCGGTTCGGGGAGGTGGCGGGACCTTGGCGGCGCCCGGAGCCGGCGTGGCGCTCATCGAGGGACGCCCGGCCCAAGTGGTAAGTTGAAAAATGGCGGAGGGGGGAAGAAGGAGGGGCTTTGCAGGGCAGGAGGCTGACCTCCCGGCCGGGGGTGGGAGGGACACGCCGGGGCCCAGTGGCGCAGCCCGGGCTGGGAGACTGACGGACCGCGCCCGGTGTCTCTTTGAGGCCCTGACGTGGACACACTTCGGGTTTCACGACTCCGGGTTTCTCCAGGGGATGGGCCGGCCGGTAGAGGCGCGTGAGGGAGACGAAGGGACTTCCGTTTCCTTCACCTAGGCTGGGGCCAAGCCGCAGAGCGGAGTTGGCATTTCCAGATTGGGGCTCGGGCCGCGCCTCCTCCGGGACCCTCCCCTTGGACCGAGCCGATCGCCGCGGGGCAGTTCGGGCCGGCTGTCCTGGCGCGGTGGGTACAGCTTGTGTAGGCTTTCCCCTCCCCCGCTTTCCCTCCTTCCCCTCTCCTCCCTCCCCTCTTCTTTTCCCCTCCACTTCCCTCGGGCCGGCGCTGCTGGGGAGGGCGGGAAGGCCGCGCCAGCCCATCAGGGGTGGCCCGGCCCCGGCTGCTTGCCCGGGTTCCTCGGACTGCCGACGGCAGGCGTGGGTGGGTGGGTGACTTCAGGCCTGCAGGATTGCCTTCCTAAACCCTGTGACACCTAAGGTAAATTGAGGCAAAGAACTTTTTAAAAAAATATGATCAAAGGGATTTCCTCCCCATGTGATAACCTGTGGCTTGTGTGGAGCAGGGTGGAGTGTGTCTGGAGAGGGCATATGAAACTGAAAGAATAAGGGCCAAAGAGCTTCCGGAAGAGGAAATTAGCTGGTGATTCTTTCCAATCTGCTTTCCCAGTCACCTTTCCGGCATGTTCTGTAAAACAAAATGTAATTTGACTTTGTTTCATTATTTTAACTCCATAACACTTAAATTGTTTTCTTTTCGGGGAGGGGAGTGTTTATTCTCAAACTAAGCAGTAGCCCTCTCCACCTTCGAAAAAGGAACAACGTCAATCCAACCTTTGTTAAAAAACTCCAACCTATCAGATTTTAATAATCTAGTAGTTTGCTTTCAAATATAATTATGTCGCTAGTTCTGTCACAACTATACTTTGATAGTTTAATGACTCACAGAAATTTGTAAGACTGGAGGTTGCAGTAGTGTTTCTTTCTTATTCTTTTTTTTCCCCATAATATTTATTATAGTCAATGAACAGTGTTACAGACGGCCATCTTAGAATTATAACATTTTAGAGTTGGAAGGGATCTTAGTCAAACCCTGTCCTTTTACAAAACCAGAAACCACGGCTTAGGAAGATTTCATAGCTTGCTAAAGGCTATCCAACTAGTTAGATTAGAACCCATGTTATCTGGCTTCTTGCCCACCACTCTTACTGCGCAATTGCTCCATATCGCCTCCAAGCATGAAAATTAAATGTATTCAATTCAACACACATTTCTGAAGAGTATAATACTTTGTACCAGTGACTGTGGTACCACTTTCTATGTATTTCAATGTATTTAACATGCTTATGGAGTACTTGAGATTCCCCCCCACCCCCACATTCAAGAAGTGGCAACAGTTTAGATTTATACACACACCTTCACATGTACGTGTGTATACTTGCATTTGCTCAGATAGTTTCTTGAAGGATACACAATAAAAATGTTAATAGTAATGACTTATGGAGGAGAAGAGAGATAGAAGACTTTTTACTTTGTACTTCACATGATCTAATGTACGGTTTGAATTTGTTATAAATTCGTATTGATTTCATAATTGAAAAGTTTTAAAGTTCACACCTTCCCACACAAATATATATATCAACATAAGCAAGTATATACCAATGGTATGTACACATTTATGTGCATATATGTATTTATACATATCAGTGGTTTGTACTGTAAAATCCGGTATGATTCAGGTCAACTCAGCTGACAAAGCAGACCTCATTATTGGATACTCATGTTTCGTTTTCTTGTATTGCTCTCTCCTAATGTAAGATAGTAAAAATAATATGTTACTAGTCGTCATATATTTTTAGAAATTGTCCTAAGCTTCTTGATTATCAAATAATGTAGCAAACTTTTAACACATTTAAAATATCAAATCTGGGTACTTGCTTCAGTGGTAGCACATATACTAAAATTCGAACAATTCAAAGAAGATTAGCATGGTGTTTTTTTTTATCAATTAATTAATTAATTTTTTTTTTTGAGACGGAGTCTTACTCTGTCATCCAGGCTGGAGTGCAGTGGCCCTATCTTGACTCACTGCAGCCTCCGCCTCCTGGGTTCAAGCTACTCAGCCTCCCCAGTAGCTAGGACTACAGGCATGCGCCACCACGCCTGGCTAATTTTTGTATTTTTAGTAGACACCGGGTTTCCCCATGTTGGCCAGGCTGATCTCGAACTCCTGACCTCAGGTGATGCACCCGCCTCGGCCTCCCAAAGTGCTGGGATTAAAGGTATGAGCCACCTCGCCTGGCCAGTCCATTTTTTTTTTTTTTGAGACAGAGTTTCGCTTTTGTTTCCCAGGCTGGAGTGCAATGGCACCATCTCAGCTCACTGCAACCTCCGCCTCCCAGGTTCAAGTGATTCTTCTGCCTCAGCCTCCCAAGTAGCTGGGATTACAGGTGCCCACCACCACACCTGGCTAATTAGGTCCCTTTTTTTTAATAAACCACAAGAAAAATTTGACACCTGACGCTGTGGCTCATGTCTGTAATCCCAGCACTTTGGGACGCCAAGGCGGGCAGATCACCTGAGGTCAGGAGTTGGAGTCCAGACTGGCCAACATGGTGAAACCCCACCTCTACTA',
                                         'alt': 'T',
                                         'gene': 'XIAP',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | X-linked lymphoproliferative disease '
                                                 'due to XIAP deficiency'},
                                     {   'rsid': '1684656',
                                         'chrom': 'X',
                                         'pos': 123880398,
                                         'ref': 'TGAAACTCTGTCTCAAAAAAAAAAAAGAAAGAAAACCCTAATAAAAAAAAAAAAAGCAGCCTGGCACAGTGGTTCACACCTGTTATCCCAGCACTTTGGGAGTTCGAGGCAGGTGGATCACCTGAGATCAGCAGTTCAATTCCAGCCTGGCCAACATGTTGAAACCCCATCTCTTCTAAAAATAAAAAAATTAGCCAGGCGTGGTGGCGGGCGCCTGTAATCCCAGCTACTTGGGAGGCTGAGACAGGAGAATGGCTTGGACCTGGGAGGCGGAGGTTGCAGTGAGTTGAGATCACGCCATTTCACTCCAGCCTGGGCCATAAGAGCAAAACTCTGTTTCAAAAAAAAAAAAAAAAAAAGGGAGAAATAGAAACTTTTGTGTCGTATACAGACACCAGGGTTTTGTATGTGCCTTTGTCTCTGTATCCCCCACCTCCACATTCCCACATTCTCGCTAGATTAGCTGTCAACCTCCTCTCCTTGGCACCTCCTGGTGGCTCTCTTTACGCAGTTGACTGGACTAAATGTATGTACATACATGTATACTGTAAAACCTTACATATCACCATTGTAGAATCTCCCAAACCCTTCATTTAAACATGCACCATTGCTTGCTGGTCCTTTTTGTCCCATTTTTTGCTTCCATAGTGCTATTTTCCCAACTACTGTTACCCTTAAGATTCCTGACTTCCCAGCCCCTTTATACCAAAAGCTTTCTTTGACATTTTTCTCTTTCCGTGCCTTCCTGCCTTTCCACTTACCCAGTACAAAGCCTGAAGATGCTTTCACAGAGAAGCCTTAAATTATCCCAGCATACTTTATTGCACCCACACCTTTTCACTTCAAAAACCTTTTTGTCACCCTTGTCTAATATTCATACCCTATTTTCTTCTATATTCTCAATTCATCTGCTCCATATATACTTGTTTTCTGTGGTATCATTTTCCCCACCTCCATTTCACTTAGATCCTATATTTTTTTACCCTATCTTACCCTTTTTGTTTGGTGCCTTCCTCCAAACCCAAGGTTTCTGTCTTTCATCAGTCATCCTTCCACCTTTCACTCTTAAACTCTGGTAATTCTGGTTTTCCTCCTTCTCAAAAAGCTCACACTCTGCTAATGTGTATATATTGTTCACTTGAGTGCTTCTAAATAAATATTTACTTTTCAAAACAGTGAAATCTGAACTATTAGCATGGAAACAACCTCTGGGAAGATAAGATCTCCACTCAAAAGCTTCAAATTGAGATTCTCCTGCTCATGTTGAATGATGGTTTTATCTAATATTTTCTGAAATAGGGTGACTACTTGAACTACACAAAATTGTGAAATGAGAATATCTTTGATTTTATACTTCTATTTTTTTTTTTTTTTTTGAGACAGAGTCTCACTCTATCACCCAGGCTGGAGTGCAGTGGCAGTCTTGGCTCATTGCACCCTCCACCTCCCAGGTTCAGGTGATTCTCGTCCCTTGGCCTCCCAAGTAGCTGGGATTATAGGCATGTGCCACCACACCCGGCTAATTTTTGTAGTTTTTGGTAGAGATGGGGTTTCACCATGTTGGCCAGGCTGGTCTTGAACTCCTGACCTCAAGTGATCCACCCACCTCAGCCTCCCAAAGTGTTGGGATTACAGGCGTGAGCCACTGTGCCTGGCCACTTACATCTATTTTGATTGACTTGAAATAAAATTTAACACCTCAGGGAAGGCAATTCTCATGTGTTTTGAATTATACTGAGCATTAATTCTTCAGGATAATTATAGACTTGGAAAGGTTTAACCCAGTCTCCCAGTCCATGCTGAAGTTCCTTTAAGTGATAGGAGGAACTCATAATCTACAAGGCAACCCAATCCATTTGGTGCTACCATCGATTGTTATAAAGCCCATCCTTGGGTTAAAATCTACTATTTACAGTTGTATTTAATGACCTTAATTCTGCCCTCAAGCTATATAAAATTTGGATCTGTTTTCTACATGATAATCTTTTAGATATCTTAAGGTAGTTAGTCTATCCTCTCTACCCTTCCCCTCACAGTTTTTCCACCCTTTGAGATAAATATCCTTCGCTATTCCAACTATTTCTCATATGGTATCATTTTTATCATCCCGATTGCTCCCTAAGGATGTTAAACTTTGTTAATGTCCCTTCCAAAATGTATTTGGAACTGGAAATAATATCCCTTGGTAGCTGAATTGGATCTGGATGTTGCACATCTGGACACTAATGCAGTCTGAAGTTGCTGTAAGTTTTTTAGTCGACTTGTAATGTTGGCTTATGATGAATTTGTAATTAAATAAAATCCCAAGGTTTTAATCTGGAGGATTGCCTTTAAGTGATTTCTTCTTAAACTAAGTCTCAATCTTCTTTTAGTTATGCAACAGATTTTTTTTGTTTGTTTTTTGAGACGCTCGCTCTGTCGCCCAGGCTGGGGTGCAGTGGCACGATCTCAGCTCACTGCAACCTCCACTTCCTGGGTTCAAGCAATTCTCCTGCCTCAGCCTCCCAAGTAGCTGGGATTACAGGCATCCGCCATCATGCCTGGCTAATTTTCTTTCTTTCTTTTTTATTTTTTTTTAGTAGAGACGGGGTTTCTCCATTTTGGTCAGGCTGGTCTCGAACTCCTGACCTCAGGTGACCCACCCTCCTCAGCCTCCCAGAGTGCTGGGATTACAGGCGTGAGCCATCACGCCCGGCCTTTTTTGAGATGGAGCCTCGCTCTGTCGCCCAGGATGGAGTGCAGTGGCATGATCTTGGCTCACTGCAACCTCCGCTCCCCGGGTTCAAGGCATTCTTCTGTTTCAGCCTTCCGAGTAGCTGGGATTACAGGTACCTGCCACCACGCCTGGCTAATTTTTGTATTTTTAGTAGAGGTGGGGGTTTCACCATGTTGGTCAGGCTGGTCTCGAACTCCTGACCTCAAGTTATCCGGCCACCTTGGCCTCCCAAAGTGCTGAGATTACAGGCATGAGTCACCGTGTCCGGCCTATGCACCAGATATTTTTTAAAAACCAGATGTAAGACTTTATACTTATCCCTATTAAATTTTATCTCATTAGCCTATCAGGTAGCCTTGGTTTTTTTCTTTTCTTTTCTTTTCTTTTTTTTTTTTTTTTTGAGACAGAGTTTCACTCTTGTTGCCCAGGCTGGAGTGCAGTGGCGCGATCTCAGCTCACTGCAACCTCTGCCTCCCGGGTTCAAGCGATTCTCCTGCCTCAGTCTCCCAAGTAGCTGGGATTACAGGCATGCTCCACCACGCCCAGCTAATTTTGTGTTTTTAGTAGAGACAGGGTTTCTCCCTGTTGGTCAGGCCGGTCTCAAACTCCCGACCTCAGGTGATTTGCCCACCTCGGCCTCCCAAAGTGCTGGGATTACAGGTGTGAACCACCATGCCCGGCTGTTTTTTTTAAGACTAGTCAAGTGCAGAGTGAGAAGGGGGGAAAGAGTAGAACAAGGAGTTTGATCAGCCTTGGTTTCTTTGAATCTTGATTTTTGTCATCCAGTTTATTGTGCTGATTCAACAAAGGGCCTTGAAGCTAATGTTGGAATGTTTTCAGACATATAGGAAATGATAATTCATCAAAAGTCATGGAGACTATATTCCAAAAGTTTTATGCAGATATAACTCAGCTGTTGAGGTATATGAGTTAATACCACTATAAATTGACATGGCCAGGAAAGACTGAAGTCCATTGCCAGCTTGCTTTGTGTTGAACATTACTCCAAAAGAGATTAAATTTTAAGGCATATTGTGTCAACATAAAGGCAAAAGAGCTGGCTAATTCTTCTCAAGAAATCAATTAATGGCAGGGCGCGGTGGCTCACGCCTGTAATCCCAGCATTTTGGAAGGCCGAGGCGGGCAGATCACCTGAGGTCAGGAGTTCAAGACCAGCCTGACCAACCTGGAGAAACCCCGTCTCTACTAAAAAATACAAAATTAGCCGGGCATGGTGGCGCATGCCTGTAATCCCAGCTACTTGAGAGGCTGAGGCAGGATAATTGCTTGAACCTGGGAGGCGGAGGTCGCATGAACCAGTATCACACCATTGCACTCCAGCCTGGGCAGCAAGAGCAAAACTCCATCTCAAAAAAAAAAAAAATCAATTAATGCACGCATAATATAGAGACAGAGTCATTGTTACCATTCTCTTATTTTGCCTTTGACAAGTTTATATTGAGCATGTTATCAGGCAATGTGGGAGATTCTGGAGAACCAGGTTTGCCTCATAACTAGGGTTACCATATACTCTAGTTTGCCTGGGGCAACCCTGATTTATGCCTGTTGTCCCAGTGTGATTATTACTAGTGTAATTTTTCACTTTGAGAAGTGTCCAGGTTTGGAGGATAAATTATCTTTCTAATAATTGATACCCTTCTCATAACCTAACGGGTTCCTTTTAGTATTTTATCTGGGTTAAAATTACCAGCTGTAATTTGGCAGCTCTAATAAGACTGCAGCAATACTTATCTTCCATTTGAACAGATTGTTACTTGACCAAGGGAAGTTAATAGCAAAAGTAACTGCAGGGCACATGTATGTCATGGGCAAAAAAAAAAAAGTAACAGCAATTAAGGTTTGCAGGTACTTAGAATTTTTCCTGAGCCACCCTCTAGAGGGCAGTGTTACATATATATCTGTAATTATCCAGTTACAACAAAAAAAGGGCTCTCATTCATGCATGAAAATCAGAAATATTTCATACTCTTAAAGAACACATTGGAACCAATATTATGATTAAAACATATTTTGCTAAGCAAAGAGATATTAAAAATTAATTCATTAACATTCTGAACATTTTTTAACTTGTAAAAACAACTTTGATGCCTTGAATATATAATGATTCATTATAACAATTATGCATAGATTTTAATAATCTGCATATTTTATGCTTTCATGTTTTTCCTAATTAATGATTTGACATGGTTAATAATTATAATATATTCTGCATCACAGTTTACATATTTATGTAAAATAAGCATTTAAAAATTATTAGTTTTATTCTGCCTGCTTAAATATTACTTTCCTCAAAAAGAGAAAACAAAAATGCTAGATTTTACTTTATGACTTGAATGATGTGGTAATGTCGAACTCTAGTATTTAGAATTAGAATGTTTCTTAGCGGTCGTGTAGTTATTTTTATGTCATAAGTGGATAATTTGTTAGCTCCTATAACAAAAGTCTGTTGCTTGTGTTTCACATTTTGGATTTCCTAATATAATGTTCTCTTTTTAGAAAAGGTGGACAAGTCCTATTTTCAAGAGAAGATGACTTTTAACAGTTTTGAAGGATCTAAAACTTGTGTACCTGCAGACATCAATAAGGAAGAAGAATTTGTAGAAGAGTTTAATAGATTAAAAACTTTTGCTAATTTTCCAAGTGGTAGTCCTGTTTCAGCATCAACACTGGCACGAGCAGGGTTTCTTTATACTGGTGAAGGAGATACCGTGCGGTGCTTTAGTTGTCATGCAGCTGTAGATAGATGGCAATATGGAGACTCAGCAGTTGGAAGACACAGGAAAGTATCCCCAAATTGCAGATTTATCAACGGCTTTTATCTTGAAAATAGTGCCACGCAGTCTACAAATTCTGGTATCCAGAATGGTCAGTACAAAGTTGAAAACTATCTGGGAAGCAGAGATCATTTTGCCTTAGACAGGCCATCTGAGACACATGCAGACTATCTTTTGAGAACTGGGCAGGTTGTAGATATATCAGACACCATATACCCGAGGAACCCTGCCATGTATAGTGAAGAAGCTAGATTAAAGTCCTTTCAGAACTGGCCAGACTATGCTCACCTAACCCCAAGAGAGTTAGCAAGTGCTGGACTCTACTACACAGGTATTGGTGACCAAGTGCAGTGCTTTTGTTGTGGTGGAAAACTGAAAAATTGGGAACCTTGTGATCGTGCCTGGTCAGAACACAGGCGACACTTTCCTAATTGCTTCTTTGTTTTGGGCCGGAATCTTAATATTCGAAGTGAATCTGATGCTGTGAGTTCTGATAGGAATTTCCCAAATTCAACAAATCTTCCAAGAAATCCATCCATGGCAGATTATGAAGCACGGATCTTTACTTTTGGGACATGGATATACTCAGTTAACAAGGAGCAGCTTGCAAGAGCTGGATTTTATGCTTTAGGTAAACTTTATTATAAAACCAATAAATAGCTTCCCAAGTATGCCAGGGCTCATAAAAAGTAAATAGATGCCCTTAGCCCCCTGAACTGGTAAATATTTAGGTATAACTTGGCATGATTATATATATATCTGTATTATTCCGTGAACTCTTATGTTGAACCTGTAATGTAACTACTGAATTTATGTGAAAAAGACTACCATATTATGAGTCATGCTTCTCTTCATGTAATTGTTTTTAGGAAGTAGATAACTTGCAAAAGATGGTAGACATCCCCAATAGCAAAATGGGTCTAATAGTAATATTAACCATCATTTATTGAGCACTTACTATAAGTGCTCAATACATATACTTCATGCATTTTCTCTAAGCTTCACAATAGCTTTGTTTGTTTGTTTTTGAGACAGAGTTTCGCTCTTGTTATCCAGGCTGGAGTGCAATGGCGTGATTTAGGCTCACCACAACCTCCACCTCCCGGGTTCAAGCGATTCTCCTGCCTCAGCCTCCTGAGTAGCTGGGATTACAGGCATGTGCCACCACGCCCGGCTAATTTTGTATTTTTAGTAGACACAGGGTCTCTCCCTGTTGGTCAGGCTGGTCTCAAACTCCTGACCTCAGGTGATCCACCCGCCTCGGCCTCCCAAAGTGCTGGGATTACAGGTGCATGCACCATGCCTGGCTAATTTTTGTACTTTTAGTAGAGACAGGGTTTCACCATGGCCAGGCTGGTCTCGAACTCCTGACCTTGTGATCCGCCCGCCTTGGCCTCCCAAAGTGCTGGGATTACAGGCATGAGCCACTGCGCCGGCCATATGAGTACTTTCAAATGGACTGTGGTAGACATTTCAGGAAGGGCCATTGGAGTGATTGCTTCTAAAGATATTTTAAAAAGTTATACCATTATATATTTGACCCATTTATTTTAAGATTGAATAATGCCTATAAAATATTGGTTATTTCGAAAGATTTTATTTATGTACCATCATATAGTAATCTTGAAGGTTTGTTTAGTGTCATGTAGCTATAAACTTAGAGAAACTTACAATTTCATTATGTAGAACTTTAATGTTACTAATACTTGAAACATAACTTGTTTTAAAATTTCACAGTTTGAAACAGTAAGGACAATATTGGTGGCCCAAATAACATACTAAAAAGAAAGTATGGCCGGGCGCGGTGGCTCCCGCCTATAATCCCAGCACTTTGGGAGGCTGAGGTGGGTGGATCACCTGAAGTCAGGAGTTCAAGACCAGCCTGGCCAACATGGTGAAACCCCGTCTCTACTAAAAATACAAAAATTAGCTGGGCGTGATGGCATGCGCCTGTAGTCCCAGCTACTTGGGAGACTGAGGCAGGAGAATCACTTGAACCCAGAAGGCAGAGGTTGCAGTGAGCCGTGATCGCGCCATTGCACTCCAGCCTGGGCAACAAGAGTA',
                                         'alt': 'T',
                                         'gene': 'XIAP',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | X-linked lymphoproliferative disease '
                                                 'due to XIAP deficiency'}],
    'gwas_lead_snps': [   {   'rsid': 'rs7517847',
                              'chrom': 'chr1',
                              'pos': 67214960,
                              'beta': 0.15,
                              'or_value': 1.16,
                              'eaf_eur': 0.43,
                              'eaf_eas': 0.3,
                              'gene': 'IL23R',
                              'effect_allele': 'G',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.3,
                              'confidence': 'high',
                              'note': 'IL23R — CD GWAS lead SNP'},
                          {   'rsid': 'rs6596075',
                              'chrom': 'chr5',
                              'pos': 131797025,
                              'beta': 0.12,
                              'or_value': 1.13,
                              'eaf_eur': 0.28,
                              'eaf_eas': 0.35,
                              'gene': 'IRF1',
                              'effect_allele': 'C',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': 'IRF1/IL3/CSF2(5q31) — CD GWAS'},
                          {   'rsid': 'rs10761659',
                              'chrom': 'chr10',
                              'pos': 63942042,
                              'beta': 0.12,
                              'or_value': 1.12,
                              'eaf_eur': 0.48,
                              'eaf_eas': 0.6,
                              'gene': 'ZNF365',
                              'effect_allele': 'T',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': 'ZNF365(10q21) — CD GWAS'},
                          {   'rsid': 'rs17234657',
                              'chrom': 'chr5',
                              'pos': 131747827,
                              'beta': 0.12,
                              'or_value': 1.12,
                              'eaf_eur': 0.3,
                              'eaf_eas': 0.1,
                              'gene': 'PTGER4',
                              'effect_allele': 'G',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': 'PTGER4(5p13) — CD GWAS'},
                          {   'rsid': 'rs3197999',
                              'chrom': 'chr3',
                              'pos': 49697751,
                              'beta': 0.12,
                              'or_value': 1.12,
                              'eaf_eur': 0.28,
                              'eaf_eas': 0.2,
                              'gene': 'MST1',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': 'MST1(3p21) — CD GWAS'},
                          {   'rsid': 'rs6017342',
                              'chrom': 'chr20',
                              'pos': 63822763,
                              'beta': 0.12,
                              'or_value': 1.12,
                              'eaf_eur': 0.43,
                              'eaf_eas': 0.5,
                              'gene': 'HNF4A',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.18,
                              'confidence': 'high',
                              'note': 'HNF4A(20q13) — UC GWAS lead SNP'},
                          {   'rsid': 'rs9264942',
                              'chrom': 'chr6',
                              'pos': 31324036,
                              'beta': 0.12,
                              'or_value': 1.13,
                              'eaf_eur': 0.35,
                              'eaf_eas': 0.25,
                              'gene': 'HLA-C',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': 'HLA-C(6p21 MHC) — UC GWAS'},
                          {   'rsid': 'rs6426833',
                              'chrom': 'chr1',
                              'pos': 241434112,
                              'beta': 0.1,
                              'or_value': 1.1,
                              'eaf_eur': 0.35,
                              'eaf_eas': 0.4,
                              'gene': 'RNF186',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.15,
                              'confidence': 'high',
                              'note': 'RNF186(1p36) — UC GWAS'},
                          {   'rsid': 'rs2476601',
                              'chrom': 'chr1',
                              'pos': 113834946,
                              'beta': None,
                              'or_value': 1.31,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'PTPN22',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.2,
                              'confidence': 'high',
                              'note': 'CD GWAS (Jostins 2012) — shared with RA/T1D'},
                          {   'rsid': 'rs9286879',
                              'chrom': 'chr1',
                              'pos': 25264334,
                              'beta': None,
                              'or_value': 1.12,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'RUNX3',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'CD GWAS (Liu 2015)'},
                          {   'rsid': 'rs7554511',
                              'chrom': 'chr1',
                              'pos': 200876534,
                              'beta': None,
                              'or_value': 1.14,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'C1orf106',
                              'effect_allele': 'C',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'CD GWAS (Jostins 2012)'},
                          {   'rsid': 'rs3024505',
                              'chrom': 'chr1',
                              'pos': 206769833,
                              'beta': None,
                              'or_value': 1.19,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'IL10',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.18,
                              'confidence': 'high',
                              'note': 'UC GWAS (Franke 2010/Jostins 2012)'},
                          {   'rsid': 'rs7608910',
                              'chrom': 'chr2',
                              'pos': 60881668,
                              'beta': None,
                              'or_value': 1.24,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'REL',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.19,
                              'confidence': 'high',
                              'note': 'UC GWAS (Jostins 2012)'},
                          {   'rsid': 'rs1728918',
                              'chrom': 'chr2',
                              'pos': 61012182,
                              'beta': None,
                              'or_value': 1.14,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'USP34',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'UC GWAS (de Lange 2017)'},
                          {   'rsid': 'rs4409764',
                              'chrom': 'chr2',
                              'pos': 198910751,
                              'beta': None,
                              'or_value': 1.1,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'PLCL1',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'CD GWAS (Liu 2015)'},
                          {   'rsid': 'rs3774959',
                              'chrom': 'chr3',
                              'pos': 49585537,
                              'beta': None,
                              'or_value': 1.15,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'NFKBIZ',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'UC GWAS (de Lange 2017)'},
                          {   'rsid': 'rs17293632',
                              'chrom': 'chr4',
                              'pos': 48666978,
                              'beta': None,
                              'or_value': 1.1,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'CNOT6L',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'IBD GWAS (Liu 2015)'},
                          {   'rsid': 'rs12521868',
                              'chrom': 'chr5',
                              'pos': 72667710,
                              'beta': None,
                              'or_value': 1.09,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'FOXD1',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'UC GWAS (de Lange 2017)'},
                          {   'rsid': 'rs12663356',
                              'chrom': 'chr6',
                              'pos': 111580766,
                              'beta': None,
                              'or_value': 1.18,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'TRAF3IP2',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.18,
                              'confidence': 'high',
                              'note': 'CD GWAS (Jostins 2012)'},
                          {   'rsid': 'rs10758669',
                              'chrom': 'chr9',
                              'pos': 54520448,
                              'beta': None,
                              'or_value': 1.14,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'JAK2',
                              'effect_allele': 'C',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'CD GWAS (Barrett 2008)'},
                          {   'rsid': 'rs561722',
                              'chrom': 'chr9',
                              'pos': 136420157,
                              'beta': None,
                              'or_value': 1.13,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'NOTCH1',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'UC GWAS (de Lange 2017)'},
                          {   'rsid': 'rs11190140',
                              'chrom': 'chr10',
                              'pos': 100197946,
                              'beta': None,
                              'or_value': 1.22,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'NKX2-3',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.18,
                              'confidence': 'high',
                              'note': 'CD GWAS (Wellcome Trust 2007)'},
                          {   'rsid': 'rs670523',
                              'chrom': 'chr14',
                              'pos': 50751850,
                              'beta': None,
                              'or_value': 1.11,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'RPL10A',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'UC GWAS (de Lange 2017)'},
                          {   'rsid': 'rs16940202',
                              'chrom': 'chr15',
                              'pos': 65269857,
                              'beta': None,
                              'or_value': 1.14,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'HAVCR2',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'IBD GWAS (de Lange 2017)'},
                          {   'rsid': 'rs12942547',
                              'chrom': 'chr17',
                              'pos': 39925250,
                              'beta': None,
                              'or_value': 1.12,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'STAT3',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'CD GWAS (Jostins 2012)'},
                          {   'rsid': 'rs254560',
                              'chrom': 'chr17',
                              'pos': 65928693,
                              'beta': None,
                              'or_value': 1.1,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'SLC16A3',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'CD GWAS (de Lange 2017)'},
                          {   'rsid': 'rs12972620',
                              'chrom': 'chr18',
                              'pos': 69850737,
                              'beta': None,
                              'or_value': 1.11,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'CD226',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'UC GWAS (de Lange 2017)'},
                          {   'rsid': 'rs516246',
                              'chrom': 'chr19',
                              'pos': 48720658,
                              'beta': None,
                              'or_value': 1.13,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'FUT2',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'CD GWAS (McGovern 2010)'},
                          {   'rsid': 'rs4809330',
                              'chrom': 'chr20',
                              'pos': 63695511,
                              'beta': None,
                              'or_value': 1.1,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'RTEL1',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'UC GWAS (de Lange 2017)'},
                          {   'rsid': 'rs2836878',
                              'chrom': 'chr21',
                              'pos': 39082278,
                              'beta': None,
                              'or_value': 1.18,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'PSMG1',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.18,
                              'confidence': 'high',
                              'note': 'CD GWAS (Jostins 2012)'},
                          {   'rsid': 'rs2413583',
                              'chrom': 'chr22',
                              'pos': 21553717,
                              'beta': None,
                              'or_value': 1.15,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'MAPK1',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'UC GWAS (de Lange 2017)'}],
    'regions': [   {   'chrom': 'chr16',
                       'start': 50722917,
                       'end': 50766507,
                       'gene': 'NOD2',
                       'rtype': 'coding',
                       'source': 'clinical',
                       'note': 'NOD2基因区域 — CD核心风险基因'}],
    'regulatory_regions': [],
    'prs_variants_high': [],
    'prs_variants': [],
    'key_literature': [   {   'pmid': '28067908',
                              'title': 'Genome-wide association study implicates immune activation of multiple '
                                       'integrin genes in inflammatory bowel disease',
                              'note': 'de Lange et al. 2017 Nat Genet; IBD GWAS ~60K cases; 25 new loci'},
                          {   'pmid': '26192919',
                              'title': 'Association analyses identify 38 susceptibility loci for inflammatory bowel '
                                       'disease and highlight shared genetic risk across populations',
                              'note': 'Liu et al. 2015 Nat Genet; 跨种族IBD GWAS; 38 new loci'},
                          {   'pmid': '23128233',
                              'title': 'Host-microbe interactions have shaped the genetic architecture of inflammatory '
                                       'bowel disease',
                              'note': 'Jostins et al. 2012 Nature; IBD GWAS meta ~75K; 163 loci'}]}
