"""Disease template: myelodysplastic syndromes (MDS) / 骨髓增生异常综合征."""

TEMPLATE_NAME = 'myelodysplastic syndromes'
TEMPLATE = {
    'aliases': [
        'myelodysplastic syndromes',
        'myelodysplastic syndrome',
        'mds',
        'myelodysplasia',
        'myelodysplastic neoplasm',
        '骨髓增生异常综合征',
        '骨髓增生异常综合症',
        '骨髓增生异常',
        'mds伴环状铁粒幼细胞',
        'mds伴多系发育异常',
        'mds伴原始细胞增多',
        'mds伴孤立del5q',
        'preleukemia',
        '白血病前期',
        'smoldering leukemia',
        '冒烟性白血病',
    ],
    'mode': 'mixed',
    'gene_set': [
        # ═══ Mendelian High (germline predisposition with high MDS/AML penetrance) ═══
        {
            'gene': 'GATA2',
            'tier': 'mendelian_high',
            'contribution_score': 1.0,
            'penetrance': '>0.90',
            'penetrance_score': 0.9,
            'evidence': 'familial',
            'note': 'GATA2缺乏综合征(MonoMAC/Emberger综合征,AD); 造血转录因子; 杂合LOF→MDS/AML(~70%终身风险); 典型表型:单核细胞减少/B细胞/NK细胞缺乏+分枝杆菌感染+淋巴水肿+肺泡蛋白沉积症; 儿童/青年发病',
            'phenotype_assoc': 'MonoMAC/Emberger(AD);GATA2-LOF→MDS/AML;单核细胞减少;免疫缺陷;淋巴水肿;造血干细胞衰竭',
            'key_domains': 'ZF1(aa295-318);ZF2(aa348-374):C4型锌指-DNA结合域;N端转录激活域;N端ZF介导FOG1互作',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'DDX41',
            'tier': 'mendelian_high',
            'contribution_score': 0.95,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.45,
            'evidence': 'familial',
            'note': '家族性MDS/AML最常见胚系易感基因(AD); DEAD-box RNA解旋酶; 胚系LOF(通常截短)+体细胞R525H热点突变→MDS/AML; 中老年发病(peak 60-70岁); 东亚人携带者频率较高; 2026 Nature Leukemia提示既往OR估计可能偏高→外显率下调; 需要终身血液学监测',
            'phenotype_assoc': '家族性MDS/AML(AD,晚期发病,低外显);胚系LOF+体细胞R525H→MDS;东亚携带者较多;OR可能被高估',
            'key_domains': 'DEAD-box RNA解旋酶域(aa151-350);Q基序;Walker A/B ATPase;R525热点突变位点(体细胞协同)',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'RUNX1',
            'tier': 'mendelian_high',
            'contribution_score': 0.95,
            'penetrance': '>0.80',
            'penetrance_score': 0.8,
            'evidence': 'familial',
            'note': '家族性血小板疾病伴AML倾向(FPD/AML或RUNX1-FPD,AD); 核心结合因子造血转录因子; 胚系LOF→血小板减少+血小板功能异常(~100%)+MDS/AML(~40%终身风险); 儿童/成年均可发病',
            'phenotype_assoc': 'FPD/AML(AD);血小板减少→MDS/AML(~40%);血小板颗粒缺乏;巨核细胞发育异常;CBF转录因子',
            'key_domains': 'Runt同源域(aa50-177):DNA结合+CBFβ异源二聚化;N端;转录激活域(aa290-370);VWRPY基序(TLE/Groucho结合)',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'CEBPA',
            'tier': 'mendelian_high',
            'contribution_score': 0.9,
            'penetrance': '>0.90',
            'penetrance_score': 0.9,
            'evidence': 'familial',
            'note': '家族性AML伴胚系CEBPA突变(AD); 髓系转录因子C/EBPα; 胚系N端LOF→AML(~100%终身风险,主要为AML非MDS); 典型双等位基因模式(胚系N端+体细胞C端); 青年AML(通常<40岁); MDS作为独立表型较少见,多为AML前驱或转化',
            'phenotype_assoc': '家族性AML-CEBPA(AD);胚系N端LOF+体细胞C端→AML;青年发病;正常核型AML预后良好亚组',
            'key_domains': 'TAD1(aa1-70);TAD2(aa71-97):转录激活域;bZIP域(aa278-358):碱性区(DBD)+亮氨酸拉链(二聚化)',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'ETV6',
            'tier': 'mendelian_high',
            'contribution_score': 0.9,
            'penetrance': '>0.70',
            'penetrance_score': 0.7,
            'evidence': 'familial',
            'note': '家族性血小板减少伴MDS/AML(AD); ETS转录因子; 胚系LOF→中度血小板减少+大红血小板+MDS/AML/ALL/B细胞ALL易感性; 儿童发病前可有长期血小板减少史',
            'phenotype_assoc': 'ETV6-FPD(AD);血小板减少→MDS/AML/ALL;大红血小板;ETS转录因子;儿童发病',
            'key_domains': 'PNT/HLH域(aa38-124):聚合/转录抑制;ETS DNA结合域(aa334-414):翼状螺旋-转角-螺旋',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'ERG',
            'tier': 'mendelian_mod',
            'contribution_score': 0.85,
            'penetrance': 'moderate',
            'penetrance_score': 0.55,
            'evidence': 'familial',
            'note': 'ERG单倍剂量不足综合征(AD,2024年新定义); ETS转录因子,与RUNX1/ETV6同家族; 胚系LOF(截短/错义)→先天性血小板减少+骨髓衰竭→MDS/AML(外显率待定,发现较晚); Blood 2024;144:1765首次报道家系; 造血干细胞自我更新关键调控因子',
            'phenotype_assoc': 'ERG-FPD(AD,2024定义);ETS转录因子;血小板减少→BMF→MDS/AML;RUNX1/ETV6同通路;HSC调控',
            'key_domains': 'PNT域(aa120-200):ETS家族N端尖域;ETS DNA结合域(aa290-370):翼状螺旋-转角-螺旋;GATA1/FOS互作域',
            'clingen_validity': 'Moderate',
        },
        {
            'gene': 'ANKRD26',
            'tier': 'mendelian_high',
            'contribution_score': 0.85,
            'penetrance': '>0.60',
            'penetrance_score': 0.6,
            'evidence': 'familial',
            'note': 'ANKRD26相关血小板减少症→MDS/AML(AD); 5\'UTR点突变(通常c.-128至c.-118区域)→ANKRD26表达失调→巨核细胞分化障碍; 中度血小板减少+正常血小板大小; MDS/AML风险~10-30%',
            'phenotype_assoc': 'ANKRD26-RT(AD);5\'UTR突变→血小板减少;MDS/AML~10-30%;巨核细胞发育;正常血小板大小',
            'key_domains': 'ANK重复域(N端);卷曲螺旋域(C端):信号通路支架;THAP1互作域',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'TP53',
            'tier': 'mendelian_high',
            'contribution_score': 0.8,
            'penetrance': '>0.80',
            'penetrance_score': 0.8,
            'evidence': 'familial',
            'note': 'Li-Fraumeni综合征(AD);TP53-LOF→广谱肿瘤易感(肉瘤/乳腺癌/脑瘤/肾上腺皮质癌)+MDS/AML(~5-10%); MDS/AML通常出现在治疗相关MDS(t-MDS)或作为第二肿瘤; 胚系TP53→MDS常伴复杂核型和不良预后',
            'phenotype_assoc': 'LFS(AD);多肿瘤→MDS/AML,t-MDS;复杂核型;不良预后;放化疗暴露后二次肿瘤风险高',
            'key_domains': 'TAD1(aa1-42);TAD2(aa43-63);PRD(脯氨酸富集域);DBD(aa102-292):核心DNA结合域(突变热点);四聚化域(aa323-356);C端调节域',
            'clingen_validity': 'Definitive',
        },

        # ═══ Mendelian Moderate (bone marrow failure → MDS progression) ═══
        {
            'gene': 'SAMD9',
            'tier': 'mendelian_mod',
            'contribution_score': 0.75,
            'penetrance': '>0.80',
            'penetrance_score': 0.8,
            'evidence': 'familial',
            'note': 'MIRAGE综合征(AD功能增强); SAMD9-GOF→骨髓衰竭+MDS/AML早发(通常<10岁); 生长受限+肾上腺发育不良+感染+肠病; 体细胞遗传挽救(monosomy 7/del7q/SAMD9回复突变)自发造血恢复; 需与SAMD9L共同评估',
            'phenotype_assoc': 'MIRAGE(AD-GOF);SAMD9→骨髓衰竭→儿童MDS;-7/del7q遗传挽救;肾上腺发育不良;germline+rescue双相',
            'key_domains': 'SAM域;N端Ala/Gly富集区;APAF1-样域(凋亡相关)',
            'clingen_validity': 'Strong',
        },
        {
            'gene': 'SAMD9L',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': '>0.70',
            'penetrance_score': 0.7,
            'evidence': 'familial',
            'note': '共济失调-全血细胞减少综合征(AD功能增强); SAMD9L-GOF→小脑萎缩+全血细胞减少+MDS/AML; 体细胞遗传挽救(monosomy 7→SAMD9L丢失→造血恢复→MDS风险降低); 儿童发病; 与SAMD9表型重叠',
            'phenotype_assoc': 'ATXPC(AD-GOF);共济失调+全血细胞减少→MDS;-7遗传挽救;SAM家族;与MIRAGE重叠',
            'key_domains': 'SAM域;Ala/Gly富集区;APAF1-样域',
            'clingen_validity': 'Strong',
        },
        {
            'gene': 'SRP72',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'high',
            'penetrance_score': 0.8,
            'evidence': 'familial',
            'note': '家族性骨髓再生障碍/MDS(AD); SRP72-LOF→信号识别颗粒组装缺陷→骨髓衰竭→MDS/AML; 先天性感音神经性耳聋+骨髓衰竭; 罕见(仅报道数个家系)',
            'phenotype_assoc': 'BMA/MDS(AD);SRP→蛋白靶向缺陷;骨髓衰竭→MDS;伴耳聋;极罕见(<10家系)',
            'key_domains': 'SRP72核心域;SRP68结合域;SRP RNA结合域;信号肽识别颗粒SRP成分',
            'clingen_validity': 'Moderate',
        },
        {
            'gene': 'TERT',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': 'moderate',
            'penetrance_score': 0.5,
            'evidence': 'familial',
            'note': '端粒病(AD/AR); TERT-LOF→端粒缩短→骨髓衰竭/再生障碍性贫血→MDS/AML(~10%); 肺纤维化+肝硬化+早白; 端粒极短(<1st百分位); 雄激素/造血干细胞移植治疗',
            'phenotype_assoc': '端粒病(AD/AR);端粒酶逆转录酶;骨髓衰竭→MDS/AML;肺纤维化;肝硬化;早白;DC/TBD谱系',
            'key_domains': 'TEN域(N端);TRBD(端粒酶RNA结合域);RT域(逆转录酶核心):手指/手掌/拇指亚域;CTE(C端延伸)',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'TERC',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.5,
            'evidence': 'familial',
            'note': '端粒病(AD); TERC-LOF→端粒酶RNA模板缺陷→端粒缩短→骨髓衰竭→MDS; 先天性角化不良症(DC)变异型; 表型变异大(一代轻→下一代重:遗传早现); 与TERT共同构成端粒维护缺陷',
            'phenotype_assoc': '端粒病/DC(AD);TERC-RNA模板→端粒缩短;遗传早现;骨髓衰竭→MDS;肺纤维化',
            'key_domains': 'CR4-CR5域;H/ACA域;假结域;端粒模板序列(CR1);CR7域(Dyskerin结合)',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'SBDS',
            'tier': 'mendelian_mod',
            'contribution_score': 0.7,
            'penetrance': '>0.90',
            'penetrance_score': 0.9,
            'evidence': 'familial',
            'note': 'Shwachman-Diamond综合征(AR); SBDS-LOF→60S核糖体亚基成熟缺陷→骨髓衰竭→MDS/AML(~30%至30岁); 胰腺外分泌功能不全+骨骼异常+中性粒细胞减少; 高MDS转化率; 7号/20号染色体异常常见',
            'phenotype_assoc': 'SDS(AR);核糖体病→中性粒细胞减少→MDS/AML~30%;胰腺功能不全;骨骼异常;7/20号异常',
            'key_domains': 'D1域(aa1-96):FYSH蛋白;D2域(aa97-170);D3域(aa171-250):EF-2 GTPase结合;核糖体60S组装',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'FANCA',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': '>0.90',
            'penetrance_score': 0.9,
            'evidence': 'familial',
            'note': 'Fanconi贫血A型(AR,~60-70%FA病例); DNA链间交联(ICL)修复缺陷→骨髓衰竭→MDS/AML(~50%至40岁); 身材矮小+桡骨异常+皮肤色素沉着+实体瘤风险; FA通路核心基因',
            'phenotype_assoc': 'FA-A(AR);ICL修复→骨髓衰竭→MDS/AML~50%;发育异常;实体瘤;DEB/MMC染色体断裂试验',
            'key_domains': 'FANCG互作域(aa1-700);FANCF结合域;FANCE结合域;FANCD2/FANCI单泛素化上游(FA核心复合体)',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'BRCA2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': '>0.90',
            'penetrance_score': 0.9,
            'evidence': 'familial',
            'note': 'Fanconi贫血D1型(AR/FANCD1); BRCA2双等位基因LOF→先天性骨髓衰竭→AML/髓系肿瘤(极高外显,通常<5岁); 杂合→遗传性乳腺癌/卵巢癌(HBOC,AD); Wilms瘤/脑瘤(MEDULLOBLASTOMA)风险',
            'phenotype_assoc': 'FA-D1/HBOC;BRCA2双等位→极早发髓系肿瘤<5岁;杂合→乳腺癌/卵巢癌/Wilms/脑瘤',
            'key_domains': 'BRC重复×8(RAD51结合);DBD(ssDNA/dsDNA结合);TR2(C端);NLS;OB-fold(C端1109-3418)',
            'clingen_validity': 'Definitive',
        },

        # Additional BMF → MDS genes
        {
            'gene': 'ELANE',
            'tier': 'mendelian_mod',
            'contribution_score': 0.6,
            'penetrance': '>0.90',
            'penetrance_score': 0.9,
            'evidence': 'familial',
            'note': '严重先天性中性粒细胞减少症1型(SCN1,AD); ELANE-LOF→中性粒细胞弹性蛋白酶错误折叠→UPR/凋亡→成熟中性粒细胞缺乏(~ANC<0.2×10⁹/L); MDS/AML转化~15-20%; G-CSF治疗可改善中性粒细胞但增加MDS风险; 儿童期严重感染',
            'phenotype_assoc': 'SCN1(AD);ELANE→中性粒细胞凋亡→严重中性粒细胞减少→MDS/AML~15-20%;G-CSF治疗',
            'key_domains': '信号肽(aa1-29);前体域(aa30-41);成熟弹性蛋白酶催化域(aa42-267):Ser-His-Asp催化三联体',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'RPS19',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': '>0.90',
            'penetrance_score': 0.9,
            'evidence': 'familial',
            'note': 'Diamond-Blackfan贫血1型(DBA1,AD,~25%病例); RPS19-LOF→40S核糖体小亚基组装缺陷→选择性红系前体凋亡→先天性纯红再障; MDS/AML~5-10%(至40岁); 身材矮小+拇指畸形; 类固醇/输血/HSCT治疗; 代表性核糖体病基因',
            'phenotype_assoc': 'DBA1(AD);核糖体病→纯红再障;MDS/AML~5-10%;身材矮小;拇指畸形;类固醇治疗;40S亚基缺陷',
            'key_domains': 'S19e核糖体蛋白;40S小亚基口部定位;18S rRNA结合域(helix 31/41);RPS19-RPS16互作',
            'clingen_validity': 'Definitive',
        },

        # ═══ Strong GWAS / moderate predisposition ═══
        {
            'gene': 'NF1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': '>0.95',
            'penetrance_score': 0.95,
            'evidence': 'familial',
            'note': '神经纤维瘤病1型(AD); NF1-LOF→RAS信号失控→NF1表型+JMML/MDS/MPN风险增高; 幼年型粒-单核细胞白血病(JMML)风险~200-500倍; 儿童MDS/JMML应排除NF1',
            'phenotype_assoc': 'NF1(AD);RAS-GAP→JMML/MDS;café-au-lait斑;神经纤维瘤;视神经胶质瘤;儿童髓系肿瘤风险',
            'key_domains': 'GRD(GAP相关域,aa1198-1530):RAS GAP活性;SEC14-PH域;CRAL-TRIO域;C端',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'ATM',
            'tier': 'mendelian_mod',
            'contribution_score': 0.45,
            'penetrance': '>0.90',
            'penetrance_score': 0.9,
            'evidence': 'familial',
            'note': '共济失调毛细血管扩张症(AR); ATM-LOF(杂合~1%人群携带)→DNA损伤修复缺陷→淋巴细胞肿瘤+MDS/AML风险~2-3倍; 杂合携带者癌症风险中度增加; 放射敏感性',
            'phenotype_assoc': 'AT(AR);DNA修复→MDS/AML风险2-3x;杂合携带~1%人群;小脑萎缩;免疫缺陷;放射敏感',
            'key_domains': 'FAT域;PI3K样催化域(aa2712-2962):PIKK超家族;FATC域;N端HEAT重复',
            'clingen_validity': 'Definitive',
        },

        # ═══ GWAS / Common variants ═══
        {
            'gene': 'TET2',
            'tier': 'gwas',
            'contribution_score': 0.2,
            'penetrance': 'very_low',
            'penetrance_score': 0.02,
            'evidence': 'gwas',
            'note': 'TET2是MDS最常见的体细胞突变基因(~20-30%MDS); 胚系TET2内含子变异(rs1548483等)与不确定潜能克隆造血(CHIP)风险关联→CH→MDS/AML转化; TET2-LOF→5hmC丢失→表观遗传失调',
            'phenotype_assoc': 'TET2;CHIP GWAS;MDS体细胞突变热点;5hmC羟甲基化;表观遗传;CH→MDS通路',
            'key_domains': 'CXXC锌指域(非甲基化CpG结合);Cys-rich域(DSBH折叠);CD域(催化域,Fe2+/αKG依赖双加氧酶)',
            'clingen_validity': '',
        },
        {
            'gene': 'DNMT3A',
            'tier': 'gwas',
            'contribution_score': 0.18,
            'penetrance': 'very_low',
            'penetrance_score': 0.02,
            'evidence': 'gwas',
            'note': 'DNMT3A是CHIP/MDS/AML常见突变基因; DNMT3A R882热点是AML最常见体细胞突变; 胚系DNMT3A变异与CHIP风险和MDS易感相关; 表观遗传调控核心酶',
            'phenotype_assoc': 'DNMT3A;CHIP GWAS;R882→AML;CH→MDS;DNA甲基化;Tatton-Brown-Rahman(AD-过度生长)',
            'key_domains': 'PWWP域;ADD域(ATRX-DNMT3-DNMT3L);MTase催化域(甲基转移酶)',
            'clingen_validity': '',
        },
        {
            'gene': 'ASXL1',
            'tier': 'gwas',
            'contribution_score': 0.18,
            'penetrance': 'very_low',
            'penetrance_score': 0.02,
            'evidence': 'gwas',
            'note': 'ASXL1体细胞突变~15-20%MDS(CHIP-MDS-AML轴), 常与不良预后相关; 胚系ASXL1变异→Bohring-Opitz综合征(AD); 少数BOS患者进展为MDS; 染色质修饰PR-DUB复合体',
            'phenotype_assoc': 'ASXL1;Bohring-Opitz(AD)→MDS;CHIP→MDS;表观遗传;PR-DUB去泛素化复合体',
            'key_domains': 'ASXN域(N端);ASXH域;PHD域(植物同源域);DEUBAD域(去泛素化适配子);ω-loop(BAP1结合)',
            'clingen_validity': '',
        },
        {
            'gene': 'SF3B1',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.02,
            'evidence': 'gwas',
            'note': 'SF3B1是最常见的MDS剪接体突变(~20-30%MDS); K700E热点→MDS-RS(环状铁粒幼细胞)亚型; 胚系SF3B1变异→RARS/骨髓衰竭罕见; 预后相对良好亚组',
            'phenotype_assoc': 'SF3B1;MDS-RS剪接体热点(K700E);环状铁粒幼细胞;RNA剪接因子;预后良好MDS亚组',
            'key_domains': 'HEAT重复(N端);PPIase-like域;U2 snRNP结合域;C端Pro-rich',
            'clingen_validity': '',
        },
    ],
    'known_pathogenic_variants': [
        # GATA2 — MonoMAC/Emberger
        {
            'rsid': 'rs587776533',
            'chrom': 'chr3',
            'pos': 128202893,
            'ref': 'C',
            'alt': 'T',
            'gene': 'GATA2',
            'effect_allele': 'T',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 1.0,
            'confidence': 'high',
            'note': 'GATA2 c.1061C>T (Thr354Met) — ZF2域; 最常见MonoMAC致病变异; ClinVar Pathogenic ★★★',
        },
        {
            'rsid': 'rs121913307',
            'chrom': 'chr3',
            'pos': 128202972,
            'ref': 'C',
            'alt': 'T',
            'gene': 'GATA2',
            'effect_allele': 'T',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 1.0,
            'confidence': 'high',
            'note': 'GATA2 c.988C>T (Arg330Ter) — N端ZF域; 无义突变→GATA2缺乏; ClinVar Pathogenic',
        },
        # DDX41 — Familial MDS/AML
        {
            'rsid': 'rs371992544',
            'chrom': 'chr5',
            'pos': 177511267,
            'ref': 'C',
            'alt': 'T',
            'gene': 'DDX41',
            'effect_allele': 'T',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.95,
            'confidence': 'high',
            'note': 'DDX41 R525H (体细胞热点,非胚系); 胚系LOF(截短)+体细胞R525H协同→MDS/AML',
        },
        # RUNX1 — FPD/AML
        {
            'rsid': 'rs121912524',
            'chrom': 'chr21',
            'pos': 34792462,
            'ref': 'C',
            'alt': 'T',
            'gene': 'RUNX1',
            'effect_allele': 'T',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.95,
            'confidence': 'high',
            'note': 'RUNX1 c.592G>A (Arg174Gln) — Runt域DBD; FPD/AML家族常见致病变异; ClinVar Pathogenic',
        },
        # TP53 — Li-Fraumeni
        {
            'rsid': 'rs28934576',
            'chrom': 'chr17',
            'pos': 7675088,
            'ref': 'C',
            'alt': 'T',
            'gene': 'TP53',
            'effect_allele': 'T',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.8,
            'confidence': 'high',
            'note': 'TP53 R273H — DBD热点; LFS经典致病变异; ClinVar Pathogenic ★★★',
        },
        # SBDS — Shwachman-Diamond
        {
            'rsid': 'rs113993993',
            'chrom': 'chr7',
            'pos': 66986690,
            'ref': 'TA',
            'alt': 'T',
            'gene': 'SBDS',
            'effect_allele': 'T',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.7,
            'confidence': 'high',
            'note': 'SBDS c.258+2T>C — 最常见SDS致病变异(~70-90%等位基因); 剪接受体位点; 与c.183_184TA>CT构成复合杂合→SDS',
        },
    ],
    'gwas_lead_snps': [
        # CHIP → MDS susceptibility GWAS
        {
            'rsid': 'rs1548483',
            'chrom': 'chr4',
            'pos': 105202134,
            'beta': None,
            'or_value': 1.2,
            'eaf_eur': 0.35,
            'eaf_eas': 0.30,
            'gene': 'TET2',
            'effect_allele': 'C',
            'other_allele': 'A',
            'variant_class': 'gwas_lead',
            'contribution_score': 0.2,
            'confidence': 'moderate',
            'note': 'TET2内含子 — CHIP GWAS (Bick et al. 2020 Nature; Jaiswal et al. 2025 Nat Genet); TET2-LOF→CHIP→MDS/AML通路; ref=A(GRCh38验证)',
        },
        {
            'rsid': 'rs144418068',
            'chrom': 'chr2',
            'pos': 25234374,
            'beta': None,
            'or_value': 1.15,
            'eaf_eur': 0.02,
            'eaf_eas': 0.01,
            'gene': 'DNMT3A',
            'effect_allele': 'A',
            'other_allele': 'G',
            'variant_class': 'gwas_lead',
            'contribution_score': 0.18,
            'confidence': 'moderate',
            'note': 'DNMT3A — CHIP/MDS GWAS; 罕见变异→CHIP→MDS风险',
        },
        {
            'rsid': 'rs2467854',
            'chrom': 'chr20',
            'pos': 32430850,
            'beta': None,
            'or_value': 1.12,
            'eaf_eur': 0.25,
            'eaf_eas': 0.40,
            'gene': 'ASXL1',
            'effect_allele': 'G',
            'other_allele': 'A',
            'variant_class': 'gwas_lead',
            'contribution_score': 0.15,
            'confidence': 'low',
            'note': 'ASXL1 — CHIP GWAS (Zink et al. 2017 Blood); CHIP风险遗传变异',
        },
    ],
    'regions': [
        {
            'chrom': 'chr3',
            'start': 128202000,
            'end': 128205000,
            'gene': 'GATA2',
            'rtype': 'coding',
            'source': 'clinical',
            'note': 'GATA2基因区域 — MonoMAC/Emberger核心基因',
        },
        {
            'chrom': 'chr5',
            'start': 177508000,
            'end': 177514000,
            'gene': 'DDX41',
            'rtype': 'coding',
            'source': 'clinical',
            'note': 'DDX41基因区域 — 最常见家族性MDS/AML胚系基因; R525体细胞热点',
        },
        {
            'chrom': 'chr21',
            'start': 34791500,
            'end': 34793500,
            'gene': 'RUNX1',
            'rtype': 'coding',
            'source': 'clinical',
            'note': 'RUNX1基因区域 — FPD/AML; 血小板减少+髓系肿瘤',
        },
        {
            'chrom': 'chr19',
            'start': 33290000,
            'end': 33303000,
            'gene': 'CEBPA',
            'rtype': 'coding',
            'source': 'clinical',
            'note': 'CEBPA基因区域 — 家族性AML; 胚系N端+体细胞C端双等位基因模式',
        },
    ],
    'regulatory_regions': [],
    'prs_variants_high': [],
    'prs_variants': [],
    'key_literature': [
        {
            'pmid': '38976897',
            'title': 'Germ line ERG haploinsufficiency defines a new syndrome with cytopenia and hematologic malignancy predisposition',
            'note': 'Zerella et al. 2024 Blood; 新发现ERG胚系LOF→血小板减少+BMF+MDS/AML; ETS转录因子',
        },
        {
            'pmid': '32199092',
            'title': 'Germline predisposition to myeloid neoplasms: Clinical evaluation, surveillance and management',
            'note': 'Tawana et al. 2020 Blood; 髓系肿瘤胚系易感临床共识; 家族史采集/基因检测/监测建议',
        },
        {
            'pmid': '32693409',
            'title': 'Inherited predisposition to myelodysplastic syndrome and acute myeloid leukemia',
            'note': 'Kennedy & Ebert 2017 Nat Rev Cancer; MDS/AML胚系易感基因综述; DDX41/GATA2/RUNX1/CEBPA',
        },
        {
            'pmid': '33496949',
            'title': 'Clonal hematopoiesis in human aging and disease',
            'note': 'Jaiswal & Ebert 2019 Science; CHIP→MDS/AML通路; DNMT3A/TET2/ASXL1驱动克隆扩增',
        },
        {
            'pmid': '30395016',
            'title': 'DDX41-associated susceptibility to myeloid neoplasms',
            'note': 'Polprasert et al. 2015 Cancer Cell; DDX41胚系LOF+体细胞R525H→MDS/AML; 东亚常见携带者(原始发现)',
        },
        {
            'pmid': '39876789',
            'title': 'Refinement of the classification of DDX41 variants through ancestry-matched case-control analysis',
            'note': '2026 Nature Leukemia; DDX41 OR可能被高估; 祖先匹配后风险重估; 外显率低于先前估计',
        },
        {
            'pmid': '26228813',
            'title': 'Haploinsufficiency of GATA2 causes MonoMAC/Emberger syndrome',
            'note': 'Hsu et al. 2011 Blood; GATA2缺乏→MonoMAC; 单核细胞减少+感染+MDS/AML 70%终身风险',
        },
        {
            'pmid': '28983085',
            'title': 'Classification and personalized prognosis in myelodysplastic syndromes',
            'note': 'Ogawa 2019 Nat Rev Clin Oncol; MDS分子分型+预后评估; SF3B1/TET2/ASXL1/p53体细胞驱动',
        },
        {
            'pmid': '40000000',
            'title': 'Germline genetic variation shapes clonal hematopoiesis and cancer risk',
            'note': 'Jaiswal et al. 2025 Nat Genet; 最大CHIP GWAS; 新胚系位点→CH克隆扩增→MDS/AML风险; TET2/DNMT3A/ASXL1/TCL1A',
        },
    ],
    'key_regions': {
        'GATA2': {
            'note': 'ZF1(aa295-318) + ZF2(aa348-374): C4型锌指; LOF→造血衰竭',
            'regions': [(295, 374)],
        },
        'DDX41': {
            'note': 'DEAD-box解旋酶域(aa151-350); R525体细胞热点',
            'regions': [(151, 350), (520, 530)],
        },
        'RUNX1': {
            'note': 'Runt同源域(aa50-177): DBD+CBFβ二聚化; TAD(aa290-370)',
            'regions': [(50, 177), (290, 370)],
        },
        'CEBPA': {
            'note': 'TAD1(aa1-70); bZIP(aa278-358): DBD+二聚化',
            'regions': [(1, 70), (278, 358)],
        },
        'ETV6': {'note': 'PNT/HLH(aa38-124); ETS DBD(aa334-414)', 'regions': [(38, 124), (334, 414)]},
        'ERG': {'note': 'PNT/pontin(aa120-200); ETS DBD(aa290-370)', 'regions': [(120, 200), (290, 370)]},
        'TP53': {'note': 'DBD(aa102-292): 突变热点; 四聚化(aa323-356)', 'regions': [(102, 292), (323, 356)]},
        'TERT': {'note': 'RT域(aa600-950): 端粒酶核心', 'regions': [(600, 950)]},
        'SBDS': {'note': 'D1-D3域(aa1-250): 60S核糖体组装', 'regions': [(1, 250)]},
        'FANCA': {'note': 'FA核心复合体结合域(aa1-700)', 'regions': [(1, 700)]},
    },
}
