"""Disease template: myocardial infarction."""

TEMPLATE_NAME = 'myocardial infarction'

TEMPLATE = {'aliases': ['myocardial infarction',
             'mi',
             'heart attack',
             'coronary artery disease',
             'cad',
             'coronary heart disease',
             'chd',
             'atherosclerotic cardiovascular disease',
             'ascvd'],
 'mode': 'complex',
 'gene_set': [{'gene': 'LDLR',
               'tier': 'mendelian_high',
               'contribution_score': 1.0,
               'penetrance': '>0.95',
               'penetrance_score': 0.95,
               'evidence': 'familial',
               'note': '家族性高胆固醇血症1型,早发心梗核心基因',
               'phenotype_assoc': 'FH1(常显);LDL-C>190;早发CAD/MI',
               'key_domains': '配体结合(1-322);EGF前体(323-698);NPxY内吞',
               'clingen_validity': 'Definitive'},
              {'gene': 'APOB',
               'tier': 'mendelian_high',
               'contribution_score': 1.0,
               'penetrance': '>0.95',
               'penetrance_score': 0.9,
               'evidence': 'familial',
               'note': '家族性高胆固醇血症2型(FH2),LDL受体结合域缺陷',
               'phenotype_assoc': 'FH2(常显);LDL受体结合域突变',
               'key_domains': 'LDL受体结合(3359-3369)',
               'clingen_validity': 'Definitive'},
              {'gene': 'PCSK9',
               'tier': 'mendelian_high',
               'contribution_score': 1.0,
               'penetrance': '>0.95',
               'penetrance_score': 0.9,
               'evidence': 'familial',
               'note': '家族性高胆固醇血症3型(FH3),功能增强突变升高LDL-C',
               'phenotype_assoc': 'FH3(常显);PCSK9抑制剂靶点',
               'key_domains': '前体(31-152);催化(153-452);C端(453-692)',
               'clingen_validity': 'Definitive'},
              {'gene': 'LDLRAP1',
               'tier': 'mendelian_mod',
               'contribution_score': 0.85,
               'penetrance': 'high',
               'penetrance_score': 0.9,
               'evidence': 'familial',
               'note': '常染色体隐性高胆固醇血症(ARH),纯合致病',
               'clingen_validity': 'Definitive'},
              {'gene': 'LPA',
               'tier': 'mendelian_mod',
               'contribution_score': 0.7,
               'penetrance': 'dosage',
               'penetrance_score': 0.4,
               'evidence': 'mixed',
               'note': 'Lp(a)升高,常见CAD/MI风险因子,剂量效应',
               'phenotype_assoc': 'Lp(a);独立CAD风险;剂量效应',
               'key_domains': 'KIV-2重复数;蛋白酶域',
               'clingen_validity': 'Strong (risk factor)'},
              {'gene': 'ABCA1',
               'tier': 'mendelian_mod',
               'contribution_score': 0.65,
               'penetrance': 'moderate',
               'penetrance_score': 0.35,
               'evidence': 'mixed',
               'note': 'Tangier病/低HDL,杂合增加早发CAD风险',
               'clingen_validity': 'Definitive'},
              {'gene': 'APOA1',
               'tier': 'mendelian_mod',
               'contribution_score': 0.6,
               'penetrance': 'moderate',
               'penetrance_score': 0.3,
               'evidence': 'mixed',
               'note': '家族性低alpha脂蛋白血症,HDL缺乏→CAD',
               'clingen_validity': 'Strong'},
              {'gene': 'APOE',
               'tier': 'mendelian_mod',
               'contribution_score': 0.65,
               'penetrance': 'dosage',
               'penetrance_score': 0.3,
               'evidence': 'common_risk',
               'note': 'III型高脂蛋白血症,E2/E2基因型增加CAD'},
              {'gene': 'LPL',
               'tier': 'mendelian_mod',
               'contribution_score': 0.65,
               'penetrance': 'moderate',
               'penetrance_score': 0.35,
               'evidence': 'mixed',
               'note': '脂蛋白脂酶缺乏,高甘油三酯血症→CAD'},
              {'gene': 'CDKN2B',
               'tier': 'strong_gwas',
               'contribution_score': 0.5,
               'penetrance': 'very_low',
               'penetrance_score': 0.1,
               'evidence': 'gwas',
               'note': '9p21位点,最强CAD GWAS信号,细胞周期/衰老通路'},
              {'gene': 'CDKN2A',
               'tier': 'strong_gwas',
               'contribution_score': 0.5,
               'penetrance': 'very_low',
               'penetrance_score': 0.1,
               'evidence': 'gwas',
               'note': '9p21位点,与CDKN2B共定位,最强CAD GWAS位点'},
              {'gene': 'PHACTR1',
               'tier': 'strong_gwas',
               'contribution_score': 0.35,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '6p24 CAD GWAS位点,内皮素通路'},
              {'gene': 'SORT1',
               'tier': 'strong_gwas',
               'contribution_score': 0.35,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '1p13 CAD GWAS位点,sortilin调控LDL代谢'},
              {'gene': 'TCF21',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '6q23 CAD GWAS位点,血管平滑肌分化'},
              {'gene': 'ZC3HC1',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '7q32 CAD GWAS位点,细胞周期调控'},
              {'gene': 'MIA3',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '1q41 CAD GWAS位点,胶原分泌'},
              {'gene': 'ADAMTS7',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '15q25 CAD GWAS位点,血管重塑'},
              {'gene': 'WDR12',
               'tier': 'gwas',
               'contribution_score': 0.25,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '2q33 CAD GWAS位点,核糖体合成'},
              {'gene': 'COL4A1',
               'tier': 'gwas',
               'contribution_score': 0.25,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '13q34 CAD GWAS位点,基底膜胶原'},
              {'gene': 'COL4A2',
               'tier': 'gwas',
               'contribution_score': 0.25,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '13q34 CAD GWAS位点,基底膜胶原'},
              {'gene': 'SMAD3',
               'tier': 'gwas',
               'contribution_score': 0.25,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '15q22 CAD GWAS位点,TGF-beta通路'},
              {'gene': 'HHIPL1',
               'tier': 'gwas',
               'contribution_score': 0.2,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '14q32 CAD GWAS位点,HHIP样蛋白'},
              {'gene': 'CETP',
               'tier': 'gwas',
               'contribution_score': 0.2,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '胆固醇酯转运蛋白,CAD GWAS位点'},
              {'gene': 'LIPC',
               'tier': 'gwas',
               'contribution_score': 0.2,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '肝脂肪酶,CAD GWAS位点'},
              {'gene': 'HMGCR',
               'tier': 'gwas',
               'contribution_score': 0.2,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HMG-CoA还原酶,CAD GWAS位点(他汀靶点)'},
              {'gene': 'APOA5',
               'tier': 'gwas',
               'contribution_score': 0.2,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '11q23 CAD GWAS位点,甘油三酯调控'},
              {'gene': 'TRIB1',
               'tier': 'gwas',
               'contribution_score': 0.2,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '8q24 CAD GWAS位点,脂质代谢调控'},
              {'gene': 'ZNF259',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '11q23 CAD GWAS位点,ZPR1/ApoA5基因簇'},
              {'gene': 'ABO',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '9q34 CAD GWAS位点,血型抗原/血栓风险'},
              {'gene': 'CXCL12',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '10q11 CAD GWAS位点,趋化因子'},
              {'gene': 'MRAS',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '3q22 CAD GWAS位点,小G蛋白'},
              {'gene': 'GUCY1A3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '4q32 CAD GWAS位点,NO-cGMP信号'},
              {'gene': 'NOS3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'eNOS/内皮一氧化氮合酶,血管功能'},
              {'gene': 'FURIN',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '15q26 CAD GWAS位点,前体蛋白转化酶'},
              {'gene': 'SH2B3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '12q24 CAD GWAS位点,血液学/炎症'},
              {'gene': 'KCNE2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '21q22 CAD GWAS位点,钾通道亚基'},
              {'gene': 'PECAM1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '17q23 CAD GWAS位点,血小板/内皮细胞粘附分子'},
              {'gene': 'EDNRA',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '4q31 CAD GWAS位点,内皮素受体A'},
              {'gene': 'HDAC9',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '7p21大动脉粥样硬化性卒中/CAD GWAS位点'},
              {'gene': 'PLPP3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '1p32 CAD GWAS位点,脂质磷酸酶'},
              {'gene': 'BCAS3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '17q23 CAD GWAS位点'},
              {'gene': 'REST',
               'tier': 'gwas',
               'contribution_score': 0.1,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '4q12 CAD GWAS位点,转录抑制因子'},
              {'gene': 'FLT1',
               'tier': 'gwas',
               'contribution_score': 0.1,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '13q12 CAD GWAS位点,VEGF受体'},
              {'gene': 'JCAD',
               'tier': 'gwas',
               'contribution_score': 0.1,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '10p11 CAD GWAS位点,细胞连接蛋白'},
              {'gene': 'IL6R',
               'tier': 'gwas',
               'contribution_score': 0.1,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': '1q21 CAD GWAS位点,IL-6炎症通路'},
              {'gene': 'ITGB3',
               'tier': 'mendelian_mod',
               'contribution_score': 0.75,
               'penetrance': 'moderate',
               'penetrance_score': 0.4,
               'evidence': 'mixed',
               'note': 'ClinVar expert-reviewed MI susceptibility'},
              {'gene': 'MEF2A',
               'tier': 'mendelian_mod',
               'contribution_score': 0.7,
               'penetrance': 'moderate',
               'penetrance_score': 0.35,
               'evidence': 'mixed',
               'note': 'Monogenic CAD gene, autosomal dominant CAD1'},
              {'gene': 'ACE',
               'tier': 'gwas',
               'contribution_score': 0.2,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'ACE I/D polymorphism, CAD/MI GWAS locus'},
              {'gene': 'AGTR1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'AGTR1 A1166C polymorphism, hypertension/MI risk'},
              {'gene': 'APOC3',
               'tier': 'gwas',
               'contribution_score': 0.2,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'apoC-III, protective LOF variants lower TG and CAD risk'},
              {'gene': 'FBN2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'FBN2/fibrillin-2, Aragam2022 new CAD locus'},
              {'gene': 'SCUBE1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'SCUBE1, platelet-secreted glycoprotein, Aragam2022'}],
 'known_pathogenic_variants': [{'rsid': 'rs879254382',
                                'chrom': 'chr19',
                                'pos': 11089549,
                                'ref': 'A',
                                'alt': 'C',
                                'gene': 'LDLR',
                                'effect_allele': 'C',
                                'other_allele': 'A',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 1.0,
                                'confidence': 'high',
                                'note': 'LDLR 错义变异;常显FH1,杂合LDL-C>190mg/dL,早发心梗~20x风险;纯合LDL-C>500mg/dL,儿童期CAD'},
                               {'rsid': 'rs5742904',
                                'chrom': 'chr2',
                                'pos': 21006288,
                                'ref': 'C',
                                'alt': 'T',
                                'gene': 'APOB',
                                'effect_allele': 'T',
                                'other_allele': 'C',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 1.0,
                                'confidence': 'high',
                                'note': 'APOB p.Arg3527Gln;常显FH2,LDL受体结合域缺陷→LDL-C清除障碍,杂合致病,早发CAD/MI风险显著升高'},
                               {'rsid': 'rs137852912',
                                'chrom': 'chr1',
                                'pos': 55057454,
                                'ref': 'G',
                                'alt': 'C',
                                'gene': 'PCSK9',
                                'effect_allele': 'C',
                                'other_allele': 'G',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 1.0,
                                'confidence': 'high',
                                'note': 'PCSK9 p.Asp374Tyr;常显FH3,功能增强突变→LDLR降解↑→LDL-C显著升高,杂合早发CAD/MI'},
                               {'rsid': 'rs121908324',
                                'chrom': 'chr1',
                                'pos': 25543763,
                                'ref': 'G',
                                'alt': 'A',
                                'gene': 'LDLRAP1',
                                'effect_allele': 'A',
                                'other_allele': 'G',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.85,
                                'confidence': 'high',
                                'note': 'LDLRAP1 无义变异;常染色体隐性高胆固醇血症,纯合/复合杂合致病,LDL-C升高类似FH,杂合携带通常正常'},
                               {'rsid': 'rs146292819',
                                'chrom': 'chr9',
                                'pos': 104794495,
                                'ref': 'T',
                                'alt': 'G',
                                'gene': 'ABCA1',
                                'effect_allele': 'G',
                                'other_allele': 'T',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.65,
                                'confidence': 'high',
                                'note': 'ABCA1 错义变异;Tangier病/家族性低alpha脂蛋白血症,杂合降低HDL并增加早发CAD风险'},
                               {'rsid': 'rs28942111',
                                'chrom': 'chr1',
                                'pos': 55044016,
                                'ref': 'T',
                                'alt': 'A',
                                'gene': 'PCSK9',
                                'effect_allele': 'A',
                                'other_allele': 'T',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.85,
                                'confidence': 'high',
                                'note': 'PCSK9 错义变异;FH3功能增强突变,杂合LDL-C升高,早发CAD/MI风险增加'},
                               {'rsid': 'rs1022839092',
                                'chrom': 'chr17',
                                'pos': 47253892,
                                'ref': 'T',
                                'alt': 'C',
                                'gene': 'ITGB3',
                                'effect_allele': 'C',
                                'other_allele': 'T',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.85,
                                'confidence': 'high',
                                'note': 'ITGB3/GPIIIa PlA2; ClinVar expert-reviewed MI susceptibility'},
                               {'rsid': 'rs121918529',
                                'chrom': 'chr15',
                                'pos': 99690400,
                                'ref': 'C',
                                'alt': 'T',
                                'gene': 'MEF2A',
                                'effect_allele': 'T',
                                'other_allele': 'C',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.8,
                                'confidence': 'high',
                                'note': 'MEF2A, autosomal dominant CAD1'},
                               {'rsid': 'rs72613567',
                                'chrom': 'chr4',
                                'pos': 87310241,
                                'ref': 'A',
                                'alt': 'AA',
                                'gene': 'ANGPTL3',
                                'effect_allele': 'AA',
                                'other_allele': 'A',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.6,
                                'confidence': 'high',
                                'note': 'ANGPTL3 p.Ser17Ter fs; LoF protective variant, reduces TG+LDL-C, lower CAD '
                                        'risk'}],
 'regulatory_regions': [],
 'regions': [{'chrom': 'chr9',
              'start': 21900000,
              'end': 22400000,
              'gene': 'CDKN2B-AS1',
              'type': 'gwas_locus',
              'contribution_score': 0.5,
              'note': '9p21 最强CAD/MI GWAS区;ANRIL长链非编码RNA'},
             {'chrom': 'chr19',
              'start': 11000000,
              'end': 11250000,
              'gene': 'LDLR',
              'type': 'mendelian_locus',
              'contribution_score': 0.7,
              'note': 'LDLR 家族性高胆固醇血症;LDL-C清除核心'},
             {'chrom': 'chr1',
              'start': 55500000,
              'end': 55550000,
              'gene': 'PCSK9',
              'type': 'mendelian_locus',
              'contribution_score': 0.5,
              'note': 'PCSK9 GOF突变;LDLR降解促进'},
             {'chrom': 'chr6',
              'start': 160900000,
              'end': 161050000,
              'gene': 'LPA',
              'type': 'gwas_locus',
              'contribution_score': 0.4,
              'note': 'LPA/Lp(a) 最强的CAD因果GWAS区'}],
 'key_regions': {'LDLR': {'note': 'LDLR介导LDL内吞,是FH最主要致病基因;配体结合域和EGF前体域为突变热点',
                          'regions': [{'name': 'Ligand_binding',
                                       'residues': '1-322',
                                       'note': 'LDLR-A类重复x7,结合ApoB/ApoE'},
                                      {'name': 'EGF_precursor',
                                       'residues': '323-698',
                                       'note': 'EGF样重复+YWTD beta-螺旋,pH依赖性配体释放'}],
                          'critical_residues': [{'residue': 'Cys27', 'note': '配体结合域关键二硫键位点'},
                                                {'residue': 'Asp206', 'note': '钙结合位点,稳定配体结合构象'},
                                                {'residue': 'Cys308', 'note': 'EGF前体域二硫键,常见FH突变热区'}]},
                 'PCSK9': {'note': 'PCSK9促进LDLR降解;功能增强突变升高LDL-C,增加CAD风险',
                           'regions': [{'name': 'Prodomain', 'residues': '31-152', 'note': '前体域,分子内伴侣'},
                                       {'name': 'Catalytic', 'residues': '153-452', 'note': '枯草杆菌蛋白酶样催化域'},
                                       {'name': 'C_terminal', 'residues': '453-692', 'note': 'C端域,LDLR结合必需'}],
                           'critical_residues': [{'residue': 'Asp374', 'note': 'D374Y经典FH3功能增强突变'},
                                                 {'residue': 'Ser127', 'note': 'S127R功能增强,影响前体域切割'}]},
                 'APOB': {'note': 'APOB是LDL主要载脂蛋白;LDL受体结合域突变是FH2病因',
                          'regions': [{'name': 'LDL_receptor_binding', 'residues': '3359-3369', 'note': 'LDL受体结合域B'},
                                      {'name': 'Lipid_binding', 'residues': '3000-4500', 'note': '脂质结合和LDL组装域'}],
                          'critical_residues': [{'residue': 'Arg3527', 'note': 'R3527Q欧洲人群最常见FH2突变'},
                                                {'residue': 'Arg3500', 'note': 'R3500Q亚洲人群FH2热点'}]}},
 'prs_variants_high': [{'rsid': 'rs1333049',
                        'chrom': 'chr9',
                        'pos': 22125504,
                        'gene': 'CDKN2B',
                        'effect_allele': 'C',
                        'other_allele': 'G',
                        'beta': None,
                        'or_value': 1.29,
                        'tier': 'prs_high',
                        'contribution_score': 0.3,
                        'confidence': 'high',
                        'note': '9p21; strongest CAD GWAS, EAS OR=1.35 (metaGRS PMID 32493739)'},
                       {'rsid': 'rs11206510',
                        'chrom': 'chr1',
                        'pos': 55038474,
                        'gene': 'PCSK9',
                        'effect_allele': 'T',
                        'other_allele': 'C',
                        'beta': None,
                        'or_value': 1.11,
                        'tier': 'prs_high',
                        'contribution_score': 0.25,
                        'confidence': 'high',
                        'note': 'PCSK9; CAD PRS top weighted, PCSK9 inhibitor target'},
                       {'rsid': 'rs646776',
                        'chrom': 'chr1',
                        'pos': 109275908,
                        'gene': 'SORT1',
                        'effect_allele': 'C',
                        'other_allele': 'T',
                        'beta': None,
                        'or_value': 1.18,
                        'tier': 'prs_high',
                        'contribution_score': 0.25,
                        'confidence': 'high',
                        'note': 'SORT1/CELSR2; major CAD PRS locus, LDL metabolism'}],
 'prs_variants': [],
 'gwas_lead_snps': [{'rsid': 'rs9349379',
                     'chrom': 'chr6',
                     'pos': 12903957,
                     'gene': 'PHACTR1',
                     'effect_allele': 'G',
                     'other_allele': 'A',
                     'beta': 0.2017,
                     'or_value': 1.15,
                     'eaf_eur': 0.4,
                     'eaf_eas': 0.65,
                     'tier': 'strong_gwas',
                     'contribution_score': 0.364,
                     'confidence': 'high',
                     'note': 'PHACTR1; EAS AF=0.65 vs EUR=0.40, 6p24 CAD GWAS (EDN1通路)'},
                    {'rsid': 'rs599839',
                     'chrom': 'chr1',
                     'pos': 109274968,
                     'gene': 'SORT1',
                     'effect_allele': 'G',
                     'other_allele': 'A',
                     'beta': 0.2086,
                     'or_value': 1.13,
                     'eaf_eur': 0.78,
                     'eaf_eas': 0.91,
                     'tier': 'strong_gwas',
                     'contribution_score': 0.364,
                     'confidence': 'high',
                     'note': 'SORT1/CELSR2/PSRC1位点;LDL代谢;OR=1.13'},
                    {'rsid': 'rs1122608',
                     'chrom': 'chr19',
                     'pos': 11060602,
                     'gene': 'LDLR',
                     'effect_allele': 'G',
                     'other_allele': 'T',
                     'beta': 0.2169,
                     'or_value': 1.14,
                     'eaf_eur': 0.76,
                     'eaf_eas': 0.96,
                     'tier': 'strong_gwas',
                     'contribution_score': 0.364,
                     'confidence': 'high',
                     'note': 'LDLR; EAS AF=0.96 vs EUR=0.76, near-fixed in EAS'},
                    {'rsid': 'rs9982601',
                     'chrom': 'chr21',
                     'pos': 34211562,
                     'gene': 'KCNE2',
                     'effect_allele': 'T',
                     'other_allele': 'C',
                     'beta': 0.2848,
                     'or_value': 1.15,
                     'eaf_eur': 0.14,
                     'eaf_eas': 0.06,
                     'tier': 'strong_gwas',
                     'contribution_score': 0.304,
                     'confidence': 'high',
                     'note': '21q22/MRPS6/KCNE2;OR=1.15'},
                    {'rsid': 'rs17114036',
                     'chrom': 'chr1',
                     'pos': 56923266,
                     'gene': 'PLPP3',
                     'effect_allele': 'A',
                     'other_allele': 'G',
                     'beta': 0.28,
                     'or_value': 1.12,
                     'eaf_eur': 0.91,
                     'eaf_eas': 0.17,
                     'tier': 'gwas',
                     'contribution_score': 0.243,
                     'confidence': 'high',
                     'note': '1p32/PLPP3;OR=1.12'},
                    {'rsid': 'rs4845625',
                     'chrom': 'chr1',
                     'pos': 153999331,
                     'gene': 'IL6R',
                     'effect_allele': 'T',
                     'other_allele': 'C',
                     'beta': 0.0991,
                     'or_value': 1.07,
                     'eaf_eur': 0.37,
                     'eaf_eas': 0.41,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': '1q21/IL6R;炎症通路;OR=1.07'},
                    {'rsid': 'rs17465637',
                     'chrom': 'chr1',
                     'pos': 222644203,
                     'gene': 'MIA3',
                     'effect_allele': 'C',
                     'other_allele': 'A',
                     'beta': 0.2337,
                     'or_value': 1.16,
                     'eaf_eur': 0.72,
                     'eaf_eas': 0.69,
                     'tier': 'gwas',
                     'contribution_score': 0.304,
                     'confidence': 'high',
                     'note': '1q41/MIA3;OR=1.16'},
                    {'rsid': 'rs2259816',
                     'chrom': 'chr12',
                     'pos': 111395710,
                     'gene': 'SH2B3',
                     'effect_allele': 'T',
                     'other_allele': 'C',
                     'beta': 0.1089,
                     'or_value': 1.08,
                     'eaf_eur': 0.48,
                     'eaf_eas': 0.03,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': '12q24/SH2B3;OR=1.08'},
                    {'rsid': 'rs2306374',
                     'chrom': 'chr3',
                     'pos': 138330569,
                     'gene': 'MRAS',
                     'effect_allele': 'C',
                     'other_allele': 'T',
                     'beta': 0.2086,
                     'or_value': 1.12,
                     'eaf_eur': 0.18,
                     'eaf_eas': 0.07,
                     'tier': 'gwas',
                     'contribution_score': 0.243,
                     'confidence': 'high',
                     'note': '3q22/MRAS;OR=1.12'},
                    {'rsid': 'rs7692387',
                     'chrom': 'chr4',
                     'pos': 147838110,
                     'gene': 'GUCY1A3',
                     'effect_allele': 'G',
                     'other_allele': 'A',
                     'beta': 0.1343,
                     'or_value': 1.09,
                     'eaf_eur': 0.71,
                     'eaf_eas': 0.89,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': '4q32/GUCY1A3-NO通路;OR=1.09'},
                    {'rsid': 'rs2107595',
                     'chrom': 'chr7',
                     'pos': 19007732,
                     'gene': 'HDAC9',
                     'effect_allele': 'A',
                     'other_allele': 'G',
                     'beta': 0.1794,
                     'or_value': 1.1,
                     'eaf_eur': 0.17,
                     'eaf_eas': 0.15,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': '7p21/HDAC9;OR=1.10'},
                    {'rsid': 'rs2954029',
                     'chrom': 'chr8',
                     'pos': 125480841,
                     'gene': 'TRIB1',
                     'effect_allele': 'A',
                     'other_allele': 'T',
                     'beta': 0.1225,
                     'or_value': 1.09,
                     'eaf_eur': 0.45,
                     'eaf_eas': 0.31,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': '8q24/TRIB1;OR=1.09'},
                    {'rsid': 'rs579459',
                     'chrom': 'chr9',
                     'pos': 133278724,
                     'gene': 'ABO',
                     'effect_allele': 'C',
                     'other_allele': 'T',
                     'beta': 0.1091,
                     'or_value': 1.07,
                     'eaf_eur': 0.26,
                     'eaf_eas': 0.38,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': '9q34/ABO血型;OR=1.07'},
                    {'rsid': 'rs2505083',
                     'chrom': 'chr10',
                     'pos': 30297854,
                     'gene': 'JCAD',
                     'effect_allele': 'C',
                     'other_allele': 'T',
                     'beta': 0.0973,
                     'or_value': 1.07,
                     'eaf_eur': 0.41,
                     'eaf_eas': 0.54,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': '10p11/JCAD(KIAA1462);OR=1.07'},
                    {'rsid': 'rs3825807',
                     'chrom': 'chr15',
                     'pos': 78780860,
                     'gene': 'ADAMTS7',
                     'effect_allele': 'A',
                     'other_allele': 'G',
                     'beta': 0.1619,
                     'or_value': 1.12,
                     'eaf_eur': 0.57,
                     'eaf_eas': 0.44,
                     'tier': 'gwas',
                     'contribution_score': 0.304,
                     'confidence': 'high',
                     'note': '15q25/ADAMTS7;OR=1.12'},
                    {'rsid': 'rs12190287',
                     'chrom': 'chr6',
                     'pos': 134209134,
                     'gene': 'TCF21',
                     'effect_allele': 'C',
                     'other_allele': 'G',
                     'beta': 0.1382,
                     'or_value': 1.1,
                     'eaf_eur': 0.61,
                     'eaf_eas': 0.42,
                     'tier': 'gwas',
                     'contribution_score': 0.243,
                     'confidence': 'high',
                     'note': '6q23/TCF21;OR=1.10'},
                    {'rsid': 'rs11556924',
                     'chrom': 'chr7',
                     'pos': 129784192,
                     'gene': 'ZC3HC1',
                     'effect_allele': 'C',
                     'other_allele': 'T',
                     'beta': 0.1249,
                     'or_value': 1.09,
                     'eaf_eur': 0.61,
                     'eaf_eas': 0.72,
                     'tier': 'gwas',
                     'contribution_score': 0.243,
                     'confidence': 'high',
                     'note': '7q32/ZC3HC1;OR=1.09'},
                    {'rsid': 'rs1412444',
                     'chrom': 'chr10',
                     'pos': 89285137,
                     'gene': 'LIPA',
                     'effect_allele': 'T',
                     'other_allele': 'C',
                     'beta': 0.1235,
                     'or_value': 1.09,
                     'eaf_eur': 0.58,
                     'eaf_eas': 0.18,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': '10q23/LIPA;溶酶体酸性脂肪酶;OR=1.09'},
                    {'rsid': 'rs1878406',
                     'chrom': 'chr4',
                     'pos': 147451314,
                     'gene': 'EDNRA',
                     'effect_allele': 'T',
                     'other_allele': 'C',
                     'beta': 0.1154,
                     'or_value': 1.06,
                     'eaf_eur': 0.15,
                     'eaf_eas': 0.23,
                     'tier': 'gwas',
                     'contribution_score': 0.121,
                     'confidence': 'low',
                     'note': '4q31/EDNRA;OR=1.06'},
                    {'rsid': 'rs79598313',
                     'chrom': 'chr1',
                     'pos': 27284913,
                     'gene': 'KDF1',
                     'effect_allele': 'T',
                     'other_allele': 'G',
                     'beta': 0.1348,
                     'or_value': 1.1,
                     'eaf_eur': 0.0416,
                     'eaf_eas': 0.0004,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': 'KDF1; Aragam2022 new CAD locus; OR=1.10'},
                    {'rsid': 'rs4954580',
                     'chrom': 'chr2',
                     'pos': 136886949,
                     'gene': 'CXCR4',
                     'effect_allele': 'T',
                     'other_allele': 'A',
                     'beta': -0.0577,
                     'or_value': 0.96,
                     'eaf_eur': 0.1303,
                     'eaf_eas': 0.4147,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': 'CXCR4; Aragam2022 cross-ancestry meta; OR=0.96'},
                    {'rsid': 'rs35611688',
                     'chrom': 'chr2',
                     'pos': 148377860,
                     'gene': 'ACVR2A',
                     'effect_allele': 'T',
                     'other_allele': 'A',
                     'beta': -0.0431,
                     'or_value': 0.97,
                     'eaf_eur': 0.6689,
                     'eaf_eas': 0.8247,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': 'ACVR2A; Aragam2022 new CAD locus; OR=0.97'},
                    {'rsid': 'rs11721038',
                     'chrom': 'chr3',
                     'pos': 169083499,
                     'gene': 'MECOM',
                     'effect_allele': 'G',
                     'other_allele': 'A',
                     'beta': 0.069,
                     'or_value': 1.05,
                     'eaf_eur': None,
                     'eaf_eas': None,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': 'MECOM/EVI1; Aragam2022 cross-ancestry meta; OR=1.05'},
                    {'rsid': 'rs4074793',
                     'chrom': 'chr5',
                     'pos': 52193125,
                     'gene': 'ITGA1',
                     'effect_allele': 'A',
                     'other_allele': 'G',
                     'beta': -0.0725,
                     'or_value': 0.95,
                     'eaf_eur': 0.9334,
                     'eaf_eas': 0.9335,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'high',
                     'note': 'ITGA1; fine-mapped PPA=0.95; Aragam2022; OR=0.95'},
                    {'rsid': 'rs112949822',
                     'chrom': 'chr5',
                     'pos': 108085190,
                     'gene': 'FER',
                     'effect_allele': 'A',
                     'other_allele': 'T',
                     'beta': -0.0725,
                     'or_value': 0.95,
                     'eaf_eur': 0.0726,
                     'eaf_eas': 0.007,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': 'FER; Aragam2022 new CAD locus; OR=0.95'},
                    {'rsid': 'rs6883598',
                     'chrom': 'chr5',
                     'pos': 127926190,
                     'gene': 'FBN2',
                     'effect_allele': 'A',
                     'other_allele': 'T',
                     'beta': -0.0431,
                     'or_value': 0.97,
                     'eaf_eur': 0.7396,
                     'eaf_eas': 0.8503,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': 'FBN2; Aragam2022 new CAD locus; OR=0.97'},
                    {'rsid': 'rs1019016',
                     'chrom': 'chr7',
                     'pos': 80708291,
                     'gene': 'SEMA3C',
                     'effect_allele': 'A',
                     'other_allele': 'G',
                     'beta': 0.0418,
                     'or_value': 1.03,
                     'eaf_eur': None,
                     'eaf_eas': None,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': 'SEMA3C; Aragam2022 cross-ancestry meta; OR=1.03'},
                    {'rsid': 'rs75082222',
                     'chrom': 'chr10',
                     'pos': 33210450,
                     'gene': 'NRP1',
                     'effect_allele': 'A',
                     'other_allele': 'G',
                     'beta': -0.0431,
                     'or_value': 0.97,
                     'eaf_eur': None,
                     'eaf_eas': None,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': 'NRP1; Aragam2022 cross-ancestry meta; OR=0.97'},
                    {'rsid': 'rs55753709',
                     'chrom': 'chr10',
                     'pos': 96029170,
                     'gene': 'PLCE1',
                     'effect_allele': 'T',
                     'other_allele': 'C',
                     'beta': -0.0577,
                     'or_value': 0.96,
                     'eaf_eur': 0.7423,
                     'eaf_eas': 0.6542,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'high',
                     'note': 'PLCE1; Aragam2022 new CAD locus; OR=0.96'},
                    {'rsid': 'rs7903146',
                     'chrom': 'chr10',
                     'pos': 114758349,
                     'gene': 'TCF7L2',
                     'effect_allele': 'T',
                     'other_allele': 'T',
                     'beta': 0.0418,
                     'or_value': 1.03,
                     'eaf_eur': 0.2919,
                     'eaf_eas': 0.0269,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'high',
                     'note': 'TCF7L2; T2D locus newly GWAS-sig for CAD; OR=1.03'},
                    {'rsid': 'rs1892971',
                     'chrom': 'chr11',
                     'pos': 102795606,
                     'gene': 'MMP13',
                     'effect_allele': 'A',
                     'other_allele': 'C',
                     'beta': -0.0577,
                     'or_value': 0.96,
                     'eaf_eur': 0.2235,
                     'eaf_eas': 0.0643,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'high',
                     'note': 'MMP13/collagenase-3; Aragam2022 new CAD locus; OR=0.96'},
                    {'rsid': 'rs2277383',
                     'chrom': 'chr12',
                     'pos': 51906396,
                     'gene': 'ACVRL1',
                     'effect_allele': 'G',
                     'other_allele': 'T',
                     'beta': -0.0431,
                     'or_value': 0.97,
                     'eaf_eur': 0.1099,
                     'eaf_eas': 0.3576,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': 'ACVRL1/ALK1; Aragam2022 cross-ancestry meta; OR=0.97'},
                    {'rsid': 'rs8075861',
                     'chrom': 'chr17',
                     'pos': 78847636,
                     'gene': 'TIMP2',
                     'effect_allele': 'G',
                     'other_allele': 'A',
                     'beta': -0.0431,
                     'or_value': 0.97,
                     'eaf_eur': None,
                     'eaf_eas': None,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'moderate',
                     'note': 'TIMP2; Aragam2022 cross-ancestry meta; OR=0.97'},
                    {'rsid': 'rs7246865',
                     'chrom': 'chr19',
                     'pos': 17219105,
                     'gene': 'MYO9B',
                     'effect_allele': 'A',
                     'other_allele': 'C',
                     'beta': 0.0418,
                     'or_value': 1.03,
                     'eaf_eur': 0.2012,
                     'eaf_eas': 0.3431,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'high',
                     'note': 'MYO9B; CRISPR-validated; Aragam2022; OR=1.03'},
                    {'rsid': 'rs2207132',
                     'chrom': 'chr20',
                     'pos': 39142516,
                     'gene': 'MAFB',
                     'effect_allele': 'A',
                     'other_allele': 'G',
                     'beta': 0.1348,
                     'or_value': 1.1,
                     'eaf_eur': 0.0358,
                     'eaf_eas': 0.0002,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'high',
                     'note': 'MAFB; Aragam2022 new CAD locus; OR=1.10'},
                    {'rsid': 'rs1390122',
                     'chrom': 'chr22',
                     'pos': 43623972,
                     'gene': 'SCUBE1',
                     'effect_allele': 'A',
                     'other_allele': 'G',
                     'beta': -0.0431,
                     'or_value': 0.97,
                     'eaf_eur': 0.7925,
                     'eaf_eas': 0.6809,
                     'tier': 'gwas',
                     'contribution_score': 0.182,
                     'confidence': 'high',
                     'note': 'SCUBE1; missense p.G398R; Aragam2022; OR=0.97'}],
 'key_literature': [{'pmid': '23202125',
                     'title': 'Large-scale association analysis identifies new risk loci for coronary artery disease.',
                     'genes': ['CDKN2B', 'PHACTR1', 'SORT1', 'MIA3', 'WDR12', 'ADAMTS7', 'TCF21', 'ZC3HC1'],
                     'note': 'CARDIoGRAMplusC4D, Nat Genet 2013',
                     'evidence_type': 'gwas'},
                    {'pmid': '28714975',
                     'title': 'Identification of 64 novel genetic loci provides an expanded view of the genetic '
                              'architecture of CAD.',
                     'genes': ['LDLR', 'APOB', 'LPA', 'LPL', 'PCSK9', 'NOS3', 'CXCL12'],
                     'note': 'UK Biobank+CARDIoGRAMplusC4D, Nat Genet 2017',
                     'evidence_type': 'gwas'},
                    {'pmid': '21378990',
                     'title': 'GWAS in Han Chinese identifies four new susceptibility loci for CAD.',
                     'genes': ['GUCY1A3', 'TTC32', 'WDR35'],
                     'note': 'Wang et al., Nat Genet 2011',
                     'evidence_type': 'gwas'},
                    {'pmid': '36474045',
                     'title': 'Discovery and systematic characterization of risk variants and genes for coronary '
                              'artery disease in over a million participants.',
                     'genes': ['FBN2',
                               'ITGA1',
                               'MMP13',
                               'MYO9B',
                               'SCUBE1',
                               'PLCE1',
                               'MAFB',
                               'NRP1',
                               'CXCR4',
                               'ACVRL1',
                               'TCF7L2',
                               'TIMP2',
                               'SEMA3C',
                               'MECOM'],
                     'note': 'Aragam et al., Nat Genet 2022 (241 loci, 68 new)',
                     'evidence_type': 'gwas'}],
 'core_genes': ['LDLR', 'APOB', 'PCSK9', 'LDLRAP1', 'LPA', 'ABCA1', 'APOA1', 'APOE', 'LPL'],
 'gwas_loci_genes': ['CDKN2B',
                     'CDKN2A',
                     'PHACTR1',
                     'SORT1',
                     'TCF21',
                     'ZC3HC1',
                     'MIA3',
                     'WDR12',
                     'COL4A1',
                     'COL4A2',
                     'SMAD3',
                     'HHIPL1',
                     'CETP',
                     'LIPC',
                     'HMGCR',
                     'APOA5',
                     'TRIB1',
                     'ZNF259',
                     'ABO',
                     'CXCL12',
                     'MRAS',
                     'GUCY1A3',
                     'NOS3',
                     'FURIN',
                     'SH2B3',
                     'KCNE2',
                     'PECAM1',
                     'EDNRA',
                     'HDAC9',
                     'PLPP3',
                     'BCAS3',
                     'REST',
                     'FLT1',
                     'JCAD',
                     'IL6R']}
