"""Disease template: osteoporosis."""

TEMPLATE_NAME = 'osteoporosis'
TEMPLATE = {   'aliases': [   'osteoporosis',
                   'low bone mineral density',
                   'low bmd',
                   'bmd',
                   'bone mineral density',
                   'osteopenia',
                   'osteoporotic fracture',
                   'fragility fracture',
                   'osteogenesis imperfecta',
                   'oi',
                   'osteoporosis-pseudoglioma syndrome',
                   'high bone mass'],
    'mode': 'complex',
    'gene_set': [   {   'gene': 'LRP5',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.9,
                        'penetrance': 'high',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': 'LRP5功能缺失→骨质疏松-假性胶质瘤综合征(AR); 功能增强→高骨量表型(AD); Wnt/β-catenin共受体',
                        'phenotype_assoc': 'OPPG(AR低骨量);高骨量(AD增强);Wnt共受体;成骨细胞分化',
                        'key_domains': 'YWTD β-螺旋×4;EGF-like×4;LDL受体A类×3;跨膜域;EGF-like 1(域,aa295-337);EGF-like 2(域,aa601-641);EGF-like 3(域,aa902-942);EGF-like 4(域,aa1213-1254);LDL-receptor class A 1(域,aa1258-1296);LDL-receptor class A 2(域,aa1297-1333)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'COL1A1',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.9,
                        'penetrance': 'high',
                        'penetrance_score': 0.85,
                        'evidence': 'familial',
                        'note': 'I型胶原α1链; 成骨不全(AD,大多数); 严重BMD降低/骨折; 骨质疏松GWAS显著位点',
                        'phenotype_assoc': '成骨不全I-IV型(AD);骨质疏松;BMD GWAS;I型胶原骨架',
                        'key_domains': '胶原三螺旋重复(Gly-X-Y);N端前肽;C端前肽;VWFC(域,aa38-96);Fibrillar collagen NC1(域,aa1229-1464);Disordered(区,aa98-1214);Nonhelical region (N-terminal)(区,aa162-178);Triple-helical region(区,aa179-1192);Nonhelical region (C-terminal)(区,aa1193-1218)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'COL1A2',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.85,
                        'penetrance': 'high',
                        'penetrance_score': 0.8,
                        'evidence': 'familial',
                        'note': 'I型胶原α2链; 成骨不全(AD,比COL1A1少); 骨质疏松表型较轻',
                        'phenotype_assoc': '成骨不全(AD);EDS关节型(AR特殊变异);骨质疏松',
                        'key_domains': '胶原三螺旋重复;N端前肽;C端前肽;Fibrillar collagen NC1(域,aa1133-1366);Disordered(区,aa28-1130);结合位点(aa1181-1181);结合位点(aa1183-1183);结合位点(aa1184-1184);结合位点(aa1186-1186)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'WNT1',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.85,
                        'penetrance': 'high',
                        'penetrance_score': 0.75,
                        'evidence': 'familial',
                        'note': 'WNT1纯合致病变异→成骨不全XV型(AR); 杂合变异→早发骨质疏松',
                        'phenotype_assoc': '成骨不全XV型(AR);早发骨质疏松(杂合);Wnt/β-catenin通路',
                        'key_domains': 'Wnt信号域;棕榈酰化位点',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'PLS3',
                        'tier': 'mendelian_high',
                        'contribution_score': 0.75,
                        'penetrance': 'high',
                        'penetrance_score': 0.7,
                        'evidence': 'familial',
                        'note': 'Plastin-3; X连锁骨质疏松伴骨折; 男性发病为主; F-actin结合蛋白',
                        'phenotype_assoc': 'X连锁骨质疏松(XLD);男性早发骨折;F-actin成束蛋白',
                        'key_domains': 'EF-hand×4(钙结合);CH域×2(肌动蛋白结合);EF-hand 1(域,aa12-47);EF-hand 2(域,aa52-87);Calponin-homology (CH) 1(域,aa123-239);Calponin-homology (CH) 2(域,aa267-378);Calponin-homology (CH) 3(域,aa397-506);Calponin-homology (CH) 4(域,aa518-627)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'LRP6',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.55,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.25,
                        'evidence': 'mixed',
                        'note': 'LRP5/6 Wnt共受体; 杂合致病变异→骨质疏松/BMD降低; 冠心病/代谢综合征共存',
                        'phenotype_assoc': 'LRP6;Wnt共受体;BMD降低;早发CAD/代谢综合征(AD)',
                        'key_domains': 'YWTD-EGF×4;LDLR-A类×3;跨膜域;EGF-like 1(域,aa282-324);EGF-like 2(域,aa588-628);EGF-like 3(域,aa889-930);EGF-like 4(域,aa1203-1244);LDL-receptor class A 1(域,aa1248-1286);LDL-receptor class A 2(域,aa1287-1323)',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'BMP2',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.5,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.2,
                        'evidence': 'mixed',
                        'note': '骨形态发生蛋白2; 成骨分化的关键诱导因子; BMD GWAS; 骨折风险关联; rhBMP2临床用于骨愈合',
                        'phenotype_assoc': 'BMP2;成骨分化;骨折风险;BMD GWAS;TGF-β超家族;rhBMP2骨移植物',
                        'key_domains': 'TGF-β前体域;TGF-β结构域;Disordered(区,aa84-121);Disordered(区,aa271-293)',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'ALPL',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.55,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'mixed',
                        'note': '组织非特异性碱性磷酸酶; 低磷酸酯酶症(AR/AD); BMD GWAS; 骨矿化必需',
                        'phenotype_assoc': '低磷酸酯酶症(AR/AD);BMD GWAS;骨矿化;TNSALP',
                        'key_domains': '碱性磷酸酶域;N端α-螺旋;活性中心Zn/Mg;Phosphoserine intermediate(活性位点,aa110-110);结合位点(aa60-60);结合位点(aa60-60);结合位点(aa110-110);结合位点(aa173-173);结合位点(aa235-235)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'VDR',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.45,
                        'penetrance': 'low',
                        'penetrance_score': 0.15,
                        'evidence': 'mixed',
                        'note': '维生素D受体; 佝偻病/1,25(OH)2D抵抗(AR); BMD GWAS候选基因; 钙吸收/骨代谢调控',
                        'phenotype_assoc': 'VDDR2A(AR维生素D抵抗);钙吸收;BMD GWAS;核受体超家族',
                        'key_domains': 'DNA结合锌指×2;配体结合域;AF-2;NR LBD(域,aa127-423);Nuclear receptor(DNA结合,aa21-96);Hinge(区,aa97-126);Disordered(区,aa158-190);Interaction with coactivator LXXLL motif(区,aa246-264);结合位点(aa24-24)',
                        'clingen_validity': 'Moderate'},
                    {   'gene': 'SOST',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.55,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'mixed',
                        'note': 'Sclerostin; 硬化性骨化病(AR高骨量)/van Buchem病; Wnt通路拮抗剂; romosozumab(硬骨抑素抗体)靶点',
                        'phenotype_assoc': '硬化性骨化病(AR高骨量);van Buchem病;Wnt拮抗剂;romosozumab靶点',
                        'key_domains': 'Cystine-knot域;CTCK(域,aa82-172);Disordered(区,aa41-71);Disordered(区,aa178-213)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'RANKL',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.3,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'TNFSF11; BMD GWAS; 破骨细胞分化必需因子; denosumab(RANKL抗体)靶点',
                        'phenotype_assoc': 'RANKL/TNFSF11;BMD GWAS;破骨细胞分化;denosumab靶点',
                        'key_domains': 'TNF同源域;跨膜域',
                        'clingen_validity': ''},
                    {   'gene': 'TNFRSF11A',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.28,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'RANK; BMD GWAS; 破骨细胞分化受体; 家族性扩张性骨溶解(AD)',
                        'phenotype_assoc': 'RANK;破骨细胞分化;BMD GWAS;扩张性骨溶解(AD);骨质疏松(AD)',
                        'key_domains': 'CRD×4(富含半胱氨酸域);跨膜域;TRAF结合',
                        'clingen_validity': ''},
                    {   'gene': 'TNFRSF11B',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.28,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'OPG(骨保护素); BMD GWAS最强位点; RANKL诱饵受体; 幼年Paget骨病(AR)',
                        'phenotype_assoc': 'OPG;BMD GWAS(Top);RANKL诱饵;幼年Paget(AR);破骨细胞抑制',
                        'key_domains': 'CRD×4;DD×2(死亡域同源)',
                        'clingen_validity': ''},
                    {   'gene': 'SP7',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'Osterix; 成骨细胞分化主转录因子; BMD GWAS; 成骨不全XII型(AR)',
                        'phenotype_assoc': 'Osterix/SP7;成骨细胞主调控因子;BMD GWAS;成骨不全XII型(AR)',
                        'key_domains': 'C2H2锌指×3',
                        'clingen_validity': ''},
                    {   'gene': 'ESR1',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '雌激素受体α; BMD GWAS; 雌激素→破骨细胞抑制/成骨细胞促进; 绝经后骨质疏松关键',
                        'phenotype_assoc': 'ERα/ESR1;BMD GWAS(仅次于OPG);雌激素信号;绝经后骨质疏松',
                        'key_domains': 'AF-1;DNA结合锌指;配体结合域;AF-2',
                        'clingen_validity': ''},
                    {   'gene': 'WNT16',
                        'tier': 'gwas',
                        'contribution_score': 0.22,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'BMD GWAS强位点; Wnt配体; 皮质骨厚度/骨折风险; 成骨细胞分化',
                        'phenotype_assoc': 'WNT16;BMD/骨折GWAS;皮质骨厚度;Wnt通路',
                        'key_domains': 'Wnt信号域',
                        'clingen_validity': ''},
                    {   'gene': 'WNT4',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'BMD GWAS; Wnt配体; 性腺发育/骨代谢; Müllerian管发育',
                        'phenotype_assoc': 'WNT4;BMD GWAS;性腺发育;骨代谢;Wnt通路',
                        'key_domains': 'Wnt信号域',
                        'clingen_validity': ''},
                    {   'gene': 'MEF2C',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'BMD GWAS; 肌细胞增强因子2C; SOST/硬骨抑素转录调控; 骨细胞分化',
                        'phenotype_assoc': 'MEF2C;BMD GWAS;骨细胞分化;SOST调控',
                        'key_domains': 'MADS-box;MEF2域;转录激活域',
                        'clingen_validity': ''},
                    {   'gene': 'RUNX2',
                        'tier': 'gwas',
                        'contribution_score': 0.22,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'RUNX2/CBFA1; 成骨细胞分化主转录因子; 锁骨颅骨发育不良(AD); BMD GWAS',
                        'phenotype_assoc': 'RUNX2;成骨分化主控基因;锁骨颅骨发育不良(AD);BMD GWAS',
                        'key_domains': 'Runt域(QA/β-barrel);转录激活域;PST域',
                        'clingen_validity': ''},
                    {   'gene': 'SOX6',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'BMD GWAS; 软骨细胞分化转录因子; SOX9共激活因子',
                        'phenotype_assoc': 'SOX6;BMD GWAS;软骨细胞分化;SOX9共因子',
                        'key_domains': 'HMG-box;卷曲螺旋域',
                        'clingen_validity': ''},
                    {   'gene': 'AXIN1',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'BMD GWAS; β-catenin降解复合体支架; Wnt通路负调控; 成骨负调控',
                        'phenotype_assoc': 'AXIN1;BMD GWAS;Wnt/β-catenin负调控;β-catenin降解复合体',
                        'key_domains': 'RGS域;β-catenin结合;DIX域',
                        'clingen_validity': ''},
                    {   'gene': 'FAM3C',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'BMD GWAS; ILEI(白细胞介素样EMT诱导因子); TGF-β通路; 成骨分化',
                        'phenotype_assoc': 'FAM3C/ILEI;BMD GWAS;TGF-β信号;成骨分化;EMT',
                        'key_domains': 'ILEI/FAM3C域',
                        'clingen_validity': ''},
                    {   'gene': 'FOXL1',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'BMD GWAS; Forkhead转录因子; 间充质/GI发育; 可能与成骨前体细胞相关',
                        'phenotype_assoc': 'FOXL1;BMD GWAS;Forkhead转录因子;间充质细胞',
                        'key_domains': 'Forkhead DNA结合域',
                        'clingen_validity': ''},
                    {   'gene': 'RSPO3',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'BMD GWAS; R-spondin-3; Wnt通路正向调控; LGR4/5/6配体; 骨形成促进',
                        'phenotype_assoc': 'R-spondin-3;BMD GWAS;Wnt通路正向调控;LGR4/5/6配体;骨形成',
                        'key_domains': 'TSR域×2(血小板反应蛋白1型重复);Furin-like富半胱氨酸域',
                        'clingen_validity': ''},
                    {   'gene': 'JAG1',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'BMD GWAS; Notch配体Jagged1; 成骨/破骨Notch信号; Alagille综合征(AD)',
                        'phenotype_assoc': 'JAG1;Notch配体;BMD GWAS;Alagille(AD肝/心/骨骼)',
                        'key_domains': 'DSL域;EGF-like重复×16;CRD域',
                        'clingen_validity': ''},
                    {   'gene': 'FUBP3',
                        'tier': 'gwas',
                        'contribution_score': 0.12,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'BMD GWAS; FUSE结合蛋白3; 转录/翻译调控',
                        'phenotype_assoc': 'FUBP3;FUSE结合蛋白;BMD GWAS;转录调控',
                        'key_domains': 'KH域×4',
                        'clingen_validity': ''},
                    {   'gene': 'DKK1',
                        'tier': 'gwas',
                        'contribution_score': 0.18,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'Dickkopf-1; Wnt通路拮抗剂; LRP5/6结合; 骨髓瘤骨病; BMD/骨折关联',
                        'phenotype_assoc': 'DKK1;Wnt拮抗剂;BMD GWAS;LRP5/6结合阻断;骨髓瘤骨病',
                        'key_domains': 'DKK N端域;富含半胱氨酸域2(Colipase-fold)',
                        'clingen_validity': ''},
                    {   'gene': 'CTNNB1',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'β-catenin; Wnt通路核心效应子; BMD GWAS; 成骨细胞分化必需; 多种肿瘤驱动基因',
                        'phenotype_assoc': 'β-catenin;Wnt通路核心;BMD GWAS;成骨细胞;Cadherin结合;肿瘤',
                        'key_domains': '犰狳重复×12;N端;反式激活C端',
                        'clingen_validity': ''},
                    {   'gene': 'SFRP4',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '分泌型Frizzled相关蛋白4; Wnt通路拮抗剂; Pyle病(AR干骺端发育不良); 骨重塑',
                        'phenotype_assoc': 'SFRP4;Wnt拮抗剂;Pyle病(AR);BMD GWAS;骨重塑',
                        'key_domains': 'NTR域(Netrin-like);Frizzled CRD',
                        'clingen_validity': ''},
                    {   'gene': 'TGFBR3',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'Betaglycan; TGF-β III型受体; BMD GWAS; BMP/ TGF-β通路辅助受体',
                        'phenotype_assoc': 'Betaglycan/TGFBR3;BMD GWAS;TGF-β/BMP共受体;骨代谢',
                        'key_domains': 'ZP域(透明带);附着域',
                        'clingen_validity': ''},
                    {   'gene': 'C7orf58',
                        'tier': 'gwas',
                        'contribution_score': 0.12,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': 'BMD GWAS(7p14); CPED1/WNT16区域',
                        'phenotype_assoc': 'C7orf58/CPED1;WNT16附近;BMD/骨折GWAS位点',
                        'key_domains': '',
                        'clingen_validity': ''},
                    {   'gene': 'HDAC5',
                        'tier': 'gwas',
                        'contribution_score': 0.15,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '组蛋白去乙酰化酶5; BMD GWAS(17q21); MEF2C共抑制因子; 成骨调控',
                        'phenotype_assoc': 'HDAC5;BMD GWAS;MEF2C共抑制;组蛋白去乙酰化;成骨/破骨',
                        'key_domains': 'HDAC域;MEF2结合域',
                        'clingen_validity': ''}],
    'known_pathogenic_variants': [   {   'rsid': 'rs121908669',
                                         'chrom': 'chr11',
                                         'pos': 68400976,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'LRP5',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.9,
                                         'confidence': 'high',
                                         'note': 'LRP5 G171V — 高骨量表型(AD功能增强); 下颌骨肥厚'},
                                     {   'rsid': 'rs121908666',
                                         'chrom': 'chr17',
                                         'pos': 43785156,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'SOST',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.8,
                                         'confidence': 'high',
                                         'note': 'SOST 无义突变 — 硬化性骨化病/van Buchem病(AR); Sclerostin缺失→极高骨量'},
                                     {   'rsid': 'rs387907209',
                                         'chrom': 'chr12',
                                         'pos': 48977984,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'WNT1',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.85,
                                         'confidence': 'high',
                                         'note': 'WNT1 C218G — 成骨不全XV型; 纯合→中重度OI; 杂合→早发骨质疏松'},
                                     {   'rsid': 'rs121918002',
                                         'chrom': 'chr1',
                                         'pos': 21560294,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'ALPL',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'high',
                                         'note': 'ALPL E174K — 低磷酸酯酶症(AD轻度/AR重度); 骨矿化缺陷'},
                                     {   'rsid': 'rs72654704',
                                         'chrom': 'chr17',
                                         'pos': 50190182,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'COL1A1',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.85,
                                         'confidence': 'high',
                                         'note': 'COL1A1 Gly→Ser替换(Gly-X-Y三螺旋破坏) — 成骨不全经典致病变异类型'},
                                     {   'rsid': '17276',
                                         'chrom': '7',
                                         'pos': 94395818,
                                         'ref': 'A',
                                         'alt': 'G',
                                         'gene': 'COL1A2',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Ehlers-Danlos syndrome, cardiac valvular type'},
                                     {   'rsid': '3390631',
                                         'chrom': '7',
                                         'pos': 94400194,
                                         'ref': 'A',
                                         'alt': 'G',
                                         'gene': 'COL1A2',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | not provided'},
                                     {   'rsid': '4727242',
                                         'chrom': 'X',
                                         'pos': 115622245,
                                         'ref': 'G',
                                         'alt': 'C',
                                         'gene': 'PLS3',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | not provided'},
                                     {   'rsid': '988269',
                                         'chrom': 'X',
                                         'pos': 115622246,
                                         'ref': 'A',
                                         'alt': 'AT',
                                         'gene': 'PLS3',
                                         'effect_allele': 'AT',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | not provided'},
                                     {   'rsid': '1175818',
                                         'chrom': '12',
                                         'pos': 12121270,
                                         'ref': 'AG',
                                         'alt': 'A',
                                         'gene': 'LRP6',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | not provided'},
                                     {   'rsid': '225147',
                                         'chrom': '12',
                                         'pos': 12121374,
                                         'ref': 'AG',
                                         'alt': 'A',
                                         'gene': 'LRP6',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Orofacial cleft|Tooth agenesis'},
                                     {   'rsid': '492936',
                                         'chrom': '20',
                                         'pos': 6770118,
                                         'ref': 'AG',
                                         'alt': 'CC',
                                         'gene': 'BMP2',
                                         'effect_allele': 'CC',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Short stature, facial dysmorphism, and '
                                                 'skeletal anomalies with or without cardia'},
                                     {   'rsid': '620208',
                                         'chrom': '20',
                                         'pos': 6770169,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'BMP2',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | not provided'},
                                     {   'rsid': '2697799',
                                         'chrom': '12',
                                         'pos': 47844075,
                                         'ref': 'GTGAGCTTGGTGACAGGGACAGCTGTCATATTCTTCTGTGAGGCTGTTTTTGTCTGTTTTTCCTCCTTGGGTCTCTCAGCAGGTGGGTTCGTGCCTGGTGCTCCAGTGATGGGAAGAAAACCCACCTCACCACAGCTACTGCCCGTGAGAATATAACCAGGGCAATGGGATGTTGGTGGGCACTGAAGGGGGTGGGGTGGGAGCTGTGGGCCGATTATTTATCGTGAGTAGGCAGGAGAGGGAGACCCCACTAGGCGCTGGACAAGCGGGGCCTGCAGTGGGGGGAGGTGCAGGTGTCTCTGTCCCTGAGGAATGGATGCATTTCTCCTGTCTGTTCCCTCAACATCAGTCAGCAGCCACTTAGGCAGCGGTGGAGGCATCTCTGGGCAAGGCCCTGCCTCCAGCCTCTGCCCTCTGCCCCCACTTGGGTTTCTTTGTCAAACAAACAGCAACTCCTCATGGCTGAGGTCTCAAGGGACCGGGGAAAAGCCCGCAGGAAAGGGGTTAGGTTGGACAGGAGAGAGAATGGGCTGGGTGGATAGGGGAGGTGGCAGAGGAGGGGCTGAACCCCAGACGGGGTGAGGAGGGCTGCTGAGTAGCCGCCAGCCCCGGGCCTGGCACGTGGCCCTGGAGGAGCAGCCCCACCCAGGCACCGCCACAGGCTGTCCTAGTCAGGAGATCTCATTGCCAAACACTTCGAGCACAAGGGGCGTTAGCTTCATGCTGCACTCAGGCTGGAAGGAGAGGCAGCGGTACTGCTTGGAGTGCTCCTCAT',
                                         'alt': 'G',
                                         'gene': 'VDR',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | not provided'},
                                     {   'rsid': '264697',
                                         'chrom': '12',
                                         'pos': 47844840,
                                         'ref': 'T',
                                         'alt': 'G',
                                         'gene': 'VDR',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Vitamin D-dependent rickets type II with '
                                                 'alopecia'}],
    'gwas_lead_snps': [   {   'rsid': 'rs9594738',
                              'chrom': 'chr13',
                              'pos': 42446215,
                              'beta': None,
                              'or_value': 1.12,
                              'eaf_eur': 0.45,
                              'eaf_eas': 0.35,
                              'gene': 'TNFRSF11B',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.28,
                              'confidence': 'high',
                              'note': 'OPG(TNFRSF11B)上游客 — BMD GWAS lead SNP (GEFOS)'},
                          {   'rsid': 'rs2566756',
                              'chrom': 'chr12',
                              'pos': 53879674,
                              'beta': None,
                              'or_value': 1.1,
                              'eaf_eur': 0.38,
                              'eaf_eas': 0.25,
                              'gene': 'SP7',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.22,
                              'confidence': 'high',
                              'note': 'SP7 (Osterix) — BMD GWAS'},
                          {   'rsid': 'rs9533090',
                              'chrom': 'chr13',
                              'pos': 42368676,
                              'beta': None,
                              'or_value': 1.12,
                              'eaf_eur': 0.32,
                              'eaf_eas': 0.3,
                              'gene': 'TNFRSF11A',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.25,
                              'confidence': 'high',
                              'note': 'RANK(TNFRSF11A) — BMD GWAS'},
                          {   'rsid': 'rs4869742',
                              'chrom': 'chr5',
                              'pos': 88942556,
                              'beta': None,
                              'or_value': 1.1,
                              'eaf_eur': 0.28,
                              'eaf_eas': 0.4,
                              'gene': 'MEF2C',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.2,
                              'confidence': 'high',
                              'note': 'MEF2C/SOST远端调控 — BMD GWAS'},
                          {   'rsid': 'rs3801387',
                              'chrom': 'chr7',
                              'pos': 120985239,
                              'beta': None,
                              'or_value': 1.1,
                              'eaf_eur': 0.45,
                              'eaf_eas': 0.55,
                              'gene': 'WNT16',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.22,
                              'confidence': 'high',
                              'note': 'WNT16/FAM3C — BMD GWAS(7q31)'},
                          {   'rsid': 'rs2941740',
                              'chrom': 'chr6',
                              'pos': 152010034,
                              'beta': None,
                              'or_value': 1.08,
                              'eaf_eur': 0.58,
                              'eaf_eas': 0.65,
                              'gene': 'ESR1',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.2,
                              'confidence': 'high',
                              'note': 'ESR1 — BMD GWAS(6q25)'},
                          {   'rsid': 'rs13245690',
                              'chrom': 'chr8',
                              'pos': 119819933,
                              'beta': None,
                              'or_value': 1.08,
                              'eaf_eur': 0.35,
                              'eaf_eas': 0.3,
                              'gene': 'TNFRSF11B',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.18,
                              'confidence': 'moderate',
                              'note': 'OPG远端 — BMD GWAS(8q24)'},
                          {   'rsid': 'rs1021188',
                              'chrom': 'chr7',
                              'pos': 21359010,
                              'beta': None,
                              'or_value': 1.08,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'SP4',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Estrada 2012 GEFOS)'},
                          {   'rsid': 'rs87938',
                              'chrom': 'chr1',
                              'pos': 22443285,
                              'beta': None,
                              'or_value': 1.06,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'WNT4',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Estrada 2012 GEFOS)'},
                          {   'rsid': 'rs3736228',
                              'chrom': 'chr11',
                              'pos': 68401713,
                              'beta': None,
                              'or_value': 1.14,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'LRP5',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.17,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Estrada 2012 GEFOS) — LRP5 A1330V'},
                          {   'rsid': 'rs10226308',
                              'chrom': 'chr7',
                              'pos': 30728565,
                              'beta': None,
                              'or_value': 1.06,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'CRHR2',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'},
                          {   'rsid': 'rs11995824',
                              'chrom': 'chr8',
                              'pos': 106575031,
                              'beta': None,
                              'or_value': 1.05,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'ZFPM2',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'},
                          {   'rsid': 'rs3755955',
                              'chrom': 'chr7',
                              'pos': 80760859,
                              'beta': None,
                              'or_value': 1.07,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'SEMA3A',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'},
                          {   'rsid': 'rs7521902',
                              'chrom': 'chr1',
                              'pos': 24402096,
                              'beta': None,
                              'or_value': 1.07,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'CLC',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'},
                          {   'rsid': 'rs7850023',
                              'chrom': 'chr9',
                              'pos': 115258898,
                              'beta': None,
                              'or_value': 1.05,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'PTGR1',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'},
                          {   'rsid': 'rs11692564',
                              'chrom': 'chr2',
                              'pos': 231442280,
                              'beta': None,
                              'or_value': 1.06,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'SP110',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'},
                          {   'rsid': 'rs13204917',
                              'chrom': 'chr6',
                              'pos': 151734178,
                              'beta': None,
                              'or_value': 1.05,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'AKAP12',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'},
                          {   'rsid': 'rs1107748',
                              'chrom': 'chr6',
                              'pos': 127215277,
                              'beta': None,
                              'or_value': 1.05,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'SOGA3',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'},
                          {   'rsid': 'rs6985743',
                              'chrom': 'chr8',
                              'pos': 119924357,
                              'beta': None,
                              'or_value': 1.06,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'TNFRSF11B',
                              'effect_allele': 'G',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'},
                          {   'rsid': 'rs884205',
                              'chrom': 'chr13',
                              'pos': 110016978,
                              'beta': None,
                              'or_value': 1.05,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'COL4A1',
                              'effect_allele': 'A',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'},
                          {   'rsid': 'rs1485305',
                              'chrom': 'chr1',
                              'pos': 24986968,
                              'beta': None,
                              'or_value': 1.05,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'SRRM1',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'},
                          {   'rsid': 'rs1366594',
                              'chrom': 'chr12',
                              'pos': 54201054,
                              'beta': None,
                              'or_value': 1.06,
                              'eaf_eur': None,
                              'eaf_eas': None,
                              'gene': 'MGP',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'variant_class': 'gwas_lead',
                              'contribution_score': 0.16,
                              'confidence': 'high',
                              'note': 'BMD GWAS (Morris 2019 GEFOS)'}],
    'regions': [   {   'chrom': 'chr11',
                       'start': 68377303,
                       'end': 68419422,
                       'gene': 'LRP5',
                       'rtype': 'coding',
                       'source': 'clinical',
                       'note': 'LRP5基因区域 — Wnt共受体;BMD核心基因'},
                   {   'chrom': 'chr13',
                       'start': 42362859,
                       'end': 42468720,
                       'gene': 'TNFRSF11B',
                       'rtype': 'regulatory',
                       'source': 'gwas',
                       'note': 'OPG基因区域 — BMD GWAS最强位点'}],
    'regulatory_regions': [],
    'prs_variants_high': [],
    'prs_variants': [],
    'key_literature': [   {   'pmid': '30617275',
                              'title': 'An atlas of genetic influences on osteoporosis in humans and mice',
                              'note': 'Morris et al. 2019 Nat Genet; GEFOS GWAS ~426K; 518 loci; 骨密度遗传结构'},
                          {   'pmid': '22504420',
                              'title': 'Genome-wide meta-analysis identifies 56 bone mineral density loci and reveals '
                                       '14 loci associated with risk of fracture',
                              'note': 'Estrada et al. 2012 Nat Genet; GEFOS GWAS ~80K; 56 BMD loci'},
                          {   'pmid': '26234160',
                              'title': 'Whole-genome sequencing identifies EN1 as a determinant of bone density and '
                                       'fracture',
                              'note': 'Zheng et al. 2015 Nature; WGS骨质疏松/骨折'}],
        'key_regions': {
        'ALPL': {'note': '碱性磷酸酶域;N端α-螺旋;活性中心Zn/Mg;Phosphoserine intermediate(活性位点,aa110-110);结合位点(aa60-60);结合位点(aa60-60);结合位点(', 'regions': [(110, 110), (60, 60), (60, 60), (110, 110), (173, 173), (235, 235)]},
        'BMP2': {'note': 'TGF-β前体域;TGF-β结构域;Disordered(区,aa84-121);Disordered(区,aa271-293)', 'regions': [(84, 121), (271, 293)]},
        'COL1A1': {'note': '胶原三螺旋重复(Gly-X-Y);N端前肽;C端前肽;VWFC(域,aa38-96);Fibrillar collagen NC1(域,aa1229-1464);Disordered(区,aa98-1', 'regions': [(38, 96), (1229, 1464), (98, 1214), (162, 178), (179, 1192), (1193, 1218)]},
        'COL1A2': {'note': '胶原三螺旋重复;N端前肽;C端前肽;Fibrillar collagen NC1(域,aa1133-1366);Disordered(区,aa28-1130);结合位点(aa1181-1181);结合', 'regions': [(1133, 1366), (28, 1130), (1181, 1181), (1183, 1183), (1184, 1184), (1186, 1186)]},
        'LRP5': {'note': 'YWTD β-螺旋×4;EGF-like×4;LDL受体A类×3;跨膜域;EGF-like 1(域,aa295-337);EGF-like 2(域,aa601-641);EGF-like 3(域,aa', 'regions': [(295, 337), (601, 641), (902, 942), (1213, 1254), (1258, 1296), (1297, 1333)]},
        'LRP6': {'note': 'YWTD-EGF×4;LDLR-A类×3;跨膜域;EGF-like 1(域,aa282-324);EGF-like 2(域,aa588-628);EGF-like 3(域,aa889-930);EGF', 'regions': [(282, 324), (588, 628), (889, 930), (1203, 1244), (1248, 1286), (1287, 1323)]},
        'PLS3': {'note': 'EF-hand×4(钙结合);CH域×2(肌动蛋白结合);EF-hand 1(域,aa12-47);EF-hand 2(域,aa52-87);Calponin-homology (CH) 1(域,aa', 'regions': [(12, 47), (52, 87), (123, 239), (267, 378), (397, 506), (518, 627)]},
        'SOST': {'note': 'Cystine-knot域;CTCK(域,aa82-172);Disordered(区,aa41-71);Disordered(区,aa178-213)', 'regions': [(82, 172), (41, 71), (178, 213)]},
        'VDR': {'note': 'DNA结合锌指×2;配体结合域;AF-2;NR LBD(域,aa127-423);Nuclear receptor(DNA结合,aa21-96);Hinge(区,aa97-126);Disordere', 'regions': [(127, 423), (21, 96), (97, 126), (158, 190), (246, 264), (24, 24)]},
    },
}
