"""Disease template: parkinson disease."""

TEMPLATE_NAME = 'parkinson disease'

TEMPLATE = {'aliases': ['parkinson', "parkinson's disease", 'pd', 'familial parkinson disease'],
 'mode': 'mixed',
 'gene_set': [{'gene': 'SNCA',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病',
               'phenotype_assoc': 'PARK1/4(常显);Lewy体成分;剂量效应',
               'key_domains': 'NAC(61-95);KTKEGV重复;C端尾',
               'clingen_validity': 'Definitive'},
              {'gene': 'LRRK2',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病',
               'phenotype_assoc': 'PARK8(常显);最常见家族性PD;激酶靶点',
               'key_domains': 'ROC-COR;激酶域(1879-2138);WD40',
               'clingen_validity': 'Definitive'},
              {'gene': 'PRKN',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病',
               'phenotype_assoc': 'PARK2(常隐);E3泛素连接酶;线粒体自噬',
               'key_domains': 'UBL;RING0/1/IBR/RING2',
               'clingen_validity': 'Definitive'},
              {'gene': 'PINK1',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病',
               'clingen_validity': 'Definitive'},
              {'gene': 'PARK7',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病',
               'clingen_validity': 'Definitive'},
              {'gene': 'ATP13A2',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病'},
              {'gene': 'PLA2G6',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病'},
              {'gene': 'FBXO7',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病'},
              {'gene': 'DNAJC6',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病'},
              {'gene': 'SYNJ1',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病'},
              {'gene': 'VPS13C',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病'},
              {'gene': 'UCHL1',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病'},
              {'gene': 'VPS35',
               'tier': 'mendelian_high',
               'contribution_score': 0.9,
               'penetrance': '>0.8',
               'penetrance_score': 0.8,
               'evidence': 'familial',
               'note': '常染色体显性或隐性早发性/家族性帕金森病',
               'clingen_validity': 'Strong'},
              {'gene': 'GBA1',
               'tier': 'mendelian_mod',
               'contribution_score': 0.75,
               'penetrance': 'moderate',
               'penetrance_score': 0.3,
               'evidence': 'mixed',
               'note': 'GBA1/葡糖脑苷脂酶，PD最强遗传风险因子之一',
               'phenotype_assoc': 'PD最强风险(~5x);Gaucher(AR)',
               'key_domains': 'TIM-barrel;催化Glu235/Glu340',
               'clingen_validity': 'Definitive (risk factor)'},
              {'gene': 'MAPT',
               'tier': 'mendelian_mod',
               'contribution_score': 0.55,
               'penetrance': 'low_to_moderate',
               'penetrance_score': 0.2,
               'evidence': 'mixed',
               'note': 'MAPT/tau，帕金森叠加综合征风险'},
              {'gene': 'CHCHD2',
               'tier': 'mendelian_mod',
               'contribution_score': 0.6,
               'penetrance': 'moderate',
               'penetrance_score': 0.3,
               'evidence': 'mixed',
               'note': 'CHCHD2，线粒体相关家族性PD'},
              {'gene': 'ASH1L',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'BST1',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'CCDC12',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'CCDC62',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'CCSER1',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'CCT3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'CELF2',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'CTNND1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'DCST1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'DISC1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'FAM47E',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'FCRL2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'GAK',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'INPP5F',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'L1TD1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'LINC02210-CRHR1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'LOC105377331',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'LOC124900602',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'MMRN1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'NOTCH2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'NSF',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'OR9Q1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'PKD2L1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'PLEKHM1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'RAB21',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'RGS10',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'RIT2',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'SCARB2',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'SIPA1L2',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'SLC2A13',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'SREBF1',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'STK39',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'STX1B',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'TMEM175',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'UBQLN4',
               'tier': 'strong_gwas',
               'contribution_score': 0.3,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'PD GWAS位点'},
              {'gene': 'ABCA7',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'ADH1C',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'AFG3L2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'ALS2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'AOPEP',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'AP5Z1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'APOE',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'APP',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'ARVCF',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'ATN1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'ATP1A3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'ATP6AP2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'ATXN2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'ATXN3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'ATXN8OS',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'C19orf12',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'C9orf72',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'CAT',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'CHCHD10',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'CHMP2B',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'CLN3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'CLN5',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'CLN6',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'CLN8',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'COASY',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'COMT',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'COQ2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'CP',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'CSF1R',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'CTSD',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'CYP27A1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'DCTN1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'DNAJC12',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'DNAJC13',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'DNAJC5',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'EIF2AK2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'EIF4G1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'FMR1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'FTL',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'FUS',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'GABRA1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'GABRG2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'GCH1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'GIGYF2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'GP1BB',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'GRN',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'HIRA',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'IMPDH2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'JAM2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'JMJD1C',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'JPH3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'KCNN2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'KIF5A',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'LYST',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'MECP2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'MFSD8',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'MPO',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'MT-TT',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'MYORG',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'NOS3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'NOTCH3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'NR4A2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PANK2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PCBD1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PCDH19',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PDE10A',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PDGFB',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PDGFRB',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PLAU',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'POLG',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PPP2R2B',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PPT1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PRKAR1B',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PRKRA',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PRNP',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PSEN1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PSEN2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'PTS',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'RAB39B',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'RREB1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SCN1A',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SCN1B',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SCN2A',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SCN9A',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SEC24C',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SIGMAR1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SLC18A2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SLC20A2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SLC30A10',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SLC39A14',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SLC6A3',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SNCAIP',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SNCB',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SORL1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SPG11',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SPTLC1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'SQSTM1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'STUB1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TARDBP',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TBK1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TBP',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TBX1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TH',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TMEM106B',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TMEM240',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TNR',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TOMM40',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TPP1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TREM2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TRPM7',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TSPOAP1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'TWNK',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'UBTF',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'UFD1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'VCP',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'VPS13A',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'WARS2',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'WDR45',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'},
              {'gene': 'XPR1',
               'tier': 'gwas',
               'contribution_score': 0.15,
               'penetrance': 'very_low',
               'penetrance_score': 0.05,
               'evidence': 'gwas',
               'note': 'HPO关联基因扩展'}],
 'known_pathogenic_variants': [{'rsid': 'rs104893875',
                                'chrom': 'chr4',
                                'pos': 89828170,
                                'ref': 'C',
                                'alt': 'T',
                                'gene': 'SNCA',
                                'effect_allele': 'T',
                                'other_allele': 'C',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 1.0,
                                'confidence': 'high',
                                'note': 'SNCA p.Ala53Thr; autosomal-dominant Parkinson disease / Lewy body dementia'},
                               {'rsid': 'rs34637584',
                                'chrom': 'chr12',
                                'pos': 40340400,
                                'ref': 'G',
                                'alt': 'A',
                                'gene': 'LRRK2',
                                'effect_allele': 'A',
                                'other_allele': 'G',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.7,
                                'confidence': 'high',
                                'note': 'LRRK2 p.Gly2019Ser; autosomal-dominant Parkinson disease with reduced '
                                        'penetrance (~30-40%)'},
                               {'rsid': 'rs35870237',
                                'chrom': 'chr12',
                                'pos': 40340404,
                                'ref': 'T',
                                'alt': 'C',
                                'gene': 'LRRK2',
                                'effect_allele': 'C',
                                'other_allele': 'T',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.8,
                                'confidence': 'high',
                                'note': 'LRRK2 p.Arg1441Cys; autosomal-dominant Parkinson disease'},
                               {'rsid': 'rs75822236',
                                'chrom': 'chr1',
                                'pos': 155235002,
                                'ref': 'C',
                                'alt': 'T',
                                'gene': 'GBA1',
                                'effect_allele': 'T',
                                'other_allele': 'C',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.5,
                                'confidence': 'high',
                                'note': 'GBA1 p.Asn370Ser; Gaucher disease / strong Parkinson disease risk factor with '
                                        'reduced penetrance'},
                               {'rsid': 'rs80356771',
                                'chrom': 'chr1',
                                'pos': 155235196,
                                'ref': 'G',
                                'alt': 'A',
                                'gene': 'GBA1',
                                'effect_allele': 'A',
                                'other_allele': 'G',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.5,
                                'confidence': 'high',
                                'note': 'GBA1 p.Leu444Pro; Gaucher disease / strong Parkinson disease risk factor with '
                                        'reduced penetrance'},
                               {'rsid': 'rs28938172',
                                'chrom': 'chr1',
                                'pos': 7984981,
                                'ref': 'T',
                                'alt': 'C',
                                'gene': 'PARK7',
                                'effect_allele': 'C',
                                'other_allele': 'T',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 1.0,
                                'confidence': 'high',
                                'note': 'PARK7 p.Ala179Thr; autosomal-recessive early-onset Parkinson disease'},
                               {'rsid': 'rs34424986',
                                'chrom': 'chr6',
                                'pos': 161785820,
                                'ref': 'G',
                                'alt': 'A',
                                'gene': 'PRKN',
                                'effect_allele': 'A',
                                'other_allele': 'G',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 1.0,
                                'confidence': 'high',
                                'note': 'PRKN p.Trp453Ter; autosomal-recessive juvenile Parkinson disease (most PRKN '
                                        'disease is copy-number / frameshift)'},
                               {'rsid': 'rs104893877',
                                'chrom': 'chr4',
                                'pos': 89828149,
                                'ref': 'C',
                                'alt': 'T',
                                'gene': 'SNCA',
                                'effect_allele': 'T',
                                'other_allele': 'C',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 1.0,
                                'confidence': 'high',
                                'note': 'SNCA p.Ala30Pro; 常染色体显性 Parkinson 病 1 型 / Lewy 体痴呆，杂合致病，纯合可能更严重'},
                               {'rsid': 'rs188286943',
                                'chrom': 'chr16',
                                'pos': 46662452,
                                'ref': 'C',
                                'alt': 'T',
                                'gene': 'VPS35',
                                'effect_allele': 'T',
                                'other_allele': 'C',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.75,
                                'confidence': 'high',
                                'note': 'VPS35 p.Asp620Asn; 常染色体显性 Parkinson 病 17 型，杂合致病，中老年起病，外显不完全'},
                               {'rsid': 'rs74315359',
                                'chrom': 'chr1',
                                'pos': 20644651,
                                'ref': 'C',
                                'alt': 'T',
                                'gene': 'PINK1',
                                'effect_allele': 'T',
                                'other_allele': 'C',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 1.0,
                                'confidence': 'high',
                                'note': 'PINK1 p.Gln456Ter; 常染色体隐性早发 Parkinson 病 6 型，纯合/复合杂合致病，杂合携带者风险争议'},
                               {'rsid': 'rs421016',
                                'chrom': 'chr1',
                                'pos': 155235252,
                                'ref': 'A',
                                'alt': 'G',
                                'gene': 'GBA1',
                                'effect_allele': 'G',
                                'other_allele': 'A',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.8,
                                'confidence': 'high',
                                'note': 'GBA1 p.Leu444Pro; heterozygous PD risk ~5x, homozygous Gaucher disease'},
                               {'rsid': 'rs33939927',
                                'chrom': 'chr12',
                                'pos': 40310434,
                                'ref': 'C',
                                'alt': 'T',
                                'gene': 'LRRK2',
                                'effect_allele': 'T',
                                'other_allele': 'C',
                                'or_value': None,
                                'beta': None,
                                'variant_class': 'known_pathogenic',
                                'contribution_score': 0.85,
                                'confidence': 'high',
                                'note': 'LRRK2 p.Arg1441Cys; AD PD8, heterozygous pathogenic, ~70% penetrance'}],
 'regulatory_regions': [],
 'key_regions': {'LRRK2': {'note': 'LRRK2; AD PD8 kinase with reduced penetrance',
                           'regions': [{'name': 'ROC', 'residues': '1335-1510', 'note': 'Ras-of-complex GTPase domain'},
                                       {'name': 'COR',
                                        'residues': '1511-1878',
                                        'note': 'C-terminal of ROC; dimerization domain'},
                                       {'name': 'Kinase',
                                        'residues': '1879-2138',
                                        'note': 'Ser/Thr kinase domain; G2019S hotspot'},
                                       {'name': 'WD40',
                                        'residues': '2139-2527',
                                        'note': 'WD40 repeat domain; protein-protein interactions'}],
                           'critical_residues': [{'residue': 'Gly2019',
                                                  'note': 'G2019S: most common PD pathogenic variant'},
                                                 {'residue': 'Arg1441', 'note': 'R1441C/G/H: GTPase domain mutation'}]},
                 'SNCA': {'note': 'Alpha-synuclein; major Lewy body component; AD PD1/PD4',
                          'regions': [{'name': 'NAC',
                                       'residues': '61-95',
                                       'note': 'Non-Abeta component; aggregation-prone core'},
                                      {'name': 'KTKEGV',
                                       'residues': '1-60',
                                       'note': 'Imperfect KTKEGV repeats; membrane-binding helices'}],
                          'critical_residues': [{'residue': 'Ala53',
                                                 'note': 'A53T/E: early-onset PD1; accelerated aggregation'},
                                                {'residue': 'Ala30', 'note': 'A30P: PD1; alters membrane binding'}]},
                 'GBA1': {'note': 'Glucocerebrosidase; Gaucher disease (AR); strongest PD risk factor',
                          'regions': [{'name': 'TIM-barrel',
                                       'residues': '40-497',
                                       'note': 'Catalytic (beta/alpha)8 fold'},
                                      {'name': 'Active_site',
                                       'residues': '235/340',
                                       'note': 'Glu235 (acid/base) + Glu340 (nucleophile)'}],
                          'critical_residues': [{'residue': 'Leu444', 'note': 'L444P: most common; PD risk ~5x'},
                                                {'residue': 'Asn370', 'note': 'N370S: Ashkenazi; PD risk ~2x'}]}},
 'prs_variants_high': [],
 'prs_variants': [],
 'gwas_lead_snps': [
                    {'rsid': 'rs76763715', 'chrom': 'chr1', 'pos': 155235843, 'beta': -0.7662, 'or_value': None, 'eaf_eur': 0.9982, 'eaf_eas': 1, 'gene': 'GBA', 'tier': 'high_effect', 'contribution_score': 0.45, 'confidence': 'high', 'note': 'GBA1 风险/保护性变异'},
                    {'rsid': 'rs35777901', 'chrom': 'chr1', 'pos': 155467920, 'beta': 0.6174, 'or_value': None, 'eaf_eur': 0.0127, 'eaf_eas': 0.000277, 'gene': 'ASH1L', 'tier': 'high_effect', 'contribution_score': 0.45, 'confidence': 'high', 'note': 'PGS000903 beta=0.6174'},
                    {'rsid': 'rs35749011', 'chrom': 'chr1', 'pos': 155162560, 'beta': 0.6077, 'or_value': None, 'eaf_eur': 0.0129, 'eaf_eas': 0.0002, 'gene': '', 'tier': 'high_effect', 'contribution_score': 0.45, 'confidence': 'high', 'note': 'GBA1 N370S，葡糖脑苷脂酶风险变异'},
                    {'rsid': 'rs9889297', 'chrom': 'chr17', 'pos': 46610330, 'beta': -0.5875, 'or_value': None, 'eaf_eur': 0.0009, 'eaf_eas': None, 'gene': 'NSF', 'tier': 'high_effect', 'contribution_score': 0.45, 'confidence': 'high', 'note': 'PGS000903 beta=-0.5875'},
                    {'rsid': 'rs35603727', 'chrom': 'chr1', 'pos': 156038197, 'beta': 0.4801, 'or_value': None, 'eaf_eur': 0.0163, 'eaf_eas': None, 'gene': 'UBQLN4', 'tier': 'high_effect', 'contribution_score': 0.38, 'confidence': 'high', 'note': 'PGS000903 beta=0.4801'},
                    {'rsid': 'rs187465649', 'chrom': 'chr1', 'pos': 1251453, 'beta': -0.4394, 'or_value': None, 'eaf_eur': 0.0148, 'eaf_eas': 0.000342, 'gene': '', 'tier': 'high_effect', 'contribution_score': 0.38, 'confidence': 'high', 'note': 'PGS000903 beta=-0.4394'},
                    {'rsid': 'rs117896735', 'chrom': 'chr10', 'pos': 119776815, 'beta': 0.4279, 'or_value': None, 'eaf_eur': 0.015, 'eaf_eas': 0.000342, 'gene': 'INPP5F', 'tier': 'high_effect', 'contribution_score': 0.38, 'confidence': 'high', 'note': 'PGS000903 beta=0.4279'},
                    {'rsid': 'rs144296031', 'chrom': 'chr12', 'pos': 40608183, 'beta': -0.3918, 'or_value': None, 'eaf_eur': 0.9851, 'eaf_eas': 0.9998, 'gene': '', 'tier': 'high_effect', 'contribution_score': 0.32, 'confidence': 'high', 'note': 'PGS000903 beta=-0.3918'},
                    {'rsid': 'rs148906682', 'chrom': 'chr10', 'pos': 119501274, 'beta': -0.3907, 'or_value': None, 'eaf_eur': 0.9855, 'eaf_eas': 1, 'gene': 'RGS10', 'tier': 'high_effect', 'contribution_score': 0.32, 'confidence': 'high', 'note': 'PGS000903 beta=-0.3907'},
                    {'rsid': 'rs145447536', 'chrom': 'chr17', 'pos': 45780083, 'beta': -0.3906, 'or_value': None, 'eaf_eur': 0.0163, 'eaf_eas': None, 'gene': 'LINC02210-CRHR1', 'tier': 'high_effect', 'contribution_score': 0.32, 'confidence': 'high', 'note': 'PGS000903 beta=-0.3906'},
                    {'rsid': 'rs140722239', 'chrom': 'chr12', 'pos': 39994307, 'beta': 0.3875, 'or_value': None, 'eaf_eur': 0.0201, 'eaf_eas': 0.0241, 'gene': 'SLC2A13', 'tier': 'high_effect', 'contribution_score': 0.32, 'confidence': 'high', 'note': 'PGS000903 beta=0.3875'},
                    {'rsid': 'rs114797774', 'chrom': 'chr1', 'pos': 161498640, 'beta': 0.3862, 'or_value': None, 'eaf_eur': 0.0196, 'eaf_eas': None, 'gene': '', 'tier': 'high_effect', 'contribution_score': 0.32, 'confidence': 'high', 'note': 'PGS000903 beta=0.3862'},
                    {'rsid': 'rs118150865', 'chrom': 'chr10', 'pos': 100296977, 'beta': 0.3817, 'or_value': None, 'eaf_eur': 0.0484, 'eaf_eas': 0.0376, 'gene': 'PKD2L1', 'tier': 'high_effect', 'contribution_score': 0.32, 'confidence': 'high', 'note': 'PGS000903 beta=0.3817'},
                    {'rsid': 'rs113997642', 'chrom': 'chr4', 'pos': 89889189, 'beta': 0.3754, 'or_value': None, 'eaf_eur': 0.0009, 'eaf_eas': 0.0004, 'gene': 'MMRN1', 'tier': 'high_effect', 'contribution_score': 0.32, 'confidence': 'high', 'note': 'PGS000903 beta=0.3754'},
                    {'rsid': 'rs148838804', 'chrom': 'chr3', 'pos': 46936660, 'beta': -0.3733, 'or_value': None, 'eaf_eur': 0.0196, 'eaf_eas': None, 'gene': 'CCDC12', 'tier': 'high_effect', 'contribution_score': 0.32, 'confidence': 'high', 'note': 'PGS000903 beta=-0.3733'},
                    {'rsid': 'rs17016889', 'chrom': 'chr4', 'pos': 90357394, 'beta': 0.3511, 'or_value': None, 'eaf_eur': 0.0003, 'eaf_eas': None, 'gene': 'CCSER1', 'tier': 'high_effect', 'contribution_score': 0.32, 'confidence': 'high', 'note': 'PGS000903 beta=0.3511'},
                    {'rsid': 'rs35161831', 'chrom': 'chr1', 'pos': 156330940, 'beta': -0.3505, 'or_value': None, 'eaf_eur': 0.9898, 'eaf_eas': 1, 'gene': 'CCT3', 'tier': 'high_effect', 'contribution_score': 0.32, 'confidence': 'high', 'note': 'PGS000903 beta=-0.3505'},
                    {'rsid': 'rs187205660', 'chrom': 'chr1', 'pos': 120013081, 'beta': 0.3455, 'or_value': None, 'eaf_eur': 0.0288, 'eaf_eas': 0.0621, 'gene': 'NOTCH2', 'tier': 'high_effect', 'contribution_score': 0.25, 'confidence': 'high', 'note': 'PGS000903 beta=0.3455'},
                    {'rsid': 'rs112893917', 'chrom': 'chr11', 'pos': 57783447, 'beta': 0.345, 'or_value': None, 'eaf_eur': 0.0115, 'eaf_eas': None, 'gene': 'CTNND1', 'tier': 'high_effect', 'contribution_score': 0.25, 'confidence': 'high', 'note': 'PGS000903 beta=0.345'},
                    {'rsid': 'rs149094961', 'chrom': 'chr4', 'pos': 90111896, 'beta': 0.3361, 'or_value': None, 'eaf_eur': 0.0071, 'eaf_eas': None, 'gene': '', 'tier': 'high_effect', 'contribution_score': 0.25, 'confidence': 'high', 'note': 'PGS000903 beta=0.3361'},
                    {'rsid': 'rs10516845', 'chrom': 'chr4', 'pos': 89763127, 'beta': -0.3359, 'or_value': None, 'eaf_eur': 0.8987, 'eaf_eas': 0.454, 'gene': 'SNCA', 'tier': 'high_effect', 'contribution_score': 0.25, 'confidence': 'high', 'note': 'SNCA 3UTR; EAS AF=0.45 vs EUR=0.90, large EAS divergence'},
                    {'rsid': 'rs17795424', 'chrom': 'chr4', 'pos': 89751992, 'beta': 0.3266, 'or_value': None, 'eaf_eur': 0.9932, 'eaf_eas': 1, 'gene': 'SNCA', 'tier': 'high_effect', 'contribution_score': 0.25, 'confidence': 'high', 'note': 'SNCA位点，PD GWAS信号'},
                    {'rsid': 'rs200789118', 'chrom': 'chr1', 'pos': 62210001, 'beta': 0.317, 'or_value': None, 'eaf_eur': None, 'eaf_eas': None, 'gene': 'L1TD1', 'tier': 'high_effect', 'contribution_score': 0.25, 'confidence': 'high', 'note': 'PGS000903 beta=0.317'},
                    {'rsid': 'rs34268490', 'chrom': 'chr2', 'pos': 168166753, 'beta': -0.3143, 'or_value': None, 'eaf_eur': 0.9922, 'eaf_eas': 1, 'gene': 'STK39', 'tier': 'high_effect', 'contribution_score': 0.25, 'confidence': 'high', 'note': 'PGS000903 beta=-0.3143'},
                    {'rsid': 'rs71609574', 'chrom': 'chr4', 'pos': 89706816, 'beta': -0.3132, 'or_value': None, 'eaf_eur': 0.0103, 'eaf_eas': 0.0006, 'gene': 'LOC124900602', 'tier': 'high_effect', 'contribution_score': 0.25, 'confidence': 'high', 'note': 'PGS000903 beta=-0.3132'},
                    {'rsid': 'rs74390872', 'chrom': 'chr4', 'pos': 89697881, 'beta': 0.3044, 'or_value': None, 'eaf_eur': 0.0161, 'eaf_eas': 0.3138, 'gene': 'LOC124900602', 'tier': 'high_effect', 'contribution_score': 0.25, 'confidence': 'high', 'note': 'PGS000903 beta=0.3044'},
                    {'rsid': 'rs17442143', 'chrom': 'chr12', 'pos': 40044167, 'beta': -0.3026, 'or_value': None, 'eaf_eur': 0.9815, 'eaf_eas': 0.9998, 'gene': 'SLC2A13', 'tier': 'high_effect', 'contribution_score': 0.25, 'confidence': 'high', 'note': 'PGS000903 beta=-0.3026'},
                    {'rsid': 'rs146092449', 'chrom': 'chr17', 'pos': 45438809, 'beta': -0.2917, 'or_value': None, 'eaf_eur': 0.0023, 'eaf_eas': None, 'gene': 'PLEKHM1', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'PGS000903 beta=-0.2917'},
                    {'rsid': 'rs148371284', 'chrom': 'chr10', 'pos': 13273397, 'beta': 0.2842, 'or_value': None, 'eaf_eur': 0.0136, 'eaf_eas': None, 'gene': '', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'PGS000903 beta=0.2842'},
                    {'rsid': 'rs61754230', 'chrom': 'chr12', 'pos': 71785666, 'beta': 0.2839, 'or_value': None, 'eaf_eur': 0.0059, 'eaf_eas': None, 'gene': 'RAB21', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'PGS000903 beta=0.2839'},
                    {'rsid': 'rs185418056', 'chrom': 'chr1', 'pos': 112383292, 'beta': -0.283, 'or_value': None, 'eaf_eur': 0.0102, 'eaf_eas': None, 'gene': '', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'PGS000903 beta=-0.283'},
                    {'rsid': 'rs72874309', 'chrom': 'chr4', 'pos': 90046189, 'beta': 0.2829, 'or_value': None, 'eaf_eur': 0.0076, 'eaf_eas': 0.0226, 'gene': 'LOC105377331', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'PGS000903 beta=0.2829'},
                    {'rsid': 'rs7134935', 'chrom': 'chr12', 'pos': 123439065, 'beta': 0.2771, 'or_value': None, 'eaf_eur': 0.01, 'eaf_eas': None, 'gene': '', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'PGS000903 beta=0.2771'},
                    {'rsid': 'rs356182', 'chrom': 'chr4', 'pos': 89704960, 'beta': -0.2764, 'or_value': None, 'eaf_eur': 0.6489, 'eaf_eas': 0.3385, 'gene': 'LOC124900602', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'SNCA; EAS AF=0.34 vs EUR=0.65, significant divergence'},
                    {'rsid': 'rs78491631', 'chrom': 'chr11', 'pos': 58102747, 'beta': 0.2761, 'or_value': None, 'eaf_eur': 0.0076, 'eaf_eas': None, 'gene': 'OR9Q1', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'PGS000903 beta=0.2761'},
                    {'rsid': 'rs146143531', 'chrom': 'chr1', 'pos': 155042492, 'beta': -0.2741, 'or_value': None, 'eaf_eur': 0.9912, 'eaf_eas': 1, 'gene': 'DCST1', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'PGS000903 beta=-0.2741'},
                    {'rsid': 'rs62053943', 'chrom': 'chr17', 'pos': 45666837, 'beta': -0.271, 'or_value': None, 'eaf_eur': 0.0494, 'eaf_eas': 0.0012, 'gene': 'LINC02210-CRHR1', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'PGS000903 beta=-0.271'},
                    {'rsid': 'rs143068046', 'chrom': 'chr1', 'pos': 157751743, 'beta': -0.2663, 'or_value': None, 'eaf_eur': 0.9886, 'eaf_eas': 0.9998, 'gene': 'FCRL2', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'PGS000903 beta=-0.2663'},
                    {'rsid': 'rs192200577', 'chrom': 'chr1', 'pos': 232025751, 'beta': 0.2638, 'or_value': None, 'eaf_eur': 0.991, 'eaf_eas': 0.9981, 'gene': 'DISC1', 'tier': 'gwas', 'contribution_score': 0.2, 'confidence': 'high', 'note': 'PGS000903 beta=0.2638'}],
 'regions': [{'chrom': 'chr4',
              'start': 89650000,
              'end': 89850000,
              'gene': 'SNCA',
              'type': 'gwas_locus',
              'contribution_score': 0.4,
              'note': 'SNCA alpha-突触核蛋白基因座'},
             {'chrom': 'chr12',
              'start': 40330000,
              'end': 40350000,
              'gene': 'LRRK2',
              'type': 'coding_exon',
              'contribution_score': 0.5,
              'note': 'LRRK2 G2019S/致病突变区'},
             {'chrom': 'chr1',
              'start': 155100000,
              'end': 155300000,
              'gene': 'GBA1',
              'type': 'gwas_locus',
              'contribution_score': 0.45,
              'note': 'GBA1 帕金森风险位点'},
             {'chrom': 'chr17',
              'start': 45800000,
              'end': 46000000,
              'gene': 'MAPT',
              'type': 'gwas_locus',
              'contribution_score': 0.3,
              'note': 'MAPT/tau 帕金森叠加风险位点'}],
 'key_literature': [{'pmid': '30617015',
                     'title': "Identification of novel risk loci, causal insights, and heritable risk for Parkinson's "
                              'disease: a meta-analysis of genome-wide association studies.',
                     'genes': ['SNCA',
                               'LRRK2',
                               'GBA1',
                               'MAPT',
                               'BST1',
                               'TMEM175',
                               'CCDC62',
                               'RIT2',
                               'STX1B',
                               'SREBF1',
                               'CELF2',
                               'SIPA1L2',
                               'INPP5F',
                               'GAK'],
                     'note': 'Nalls et al., Lancet Neurol 2019 (PGS000903)',
                     'evidence_type': 'gwas'},
                    {'pmid': '37938789',
                     'title': "Multi-ancestry genome-wide association meta-analysis of Parkinson's disease.",
                     'genes': ['SNCA', 'LRRK2', 'GBA1', 'MAPT', 'BST1', 'TMEM175', 'CCDC62'],
                     'note': 'Kim et al., Nat Genet 2024',
                     'evidence_type': 'gwas'},
                    {'pmid': '16406073',
                     'title': 'PINK1 mutations are associated with sporadic early-onset parkinsonism.',
                     'genes': ['PINK1'],
                     'note': 'Valente et al., Science 2004',
                     'evidence_type': 'familial'},
                    {'pmid': '18509534',
                     'title': 'Mutations in LRRK2 cause autosomal-dominant parkinsonism with pleomorphic pathology.',
                     'genes': ['LRRK2'],
                     'note': 'Zimprich et al., Neuron 2004',
                     'evidence_type': 'familial'},
                    {'pmid': '16909391',
                     'title': "Multicenter analysis of glucocerebrosidase mutations in Parkinson's disease.",
                     'genes': ['GBA1'],
                     'note': 'Sidransky et al., N Engl J Med 2009',
                     'evidence_type': 'rare_variant_functional'},
                    {'pmid': '12802786',
                     'title': 'PARK7 DJ-1 mutations cause autosomal-recessive early-onset parkinsonism.',
                     'genes': ['PARK7'],
                     'note': 'Bonifati et al., Am J Hum Genet 2003',
                     'evidence_type': 'familial'},
                    {'pmid': '31701892',
                     'title': 'Identification of novel risk loci, causal insights, and heritable risk for Parkinsons '
                              'disease.',
                     'genes': ['SNCA', 'LRRK2', 'GBA1', 'TMEM175', 'GAK', 'BST1', 'RIT2'],
                     'note': 'Nalls et al., Lancet Neurol 2019 (largest PD GWAS meta-analysis, 90 loci)',
                     'evidence_type': 'gwas'}],
 'core_genes': ['SNCA',
                'LRRK2',
                'PRKN',
                'PINK1',
                'PARK7',
                'ATP13A2',
                'PLA2G6',
                'FBXO7',
                'DNAJC6',
                'SYNJ1',
                'VPS13C',
                'UCHL1',
                'VPS35',
                'GBA1',
                'MAPT',
                'CHCHD2'],
 'gwas_loci_genes': ['ASH1L',
                     'BST1',
                     'CCDC12',
                     'CCDC62',
                     'CCSER1',
                     'CCT3',
                     'CELF2',
                     'CTNND1',
                     'DCST1',
                     'DISC1',
                     'FAM47E',
                     'FCRL2',
                     'GAK',
                     'INPP5F',
                     'L1TD1',
                     'LINC02210-CRHR1',
                     'LOC105377331',
                     'LOC124900602',
                     'MMRN1',
                     'NOTCH2',
                     'NSF',
                     'OR9Q1',
                     'PKD2L1',
                     'PLEKHM1',
                     'RAB21',
                     'RGS10',
                     'RIT2',
                     'SCARB2',
                     'SIPA1L2',
                     'SLC2A13',
                     'SREBF1',
                     'STK39',
                     'STX1B',
                     'TMEM175',
                     'UBQLN4']}
