"""Disease template: prostate cancer / 前列腺癌."""

TEMPLATE_NAME = 'prostate cancer'
TEMPLATE = {
    'aliases': [
        'prostate cancer',
        'prostate',
        'prostatic cancer',
        'prostatic carcinoma',
        'prostate adenocarcinoma',
        'prostate neoplasm',
        'hereditary prostate cancer',
        'familial prostate cancer',
        'pca',
        '前列腺癌',
        '前列腺',
        '前列腺肿瘤',
        '前列腺恶性肿瘤',
        '家族性前列腺癌',
        '遗传性前列腺癌',
    ],
    'mode': 'complex',
    'gene_set': [
        # ═══ Mendelian High (germline predisposition with high prostate cancer penetrance) ═══
        {
            'gene': 'BRCA2',
            'tier': 'mendelian_high',
            'contribution_score': 1.0,
            'penetrance': 'high',
            'penetrance_score': 0.7,
            'evidence': 'familial',
            'note': 'HBOC/FA-D1(AD); BRCA2胚系LOF→前列腺癌风险~5-8×(最高); 早发性(<65岁)和侵袭性前列腺癌关联最强; 胚系BRCA2阳性~2-3%未选择前列腺癌患者; PARPi获益; 终身风险~20-30%; BRCA2截短→Gleason≥8风险增高',
            'phenotype_assoc': 'HBOC(AD);BRCA2-LOF→前列腺癌5-8x;早发/侵袭性;Gleason≥8;PARPi;终身风险20-30%',
            'key_domains': 'BRC重复×8(RAD51结合,aa1002-2051);OB-fold×3(aa2670-3181,DNA结合);NLS;TR2(C端)',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'HOXB13',
            'tier': 'mendelian_high',
            'contribution_score': 0.9,
            'penetrance': 'high',
            'penetrance_score': 0.65,
            'evidence': 'familial',
            'note': '家族性前列腺癌(AD); HOXB13 G84E(北欧创始人变异, 杂合→风险~3-5×, 终身~33-60%); 其他罕见错义变异也有报道; HOXB13是同源框转录因子, 前列腺发育关键调控; 主要见于欧洲裔(~0.1-1.5%携带率), 东亚罕见',
            'phenotype_assoc': 'HPC(AD);HOXB13 G84E→前列腺癌3-5x;北欧创始人;前列腺发育调控;同源框转录因子',
            'key_domains': 'MEIS互作域(aa1-130);同源框DNA结合域(aa218-277):螺旋-转角-螺旋;HOX蛋白C端',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'BRCA1',
            'tier': 'mendelian_high',
            'contribution_score': 0.8,
            'penetrance': 'moderate',
            'penetrance_score': 0.4,
            'evidence': 'familial',
            'note': 'HBOC(AD); BRCA1-LOF→前列腺癌风险~2-3×(低于BRCA2); 同样与早发/侵袭性前列腺癌相关; PARPi获益; BRCA1对前列腺癌的外显率低于乳腺癌/卵巢癌; 终身风险~10-15%',
            'phenotype_assoc': 'HBOC(AD);BRCA1-LOF→前列腺癌2-3x;低于BRCA2但早发/侵袭;PARPi',
            'key_domains': 'RING域(aa1-109):E3泛素连接酶;BARD1异源二聚化;BRCT×2(aa1646-1863):磷酸肽结合;DNA损伤应答',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'ATM',
            'tier': 'mendelian_high',
            'contribution_score': 0.75,
            'penetrance': 'moderate',
            'penetrance_score': 0.4,
            'evidence': 'familial',
            'note': '共济失调毛细血管扩张症(AR杂合携带者→AD癌症易感); ATM杂合LOF→前列腺癌风险~2-3×; 较常见携带(人群~0.5-1%); 与放射敏感性相关; PARPi可能获益; DNA损伤应答核心激酶',
            'phenotype_assoc': 'AT杂合(AD癌症易感);ATM-LOF→前列腺癌2-3x;DNA修复/PIKK;PARPi;放射敏感性',
            'key_domains': 'FAT域(N端);PI3K样催化域(aa2712-2962):PIKK超家族;FATC域;HEAT重复;kinase域',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'CHEK2',
            'tier': 'mendelian_high',
            'contribution_score': 0.7,
            'penetrance': 'moderate',
            'penetrance_score': 0.35,
            'evidence': 'familial',
            'note': 'Li-Fraumeni谱系(AD); CHEK2-LOF→前列腺癌风险~2×; CHEK2 1100delC(欧洲创始人)及其他截短; 多癌症易感(乳腺/结肠/前列腺); 细胞周期检查点激酶→p53/BRCA1磷酸化',
            'phenotype_assoc': 'CHEK2癌症易感(AD);1100delC→前列腺癌~2x;多癌种(乳腺/结肠/前列腺);CHK2激酶',
            'key_domains': 'SQ/TQ簇域(aa1-90);FHA域(aa92-205):磷酸肽结合;激酶域(aa220-486):Ser/Thr激酶',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'MSH2',
            'tier': 'mendelian_high',
            'contribution_score': 0.7,
            'penetrance': 'moderate',
            'penetrance_score': 0.35,
            'evidence': 'familial',
            'note': 'Lynch综合征(AD); MSH2-LOF→前列腺癌风险~2-4×; 错配修复缺陷→MSI-H/dMMR前列腺癌; 免疫治疗获益(Pembrolizumab); 常与泌尿道上皮癌共存; 终身前列腺癌风险~8-24%',
            'phenotype_assoc': 'Lynch(AD);MSH2→MMR缺陷→前列腺癌2-4x;MSI-H/dMMR;抗PD-1免疫治疗;尿路上皮',
            'key_domains': 'DNA错配结合域(aa1-200);ATP酶域(aa500-850):MutS家族;MSH6/MSH3互作域',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'MSH6',
            'tier': 'mendelian_high',
            'contribution_score': 0.6,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'familial',
            'note': 'Lynch综合征(AD); MSH6-LOF→前列腺癌风险~2-3×(低于MSH2); 更常见子宫内膜癌; MMR缺陷→MSI-H/dMMR→免疫治疗',
            'phenotype_assoc': 'Lynch(AD);MSH6→MMR→前列腺癌~2-3x;子宫内膜癌;MSI-H免疫治疗',
            'key_domains': 'PWWP域(N端);MutS域(错配结合,aa300-800);ATPase域(aa900-1360)',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'PALB2',
            'tier': 'mendelian_high',
            'contribution_score': 0.65,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'familial',
            'note': 'FA-N/HBOC(AD/AR); PALB2-LOF→前列腺癌风险~2×(低于BRCA2); BRCA2功能伙伴(FANCN); 乳腺癌/胰腺癌风险增高更显著; DNA链间交联修复',
            'phenotype_assoc': 'FA-N/HBOC;PALB2→前列腺癌~2x;FANCN;BRCA2伙伴;乳腺癌/胰腺癌更显著',
            'key_domains': '卷曲螺旋域(aa9-44):BRCA1结合;WD40重复×7(aa852-1186):BRCA2/RAD51结合;ChAM域',
            'clingen_validity': 'Definitive',
        },

        # ═══ Mendelian Moderate (moderate prostate cancer risk) ═══
        {
            'gene': 'MLH1',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'familial',
            'note': 'Lynch综合征(AD); MLH1-LOF→前列腺癌风险~2×; 最常见Lynch基因; 结直肠癌/子宫内膜癌风险远高于前列腺; MMR缺陷',
            'phenotype_assoc': 'Lynch(AD);MLH1→MMR→前列腺癌~2x;CRC/EC主导;MSI-H免疫治疗',
            'key_domains': 'ATPase域(aa1-350):GHKL家族;MutL C端域(aa500-756):PMS2二聚化;DNA结合',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'PMS2',
            'tier': 'mendelian_mod',
            'contribution_score': 0.5,
            'penetrance': 'low_to_moderate',
            'penetrance_score': 0.25,
            'evidence': 'familial',
            'note': 'Lynch综合征(AD); PMS2-LOF→癌症风险整体低于MSH2/MLH1; 前列腺癌风险~1.5-2×; MMR MutLα复合体(MLH1-PMS2异源二聚体)',
            'phenotype_assoc': 'Lynch(AD);PMS2→MMR→低外显;前列腺癌~2x;MutLα复合体',
            'key_domains': 'ATPase域(aa1-300);MutL C端域(aa600-862):MLH1二聚化;内切酶域(含DQHA(X)2E(X)4E基序)',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'NBN',
            'tier': 'mendelian_mod',
            'contribution_score': 0.55,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'familial',
            'note': 'Nijmegen断裂综合征(AR杂合→AD癌症易感); NBN/NBS1杂合LOF→前列腺癌风险~2×; MRE11-RAD50-NBN(MRN)复合体→DNA双链断裂修复/ATM信号; 多见于中欧/东欧人群',
            'phenotype_assoc': 'NBS杂合(AD);NBN→MRN→DSB修复→前列腺癌2x;中欧/东欧创始人;ATM信号',
            'key_domains': 'FHA域(aa24-110):磷酸肽结合;BRCT×2(aa110-400):ATM/MRE11结合;MRE11结合域',
            'clingen_validity': 'Definitive',
        },
        {
            'gene': 'RAD51D',
            'tier': 'mendelian_mod',
            'contribution_score': 0.5,
            'penetrance': 'moderate',
            'penetrance_score': 0.25,
            'evidence': 'familial',
            'note': '卵巢癌易感(AD); RAD51D-LOF→前列腺癌风险~2×(较新证据); RAD51旁系同源→同源重组修复; PARPi可能获益; 卵巢癌为主要关联',
            'phenotype_assoc': '卵巢癌(AD);RAD51D→同源重组→前列腺癌2x;RAD51旁系同源;PARPi',
            'key_domains': 'Walker A/B ATPase基序(aa90-300):RecA/RAD51家族;DNA结合环L1/L2;RAD51C互作域',
            'clingen_validity': 'Strong',
        },
        {
            'gene': 'TP53',
            'tier': 'mendelian_mod',
            'contribution_score': 0.65,
            'penetrance': '>0.80',
            'penetrance_score': 0.8,
            'evidence': 'familial',
            'note': 'Li-Fraumeni综合征(AD); TP53-LOF→广谱癌症易感+前列腺癌风险~2-3×; 前列腺癌在LFS中非主导癌种(肉瘤/乳腺癌/脑瘤/肾上腺皮质癌为主); 放射治疗需格外谨慎(放射致二次肿瘤风险)',
            'phenotype_assoc': 'LFS(AD);TP53→多肿瘤→前列腺癌2-3x;放射禁忌;DBD突变热点',
            'key_domains': 'TAD1(aa1-42);TAD2(aa43-63);DBD(aa102-292):核心DNA结合域;四聚化域(aa323-356)',
            'clingen_validity': 'Definitive',
        },

        # ═══ Strong GWAS / moderate evidence ═══
        {
            'gene': 'EPCAM',
            'tier': 'mendelian_mod',
            'contribution_score': 0.5,
            'penetrance': 'moderate',
            'penetrance_score': 0.3,
            'evidence': 'familial',
            'note': 'Lynch综合征(AD, EPCAM 3\'缺失→MSH2表观遗传沉默); EPCAM-LOF→MSH2启动子甲基化→Lynch表型; 前列腺癌风险同MSH2相关Lynch; 结直肠癌优势',
            'phenotype_assoc': 'Lynch(AD);EPCAM缺失→MSH2沉默→MMR→前列腺癌~2x;CRC主导',
            'key_domains': 'EPCAM胞外域(aa1-265):上皮细胞黏附;跨膜域(aa266-288);EpEX域(EpCAM胞外域脱落);EpICD(胞内域)',
            'clingen_validity': 'Definitive',
        },

        # ═══ GWAS — common variants ═══
        {
            'gene': 'MYC',
            'tier': 'strong_gwas',
            'contribution_score': 0.3,
            'penetrance': 'very_low',
            'penetrance_score': 0.05,
            'evidence': 'gwas',
            'note': '8q24区域(距MYC ~500kb) — 前列腺癌GWAS最强信号; 多个独立风险位点(region1/2/3); rs6983267(G等位基因→风险~1.3×/等位基因, 欧洲); 东亚人群效应量相似; 增强子元件调控MYC表达',
            'phenotype_assoc': '8q24/MYC;前列腺癌GWAS最强;rs6983267→1.3x;增强子→MYC;多独立位点;欧洲+东亚',
            'key_domains': '(非编码调控区域,距MYC基因~500kb);MYC: bHLH域(aa354-433):MAX二聚化+DNA结合;转录激活域',
            'clingen_validity': '',
        },
        {
            'gene': 'TMPRSS2',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.02,
            'evidence': 'gwas',
            'note': 'AR调控的跨膜丝氨酸蛋白酶; 前列腺特异性表达; 胚系变异→前列腺癌风险(rs12329760); 体细胞TMPRSS2-ERG融合是前列腺癌最常见基因重排(~50%)',
            'phenotype_assoc': 'TMPRSS2;前列腺特异性;AR靶基因;rs12329760→GWAS;体细胞TMPRSS2-ERG融合~50%',
            'key_domains': '胞外域(aa106-492):Ⅱ型跨膜丝氨酸蛋白酶;SRCR域;LDL受体A类域;C端催化域',
            'clingen_validity': '',
        },
        {
            'gene': 'KLK3',
            'tier': 'gwas',
            'contribution_score': 0.15,
            'penetrance': 'very_low',
            'penetrance_score': 0.02,
            'evidence': 'gwas',
            'note': 'PSA/kallikrein-3编码基因; 前列腺特异性丝氨酸蛋白酶; rs2735839→前列腺癌风险GWAS; PSA用于前列腺癌筛查; KLK3变异影响PSA水平→可能混淆筛查',
            'phenotype_assoc': 'KLK3/PSA;前列腺特异性;rs2735839→GWAS;PSA筛查相关;丝氨酸蛋白酶',
            'key_domains': '前体域(aa1-24);催化域(aa25-261):Ser-His-Asp催化三联体;kallikrein环',
            'clingen_validity': '',
        },
    ],
    'known_pathogenic_variants': [
        # BRCA2 — most important prostate cancer predisposition gene
        {
            'rsid': 'rs80359618',
            'chrom': 'chr13',
            'pos': 32332468,
            'ref': 'T',
            'alt': 'TG',
            'gene': 'BRCA2',
            'effect_allele': 'TG',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 1.0,
            'confidence': 'high',
            'note': 'BRCA2 c.5946delT (6174delT) — Ashkenazi犹太创始人; 截短突变; 前列腺癌~5-8×; ClinVar Pathogenic ★★★',
        },
        # HOXB13 G84E — European founder
        {
            'rsid': 'rs138213197',
            'chrom': 'chr17',
            'pos': 48730391,
            'ref': 'G',
            'alt': 'A',
            'gene': 'HOXB13',
            'effect_allele': 'A',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.9,
            'confidence': 'high',
            'note': 'HOXB13 G84E (c.251G>A) — 北欧创始人变异; 前列腺癌~3-5×; 欧洲裔~0.5-1.5%携带率; ClinVar Pathogenic ★★★',
        },
        # CHEK2 1100delC
        {
            'rsid': 'rs555607708',
            'chrom': 'chr22',
            'pos': 28695873,
            'ref': 'T',
            'alt': 'TC',
            'gene': 'CHEK2',
            'effect_allele': 'TC',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.7,
            'confidence': 'high',
            'note': 'CHEK2 1100delC — 欧洲创始人; 前列腺癌~2×; 多癌症易感; ClinVar Pathogenic ★★★',
        },
        # ATM — common pathogenic variant
        {
            'rsid': 'rs587782449',
            'chrom': 'chr11',
            'pos': 108317017,
            'ref': 'C',
            'alt': 'CT',
            'gene': 'ATM',
            'effect_allele': 'CT',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.75,
            'confidence': 'high',
            'note': 'ATM c.7271T>G (V2424G) — 错义突变; ATM杂合→前列腺癌~2-3×; ClinVar Pathogenic',
        },
        # TP53 — classic Li-Fraumeni
        {
            'rsid': 'rs28934576',
            'chrom': 'chr17',
            'pos': 7675088,
            'ref': 'C',
            'alt': 'T',
            'gene': 'TP53',
            'effect_allele': 'T',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.65,
            'confidence': 'high',
            'note': 'TP53 R273H — DBD热点; LFS经典致病变异; 前列腺癌~2-3×; ClinVar Pathogenic ★★★',
        },
        # BRCA1 Ashkenazi founder
        {
            'rsid': 'rs80357547',
            'chrom': 'chr17',
            'pos': 43092938,
            'ref': 'A',
            'alt': 'AG',
            'gene': 'BRCA1',
            'effect_allele': 'AG',
            'or_value': None,
            'beta': None,
            'variant_class': 'known_pathogenic',
            'contribution_score': 0.8,
            'confidence': 'high',
            'note': 'BRCA1 c.68_69delAG (185delAG) — Ashkenazi创始人; 卵巢癌/乳腺癌; 前列腺癌~2-3×',
        },
    ],
    'gwas_lead_snps': [
        # 8q24 — strongest prostate cancer GWAS signal
        {
            'rsid': 'rs6983267',
            'chrom': '8',
            'pos': 127401060,
            'beta': None,
            'or_value': 1.26,
            'eaf_eur': 0.50,
            'eaf_eas': 0.40,
            'gene': 'MYC',
            'effect_allele': 'G',
            'other_allele': 'T',
            'variant_class': 'gwas_lead',
            'contribution_score': 0.3,
            'confidence': 'high',
            'note': '8q24 Region 3 — 前列腺癌GWAS最强信号; MYC增强子元件; PRACTICAL 2018',
        },
        # KLK3/PSA region
        {
            'rsid': 'rs2735839',
            'chrom': '19',
            'pos': 50846683,
            'beta': None,
            'or_value': 1.20,
            'eaf_eur': 0.15,
            'eaf_eas': 0.30,
            'gene': 'KLK3',
            'effect_allele': 'A',
            'other_allele': 'G',
            'variant_class': 'gwas_lead',
            'contribution_score': 0.2,
            'confidence': 'high',
            'note': 'KLK3 (PSA) — 前列腺癌GWAS; 影响PSA水平; PRACTICAL 2018',
        },
        # TMPRSS2
        {
            'rsid': 'rs12329760',
            'chrom': '21',
            'pos': 41469544,
            'beta': None,
            'or_value': 1.15,
            'eaf_eur': 0.25,
            'eaf_eas': 0.35,
            'gene': 'TMPRSS2',
            'effect_allele': 'T',
            'other_allele': 'C',
            'variant_class': 'gwas_lead',
            'contribution_score': 0.15,
            'confidence': 'moderate',
            'note': 'TMPRSS2 — 错义V160M; 前列腺癌GWAS; PRACTICAL 2021',
        },
    ],
    'regions': [
        {
            'chrom': 'chr13',
            'start': 32315086,
            'end': 32400266,
            'gene': 'BRCA2',
            'rtype': 'coding',
            'source': 'clinical',
            'note': 'BRCA2基因区域 — 前列腺癌最强胚系易感基因; 5-8×风险; PARPi治疗靶点',
        },
        {
            'chrom': 'chr17',
            'start': 48728000,
            'end': 48733000,
            'gene': 'HOXB13',
            'rtype': 'coding',
            'source': 'clinical',
            'note': 'HOXB13基因区域 — G84E北欧创始人变异; 家族性前列腺癌; 同源框转录因子',
        },
        {
            'chrom': 'chr17',
            'start': 43044295,
            'end': 43125483,
            'gene': 'BRCA1',
            'rtype': 'coding',
            'source': 'clinical',
            'note': 'BRCA1基因区域 — HBOC; 前列腺癌2-3×; PARPi',
        },
        {
            'chrom': 'chr8',
            'pos': 127400000,
            'start': 127400000,
            'end': 127410000,
            'gene': 'MYC',
            'rtype': 'regulatory',
            'source': 'gwas',
            'note': '8q24 — 前列腺癌GWAS最强区域; MYC增强子元件; 多个独立风险位点',
        },
    ],
    'regulatory_regions': [],
    'prs_variants_high': [],
    'prs_variants': [],
    'key_literature': [
        {
            'pmid': '29892016',
            'title': 'Association analyses of more than 140,000 men identify 63 new prostate cancer susceptibility loci',
            'note': 'Schumacher et al. 2018 Nat Genet; PRACTICAL GWAS ~140K; 63 new loci; 总共>160 loci',
        },
        {
            'pmid': '34373979',
            'title': 'Trans-ancestry genome-wide association meta-analysis of prostate cancer identifies new susceptibility loci and informs genetic risk prediction',
            'note': 'Conti et al. 2021 Nat Genet; PRACTICAL跨种族GWAS ~235K; 86 new loci; 多基因风险评分',
        },
        {
            'pmid': '32300258',
            'title': 'Germline mutations in prostate cancer: a systematic review and meta-analysis',
            'note': 'Pritchard et al. 2020; 胚系突变荟萃; BRCA2/GATA2/ATM/CHEK2 DNA修复基因; 11.8%转移性前列腺癌携带胚系突变',
        },
        {
            'pmid': '27433846',
            'title': 'Inherited DNA-repair gene mutations in men with metastatic prostate cancer',
            'note': 'Pritchard et al. 2016 NEJM; 转移性前列腺癌11.8%胚系DNA修复基因突变; BRCA2最显著; PARPi获益',
        },
        {
            'pmid': '32040552',
            'title': 'BRCA mutations and prostate cancer: diagnostic and therapeutic implications',
            'note': 'Mateo et al. 2020; BRCA1/2胚系突变→侵袭性前列腺癌; PARP抑制剂olaparib/rucaparib; 铂类化疗',
        },
        {
            'pmid': '22236224',
            'title': 'Germline mutations in HOXB13 and prostate-cancer risk',
            'note': 'Ewing et al. 2012 NEJM; HOXB13 G84E→家族性前列腺癌~3-5×; 北欧创始人',
        },
    ],
}
