"""Type 2 Diabetes disease template.

Source: Mahajan et al. 2018 (Nat Genet), DIAGRAM Consortium,
MODY from ClinVar + OMIM, PPARG Pro12Ala, KCNJ11 E23K.

TEMPLATE_NAME is the canonical key used in DISEASE_BUILTIN_REFS.
"""

TEMPLATE_NAME = "type 2 diabetes"

TEMPLATE = {   'aliases': ['type 2 diabetes', 't2d', 'diabetes mellitus type 2', 'niddm', 'adult-onset diabetes'],
    'mode': 'complex',
    'gene_set': [   {   'gene': 'HNF1A',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.75,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.35,
                        'evidence': 'monogenic',
                        'note': 'MODY3; 最常见MODY(~52%); 杂合致病变异->早发beta细胞功能障碍',
                        'phenotype_assoc': 'MODY3;常显;早发非胰岛素依赖糖尿病',
                        'key_domains': '二聚化域(aa1-32);DNA结合POU域(aa99-280);转录激活域(aa281-631)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'HNF4A',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.7,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'monogenic',
                        'note': 'MODY1; 转录因子;杂合突变->胰岛素分泌缺陷',
                        'phenotype_assoc': 'MODY1;常显;进行性beta细胞衰竭;HNF1A上游调控因子',
                        'key_domains': 'AF-1域(aa1-54);DNA结合锌指(aa55-133);配体结合域(aa134-374);AF-2(aa456-474)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'GCK',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.65,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'monogenic',
                        'note': 'MODY2; 葡萄糖激酶;杂合->轻度空腹高血糖;纯合->新生儿糖尿病',
                        'phenotype_assoc': 'MODY2;常显;轻度稳定高血糖;微血管并发症风险低',
                        'key_domains': 'ATP结合域(aa155-200);葡萄糖结合域(aa210-260);铰链区(aa68-100)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'HNF1B',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.7,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'monogenic',
                        'note': 'MODY5; 转录因子;杂合突变->糖尿病+肾囊肿+胰腺萎缩',
                        'phenotype_assoc': 'MODY5;常显;糖尿病+肾囊肿+泌尿生殖异常;HNF1B缺失(17q12)',
                        'key_domains': '二聚化域(aa1-32);POU特异性域(aa99-180);POU同源域(aa227-286)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'ABCC8',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.65,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'monogenic',
                        'note': 'MODY12; SUR1/KATP通道;杂合->糖尿病;纯合LOF->先天性高胰岛素血症',
                        'phenotype_assoc': 'MODY12;常显杂合糖尿病;常隐纯合高胰岛素血症;磺脲类敏感',
                        'key_domains': 'TMD0(aa1-195);NBD1(aa395-630);TMD1(aa631-960);NBD2(aa1050-1320)',
                        'clingen_validity': 'Strong'},
                    {   'gene': 'KCNJ11',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.65,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.3,
                        'evidence': 'monogenic',
                        'note': 'MODY13; Kir6.2/KATP通道;激活突变->新生儿糖尿病;E23K多态->T2D风险',
                        'phenotype_assoc': 'MODY13;永久性新生儿糖尿病(激活);高胰岛素血症(失活);E23K常见T2D风险',
                        'key_domains': 'Kir6.2孔道形成;ATP结合位点;NBD1相互作用面;结合位点(aa48-48);结合位点(aa50-50);结合位点(aa130-130);结合位点(aa133-133);结合位点(aa176-176);结合位点(aa330-330)',
                        'clingen_validity': 'Strong'},
                    {   'gene': 'INS',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.6,
                        'penetrance': 'moderate',
                        'penetrance_score': 0.25,
                        'evidence': 'monogenic',
                        'note': '胰岛素基因;杂合错义->永久性新生儿糖尿病;信号肽突变->ER应激',
                        'phenotype_assoc': '永久性新生儿糖尿病(杂合);MODY10;胰岛素原加工缺陷',
                        'key_domains': '信号肽(aa1-24);B链(aa25-54);C肽(aa55-89);A链(aa90-110)',
                        'clingen_validity': 'Definitive'},
                    {   'gene': 'NEUROD1',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.55,
                        'penetrance': 'low_to_moderate',
                        'penetrance_score': 0.2,
                        'evidence': 'monogenic',
                        'note': 'MODY6; bHLH转录因子;杂合突变->beta细胞分化缺陷',
                        'phenotype_assoc': 'MODY6;常显;beta细胞转录因子;罕见变异外显率可变',
                        'clingen_validity': 'Moderate',
                        'key_domains': 'Myc-type, basic helix-loop-helix (bHLH) domain;Neurogenic differentiation '
                                       'factor NeuroD;Neurogenic differentiation factor, domain of unknown '
                                       'function;Helix-loop-helix DNA-binding domain superfamily'},
                    {   'gene': 'PDX1',
                        'tier': 'mendelian_mod',
                        'contribution_score': 0.55,
                        'penetrance': 'low_to_moderate',
                        'penetrance_score': 0.2,
                        'evidence': 'monogenic',
                        'note': 'MODY4; beta细胞发育主调控因子;杂合->MODY;纯合->胰腺发育不全',
                        'phenotype_assoc': 'MODY4;常显杂合糖尿病;常隐纯合胰腺发育不全/新生儿糖尿病',
                        'clingen_validity': 'Moderate',
                        'key_domains': 'Homeodomain;Homedomain-like superfamily;Homeobox, conserved site;Homeobox '
                                       'protein, antennapedia type'},
                    {   'gene': 'TCF7L2',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.45,
                        'penetrance': 'low',
                        'penetrance_score': 0.15,
                        'evidence': 'gwas',
                        'note': '最强T2D GWAS位点;Wnt信号通路转录因子;rs7903146 intronic->影响胰岛beta细胞',
                        'phenotype_assoc': 'T2D GWAS最强信号;胰岛beta细胞功能;肠促胰岛素轴;OR~1.37/allele',
                        'clingen_validity': 'Moderate (risk factor, not monogenic)',
                        'key_domains': 'High mobility group box domain;CTNNB1 binding, N-teminal;Transcription factor '
                                       'TCF/LEF;Catenin binding domain superfamily'},
                    {   'gene': 'SLC30A8',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.4,
                        'penetrance': 'low',
                        'penetrance_score': 0.12,
                        'evidence': 'gwas',
                        'note': 'ZnT8锌转运蛋白;rs13266634 R325W->胰岛素分泌颗粒锌转运',
                        'phenotype_assoc': 'T2D GWAS;ZnT8胰岛锌转运蛋白;自身抗体靶点(1型糖尿病);LOF降低T2D风险',
                        'clingen_validity': 'Moderate',
                        'key_domains': 'Cation efflux protein;Cation efflux transmembrane domain superfamily;Cation '
                                       'efflux protein, cytoplasmic domain superfamily;Cation Diffusion '
                                       'Facilitator/SLC30A'},
                    {   'gene': 'PPARG',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.4,
                        'penetrance': 'low',
                        'penetrance_score': 0.12,
                        'evidence': 'gwas',
                        'note': 'TZD药物靶点;核受体;rs1801282 Pro12Ala保护性;稀有突变->家族性部分脂肪萎缩',
                        'phenotype_assoc': 'T2D;脂肪分化/胰岛素敏感性关键调控因子;噻唑烷二酮类靶点',
                        'key_domains': 'AF-1域(aa1-137);DNA结合域(aa138-203);配体结合域(aa204-505)',
                        'clingen_validity': 'Strong (ligand-binding domain: FPLD3)'},
                    {   'gene': 'KCNQ1',
                        'tier': 'strong_gwas',
                        'contribution_score': 0.45,
                        'penetrance': 'low',
                        'penetrance_score': 0.12,
                        'evidence': 'gwas',
                        'note': 'Kv7.1钾通道;rs2237892/rs2237895;东亚人群T2D GWAS最强信号',
                        'phenotype_assoc': 'T2D GWAS东亚最强;心肌+胰岛Kv7.1钾通道;LQT1致病基因',
                        'clingen_validity': 'Moderate (T2D risk, monogenic LQT)',
                        'key_domains': 'Potassium channel, voltage dependent, KCNQ;Ion transport domain;Potassium '
                                       'channel, voltage dependent, KCNQ1;Potassium channel, voltage dependent, KCNQ, '
                                       'C-terminal'},
                    {   'gene': 'CDKAL1',
                        'tier': 'gwas',
                        'contribution_score': 0.3,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': 'tRNA修饰酶;rs7754840;影响胰岛beta细胞胰岛素分泌',
                        'phenotype_assoc': 'The protein encoded by this gene is a member of the methylthiotransferase '
                                           'family',
                        'key_domains': 'TRAM domain;Methylthiotransferase;MiaB-like tRNA modifying enzyme, '
                                       'archaea/eukaryota;Elp3/MiaA/NifB-like, radical SAM core domain'},
                    {   'gene': 'CDKN2A',
                        'tier': 'gwas',
                        'contribution_score': 0.3,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': 'p16/p14ARF;rs10811661;beta细胞周期调控;多效性(癌症/T2D)',
                        'phenotype_assoc': 'T2D;细胞周期/衰老;共位黑色素瘤/胰腺癌风险基因',
                        'key_domains': 'Ankyrin repeat-containing domain superfamily;Ankyrin Repeat and '
                                       'Cyclin-Dependent Kinase Inhibitor;Tumor suppressor ARF'},
                    {   'gene': 'CDKN2B',
                        'tier': 'gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': 'p15;CDKN2A/B位点;rs10811661附近;beta细胞发育',
                        'phenotype_assoc': 'This gene lies adjacent to the tumor suppressor gene CDKN2A in a region '
                                           'that is frequently mutated and deleted in a wide variety of tumors',
                        'key_domains': 'Ankyrin repeat-containing domain superfamily;Ankyrin Repeat and '
                                       'Cyclin-Dependent Kinase Inhibitor;Ankyrin repeat'},
                    {   'gene': 'IGF2BP2',
                        'tier': 'gwas',
                        'contribution_score': 0.3,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': 'RNA结合蛋白;rs4402960;胰岛素信号/beta细胞功能',
                        'phenotype_assoc': "This gene encodes a protein that binds the 5' UTR of insulin-like growth "
                                           'factor 2 (IGF2) mRNA and regulates its translation',
                        'key_domains': 'RNA recognition motif domain;K Homology domain;K Homology domain, type '
                                       '1;Nucleotide-binding alpha-beta plait domain superfamily'},
                    {   'gene': 'FTO',
                        'tier': 'gwas',
                        'contribution_score': 0.3,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': '肥胖/T2D GWAS;rs9939609;脂肪生成/能量稳态;BMI介导效应',
                        'phenotype_assoc': 'This gene is a nuclear protein of the AlkB related non-haem iron and '
                                           '2-oxoglutarate-dependent oxygenase superfamily but the exact physiological '
                                           'function of this gene is not known',
                        'key_domains': 'Alpha-ketoglutarate-dependent dioxygenase FTO, '
                                       'C-terminal;Alpha-ketoglutarate-dependent dioxygenase FTO, catalytic '
                                       'domain;Alpha-ketoglutarate-dependent dioxygenase '
                                       'FTO;Alpha-ketoglutarate-dependent...'},
                    {   'gene': 'HHEX',
                        'tier': 'gwas',
                        'contribution_score': 0.3,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': '转录因子;rs1111875;胰腺发育/beta细胞分化',
                        'phenotype_assoc': 'This gene encodes a member of the homeobox family of transcription '
                                           'factors, many of which are involved in developmental processes',
                        'key_domains': 'Homeodomain;Homedomain-like superfamily;Homeobox, conserved site;Homeodomain, '
                                       'metazoa'},
                    {   'gene': 'IDE',
                        'tier': 'gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': '胰岛素降解酶;HHEX-IDE位点;rs1111875共定位',
                        'phenotype_assoc': 'This gene encodes a zinc metallopeptidase that degrades intracellular '
                                           'insulin, and thereby terminates insulins activity, as well as '
                                           'participating in intercellular peptide signalling by degrading di...',
                        'key_domains': 'Peptidase M16, zinc-binding site;Peptidase M16, C-terminal;Metalloenzyme, '
                                       'LuxS/M16 peptidase-like;Peptidase M16, N-terminal'},
                    {   'gene': 'WFS1',
                        'tier': 'gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': 'Wolframin;rs10010131;ER应激/beta细胞凋亡;纯合LOF->Wolfram综合征',
                        'phenotype_assoc': 'This gene encodes a transmembrane protein, which is located primarily in '
                                           'the endoplasmic reticulum and ubiquitously expressed with highest levels '
                                           'in brain, pancreas, heart, and insulinoma beta-cell...',
                        'key_domains': 'Tetratricopeptide-like helical domain superfamily;Wolframin;Wolframin '
                                       'family;Wolframin, cysteine-rich domain'},
                    {   'gene': 'JAZF1',
                        'tier': 'gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': '转录调控因子;rs864745;胰岛素信号通路',
                        'phenotype_assoc': 'This gene encodes a nuclear protein with three C2H2-type zinc fingers, and '
                                           'functions as a transcriptional repressor',
                        'key_domains': 'Zinc finger C2H2-type;Zinc finger C2H2 superfamily;Zinc finger and chromatin '
                                       'remodeling-associated protein'},
                    {   'gene': 'THADA',
                        'tier': 'gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': '甲状腺腺瘤相关;rs7578597;beta细胞内质网;T2D GWAS',
                        'phenotype_assoc': 'This gene is the target of 2p21 choromosomal aberrations in benign thyroid '
                                           'adenomas',
                        'key_domains': "Armadillo-type fold;THADA/TRM732, DUF2428;tRNA (32-2'-O)-methyltransferase "
                                       "regulator THADA;tRNA (32-2'-O)-methyltransferase regulator THADA-like, "
                                       'C-terminal TPR repeats region'},
                    {   'gene': 'ADCY5',
                        'tier': 'gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': '腺苷酸环化酶5;rs11708067;cAMP信号/胰岛素分泌;出生体重多效性',
                        'phenotype_assoc': 'This gene encodes a member of the membrane-bound adenylyl cyclase enzymes',
                        'key_domains': 'Adenylyl cyclase class-3/4/guanylyl cyclase;Adenylate cyclase, conserved '
                                       'domain;Adenylyl cyclase class-4/guanylyl cyclase, conserved site;Nucleotide '
                                       'cyclase'},
                    {   'gene': 'PROX1',
                        'tier': 'gwas',
                        'contribution_score': 0.22,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '转录因子;rs340874;淋巴管发育;肝脏代谢;空腹血糖',
                        'phenotype_assoc': 'The protein encoded by this gene is a member of the homeobox transcription '
                                           'factor family',
                        'key_domains': 'Homedomain-like superfamily;Homeo-prospero domain;Homeo-prospero domain '
                                       'superfamily;Prospero homeodomain family'},
                    {   'gene': 'MTNR1B',
                        'tier': 'gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': '褪黑素受体1B;rs10830963;胰岛分泌;空腹血糖GWAS',
                        'phenotype_assoc': 'This gene encodes one of two high affinity forms of a receptor for '
                                           'melatonin, the primary hormone secreted by the pineal gland',
                        'key_domains': 'Melatonin receptor family;G protein-coupled receptor, rhodopsin-like;Melatonin '
                                       'receptor 1A/1B;GPCR, rhodopsin-like, 7TM'},
                    {   'gene': 'DGKB',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '甘油二酯激酶beta;rs2191349;DAG信号/胰岛素分泌',
                        'phenotype_assoc': 'Diacylglycerol kinases (DGKs) are regulators of the intracellular '
                                           'concentration of the second messenger diacylglycerol (DAG) and thus play a '
                                           'key role in cellular processes',
                        'key_domains': 'Diacylglycerol kinase, accessory domain;Diacylglycerol kinase, catalytic '
                                       'domain;EF-hand domain;Protein kinase C-like, phorbol '
                                       'ester/diacylglycerol-binding domain'},
                    {   'gene': 'GCKR',
                        'tier': 'gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': '葡萄糖激酶调节蛋白;rs1260326;肝脏葡萄糖感应/代谢',
                        'phenotype_assoc': 'This gene encodes a protein belonging to the GCKR subfamily of the SIS '
                                           '(Sugar ISomerase) family of proteins',
                        'key_domains': 'SIS domain;Glucokinase regulatory protein, conserved site;N-acetylmuramic acid '
                                       '6-phosphate etherase/glucokinase regulatory protein;SIS domain superfamily'},
                    {   'gene': 'IRS1',
                        'tier': 'gwas',
                        'contribution_score': 0.25,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.08,
                        'evidence': 'gwas',
                        'note': '胰岛素受体底物1;rs2943641;胰岛素信号通路核心;T2D+胰岛素抵抗',
                        'phenotype_assoc': 'This gene encodes a protein which is phosphorylated by insulin receptor '
                                           'tyrosine kinase',
                        'key_domains': 'Pleckstrin homology domain;IRS-type PTB domain;PH-like domain '
                                       'superfamily;Insulin receptor substrate'},
                    {   'gene': 'TLE4',
                        'tier': 'gwas',
                        'contribution_score': 0.2,
                        'penetrance': 'very_low',
                        'penetrance_score': 0.05,
                        'evidence': 'gwas',
                        'note': '转录共抑制因子;rs1535500;Wnt通路;T2D fine-mapped位点',
                        'phenotype_assoc': 'Predicted to enable transcription corepressor activity',
                        'key_domains': 'WD40 repeat;Groucho/TLE, N-terminal Q-rich domain;Groucho/transducin-like '
                                       'enhancer;WD40/YVTN repeat-like-containing domain superfamily'}],
    'known_pathogenic_variants': [   {   'rsid': 'rs137853236',
                                         'chrom': 'chr12',
                                         'pos': 120979776,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'HNF1A',
                                         'effect_allele': 'T',
                                         'other_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.9,
                                         'confidence': 'high',
                                         'note': 'HNF1A p.Gly292fs (c.872delC); MODY3最常见移码突变;杂合->早发beta细胞功能障碍;常显'},
                                     {   'rsid': 'rs28934872',
                                         'chrom': 'chr12',
                                         'pos': 120983359,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'HNF1A',
                                         'effect_allele': 'T',
                                         'other_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.85,
                                         'confidence': 'high',
                                         'note': 'HNF1A p.Arg131Trp; MODY3;破坏DNA结合域POU区域;ClinVar P/LP;杂合致病'},
                                     {   'rsid': 'rs104894138',
                                         'chrom': 'chr7',
                                         'pos': 44113574,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'GCK',
                                         'effect_allele': 'A',
                                         'other_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.8,
                                         'confidence': 'high',
                                         'note': 'GCK p.Gly261Arg; MODY2;破坏葡萄糖结合域;杂合->轻度空腹高血糖(5.5-8mmol/L);ClinVar '
                                                 'P/LP'},
                                     {   'rsid': 'rs775871726',
                                         'chrom': 'chr20',
                                         'pos': 44413932,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'HNF4A',
                                         'effect_allele': 'T',
                                         'other_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.8,
                                         'confidence': 'high',
                                         'note': 'HNF4A p.Arg76Trp (c.226C>T); MODY1;DNA结合域突变;HNF1A上游调控因子缺陷;ClinVar '
                                                 'P/LP'},
                                     {   'rsid': 'rs1801282',
                                         'chrom': 'chr3',
                                         'pos': 12417610,
                                         'ref': 'C',
                                         'alt': 'G',
                                         'gene': 'PPARG',
                                         'effect_allele': 'G',
                                         'other_allele': 'C',
                                         'or_value': 0.85,
                                         'beta': -0.1625,
                                         'eaf_eur': 0.12,
                                         'eaf_eas': 0.04,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.55,
                                         'confidence': 'high',
                                         'note': 'PPARG Pro12Ala;保护性等位基因(C->G);OR=0.85 T2D;杂合~20%风险降低;ClinVar risk '
                                                 'factor'},
                                     {   'rsid': '635574',
                                         'chrom': '17',
                                         'pos': 37687394,
                                         'ref': 'T',
                                         'alt': 'A',
                                         'gene': 'HNF1B',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic | Renal cysts and diabetes syndrome'},
                                     {   'rsid': '635575',
                                         'chrom': '17',
                                         'pos': 37699089,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'HNF1B',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Renal cysts and diabetes syndrome'},
                                     {   'rsid': '2848441',
                                         'chrom': '11',
                                         'pos': 17393076,
                                         'ref': 'C',
                                         'alt': 'A',
                                         'gene': 'ABCC8',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic/Likely_pathogenic | Leucine-induced '
                                                 'hypoglycemia|Hyperinsulinemic hypoglycemia, familial, 1|Type 2 d'},
                                     {   'rsid': '2735544',
                                         'chrom': '11',
                                         'pos': 17393076,
                                         'ref': 'C',
                                         'alt': 'T',
                                         'gene': 'ABCC8',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Pathogenic/Likely_pathogenic | Hereditary '
                                                 'hyperinsulinism|not provided'},
                                     {   'rsid': '3239673',
                                         'chrom': '11',
                                         'pos': 17387001,
                                         'ref': 'GC',
                                         'alt': 'G',
                                         'gene': 'KCNJ11',
                                         'effect_allele': 'G',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Hyperinsulinemic hypoglycemia, '
                                                 'familial, 2'},
                                     {   'rsid': '4814298',
                                         'chrom': '11',
                                         'pos': 17387056,
                                         'ref': 'C',
                                         'alt': 'CCGTGCAGAGTGGTGTGG',
                                         'gene': 'KCNJ11',
                                         'effect_allele': 'CCGTGCAGAGTGGTGTGG',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Permanent neonatal diabetes mellitus'},
                                     {   'rsid': '65581',
                                         'chrom': '11',
                                         'pos': 2159793,
                                         'ref': 'T',
                                         'alt': 'C',
                                         'gene': 'INS',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Permanent neonatal diabetes '
                                                 'mellitus|Maturity-onset diabetes of the young type 1'},
                                     {   'rsid': '1526011',
                                         'chrom': '11',
                                         'pos': 2159859,
                                         'ref': 'C',
                                         'alt': 'A',
                                         'gene': 'INS',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Neonatal diabetes mellitus'},
                                     {   'rsid': '3027521',
                                         'chrom': '2',
                                         'pos': 181678097,
                                         'ref': 'G',
                                         'alt': 'A',
                                         'gene': 'NEUROD1',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Retinal dystrophy'},
                                     {   'rsid': '3033670',
                                         'chrom': '2',
                                         'pos': 181678520,
                                         'ref': 'A',
                                         'alt': 'T',
                                         'gene': 'NEUROD1',
                                         'effect_allele': 'T',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | NEUROD1-related disorder|not provided'},
                                     {   'rsid': '3906449',
                                         'chrom': '13',
                                         'pos': 27920192,
                                         'ref': 'C',
                                         'alt': 'A',
                                         'gene': 'PDX1',
                                         'effect_allele': 'A',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | not provided'},
                                     {   'rsid': '4850590',
                                         'chrom': '13',
                                         'pos': 27920546,
                                         'ref': 'T',
                                         'alt': 'C',
                                         'gene': 'PDX1',
                                         'effect_allele': 'C',
                                         'or_value': None,
                                         'beta': None,
                                         'variant_class': 'known_pathogenic',
                                         'contribution_score': 0.7,
                                         'confidence': 'moderate',
                                         'note': 'ClinVar: Likely_pathogenic | Pancreatic agenesis 1'}],
    'regions': [   {   'chrom': 'chr10',
                       'start': 114700000,
                       'end': 114850000,
                       'gene': 'TCF7L2',
                       'type': 'gwas_locus',
                       'contribution_score': 0.55,
                       'note': 'TCF7L2 最强T2D GWAS区;Wnt/β-catenin信号'},
                   {   'chrom': 'chr11',
                       'start': 2400000,
                       'end': 2800000,
                       'gene': 'KCNQ1',
                       'type': 'gwas_locus',
                       'contribution_score': 0.45,
                       'note': 'KCNQ1 东亚T2D最强信号;胰岛KATP通道'},
                   {   'chrom': 'chr6',
                       'start': 20500000,
                       'end': 20600000,
                       'gene': 'CDKAL1',
                       'type': 'gwas_locus',
                       'contribution_score': 0.35,
                       'note': 'CDKAL1 T2D GWAS;tRNA修饰/胰岛素分泌'},
                   {   'chrom': 'chr16',
                       'start': 53700000,
                       'end': 54100000,
                       'gene': 'FTO',
                       'type': 'gwas_locus',
                       'contribution_score': 0.3,
                       'note': 'FTO 肥胖/T2D共同GWAS区;IRX3/IRX5调控'}],
    'regulatory_regions': [],
        'key_regions': {
        'ABCC8': {'note': 'TMD0(aa1-195);NBD1(aa395-630);TMD1(aa631-960);NBD2(aa1050-1320)', 'regions': [(1, 195), (395, 630), (631, 960), (1050, 1320)]},
        'GCK': {'note': 'ATP结合域(aa155-200);葡萄糖结合域(aa210-260);铰链区(aa68-100)', 'regions': [(155, 200), (210, 260), (68, 100)]},
        'HNF1A': {'note': '二聚化域(aa1-32);DNA结合POU域(aa99-280);转录激活域(aa281-631)', 'regions': [(1, 32), (99, 280), (281, 631)]},
        'HNF1B': {'note': '二聚化域(aa1-32);POU特异性域(aa99-180);POU同源域(aa227-286)', 'regions': [(1, 32), (99, 180), (227, 286)]},
        'HNF4A': {'note': 'AF-1域(aa1-54);DNA结合锌指(aa55-133);配体结合域(aa134-374);AF-2(aa456-474)', 'regions': [(1, 54), (55, 133), (134, 374), (456, 474)]},
        'INS': {'note': '信号肽(aa1-24);B链(aa25-54);C肽(aa55-89);A链(aa90-110)', 'regions': [(1, 24), (25, 54), (55, 89), (90, 110)]},
        'KCNJ11': {'note': 'Kir6.2孔道形成;ATP结合位点;NBD1相互作用面;结合位点(aa48-48);结合位点(aa50-50);结合位点(aa130-130);结合位点(aa133-133);结合位点(aa176-', 'regions': [(48, 48), (50, 50), (130, 130), (133, 133), (176, 176), (330, 330)]},
        'PPARG': {'note': 'AF-1域(aa1-137);DNA结合域(aa138-203);配体结合域(aa204-505)', 'regions': [(1, 137), (138, 203), (204, 505)]},
    },
    'prs_variants_high': [   {   'rsid': 'rs7903146',
                                 'chrom': 'chr10',
                                 'pos': 112998590,
                                 'gene': 'TCF7L2',
                                 'effect_allele': 'T',
                                 'other_allele': 'C',
                                 'beta': None,
                                 'or_value': 1.37,
                                 'tier': 'prs_high',
                                 'contribution_score': 0.4,
                                 'confidence': 'high',
                                 'note': 'TCF7L2;最强T2D locus;intronic增强子变异;OR=1.37;EAS AF~3%'},
                             {   'rsid': 'rs2237892',
                                 'chrom': 'chr11',
                                 'pos': 2818521,
                                 'gene': 'KCNQ1',
                                 'effect_allele': 'C',
                                 'other_allele': 'T',
                                 'beta': None,
                                 'or_value': 1.3,
                                 'tier': 'prs_high',
                                 'contribution_score': 0.35,
                                 'confidence': 'high',
                                 'note': 'KCNQ1;东亚T2D GWAS最强;OR=1.30;EAS AF~30%'},
                             {   'rsid': 'rs10830963',
                                 'chrom': 'chr11',
                                 'pos': 92975544,
                                 'gene': 'MTNR1B',
                                 'effect_allele': 'G',
                                 'other_allele': 'C',
                                 'beta': None,
                                 'or_value': 1.09,
                                 'tier': 'prs_high',
                                 'contribution_score': 0.3,
                                 'confidence': 'high',
                                 'note': 'MTNR1B;褪黑素受体;胰岛分泌;空腹血糖;EAS AF~40%'},
                             {   'rsid': 'rs13266634',
                                 'chrom': 'chr8',
                                 'pos': 117172544,
                                 'gene': 'SLC30A8',
                                 'effect_allele': 'C',
                                 'other_allele': 'T',
                                 'beta': None,
                                 'or_value': 1.15,
                                 'tier': 'prs_high',
                                 'contribution_score': 0.3,
                                 'confidence': 'high',
                                 'note': 'SLC30A8;ZnT8 R325W;胰岛素颗粒锌转运;OR=1.15;EAS AF~55%'},
                             {   'rsid': 'rs5219',
                                 'chrom': 'chr11',
                                 'pos': 17388025,
                                 'gene': 'KCNJ11',
                                 'effect_allele': 'T',
                                 'other_allele': 'C',
                                 'beta': None,
                                 'or_value': 1.15,
                                 'tier': 'prs_high',
                                 'contribution_score': 0.3,
                                 'confidence': 'high',
                                 'note': 'KCNJ11 E23K;KATP通道;常见T2D多态;OR=1.15;EAS AF~40%'}],
    'prs_variants': [],
    'gwas_lead_snps': [   {   'rsid': 'rs7903146',
                              'chrom': 'chr10',
                              'pos': 112998590,
                              'gene': 'TCF7L2',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'beta': 0.3147,
                              'or_value': 1.37,
                              'eaf_eur': 0.29,
                              'eaf_eas': 0.03,
                              'tier': 'strong_gwas',
                              'contribution_score': 0.4,
                              'confidence': 'high',
                              'note': 'TCF7L2;最强T2D GWAS;intronic SNV;Wnt通路和GLP-1分泌;OR=1.37;EAS AF=0.03'},
                          {   'rsid': 'rs13266634',
                              'chrom': 'chr8',
                              'pos': 117172544,
                              'gene': 'SLC30A8',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'beta': 0.1398,
                              'or_value': 1.15,
                              'eaf_eur': 0.69,
                              'eaf_eas': 0.55,
                              'tier': 'strong_gwas',
                              'contribution_score': 0.35,
                              'confidence': 'high',
                              'note': 'SLC30A8 R325W;ZnT8锌转运蛋白;胰岛素颗粒锌累积;OR=1.15'},
                          {   'rsid': 'rs10811661',
                              'chrom': 'chr9',
                              'pos': 22134095,
                              'gene': 'CDKN2A',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'beta': 0.1823,
                              'or_value': 1.2,
                              'eaf_eur': 0.83,
                              'eaf_eas': 0.56,
                              'tier': 'strong_gwas',
                              'contribution_score': 0.35,
                              'confidence': 'high',
                              'note': 'CDKN2A/B;p16/p15;beta细胞周期调控;多效性(T2D+CVD+癌症);OR=1.20'},
                          {   'rsid': 'rs2237892',
                              'chrom': 'chr11',
                              'pos': 2818521,
                              'gene': 'KCNQ1',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'beta': 0.2231,
                              'or_value': 1.3,
                              'eaf_eur': 0.54,
                              'eaf_eas': 0.3,
                              'tier': 'strong_gwas',
                              'contribution_score': 0.35,
                              'confidence': 'high',
                              'note': 'KCNQ1内含子11;东亚T2D GWAS最强;Kv7.1钾通道(胰岛+心肌);OR=1.30'},
                          {   'rsid': 'rs1111875',
                              'chrom': 'chr10',
                              'pos': 92703125,
                              'gene': 'HHEX',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'beta': 0.1222,
                              'or_value': 1.13,
                              'eaf_eur': 0.56,
                              'eaf_eas': 0.75,
                              'tier': 'strong_gwas',
                              'contribution_score': 0.3,
                              'confidence': 'high',
                              'note': 'HHEX/IDE;胰腺发育;胰岛素降解酶IDE;OR=1.13'},
                          {   'rsid': 'rs4402960',
                              'chrom': 'chr3',
                              'pos': 185511687,
                              'gene': 'IGF2BP2',
                              'effect_allele': 'T',
                              'other_allele': 'G',
                              'beta': 0.131,
                              'or_value': 1.14,
                              'eaf_eur': 0.3,
                              'eaf_eas': 0.27,
                              'tier': 'gwas',
                              'contribution_score': 0.28,
                              'confidence': 'high',
                              'note': 'IGF2BP2;RNA结合蛋白;胰岛素信号;OR=1.14'},
                          {   'rsid': 'rs7754840',
                              'chrom': 'chr6',
                              'pos': 20661250,
                              'gene': 'CDKAL1',
                              'effect_allele': 'C',
                              'other_allele': 'G',
                              'beta': 0.1133,
                              'or_value': 1.12,
                              'eaf_eur': 0.31,
                              'eaf_eas': 0.42,
                              'tier': 'gwas',
                              'contribution_score': 0.28,
                              'confidence': 'high',
                              'note': 'CDKAL1;tRNA修饰酶;影响胰岛beta细胞胰岛素原翻译;OR=1.12'},
                          {   'rsid': 'rs9939609',
                              'chrom': 'chr16',
                              'pos': 53786615,
                              'gene': 'FTO',
                              'effect_allele': 'A',
                              'other_allele': 'T',
                              'beta': 0.1398,
                              'or_value': 1.15,
                              'eaf_eur': 0.42,
                              'eaf_eas': 0.12,
                              'tier': 'gwas',
                              'contribution_score': 0.28,
                              'confidence': 'high',
                              'note': 'FTO;肥胖GWAS最强信号;通过BMI中介增加T2D风险;OR=1.15;EAS AF=0.12'},
                          {   'rsid': 'rs5219',
                              'chrom': 'chr11',
                              'pos': 17388025,
                              'gene': 'KCNJ11',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'beta': 0.1398,
                              'or_value': 1.15,
                              'eaf_eur': 0.36,
                              'eaf_eas': 0.39,
                              'tier': 'gwas',
                              'contribution_score': 0.28,
                              'confidence': 'high',
                              'note': 'KCNJ11 E23K;KATP通道Kir6.2;OR=1.15;EAS AF=0.39'},
                          {   'rsid': 'rs10010131',
                              'chrom': 'chr4',
                              'pos': 6302547,
                              'gene': 'WFS1',
                              'effect_allele': 'G',
                              'other_allele': 'A',
                              'beta': 0.1044,
                              'or_value': 1.11,
                              'eaf_eur': 0.6,
                              'eaf_eas': 0.96,
                              'tier': 'gwas',
                              'contribution_score': 0.25,
                              'confidence': 'high',
                              'note': 'WFS1/Wolframin;ER应激/beta细胞凋亡;OR=1.11;EAS near-fixed G'},
                          {   'rsid': 'rs864745',
                              'chrom': 'chr7',
                              'pos': 28165616,
                              'gene': 'JAZF1',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'beta': 0.0953,
                              'or_value': 1.1,
                              'eaf_eur': 0.69,
                              'eaf_eas': 0.72,
                              'tier': 'gwas',
                              'contribution_score': 0.22,
                              'confidence': 'high',
                              'note': 'JAZF1;转录调控;胰岛素信号;OR=1.10'},
                          {   'rsid': 'rs7578597',
                              'chrom': 'chr2',
                              'pos': 43636369,
                              'gene': 'THADA',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'beta': 0.1398,
                              'or_value': 1.15,
                              'eaf_eur': 0.78,
                              'eaf_eas': 0.95,
                              'tier': 'gwas',
                              'contribution_score': 0.25,
                              'confidence': 'high',
                              'note': 'THADA;beta细胞内质网;OR=1.15;EAS near-fixed T'},
                          {   'rsid': 'rs11708067',
                              'chrom': 'chr3',
                              'pos': 123482084,
                              'gene': 'ADCY5',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'beta': 0.1133,
                              'or_value': 1.12,
                              'eaf_eur': 0.79,
                              'eaf_eas': 0.36,
                              'tier': 'gwas',
                              'contribution_score': 0.25,
                              'confidence': 'high',
                              'note': 'ADCY5;腺苷酸环化酶5;cAMP信号;胰岛素分泌;出生体重多效性;OR=1.12'},
                          {   'rsid': 'rs340874',
                              'chrom': 'chr1',
                              'pos': 213985914,
                              'gene': 'PROX1',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'beta': 0.0677,
                              'or_value': 1.07,
                              'eaf_eur': 0.5,
                              'eaf_eas': 0.28,
                              'tier': 'gwas',
                              'contribution_score': 0.18,
                              'confidence': 'high',
                              'note': 'PROX1;转录因子;空腹血糖;肝脏代谢;OR=1.07'},
                          {   'rsid': 'rs10830963',
                              'chrom': 'chr11',
                              'pos': 92975544,
                              'gene': 'MTNR1B',
                              'effect_allele': 'G',
                              'other_allele': 'C',
                              'beta': 0.0862,
                              'or_value': 1.09,
                              'eaf_eur': 0.29,
                              'eaf_eas': 0.4,
                              'tier': 'gwas',
                              'contribution_score': 0.22,
                              'confidence': 'high',
                              'note': 'MTNR1B;褪黑素受体1B;胰岛分泌;空腹血糖;OR=1.09'},
                          {   'rsid': 'rs2191349',
                              'chrom': 'chr7',
                              'pos': 15064602,
                              'gene': 'DGKB',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'beta': 0.0583,
                              'or_value': 1.06,
                              'eaf_eur': 0.55,
                              'eaf_eas': 0.48,
                              'tier': 'gwas',
                              'contribution_score': 0.18,
                              'confidence': 'moderate',
                              'note': 'DGKB;甘油二酯激酶beta;DAG信号/胰岛素分泌;空腹血糖;OR=1.06'},
                          {   'rsid': 'rs1260326',
                              'chrom': 'chr2',
                              'pos': 27508073,
                              'gene': 'GCKR',
                              'effect_allele': 'T',
                              'other_allele': 'C',
                              'beta': 0.077,
                              'or_value': 1.08,
                              'eaf_eur': 0.39,
                              'eaf_eas': 0.22,
                              'tier': 'gwas',
                              'contribution_score': 0.2,
                              'confidence': 'high',
                              'note': 'GCKR P446L;葡萄糖激酶调节蛋白;肝脏葡萄糖感应;OR=1.08'},
                          {   'rsid': 'rs2943641',
                              'chrom': 'chr2',
                              'pos': 226466026,
                              'gene': 'IRS1',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'beta': 0.1222,
                              'or_value': 1.13,
                              'eaf_eur': 0.63,
                              'eaf_eas': 0.92,
                              'tier': 'gwas',
                              'contribution_score': 0.25,
                              'confidence': 'high',
                              'note': 'IRS1;胰岛素受体底物1;胰岛素信号核心;T2D+胰岛素抵抗;OR=1.13'},
                          {   'rsid': 'rs1535500',
                              'chrom': 'chr9',
                              'pos': 81721190,
                              'gene': 'TLE4',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'beta': 0.0583,
                              'or_value': 1.06,
                              'eaf_eur': 0.36,
                              'eaf_eas': 0.17,
                              'tier': 'gwas',
                              'contribution_score': 0.18,
                              'confidence': 'moderate',
                              'note': 'TLE4;转录共抑制因子;Wnt信号;T2D fine-mapped位点;OR=1.06'},
                          {   'rsid': 'rs2237895',
                              'chrom': 'chr11',
                              'pos': 2857194,
                              'gene': 'KCNQ1',
                              'effect_allele': 'C',
                              'other_allele': 'T',
                              'beta': 0.2151,
                              'or_value': 1.24,
                              'eaf_eur': 0.37,
                              'eaf_eas': 0.33,
                              'tier': 'gwas',
                              'contribution_score': 0.28,
                              'confidence': 'high',
                              'note': 'KCNQ1内含子15;东亚T2D GWAS;独立于rs2237892信号;OR=1.24'},
                          {   'rsid': 'rs1552224',
                              'chrom': 'chr11',
                              'pos': 72688823,
                              'gene': 'ARAP1',
                              'effect_allele': 'A',
                              'other_allele': 'G',
                              'beta': 0.1133,
                              'or_value': 1.12,
                              'eaf_eur': 0.81,
                              'eaf_eas': 0.78,
                              'tier': 'gwas',
                              'contribution_score': 0.25,
                              'confidence': 'high',
                              'note': 'ARAP1/CENTD2;beta细胞胰岛素分泌;OR=1.12'}],
    'key_literature': [   {   'pmid': '29632382',
                              'title': 'Fine-mapping type 2 diabetes loci to single-variant resolution.',
                              'genes': [   'TCF7L2',
                                           'SLC30A8',
                                           'KCNQ1',
                                           'CDKAL1',
                                           'CDKN2A',
                                           'IGF2BP2',
                                           'FTO',
                                           'HHEX',
                                           'PPARG',
                                           'KCNJ11',
                                           'WFS1',
                                           'JAZF1',
                                           'THADA',
                                           'ADCY5',
                                           'PROX1',
                                           'MTNR1B',
                                           'DGKB'],
                              'note': 'Mahajan et al., Nat Genet 2018; 243 T2D loci fine-mapped',
                              'evidence_type': 'gwas'},
                          {   'pmid': '24509480',
                              'title': 'Trans-ancestry meta-analysis provides insight into T2D genetic architecture.',
                              'genes': [   'TCF7L2',
                                           'SLC30A8',
                                           'CDKAL1',
                                           'CDKN2A',
                                           'IGF2BP2',
                                           'HHEX',
                                           'KCNJ11',
                                           'KCNQ1',
                                           'PPARG',
                                           'FTO'],
                              'note': 'DIAGRAM Consortium, Nat Genet 2014; 26,488 cases + 83,964 controls',
                              'evidence_type': 'gwas'},
                          {   'pmid': '19651813',
                              'title': 'Twelve type 2 diabetes susceptibility loci identified through large-scale '
                                       'analysis.',
                              'genes': ['IRS1', 'GCKR', 'ADCY5', 'PROX1', 'DGKB', 'TLE4'],
                              'note': 'Voight et al., Nat Genet 2010; DIAGRAM+; 12 novel T2D loci',
                              'evidence_type': 'gwas'}],
    'core_genes': [   'HNF1A',
                      'HNF4A',
                      'GCK',
                      'HNF1B',
                      'ABCC8',
                      'KCNJ11',
                      'INS',
                      'NEUROD1',
                      'PDX1',
                      'TCF7L2',
                      'SLC30A8',
                      'PPARG',
                      'KCNQ1'],
    'gwas_loci_genes': [   'CDKAL1',
                           'CDKN2A',
                           'CDKN2B',
                           'IGF2BP2',
                           'FTO',
                           'HHEX',
                           'IDE',
                           'WFS1',
                           'JAZF1',
                           'THADA',
                           'ADCY5',
                           'PROX1',
                           'MTNR1B',
                           'DGKB',
                           'GCKR',
                           'IRS1',
                           'TLE4',
                           'ARAP1',
                           'PAX4',
                           'KLF11',
                           'CEL']}
